namespace QMC.CDT320.Sequencing
{
    internal enum PickerSideInspectionStep
    {
        Idle,
        CheckUnit,
        BuildPickedPickerList,
        MoveAllPickerZToAvoid,
        MoveOppositePickerToAvoidBeforeInspection,
        SelectNextPicker,
        MoveSideEntryYToAvoid,
        MoveSideXToInspection,
        MoveSideYToInspection,
        MoveSideZ,
        MoveSideT0,
        RequestSide0Inspection,
        MoveSideT90,
        RequestSide90Inspection,
        ApplySideInspectionResult,
        MoveSideZToAvoid,
        MoveSideTToSafe,
        MoveAllPickerZToAvoidAfterInspection,
        MoveSideYToAvoid,
        MoveSideXToAvoid,
        SelectNextPickerOrComplete,
        Complete,
        Error
    }
}
