namespace QMC.CDT320.Sequencing
{
    internal enum PickerPickUpStep
    {
        Idle,
        CheckUnit,
        CheckPickerSideEnabled,
        BuildEnabledPickerList,
        CheckInputStageReady,
        MoveAllPickerZToAvoid,
        SelectNextPicker,
        ReserveNextInputDie,
        VerifyReservedInputDie,
        MovePickersToAvoidForInputVisionMove,
        MoveInputStageAndVisionToDie,
        RequestInputDieVisionInspection,
        ApplyInputDieVisionOffset,
        MoveInputVisionToAvoidForPickerMove,
        CalculatePickTarget,
        MoveOppositePickerToAvoidForPickerMove,
        MovePickerXStageYPickerT,
        VerifyPickTarget,
        MovePickerZPick,
        VacuumOn,
        VerifyDiePicked,
        MovePickerZToAvoid,
        UpdateMaterialToPicker,
        SelectNextPickerOrComplete,
        Complete,
        Error
    }
}
