namespace QMC.CDT320.Sequencing
{
    internal enum PickerPickUpStep
    {
        Idle,
        CheckUnit,
        CheckPickerSideEnabled,
        BuildEnabledPickerList,
        CheckInputStageReady,
        MoveAllPickerZToAvoid,
        BuildPickBatch,
        SelectNextInspectionTarget,
        VerifyReservedInputDie,
        MovePickersToAvoidForInputVisionMove,
        MoveInputStageAndVisionToDie,
        RequestInputDieVisionInspection,
        ApplyInputDieVisionOffset,
        SelectNextInspectionTargetOrPickerMove,
        MoveInputVisionToAvoidForPickerMove,
        CalculatePickTargets,
        SelectNextPickTarget,
        MoveOppositePickerToAvoidForPickerMove,
        MovePickerXStageYPickerT,
        VerifyPickTarget,
        VerifyPickerEmptyBeforePick,
        MovePickerZPick,
        VacuumOn,
        VerifyDiePicked,
        MovePickerZToAvoid,
        UpdateMaterialToPicker,
        SelectNextPickTargetOrComplete,
        Complete,
        Error
    }
}
