namespace QMC.CDT320.Sequencing
{
    internal enum PickerPlaceStep
    {
        Idle,
        CheckUnit,
        BuildPickedPickerList,
        MoveAllPickerZToAvoid,
        SelectNextPicker,
        ResolveOutputSide,
        VerifyOutputStageReady,
        ReserveOutputStageTarget,
        MoveOutputStageAvoidPosition,
        MoveOutputStageReceivePosition,
        CalculatePlaceTarget,
        MovePickerXYAndTToPlace,
        VerifyPlaceTarget,
        MovePickerZPlace,
        VacuumOff,
        BlowOff,
        MovePickerZToAvoid,
        VerifyFlowOff,
        UpdateMaterialToOutputStage,
        MovePickerToAvoidBeforeOutputInspection,
        MoveOutputCameraToPlacedDie,
        TriggerOutputDieInspection,
        MoveOutputCameraToAvoidAfterInspection,
        RecoverOutputStageAfterPlace,
        SelectNextPickerOrComplete,
        MovePickerToAvoidAfterPlace,
        Complete,
        Error
    }
}
