namespace QMC.CDT_320.Ui.Dialogs
{
    partial class BarcodeRecoveryDialog
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.TableLayoutPanel infoLayout;
        private System.Windows.Forms.Label lblChannelTitle;
        private System.Windows.Forms.Label lblChannelValue;
        private System.Windows.Forms.Label lblMaterialTitle;
        private System.Windows.Forms.Label lblMaterialValue;
        private System.Windows.Forms.Label lblInstanceTitle;
        private System.Windows.Forms.Label lblInstanceValue;
        private System.Windows.Forms.Label lblFailureTitle;
        private System.Windows.Forms.TextBox txtFailure;
        private System.Windows.Forms.GroupBox grpRetry;
        private System.Windows.Forms.TableLayoutPanel retryLayout;
        private System.Windows.Forms.Label lblRetryCount;
        private System.Windows.Forms.NumericUpDown numRetryCount;
        private System.Windows.Forms.Label lblRetryStep;
        private System.Windows.Forms.NumericUpDown numRetryStep;
        private System.Windows.Forms.Button btnRetry;
        private System.Windows.Forms.GroupBox grpManual;
        private System.Windows.Forms.TableLayoutPanel manualLayout;
        private System.Windows.Forms.Label lblManualBarcode;
        private System.Windows.Forms.TextBox txtManualBarcode;
        private System.Windows.Forms.Button btnManualApply;
        private System.Windows.Forms.TableLayoutPanel buttonLayout;
        private System.Windows.Forms.Button btnBuzzerStop;
        private System.Windows.Forms.Button btnCloseRetry;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.infoLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblChannelTitle = new System.Windows.Forms.Label();
            this.lblChannelValue = new System.Windows.Forms.Label();
            this.lblMaterialTitle = new System.Windows.Forms.Label();
            this.lblMaterialValue = new System.Windows.Forms.Label();
            this.lblInstanceTitle = new System.Windows.Forms.Label();
            this.lblInstanceValue = new System.Windows.Forms.Label();
            this.lblFailureTitle = new System.Windows.Forms.Label();
            this.txtFailure = new System.Windows.Forms.TextBox();
            this.grpRetry = new System.Windows.Forms.GroupBox();
            this.retryLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblRetryCount = new System.Windows.Forms.Label();
            this.numRetryCount = new System.Windows.Forms.NumericUpDown();
            this.lblRetryStep = new System.Windows.Forms.Label();
            this.numRetryStep = new System.Windows.Forms.NumericUpDown();
            this.btnRetry = new System.Windows.Forms.Button();
            this.grpManual = new System.Windows.Forms.GroupBox();
            this.manualLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblManualBarcode = new System.Windows.Forms.Label();
            this.txtManualBarcode = new System.Windows.Forms.TextBox();
            this.btnManualApply = new System.Windows.Forms.Button();
            this.buttonLayout = new System.Windows.Forms.TableLayoutPanel();
            this.btnBuzzerStop = new System.Windows.Forms.Button();
            this.btnCloseRetry = new System.Windows.Forms.Button();
            this.rootLayout.SuspendLayout();
            this.infoLayout.SuspendLayout();
            this.grpRetry.SuspendLayout();
            this.retryLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numRetryCount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numRetryStep)).BeginInit();
            this.grpManual.SuspendLayout();
            this.manualLayout.SuspendLayout();
            this.buttonLayout.SuspendLayout();
            this.SuspendLayout();
            // rootLayout
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.infoLayout, 0, 1);
            this.rootLayout.Controls.Add(this.grpRetry, 0, 2);
            this.rootLayout.Controls.Add(this.grpManual, 0, 3);
            this.rootLayout.Controls.Add(this.buttonLayout, 0, 4);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Padding = new System.Windows.Forms.Padding(12);
            this.rootLayout.RowCount = 5;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 52F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 158F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 92F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 88F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            // lblHeader
            this.lblHeader.BackColor = System.Drawing.Color.FromArgb(229, 113, 0);
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("맑은 고딕", 15F, System.Drawing.FontStyle.Bold);
            this.lblHeader.ForeColor = System.Drawing.Color.White;
            this.lblHeader.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.lblHeader.Text = "BARCODE READ RECOVERY";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // infoLayout
            this.infoLayout.ColumnCount = 2;
            this.infoLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.infoLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.infoLayout.Controls.Add(this.lblChannelTitle, 0, 0);
            this.infoLayout.Controls.Add(this.lblChannelValue, 1, 0);
            this.infoLayout.Controls.Add(this.lblMaterialTitle, 0, 1);
            this.infoLayout.Controls.Add(this.lblMaterialValue, 1, 1);
            this.infoLayout.Controls.Add(this.lblInstanceTitle, 0, 2);
            this.infoLayout.Controls.Add(this.lblInstanceValue, 1, 2);
            this.infoLayout.Controls.Add(this.lblFailureTitle, 0, 3);
            this.infoLayout.Controls.Add(this.txtFailure, 1, 3);
            this.infoLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.infoLayout.Padding = new System.Windows.Forms.Padding(0, 8, 0, 4);
            this.infoLayout.RowCount = 4;
            this.infoLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.infoLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.infoLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.infoLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lblChannelTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblChannelTitle.Text = "CHANNEL";
            this.lblChannelTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblChannelValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblChannelValue.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblChannelValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblMaterialTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblMaterialTitle.Text = "MATERIAL";
            this.lblMaterialTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblMaterialValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblMaterialValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblInstanceTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInstanceTitle.Text = "INSTANCE";
            this.lblInstanceTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblInstanceValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInstanceValue.Font = new System.Drawing.Font("Consolas", 8F);
            this.lblInstanceValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblFailureTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFailureTitle.Text = "LAST FAILURE";
            this.lblFailureTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtFailure.BackColor = System.Drawing.Color.WhiteSmoke;
            this.txtFailure.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtFailure.Multiline = true;
            this.txtFailure.ReadOnly = true;
            // grpRetry
            this.grpRetry.Controls.Add(this.retryLayout);
            this.grpRetry.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpRetry.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.grpRetry.Text = "AUTOMATIC RETRY";
            // retryLayout
            this.retryLayout.ColumnCount = 5;
            this.retryLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 120F));
            this.retryLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.retryLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 135F));
            this.retryLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 110F));
            this.retryLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.retryLayout.Controls.Add(this.lblRetryCount, 0, 0);
            this.retryLayout.Controls.Add(this.numRetryCount, 1, 0);
            this.retryLayout.Controls.Add(this.lblRetryStep, 2, 0);
            this.retryLayout.Controls.Add(this.numRetryStep, 3, 0);
            this.retryLayout.Controls.Add(this.btnRetry, 4, 0);
            this.retryLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.retryLayout.Padding = new System.Windows.Forms.Padding(8);
            this.lblRetryCount.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRetryCount.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblRetryCount.Text = "RETRY COUNT";
            this.lblRetryCount.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.numRetryCount.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numRetryCount.Maximum = new decimal(new int[] { 20, 0, 0, 0 });
            this.numRetryCount.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.lblRetryStep.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRetryStep.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblRetryStep.Text = "Y STEP (mm)";
            this.lblRetryStep.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.numRetryStep.DecimalPlaces = 3;
            this.numRetryStep.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numRetryStep.Increment = new decimal(new int[] { 1, 0, 0, 196608 });
            this.numRetryStep.Minimum = new decimal(new int[] { 1, 0, 0, 196608 });
            this.numRetryStep.Maximum = new decimal(new int[] { 100, 0, 0, 0 });
            this.numRetryStep.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.btnRetry.BackColor = System.Drawing.Color.FromArgb(49, 122, 75);
            this.btnRetry.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnRetry.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRetry.ForeColor = System.Drawing.Color.White;
            this.btnRetry.Text = "RETRY SCAN";
            this.btnRetry.UseVisualStyleBackColor = false;
            // grpManual
            this.grpManual.Controls.Add(this.manualLayout);
            this.grpManual.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpManual.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.grpManual.Text = "MANUAL BARCODE";
            // manualLayout
            this.manualLayout.ColumnCount = 3;
            this.manualLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 130F));
            this.manualLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.manualLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 160F));
            this.manualLayout.Controls.Add(this.lblManualBarcode, 0, 0);
            this.manualLayout.Controls.Add(this.txtManualBarcode, 1, 0);
            this.manualLayout.Controls.Add(this.btnManualApply, 2, 0);
            this.manualLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.manualLayout.Padding = new System.Windows.Forms.Padding(8);
            this.lblManualBarcode.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblManualBarcode.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblManualBarcode.Text = "BARCODE ID";
            this.lblManualBarcode.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtManualBarcode.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtManualBarcode.Font = new System.Drawing.Font("Consolas", 11F);
            this.txtManualBarcode.MaxLength = 128;
            this.btnManualApply.BackColor = System.Drawing.Color.FromArgb(49, 122, 75);
            this.btnManualApply.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnManualApply.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnManualApply.ForeColor = System.Drawing.Color.White;
            this.btnManualApply.Text = "MANUAL APPLY";
            this.btnManualApply.UseVisualStyleBackColor = false;
            // buttonLayout
            this.buttonLayout.ColumnCount = 3;
            this.buttonLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.buttonLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 180F));
            this.buttonLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 180F));
            this.buttonLayout.Controls.Add(this.btnBuzzerStop, 1, 0);
            this.buttonLayout.Controls.Add(this.btnCloseRetry, 2, 0);
            this.buttonLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonLayout.Padding = new System.Windows.Forms.Padding(0, 12, 0, 0);
            this.btnBuzzerStop.BackColor = System.Drawing.Color.FromArgb(181, 119, 26);
            this.btnBuzzerStop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnBuzzerStop.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBuzzerStop.ForeColor = System.Drawing.Color.White;
            this.btnBuzzerStop.Text = "BUZZER STOP";
            this.btnBuzzerStop.UseVisualStyleBackColor = false;
            this.btnCloseRetry.BackColor = System.Drawing.Color.FromArgb(100, 100, 100);
            this.btnCloseRetry.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnCloseRetry.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCloseRetry.ForeColor = System.Drawing.Color.White;
            this.btnCloseRetry.Text = "CLOSE / RETRY";
            this.btnCloseRetry.UseVisualStyleBackColor = false;
            // BarcodeRecoveryDialog
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(720, 488);
            this.Controls.Add(this.rootLayout);
            this.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "BarcodeRecoveryDialog";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Barcode Recovery";
            this.TopMost = true;
            this.rootLayout.ResumeLayout(false);
            this.infoLayout.ResumeLayout(false);
            this.infoLayout.PerformLayout();
            this.grpRetry.ResumeLayout(false);
            this.retryLayout.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numRetryCount)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numRetryStep)).EndInit();
            this.grpManual.ResumeLayout(false);
            this.manualLayout.ResumeLayout(false);
            this.manualLayout.PerformLayout();
            this.buttonLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
