namespace QMC.CDT_320.Ui.Dialogs
{
    partial class CstStatusDialog
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.TableLayoutPanel legendLayout;
        private System.Windows.Forms.Label legendReadyColor;
        private System.Windows.Forms.Label legendReadyText;
        private System.Windows.Forms.Label legendEmptyColor;
        private System.Windows.Forms.Label legendEmptyText;
        private System.Windows.Forms.Label legendWorkingColor;
        private System.Windows.Forms.Label legendWorkingText;
        private System.Windows.Forms.Label legendFinishColor;
        private System.Windows.Forms.Label legendFinishText;
        private System.Windows.Forms.Label legendWorkReadyColor;
        private System.Windows.Forms.Label legendWorkReadyText;
        private System.Windows.Forms.Panel slotsPanel;
        private System.Windows.Forms.TableLayoutPanel slotsLayout;
        private System.Windows.Forms.TableLayoutPanel bottomLayout;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.Label[] slotStateLabels;
        private System.Windows.Forms.Label slotState25;
        private System.Windows.Forms.Label slotState24;
        private System.Windows.Forms.Label slotState23;
        private System.Windows.Forms.Label slotState22;
        private System.Windows.Forms.Label slotState21;
        private System.Windows.Forms.Label slotState20;
        private System.Windows.Forms.Label slotState19;
        private System.Windows.Forms.Label slotState18;
        private System.Windows.Forms.Label slotState17;
        private System.Windows.Forms.Label slotState16;
        private System.Windows.Forms.Label slotState15;
        private System.Windows.Forms.Label slotState14;
        private System.Windows.Forms.Label slotState13;
        private System.Windows.Forms.Label slotState12;
        private System.Windows.Forms.Label slotState11;
        private System.Windows.Forms.Label slotState10;
        private System.Windows.Forms.Label slotState09;
        private System.Windows.Forms.Label slotState08;
        private System.Windows.Forms.Label slotState07;
        private System.Windows.Forms.Label slotState06;
        private System.Windows.Forms.Label slotState05;
        private System.Windows.Forms.Label slotState04;
        private System.Windows.Forms.Label slotState03;
        private System.Windows.Forms.Label slotState02;
        private System.Windows.Forms.Label slotState01;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.legendLayout = new System.Windows.Forms.TableLayoutPanel();
            this.legendReadyColor = new System.Windows.Forms.Label();
            this.legendReadyText = new System.Windows.Forms.Label();
            this.legendEmptyColor = new System.Windows.Forms.Label();
            this.legendEmptyText = new System.Windows.Forms.Label();
            this.legendWorkingColor = new System.Windows.Forms.Label();
            this.legendWorkingText = new System.Windows.Forms.Label();
            this.legendFinishColor = new System.Windows.Forms.Label();
            this.legendFinishText = new System.Windows.Forms.Label();
            this.legendWorkReadyColor = new System.Windows.Forms.Label();
            this.legendWorkReadyText = new System.Windows.Forms.Label();
            this.slotsPanel = new System.Windows.Forms.Panel();
            this.slotsLayout = new System.Windows.Forms.TableLayoutPanel();
            this.bottomLayout = new System.Windows.Forms.TableLayoutPanel();
            this.btnClose = new System.Windows.Forms.Button();
            this.slotState25 = new System.Windows.Forms.Label();
            this.slotState24 = new System.Windows.Forms.Label();
            this.slotState23 = new System.Windows.Forms.Label();
            this.slotState22 = new System.Windows.Forms.Label();
            this.slotState21 = new System.Windows.Forms.Label();
            this.slotState20 = new System.Windows.Forms.Label();
            this.slotState19 = new System.Windows.Forms.Label();
            this.slotState18 = new System.Windows.Forms.Label();
            this.slotState17 = new System.Windows.Forms.Label();
            this.slotState16 = new System.Windows.Forms.Label();
            this.slotState15 = new System.Windows.Forms.Label();
            this.slotState14 = new System.Windows.Forms.Label();
            this.slotState13 = new System.Windows.Forms.Label();
            this.slotState12 = new System.Windows.Forms.Label();
            this.slotState11 = new System.Windows.Forms.Label();
            this.slotState10 = new System.Windows.Forms.Label();
            this.slotState09 = new System.Windows.Forms.Label();
            this.slotState08 = new System.Windows.Forms.Label();
            this.slotState07 = new System.Windows.Forms.Label();
            this.slotState06 = new System.Windows.Forms.Label();
            this.slotState05 = new System.Windows.Forms.Label();
            this.slotState04 = new System.Windows.Forms.Label();
            this.slotState03 = new System.Windows.Forms.Label();
            this.slotState02 = new System.Windows.Forms.Label();
            this.slotState01 = new System.Windows.Forms.Label();
            this.rootLayout.SuspendLayout();
            this.legendLayout.SuspendLayout();
            this.slotsPanel.SuspendLayout();
            this.bottomLayout.SuspendLayout();
            this.SuspendLayout();
            // 
            // rootLayout
            // 
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblTitle, 0, 0);
            this.rootLayout.Controls.Add(this.legendLayout, 0, 1);
            this.rootLayout.Controls.Add(this.slotsPanel, 0, 2);
            this.rootLayout.Controls.Add(this.bottomLayout, 0, 3);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Padding = new System.Windows.Forms.Padding(10);
            this.rootLayout.RowCount = 4;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 76F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 42F));
            // 
            // lblTitle
            // 
            this.lblTitle.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitle.Font = new System.Drawing.Font("맑은 고딕", 14F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Text = "CASSETTE STATUS";
            this.lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // legendLayout
            // 
            this.legendLayout.CellBorderStyle = System.Windows.Forms.TableLayoutPanelCellBorderStyle.Single;
            this.legendLayout.ColumnCount = 6;
            this.legendLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.legendLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.legendLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.legendLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.legendLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.legendLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.legendLayout.Controls.Add(this.legendReadyColor, 0, 0);
            this.legendLayout.Controls.Add(this.legendReadyText, 1, 0);
            this.legendLayout.Controls.Add(this.legendEmptyColor, 2, 0);
            this.legendLayout.Controls.Add(this.legendEmptyText, 3, 0);
            this.legendLayout.Controls.Add(this.legendWorkingColor, 4, 0);
            this.legendLayout.Controls.Add(this.legendWorkingText, 5, 0);
            this.legendLayout.Controls.Add(this.legendFinishColor, 0, 1);
            this.legendLayout.Controls.Add(this.legendFinishText, 1, 1);
            this.legendLayout.Controls.Add(this.legendWorkReadyColor, 2, 1);
            this.legendLayout.Controls.Add(this.legendWorkReadyText, 3, 1);
            this.legendLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.legendLayout.Margin = new System.Windows.Forms.Padding(0, 10, 0, 10);
            this.legendLayout.RowCount = 2;
            this.legendLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.legendLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.legendReadyColor.BackColor = System.Drawing.Color.Cyan;
            this.legendReadyText.Text = "READY";
            this.legendEmptyColor.BackColor = System.Drawing.Color.LimeGreen;
            this.legendEmptyText.Text = "EMPTY";
            this.legendWorkingColor.BackColor = System.Drawing.Color.Orange;
            this.legendWorkingText.Text = "WORKING";
            this.legendFinishColor.BackColor = System.Drawing.Color.Red;
            this.legendFinishText.Text = "FINISH";
            this.legendWorkReadyColor.BackColor = System.Drawing.Color.Navy;
            this.legendWorkReadyText.Text = "WORK READY";
            this.legendReadyColor.Dock = System.Windows.Forms.DockStyle.Fill;
            this.legendEmptyColor.Dock = System.Windows.Forms.DockStyle.Fill;
            this.legendWorkingColor.Dock = System.Windows.Forms.DockStyle.Fill;
            this.legendFinishColor.Dock = System.Windows.Forms.DockStyle.Fill;
            this.legendWorkReadyColor.Dock = System.Windows.Forms.DockStyle.Fill;
            this.legendReadyText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.legendEmptyText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.legendWorkingText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.legendFinishText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.legendWorkReadyText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.legendReadyText.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.legendEmptyText.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.legendWorkingText.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.legendFinishText.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.legendWorkReadyText.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.legendReadyText.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.legendEmptyText.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.legendWorkingText.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.legendFinishText.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.legendWorkReadyText.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // slotsPanel
            // 
            this.slotsPanel.AutoScroll = true;
            this.slotsPanel.BackColor = System.Drawing.Color.White;
            this.slotsPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.slotsPanel.Controls.Add(this.slotsLayout);
            this.slotsPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            // 
            // slotsLayout
            // 
            this.slotsLayout.ColumnCount = 2;
            this.slotsLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 44F));
            this.slotsLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.slotsLayout.Dock = System.Windows.Forms.DockStyle.Top;
            this.slotsLayout.RowCount = 25;
            this.slotsLayout.Size = new System.Drawing.Size(480, 600);
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.slotsLayout.Controls.Add(this.slotState25, 0, 0);
            this.slotsLayout.Controls.Add(this.slotState24, 0, 1);
            this.slotsLayout.Controls.Add(this.slotState23, 0, 2);
            this.slotsLayout.Controls.Add(this.slotState22, 0, 3);
            this.slotsLayout.Controls.Add(this.slotState21, 0, 4);
            this.slotsLayout.Controls.Add(this.slotState20, 0, 5);
            this.slotsLayout.Controls.Add(this.slotState19, 0, 6);
            this.slotsLayout.Controls.Add(this.slotState18, 0, 7);
            this.slotsLayout.Controls.Add(this.slotState17, 0, 8);
            this.slotsLayout.Controls.Add(this.slotState16, 0, 9);
            this.slotsLayout.Controls.Add(this.slotState15, 0, 10);
            this.slotsLayout.Controls.Add(this.slotState14, 0, 11);
            this.slotsLayout.Controls.Add(this.slotState13, 0, 12);
            this.slotsLayout.Controls.Add(this.slotState12, 0, 13);
            this.slotsLayout.Controls.Add(this.slotState11, 0, 14);
            this.slotsLayout.Controls.Add(this.slotState10, 0, 15);
            this.slotsLayout.Controls.Add(this.slotState09, 0, 16);
            this.slotsLayout.Controls.Add(this.slotState08, 0, 17);
            this.slotsLayout.Controls.Add(this.slotState07, 0, 18);
            this.slotsLayout.Controls.Add(this.slotState06, 0, 19);
            this.slotsLayout.Controls.Add(this.slotState05, 0, 20);
            this.slotsLayout.Controls.Add(this.slotState04, 0, 21);
            this.slotsLayout.Controls.Add(this.slotState03, 0, 22);
            this.slotsLayout.Controls.Add(this.slotState02, 0, 23);
            this.slotsLayout.Controls.Add(this.slotState01, 0, 24);
            this.slotsLayout.SetColumnSpan(this.slotState25, 2);
            this.slotsLayout.SetColumnSpan(this.slotState24, 2);
            this.slotsLayout.SetColumnSpan(this.slotState23, 2);
            this.slotsLayout.SetColumnSpan(this.slotState22, 2);
            this.slotsLayout.SetColumnSpan(this.slotState21, 2);
            this.slotsLayout.SetColumnSpan(this.slotState20, 2);
            this.slotsLayout.SetColumnSpan(this.slotState19, 2);
            this.slotsLayout.SetColumnSpan(this.slotState18, 2);
            this.slotsLayout.SetColumnSpan(this.slotState17, 2);
            this.slotsLayout.SetColumnSpan(this.slotState16, 2);
            this.slotsLayout.SetColumnSpan(this.slotState15, 2);
            this.slotsLayout.SetColumnSpan(this.slotState14, 2);
            this.slotsLayout.SetColumnSpan(this.slotState13, 2);
            this.slotsLayout.SetColumnSpan(this.slotState12, 2);
            this.slotsLayout.SetColumnSpan(this.slotState11, 2);
            this.slotsLayout.SetColumnSpan(this.slotState10, 2);
            this.slotsLayout.SetColumnSpan(this.slotState09, 2);
            this.slotsLayout.SetColumnSpan(this.slotState08, 2);
            this.slotsLayout.SetColumnSpan(this.slotState07, 2);
            this.slotsLayout.SetColumnSpan(this.slotState06, 2);
            this.slotsLayout.SetColumnSpan(this.slotState05, 2);
            this.slotsLayout.SetColumnSpan(this.slotState04, 2);
            this.slotsLayout.SetColumnSpan(this.slotState03, 2);
            this.slotsLayout.SetColumnSpan(this.slotState02, 2);
            this.slotsLayout.SetColumnSpan(this.slotState01, 2);
            this.slotState25.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState25.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState25.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState25.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState25.Text = "25";
            this.slotState25.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState24.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState24.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState24.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState24.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState24.Text = "24";
            this.slotState24.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState23.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState23.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState23.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState23.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState23.Text = "23";
            this.slotState23.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState22.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState22.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState22.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState22.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState22.Text = "22";
            this.slotState22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState21.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState21.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState21.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState21.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState21.Text = "21";
            this.slotState21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState20.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState20.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState20.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState20.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState20.Text = "20";
            this.slotState20.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState19.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState19.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState19.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState19.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState19.Text = "19";
            this.slotState19.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState18.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState18.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState18.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState18.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState18.Text = "18";
            this.slotState18.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState17.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState17.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState17.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState17.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState17.Text = "17";
            this.slotState17.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState16.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState16.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState16.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState16.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState16.Text = "16";
            this.slotState16.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState15.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState15.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState15.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState15.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState15.Text = "15";
            this.slotState15.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState14.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState14.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState14.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState14.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState14.Text = "14";
            this.slotState14.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState13.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState13.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState13.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState13.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState13.Text = "13";
            this.slotState13.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState12.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState12.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState12.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState12.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState12.Text = "12";
            this.slotState12.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState11.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState11.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState11.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState11.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState11.Text = "11";
            this.slotState11.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState10.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState10.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState10.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState10.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState10.Text = "10";
            this.slotState10.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState09.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState09.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState09.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState09.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState09.Text = "09";
            this.slotState09.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState08.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState08.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState08.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState08.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState08.Text = "08";
            this.slotState08.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState07.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState07.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState07.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState07.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState07.Text = "07";
            this.slotState07.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState06.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState06.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState06.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState06.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState06.Text = "06";
            this.slotState06.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState05.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState05.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState05.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState05.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState05.Text = "05";
            this.slotState05.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState04.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState04.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState04.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState04.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState04.Text = "04";
            this.slotState04.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState03.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState03.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState03.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState03.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState03.Text = "03";
            this.slotState03.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState02.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState02.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState02.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState02.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState02.Text = "02";
            this.slotState02.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotState01.BackColor = System.Drawing.Color.LimeGreen;
            this.slotState01.Dock = System.Windows.Forms.DockStyle.Fill;
            this.slotState01.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold);
            this.slotState01.Margin = new System.Windows.Forms.Padding(0, 1, 0, 1);
            this.slotState01.Text = "01";
            this.slotState01.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.slotStateLabels = new System.Windows.Forms.Label[]
            {
                this.slotState25, this.slotState24, this.slotState23, this.slotState22, this.slotState21, this.slotState20, this.slotState19, this.slotState18, this.slotState17, this.slotState16, this.slotState15, this.slotState14, this.slotState13,
                this.slotState12, this.slotState11, this.slotState10, this.slotState09, this.slotState08, this.slotState07, this.slotState06, this.slotState05, this.slotState04, this.slotState03, this.slotState02, this.slotState01
            };
            // 
            // bottomLayout
            // 
            this.bottomLayout.ColumnCount = 3;
            this.bottomLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.bottomLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 110F));
            this.bottomLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 1F));
            this.bottomLayout.Controls.Add(this.btnClose, 1, 0);
            this.bottomLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bottomLayout.Padding = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.bottomLayout.RowCount = 1;
            this.bottomLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnClose.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnClose.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.btnClose.Tag = "i18n:common.ok";
            this.btnClose.Text = "OK";
            // 
            // CstStatusDialog
            // 
            this.AcceptButton = this.btnClose;
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.ClientSize = new System.Drawing.Size(520, 720);
            this.Controls.Add(this.rootLayout);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "CstStatusDialog";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "CASSETTE STATUS";
            this.rootLayout.ResumeLayout(false);
            this.legendLayout.ResumeLayout(false);
            this.slotsPanel.ResumeLayout(false);
            this.bottomLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
