namespace QMC.CDT_320.Ui.Dialogs
{
    partial class InputStageRunReviewDialog
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.TableLayoutPanel headerLayout;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label lblDialogMode;
        private System.Windows.Forms.Label lblWaferCaption;
        private System.Windows.Forms.Label lblWaferValue;
        private System.Windows.Forms.Label lblRecipeCaption;
        private System.Windows.Forms.Label lblRecipeValue;
        private System.Windows.Forms.Label lblVisionCaption;
        private System.Windows.Forms.Label lblVisionValue;
        private System.Windows.Forms.Label lblAlignCaption;
        private System.Windows.Forms.Label lblAlignValue;
        private System.Windows.Forms.Label lblMappingCaption;
        private System.Windows.Forms.Label lblMappingValue;
        private System.Windows.Forms.Label lblReviewCaption;
        private System.Windows.Forms.Label lblReviewValue;
        private System.Windows.Forms.TableLayoutPanel bodyLayout;
        private System.Windows.Forms.TableLayoutPanel leftLayout;
        private QMC.CDT320.Ui.Controls.DieMapView mapView;
        private System.Windows.Forms.DataGridView dieGrid;
        private System.Windows.Forms.DataGridViewTextBoxColumn colSequence;
        private System.Windows.Forms.DataGridViewTextBoxColumn colMapX;
        private System.Windows.Forms.DataGridViewTextBoxColumn colMapY;
        private System.Windows.Forms.DataGridViewTextBoxColumn colGridX;
        private System.Windows.Forms.DataGridViewTextBoxColumn colGridY;
        private System.Windows.Forms.DataGridViewTextBoxColumn colOriginalX;
        private System.Windows.Forms.DataGridViewTextBoxColumn colOriginalY;
        private System.Windows.Forms.DataGridViewTextBoxColumn colState;
        private System.Windows.Forms.DataGridViewTextBoxColumn colResult;
        private System.Windows.Forms.DataGridViewTextBoxColumn colBin;
        private System.Windows.Forms.DataGridViewTextBoxColumn colPosX;
        private System.Windows.Forms.DataGridViewTextBoxColumn colPosY;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDieUid;
        private System.Windows.Forms.TableLayoutPanel centerLayout;
        private System.Windows.Forms.GroupBox grpDieState;
        private System.Windows.Forms.TableLayoutPanel dieStateLayout;
        private System.Windows.Forms.FlowLayoutPanel dieStateOptions;
        private System.Windows.Forms.RadioButton rbDieStateWait;
        private System.Windows.Forms.RadioButton rbDieStateGood;
        private System.Windows.Forms.RadioButton rbDieStateNg;
        private System.Windows.Forms.RadioButton rbDieStateSkip;
        private System.Windows.Forms.Button btnApplyDieState;
        private System.Windows.Forms.GroupBox grpStartDie;
        private System.Windows.Forms.TableLayoutPanel startDieLayout;
        private System.Windows.Forms.Label lblStartDieCaption;
        private System.Windows.Forms.Label lblStartDieValue;
        private System.Windows.Forms.Label lblStartIndexCaption;
        private System.Windows.Forms.NumericUpDown numStartIndex;
        private System.Windows.Forms.Button btnSetStartIndex;
        private System.Windows.Forms.CheckBox chkUseSelectedStart;
        private System.Windows.Forms.Button btnSetStartDie;
        private System.Windows.Forms.GroupBox grpJog;
        private System.Windows.Forms.TableLayoutPanel jogLayout;
        private System.Windows.Forms.Label lblJogSpeed;
        private System.Windows.Forms.ComboBox cmbJogSpeed;
        private System.Windows.Forms.Label lblVisionXCaption;
        private System.Windows.Forms.Label lblVisionXValue;
        private System.Windows.Forms.Button btnVisionXMinus;
        private System.Windows.Forms.Button btnVisionXPlus;
        private System.Windows.Forms.Label lblWaferYCaption;
        private System.Windows.Forms.Label lblWaferYValue;
        private System.Windows.Forms.Button btnWaferYMinus;
        private System.Windows.Forms.Button btnWaferYPlus;
        private System.Windows.Forms.Label lblWaferTCaption;
        private System.Windows.Forms.Label lblWaferTValue;
        private System.Windows.Forms.Button btnWaferTMinus;
        private System.Windows.Forms.Button btnWaferTPlus;
        private System.Windows.Forms.Button btnJogStop;
        private System.Windows.Forms.GroupBox grpActions;
        private System.Windows.Forms.TableLayoutPanel actionLayout;
        private System.Windows.Forms.Button btnMoveSelectedDie;
        private System.Windows.Forms.Button btnThetaCorrection;
        private System.Windows.Forms.Button btnDieDetection;
        private System.Windows.Forms.Button btnOffsetApply;
        private System.Windows.Forms.Button btnVisionTest;
        private System.Windows.Forms.TableLayoutPanel rightLayout;
        private System.Windows.Forms.GroupBox grpMapInfo;
        private System.Windows.Forms.TableLayoutPanel mapInfoLayout;
        private System.Windows.Forms.Label lblMapGridCaption;
        private System.Windows.Forms.Label lblMapGridValue;
        private System.Windows.Forms.Label lblMapProgressCaption;
        private System.Windows.Forms.Label lblMapProgressValue;
        private System.Windows.Forms.Label lblTargetCountCaption;
        private System.Windows.Forms.Label lblTargetCountValue;
        private System.Windows.Forms.Label lblDieSizeXCaption;
        private System.Windows.Forms.Label lblDieSizeXValue;
        private System.Windows.Forms.Label lblDieSizeYCaption;
        private System.Windows.Forms.Label lblDieSizeYValue;
        private System.Windows.Forms.Label lblPitchGapXCaption;
        private System.Windows.Forms.Label lblPitchGapXValue;
        private System.Windows.Forms.Label lblPitchGapYCaption;
        private System.Windows.Forms.Label lblPitchGapYValue;
        private System.Windows.Forms.Label lblWaferDiameterCaption;
        private System.Windows.Forms.Label lblWaferDiameterValue;
        private System.Windows.Forms.Label lblInputCameraXCaption;
        private System.Windows.Forms.Label lblInputCameraXValue;
        private System.Windows.Forms.Label lblInputStageYCaption;
        private System.Windows.Forms.Label lblInputStageYValue;
        private System.Windows.Forms.Label lblEquipmentGridCaption;
        private System.Windows.Forms.Label lblEquipmentGridValue;
        private System.Windows.Forms.Label lblOriginalMapCaption;
        private System.Windows.Forms.Label lblOriginalMapValue;
        private System.Windows.Forms.Label lblMappingOriginCaption;
        private System.Windows.Forms.Label lblMappingOriginValue;
        private System.Windows.Forms.Label lblSelectedDieCaption;
        private System.Windows.Forms.Label lblSelectedDieValue;
        private System.Windows.Forms.Label lblSelectedSequenceCaption;
        private System.Windows.Forms.Label lblSelectedSequenceValue;
        private System.Windows.Forms.Label lblSelectedPositionCaption;
        private System.Windows.Forms.Label lblSelectedPositionValue;
        private System.Windows.Forms.GroupBox grpPickupRoute;
        private System.Windows.Forms.TableLayoutPanel pickupRouteLayout;
        private System.Windows.Forms.Label lblCornerCaption;
        private System.Windows.Forms.FlowLayoutPanel cornerOptions;
        private System.Windows.Forms.RadioButton rbCornerTopLeft;
        private System.Windows.Forms.RadioButton rbCornerTopRight;
        private System.Windows.Forms.RadioButton rbCornerBottomLeft;
        private System.Windows.Forms.RadioButton rbCornerBottomRight;
        private System.Windows.Forms.Label lblDirectionCaption;
        private System.Windows.Forms.FlowLayoutPanel directionOptions;
        private System.Windows.Forms.RadioButton rbDirectionHorizontal;
        private System.Windows.Forms.RadioButton rbDirectionVertical;
        private System.Windows.Forms.Label lblPatternCaption;
        private System.Windows.Forms.FlowLayoutPanel patternOptions;
        private System.Windows.Forms.RadioButton rbPatternStraight;
        private System.Windows.Forms.RadioButton rbPatternZigZag;
        private System.Windows.Forms.Button btnPreviewPath;
        private System.Windows.Forms.Button btnApplyPickupOrder;
        private System.Windows.Forms.GroupBox grpWorkflow;
        private System.Windows.Forms.TableLayoutPanel workflowLayout;
        private System.Windows.Forms.Label lblRevisionCaption;
        private System.Windows.Forms.Label lblMappingRevisionValue;
        private System.Windows.Forms.TextBox txtFailureDetail;
        private System.Windows.Forms.Button btnRetryAlign;
        private System.Windows.Forms.Button btnRetryMapping;
        private System.Windows.Forms.Button btnMappingSetup;
        private System.Windows.Forms.Button btnStartRun;
        private System.Windows.Forms.Button btnAbortAuto;
        private System.Windows.Forms.TableLayoutPanel footerLayout;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.Button btnClose;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle headerStyle = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle cellStyle = new System.Windows.Forms.DataGridViewCellStyle();
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.headerLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.lblDialogMode = new System.Windows.Forms.Label();
            this.lblWaferCaption = new System.Windows.Forms.Label();
            this.lblWaferValue = new System.Windows.Forms.Label();
            this.lblRecipeCaption = new System.Windows.Forms.Label();
            this.lblRecipeValue = new System.Windows.Forms.Label();
            this.lblVisionCaption = new System.Windows.Forms.Label();
            this.lblVisionValue = new System.Windows.Forms.Label();
            this.lblAlignCaption = new System.Windows.Forms.Label();
            this.lblAlignValue = new System.Windows.Forms.Label();
            this.lblMappingCaption = new System.Windows.Forms.Label();
            this.lblMappingValue = new System.Windows.Forms.Label();
            this.lblReviewCaption = new System.Windows.Forms.Label();
            this.lblReviewValue = new System.Windows.Forms.Label();
            this.bodyLayout = new System.Windows.Forms.TableLayoutPanel();
            this.leftLayout = new System.Windows.Forms.TableLayoutPanel();
            this.mapView = new QMC.CDT320.Ui.Controls.DieMapView();
            this.dieGrid = new System.Windows.Forms.DataGridView();
            this.colSequence = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colMapX = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colMapY = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colGridX = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colGridY = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colOriginalX = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colOriginalY = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colState = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colResult = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colBin = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colPosX = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colPosY = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colDieUid = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.centerLayout = new System.Windows.Forms.TableLayoutPanel();
            this.grpDieState = new System.Windows.Forms.GroupBox();
            this.dieStateLayout = new System.Windows.Forms.TableLayoutPanel();
            this.dieStateOptions = new System.Windows.Forms.FlowLayoutPanel();
            this.rbDieStateWait = new System.Windows.Forms.RadioButton();
            this.rbDieStateGood = new System.Windows.Forms.RadioButton();
            this.rbDieStateNg = new System.Windows.Forms.RadioButton();
            this.rbDieStateSkip = new System.Windows.Forms.RadioButton();
            this.btnApplyDieState = new System.Windows.Forms.Button();
            this.grpStartDie = new System.Windows.Forms.GroupBox();
            this.startDieLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblStartDieCaption = new System.Windows.Forms.Label();
            this.lblStartDieValue = new System.Windows.Forms.Label();
            this.lblStartIndexCaption = new System.Windows.Forms.Label();
            this.numStartIndex = new System.Windows.Forms.NumericUpDown();
            this.btnSetStartIndex = new System.Windows.Forms.Button();
            this.chkUseSelectedStart = new System.Windows.Forms.CheckBox();
            this.btnSetStartDie = new System.Windows.Forms.Button();
            this.grpJog = new System.Windows.Forms.GroupBox();
            this.jogLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblJogSpeed = new System.Windows.Forms.Label();
            this.cmbJogSpeed = new System.Windows.Forms.ComboBox();
            this.lblVisionXCaption = new System.Windows.Forms.Label();
            this.lblVisionXValue = new System.Windows.Forms.Label();
            this.btnVisionXMinus = new System.Windows.Forms.Button();
            this.btnVisionXPlus = new System.Windows.Forms.Button();
            this.lblWaferYCaption = new System.Windows.Forms.Label();
            this.lblWaferYValue = new System.Windows.Forms.Label();
            this.btnWaferYMinus = new System.Windows.Forms.Button();
            this.btnWaferYPlus = new System.Windows.Forms.Button();
            this.lblWaferTCaption = new System.Windows.Forms.Label();
            this.lblWaferTValue = new System.Windows.Forms.Label();
            this.btnWaferTMinus = new System.Windows.Forms.Button();
            this.btnWaferTPlus = new System.Windows.Forms.Button();
            this.btnJogStop = new System.Windows.Forms.Button();
            this.grpActions = new System.Windows.Forms.GroupBox();
            this.actionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.btnMoveSelectedDie = new System.Windows.Forms.Button();
            this.btnThetaCorrection = new System.Windows.Forms.Button();
            this.btnDieDetection = new System.Windows.Forms.Button();
            this.btnOffsetApply = new System.Windows.Forms.Button();
            this.btnVisionTest = new System.Windows.Forms.Button();
            this.rightLayout = new System.Windows.Forms.TableLayoutPanel();
            this.grpMapInfo = new System.Windows.Forms.GroupBox();
            this.mapInfoLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblMapGridCaption = new System.Windows.Forms.Label();
            this.lblMapGridValue = new System.Windows.Forms.Label();
            this.lblMapProgressCaption = new System.Windows.Forms.Label();
            this.lblMapProgressValue = new System.Windows.Forms.Label();
            this.lblTargetCountCaption = new System.Windows.Forms.Label();
            this.lblTargetCountValue = new System.Windows.Forms.Label();
            this.lblDieSizeXCaption = new System.Windows.Forms.Label();
            this.lblDieSizeXValue = new System.Windows.Forms.Label();
            this.lblDieSizeYCaption = new System.Windows.Forms.Label();
            this.lblDieSizeYValue = new System.Windows.Forms.Label();
            this.lblPitchGapXCaption = new System.Windows.Forms.Label();
            this.lblPitchGapXValue = new System.Windows.Forms.Label();
            this.lblPitchGapYCaption = new System.Windows.Forms.Label();
            this.lblPitchGapYValue = new System.Windows.Forms.Label();
            this.lblWaferDiameterCaption = new System.Windows.Forms.Label();
            this.lblWaferDiameterValue = new System.Windows.Forms.Label();
            this.lblInputCameraXCaption = new System.Windows.Forms.Label();
            this.lblInputCameraXValue = new System.Windows.Forms.Label();
            this.lblInputStageYCaption = new System.Windows.Forms.Label();
            this.lblInputStageYValue = new System.Windows.Forms.Label();
            this.lblEquipmentGridCaption = new System.Windows.Forms.Label();
            this.lblEquipmentGridValue = new System.Windows.Forms.Label();
            this.lblOriginalMapCaption = new System.Windows.Forms.Label();
            this.lblOriginalMapValue = new System.Windows.Forms.Label();
            this.lblMappingOriginCaption = new System.Windows.Forms.Label();
            this.lblMappingOriginValue = new System.Windows.Forms.Label();
            this.lblSelectedDieCaption = new System.Windows.Forms.Label();
            this.lblSelectedDieValue = new System.Windows.Forms.Label();
            this.lblSelectedSequenceCaption = new System.Windows.Forms.Label();
            this.lblSelectedSequenceValue = new System.Windows.Forms.Label();
            this.lblSelectedPositionCaption = new System.Windows.Forms.Label();
            this.lblSelectedPositionValue = new System.Windows.Forms.Label();
            this.grpPickupRoute = new System.Windows.Forms.GroupBox();
            this.pickupRouteLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblCornerCaption = new System.Windows.Forms.Label();
            this.cornerOptions = new System.Windows.Forms.FlowLayoutPanel();
            this.rbCornerTopLeft = new System.Windows.Forms.RadioButton();
            this.rbCornerTopRight = new System.Windows.Forms.RadioButton();
            this.rbCornerBottomLeft = new System.Windows.Forms.RadioButton();
            this.rbCornerBottomRight = new System.Windows.Forms.RadioButton();
            this.lblDirectionCaption = new System.Windows.Forms.Label();
            this.directionOptions = new System.Windows.Forms.FlowLayoutPanel();
            this.rbDirectionHorizontal = new System.Windows.Forms.RadioButton();
            this.rbDirectionVertical = new System.Windows.Forms.RadioButton();
            this.lblPatternCaption = new System.Windows.Forms.Label();
            this.patternOptions = new System.Windows.Forms.FlowLayoutPanel();
            this.rbPatternStraight = new System.Windows.Forms.RadioButton();
            this.rbPatternZigZag = new System.Windows.Forms.RadioButton();
            this.btnPreviewPath = new System.Windows.Forms.Button();
            this.btnApplyPickupOrder = new System.Windows.Forms.Button();
            this.grpWorkflow = new System.Windows.Forms.GroupBox();
            this.workflowLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblRevisionCaption = new System.Windows.Forms.Label();
            this.lblMappingRevisionValue = new System.Windows.Forms.Label();
            this.txtFailureDetail = new System.Windows.Forms.TextBox();
            this.btnRetryAlign = new System.Windows.Forms.Button();
            this.btnRetryMapping = new System.Windows.Forms.Button();
            this.btnMappingSetup = new System.Windows.Forms.Button();
            this.btnStartRun = new System.Windows.Forms.Button();
            this.btnAbortAuto = new System.Windows.Forms.Button();
            this.footerLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblStatus = new System.Windows.Forms.Label();
            this.btnClose = new System.Windows.Forms.Button();
            this.rootLayout.SuspendLayout();
            this.headerLayout.SuspendLayout();
            this.bodyLayout.SuspendLayout();
            this.leftLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dieGrid)).BeginInit();
            this.centerLayout.SuspendLayout();
            this.grpDieState.SuspendLayout();
            this.dieStateLayout.SuspendLayout();
            this.dieStateOptions.SuspendLayout();
            this.grpStartDie.SuspendLayout();
            this.startDieLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numStartIndex)).BeginInit();
            this.grpJog.SuspendLayout();
            this.jogLayout.SuspendLayout();
            this.grpActions.SuspendLayout();
            this.actionLayout.SuspendLayout();
            this.rightLayout.SuspendLayout();
            this.grpMapInfo.SuspendLayout();
            this.mapInfoLayout.SuspendLayout();
            this.grpPickupRoute.SuspendLayout();
            this.pickupRouteLayout.SuspendLayout();
            this.cornerOptions.SuspendLayout();
            this.directionOptions.SuspendLayout();
            this.patternOptions.SuspendLayout();
            this.grpWorkflow.SuspendLayout();
            this.workflowLayout.SuspendLayout();
            this.footerLayout.SuspendLayout();
            this.SuspendLayout();
            //
            // rootLayout
            //
            this.rootLayout.BackColor = System.Drawing.Color.FromArgb(238, 241, 245);
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.headerLayout, 0, 0);
            this.rootLayout.Controls.Add(this.bodyLayout, 0, 1);
            this.rootLayout.Controls.Add(this.footerLayout, 0, 2);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Location = new System.Drawing.Point(8, 8);
            this.rootLayout.Name = "rootLayout";
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 72F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 64F));
            this.rootLayout.Size = new System.Drawing.Size(1724, 924);
            this.rootLayout.TabIndex = 0;
            //
            // headerLayout
            //
            this.headerLayout.BackColor = System.Drawing.Color.FromArgb(42, 48, 58);
            this.headerLayout.ColumnCount = 14;
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 280F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 145F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 55F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 24F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 60F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 58F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 55F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 62F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14F));
            this.headerLayout.Controls.Add(this.lblTitle, 0, 0);
            this.headerLayout.Controls.Add(this.lblDialogMode, 1, 0);
            this.headerLayout.Controls.Add(this.lblWaferCaption, 2, 0);
            this.headerLayout.Controls.Add(this.lblWaferValue, 3, 0);
            this.headerLayout.Controls.Add(this.lblRecipeCaption, 4, 0);
            this.headerLayout.Controls.Add(this.lblRecipeValue, 5, 0);
            this.headerLayout.Controls.Add(this.lblVisionCaption, 6, 0);
            this.headerLayout.Controls.Add(this.lblVisionValue, 7, 0);
            this.headerLayout.Controls.Add(this.lblAlignCaption, 8, 0);
            this.headerLayout.Controls.Add(this.lblAlignValue, 9, 0);
            this.headerLayout.Controls.Add(this.lblMappingCaption, 10, 0);
            this.headerLayout.Controls.Add(this.lblMappingValue, 11, 0);
            this.headerLayout.Controls.Add(this.lblReviewCaption, 12, 0);
            this.headerLayout.Controls.Add(this.lblReviewValue, 13, 0);
            this.headerLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.headerLayout.Margin = new System.Windows.Forms.Padding(0, 0, 0, 6);
            this.headerLayout.Name = "headerLayout";
            this.headerLayout.RowCount = 1;
            this.headerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.headerLayout.TabIndex = 0;
            //
            // header labels
            //
            this.lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitle.Font = new System.Drawing.Font("맑은 고딕", 15F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Text = "WAFER ALIGN / DIE MAP REVIEW";
            this.lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblTitle.Padding = new System.Windows.Forms.Padding(14, 0, 0, 0);
            this.lblDialogMode.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDialogMode.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.lblDialogMode.ForeColor = System.Drawing.Color.White;
            this.lblDialogMode.Margin = new System.Windows.Forms.Padding(6, 14, 6, 14);
            this.lblDialogMode.Text = "MAPPING REVIEW";
            this.lblDialogMode.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblWaferCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblWaferCaption.ForeColor = System.Drawing.Color.Silver;
            this.lblWaferCaption.Text = "WAFER";
            this.lblWaferCaption.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblWaferValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblWaferValue.ForeColor = System.Drawing.Color.White;
            this.lblWaferValue.Text = "-";
            this.lblWaferValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblRecipeCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRecipeCaption.ForeColor = System.Drawing.Color.Silver;
            this.lblRecipeCaption.Text = "RECIPE";
            this.lblRecipeCaption.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblRecipeValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRecipeValue.ForeColor = System.Drawing.Color.White;
            this.lblRecipeValue.Text = "-";
            this.lblRecipeValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblVisionCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVisionCaption.ForeColor = System.Drawing.Color.Silver;
            this.lblVisionCaption.Text = "VISION";
            this.lblVisionCaption.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblVisionValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVisionValue.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblVisionValue.Text = "-";
            this.lblVisionValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblAlignCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAlignCaption.ForeColor = System.Drawing.Color.Silver;
            this.lblAlignCaption.Text = "ALIGN";
            this.lblAlignCaption.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblAlignValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAlignValue.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblAlignValue.Text = "-";
            this.lblAlignValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblMappingCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblMappingCaption.ForeColor = System.Drawing.Color.Silver;
            this.lblMappingCaption.Text = "MAPPING";
            this.lblMappingCaption.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblMappingValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblMappingValue.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblMappingValue.Text = "-";
            this.lblMappingValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblReviewCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblReviewCaption.ForeColor = System.Drawing.Color.Silver;
            this.lblReviewCaption.Text = "REVIEW";
            this.lblReviewCaption.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblReviewValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblReviewValue.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblReviewValue.ForeColor = System.Drawing.Color.Khaki;
            this.lblReviewValue.Text = "REQUIRED";
            this.lblReviewValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            //
            // bodyLayout
            //
            this.bodyLayout.ColumnCount = 3;
            this.bodyLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 51F));
            this.bodyLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.bodyLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 24F));
            this.bodyLayout.Controls.Add(this.leftLayout, 0, 0);
            this.bodyLayout.Controls.Add(this.centerLayout, 1, 0);
            this.bodyLayout.Controls.Add(this.rightLayout, 2, 0);
            this.bodyLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bodyLayout.Margin = new System.Windows.Forms.Padding(0);
            this.bodyLayout.Name = "bodyLayout";
            this.bodyLayout.RowCount = 1;
            this.bodyLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.bodyLayout.TabIndex = 1;
            //
            // leftLayout
            //
            this.leftLayout.ColumnCount = 1;
            this.leftLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.leftLayout.Controls.Add(this.mapView, 0, 0);
            this.leftLayout.Controls.Add(this.dieGrid, 0, 1);
            this.leftLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.leftLayout.Margin = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.leftLayout.Name = "leftLayout";
            this.leftLayout.RowCount = 2;
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 64F));
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 36F));
            this.leftLayout.TabIndex = 0;
            //
            // mapView
            //
            this.mapView.BackColor = System.Drawing.Color.White;
            this.mapView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mapView.Location = new System.Drawing.Point(0, 0);
            this.mapView.Margin = new System.Windows.Forms.Padding(0, 0, 0, 6);
            this.mapView.Name = "mapView";
            this.mapView.Size = new System.Drawing.Size(873, 497);
            this.mapView.TabIndex = 0;
            this.mapView.CellClicked += new System.Action<QMC.CDT320.DieMaps.DieMapEntry>(this.MapView_CellClicked);
            this.mapView.CellDoubleClicked += new System.Action<QMC.CDT320.DieMaps.DieMapEntry>(this.MapView_CellDoubleClicked);
            this.mapView.SelectionRectangleCompleted += new System.Action<System.Collections.Generic.IReadOnlyList<QMC.CDT320.DieMaps.DieMapEntry>>(this.MapView_SelectionRectangleCompleted);
            //
            // dieGrid
            //
            this.dieGrid.AllowUserToAddRows = false;
            this.dieGrid.AllowUserToDeleteRows = false;
            this.dieGrid.AllowUserToResizeRows = false;
            this.dieGrid.BackgroundColor = System.Drawing.Color.White;
            this.dieGrid.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            headerStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            headerStyle.BackColor = System.Drawing.Color.FromArgb(225, 230, 236);
            headerStyle.Font = new System.Drawing.Font("맑은 고딕", 8.5F, System.Drawing.FontStyle.Bold);
            headerStyle.ForeColor = System.Drawing.Color.FromArgb(42, 48, 58);
            headerStyle.SelectionBackColor = System.Drawing.Color.FromArgb(225, 230, 236);
            headerStyle.SelectionForeColor = System.Drawing.Color.FromArgb(42, 48, 58);
            headerStyle.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dieGrid.ColumnHeadersDefaultCellStyle = headerStyle;
            this.dieGrid.ColumnHeadersHeight = 36;
            this.dieGrid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dieGrid.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.colSequence,
            this.colMapX,
            this.colMapY,
            this.colGridX,
            this.colGridY,
            this.colOriginalX,
            this.colOriginalY,
            this.colState,
            this.colResult,
            this.colBin,
            this.colPosX,
            this.colPosY,
            this.colDieUid});
            cellStyle.BackColor = System.Drawing.Color.White;
            cellStyle.ForeColor = System.Drawing.Color.FromArgb(42, 48, 58);
            cellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(48, 121, 190);
            cellStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dieGrid.DefaultCellStyle = cellStyle;
            this.dieGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dieGrid.Location = new System.Drawing.Point(0, 503);
            this.dieGrid.Margin = new System.Windows.Forms.Padding(0);
            this.dieGrid.MultiSelect = false;
            this.dieGrid.Name = "dieGrid";
            this.dieGrid.ReadOnly = true;
            this.dieGrid.RowHeadersVisible = false;
            this.dieGrid.RowTemplate.Height = 26;
            this.dieGrid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dieGrid.TabIndex = 1;
            this.dieGrid.SelectionChanged += new System.EventHandler(this.DieGrid_SelectionChanged);
            this.colSequence.HeaderText = "SEQ";
            this.colSequence.Name = "colSequence";
            this.colSequence.ReadOnly = true;
            this.colSequence.Width = 52;
            this.colMapX.HeaderText = "MAP X";
            this.colMapX.Name = "colMapX";
            this.colMapX.ReadOnly = true;
            this.colMapX.Width = 55;
            this.colMapY.HeaderText = "MAP Y";
            this.colMapY.Name = "colMapY";
            this.colMapY.ReadOnly = true;
            this.colMapY.Width = 55;
            this.colGridX.HeaderText = "GRID X";
            this.colGridX.Name = "colGridX";
            this.colGridX.ReadOnly = true;
            this.colGridX.Width = 62;
            this.colGridY.HeaderText = "GRID Y";
            this.colGridY.Name = "colGridY";
            this.colGridY.ReadOnly = true;
            this.colGridY.Width = 62;
            this.colOriginalX.HeaderText = "ORG X";
            this.colOriginalX.Name = "colOriginalX";
            this.colOriginalX.ReadOnly = true;
            this.colOriginalX.Width = 58;
            this.colOriginalY.HeaderText = "ORG Y";
            this.colOriginalY.Name = "colOriginalY";
            this.colOriginalY.ReadOnly = true;
            this.colOriginalY.Width = 58;
            this.colState.HeaderText = "STATE";
            this.colState.Name = "colState";
            this.colState.ReadOnly = true;
            this.colState.Width = 70;
            this.colResult.HeaderText = "RESULT";
            this.colResult.Name = "colResult";
            this.colResult.ReadOnly = true;
            this.colResult.Width = 70;
            this.colBin.HeaderText = "BIN";
            this.colBin.Name = "colBin";
            this.colBin.ReadOnly = true;
            this.colBin.Width = 45;
            this.colPosX.HeaderText = "MACHINE X";
            this.colPosX.Name = "colPosX";
            this.colPosX.ReadOnly = true;
            this.colPosX.Width = 82;
            this.colPosY.HeaderText = "MACHINE Y";
            this.colPosY.Name = "colPosY";
            this.colPosY.ReadOnly = true;
            this.colPosY.Width = 82;
            this.colDieUid.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            this.colDieUid.HeaderText = "DIE UID";
            this.colDieUid.MinimumWidth = 120;
            this.colDieUid.Name = "colDieUid";
            this.colDieUid.ReadOnly = true;
            //
            // centerLayout
            //
            this.centerLayout.ColumnCount = 1;
            this.centerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.centerLayout.Controls.Add(this.grpDieState, 0, 0);
            this.centerLayout.Controls.Add(this.grpStartDie, 0, 1);
            this.centerLayout.Controls.Add(this.grpJog, 0, 2);
            this.centerLayout.Controls.Add(this.grpActions, 0, 3);
            this.centerLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.centerLayout.Margin = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.centerLayout.Name = "centerLayout";
            this.centerLayout.RowCount = 4;
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 180F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 235F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.centerLayout.TabIndex = 1;
            //
            // grpDieState
            //
            this.grpDieState.Controls.Add(this.dieStateLayout);
            this.grpDieState.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpDieState.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.grpDieState.Location = new System.Drawing.Point(0, 0);
            this.grpDieState.Margin = new System.Windows.Forms.Padding(0, 0, 0, 6);
            this.grpDieState.Name = "grpDieState";
            this.grpDieState.Padding = new System.Windows.Forms.Padding(8);
            this.grpDieState.Size = new System.Drawing.Size(424, 144);
            this.grpDieState.TabIndex = 0;
            this.grpDieState.TabStop = false;
            this.grpDieState.Text = "DIE STATE EDIT";
            this.dieStateLayout.ColumnCount = 1;
            this.dieStateLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.dieStateLayout.Controls.Add(this.dieStateOptions, 0, 0);
            this.dieStateLayout.Controls.Add(this.btnApplyDieState, 0, 1);
            this.dieStateLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dieStateLayout.RowCount = 2;
            this.dieStateLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.dieStateLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 42F));
            this.dieStateOptions.Controls.Add(this.rbDieStateWait);
            this.dieStateOptions.Controls.Add(this.rbDieStateGood);
            this.dieStateOptions.Controls.Add(this.rbDieStateNg);
            this.dieStateOptions.Controls.Add(this.rbDieStateSkip);
            this.dieStateOptions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dieStateOptions.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.dieStateOptions.WrapContents = false;
            this.rbDieStateWait.AutoSize = true;
            this.rbDieStateWait.Checked = true;
            this.rbDieStateWait.Margin = new System.Windows.Forms.Padding(3, 1, 3, 1);
            this.rbDieStateWait.Text = "WAIT / 검사 대기";
            this.rbDieStateGood.AutoSize = true;
            this.rbDieStateGood.Margin = new System.Windows.Forms.Padding(3, 1, 3, 1);
            this.rbDieStateGood.Text = "GOOD / 검사 완료";
            this.rbDieStateNg.AutoSize = true;
            this.rbDieStateNg.Margin = new System.Windows.Forms.Padding(3, 1, 3, 1);
            this.rbDieStateNg.Text = "NG / 검사 불량";
            this.rbDieStateSkip.AutoSize = true;
            this.rbDieStateSkip.Margin = new System.Windows.Forms.Padding(3, 1, 3, 1);
            this.rbDieStateSkip.Text = "SKIP / 제외";
            this.btnApplyDieState.BackColor = System.Drawing.Color.FromArgb(220, 228, 237);
            this.btnApplyDieState.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnApplyDieState.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnApplyDieState.Name = "btnApplyDieState";
            this.btnApplyDieState.Text = "APPLY SELECTED STATE";
            this.btnApplyDieState.UseVisualStyleBackColor = false;
            this.btnApplyDieState.Click += new System.EventHandler(this.BtnApplyDieState_Click);
            //
            // grpStartDie
            //
            this.grpStartDie.Controls.Add(this.startDieLayout);
            this.grpStartDie.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpStartDie.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.grpStartDie.Margin = new System.Windows.Forms.Padding(0, 0, 0, 6);
            this.grpStartDie.Name = "grpStartDie";
            this.grpStartDie.Padding = new System.Windows.Forms.Padding(8);
            this.grpStartDie.Text = "START DIE";
            this.startDieLayout.ColumnCount = 3;
            this.startDieLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 94F));
            this.startDieLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.startDieLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 92F));
            this.startDieLayout.Controls.Add(this.lblStartDieCaption, 0, 0);
            this.startDieLayout.Controls.Add(this.lblStartDieValue, 1, 0);
            this.startDieLayout.Controls.Add(this.btnSetStartDie, 2, 0);
            this.startDieLayout.Controls.Add(this.lblStartIndexCaption, 0, 1);
            this.startDieLayout.Controls.Add(this.numStartIndex, 1, 1);
            this.startDieLayout.Controls.Add(this.btnSetStartIndex, 2, 1);
            this.startDieLayout.Controls.Add(this.chkUseSelectedStart, 0, 2);
            this.startDieLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.startDieLayout.RowCount = 3;
            this.startDieLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 34F));
            this.startDieLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33F));
            this.startDieLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33F));
            this.startDieLayout.SetColumnSpan(this.chkUseSelectedStart, 3);
            this.lblStartDieCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStartDieCaption.Text = "Selected Die";
            this.lblStartDieCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblStartDieValue.BackColor = System.Drawing.Color.White;
            this.lblStartDieValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblStartDieValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStartDieValue.Margin = new System.Windows.Forms.Padding(3, 5, 3, 5);
            this.lblStartDieValue.Text = "NOT SET";
            this.lblStartDieValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSetStartDie.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnSetStartDie.Margin = new System.Windows.Forms.Padding(3, 4, 0, 4);
            this.btnSetStartDie.Name = "btnSetStartDie";
            this.btnSetStartDie.Text = "SET SELECT";
            this.btnSetStartDie.Click += new System.EventHandler(this.BtnSetStartDie_Click);
            this.lblStartIndexCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStartIndexCaption.Text = "Start Index";
            this.lblStartIndexCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.numStartIndex.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.numStartIndex.Maximum = new decimal(new int[] { 100000, 0, 0, 0 });
            this.numStartIndex.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.numStartIndex.Name = "numStartIndex";
            this.numStartIndex.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numStartIndex.Value = new decimal(new int[] { 1, 0, 0, 0 });
            this.btnSetStartIndex.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnSetStartIndex.Margin = new System.Windows.Forms.Padding(3, 4, 0, 4);
            this.btnSetStartIndex.Name = "btnSetStartIndex";
            this.btnSetStartIndex.Text = "SET INDEX";
            this.btnSetStartIndex.Click += new System.EventHandler(this.BtnSetStartIndex_Click);
            this.chkUseSelectedStart.AutoSize = true;
            this.chkUseSelectedStart.Checked = true;
            this.chkUseSelectedStart.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkUseSelectedStart.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chkUseSelectedStart.Text = "선택 Die를 첫 번째 순서로 사용";
            this.chkUseSelectedStart.CheckedChanged += new System.EventHandler(this.ChkUseSelectedStart_CheckedChanged);
            //
            // grpJog
            //
            this.grpJog.Controls.Add(this.jogLayout);
            this.grpJog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpJog.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.grpJog.Margin = new System.Windows.Forms.Padding(0, 0, 0, 6);
            this.grpJog.Name = "grpJog";
            this.grpJog.Padding = new System.Windows.Forms.Padding(8);
            this.grpJog.Text = "INPUT STAGE JOG";
            this.jogLayout.ColumnCount = 4;
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 26F));
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 24F));
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.jogLayout.Controls.Add(this.lblJogSpeed, 0, 0);
            this.jogLayout.Controls.Add(this.cmbJogSpeed, 1, 0);
            this.jogLayout.Controls.Add(this.lblVisionXCaption, 0, 1);
            this.jogLayout.Controls.Add(this.lblVisionXValue, 1, 1);
            this.jogLayout.Controls.Add(this.btnVisionXMinus, 2, 1);
            this.jogLayout.Controls.Add(this.btnVisionXPlus, 3, 1);
            this.jogLayout.Controls.Add(this.lblWaferYCaption, 0, 2);
            this.jogLayout.Controls.Add(this.lblWaferYValue, 1, 2);
            this.jogLayout.Controls.Add(this.btnWaferYMinus, 2, 2);
            this.jogLayout.Controls.Add(this.btnWaferYPlus, 3, 2);
            this.jogLayout.Controls.Add(this.lblWaferTCaption, 0, 3);
            this.jogLayout.Controls.Add(this.lblWaferTValue, 1, 3);
            this.jogLayout.Controls.Add(this.btnWaferTMinus, 2, 3);
            this.jogLayout.Controls.Add(this.btnWaferTPlus, 3, 3);
            this.jogLayout.Controls.Add(this.btnJogStop, 0, 4);
            this.jogLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.jogLayout.RowCount = 5;
            this.jogLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.jogLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.jogLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.jogLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.jogLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.jogLayout.SetColumnSpan(this.cmbJogSpeed, 3);
            this.jogLayout.SetColumnSpan(this.btnJogStop, 4);
            this.lblJogSpeed.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblJogSpeed.Text = "Jog Speed";
            this.lblJogSpeed.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cmbJogSpeed.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.cmbJogSpeed.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbJogSpeed.Items.AddRange(new object[] { "Fine", "Medium", "Coarse" });
            this.cmbJogSpeed.Name = "cmbJogSpeed";
            this.cmbJogSpeed.SelectedIndex = 0;
            this.lblVisionXCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVisionXCaption.Text = "Camera X";
            this.lblVisionXCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblVisionXValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVisionXValue.Text = "0.000";
            this.lblVisionXValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblWaferYCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblWaferYCaption.Text = "Stage Y";
            this.lblWaferYCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblWaferYValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblWaferYValue.Text = "0.000";
            this.lblWaferYValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblWaferTCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblWaferTCaption.Text = "Stage T";
            this.lblWaferTCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblWaferTValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblWaferTValue.Text = "0.0000";
            this.lblWaferTValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVisionXMinus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnVisionXMinus.Name = "btnVisionXMinus";
            this.btnVisionXMinus.Tag = InputStageReviewJogAxis.VisionX;
            this.btnVisionXMinus.Text = "X-";
            this.btnVisionXPlus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnVisionXPlus.Name = "btnVisionXPlus";
            this.btnVisionXPlus.Tag = InputStageReviewJogAxis.VisionX;
            this.btnVisionXPlus.Text = "X+";
            this.btnWaferYMinus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnWaferYMinus.Name = "btnWaferYMinus";
            this.btnWaferYMinus.Tag = InputStageReviewJogAxis.WaferY;
            this.btnWaferYMinus.Text = "Y-";
            this.btnWaferYPlus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnWaferYPlus.Name = "btnWaferYPlus";
            this.btnWaferYPlus.Tag = InputStageReviewJogAxis.WaferY;
            this.btnWaferYPlus.Text = "Y+";
            this.btnWaferTMinus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnWaferTMinus.Name = "btnWaferTMinus";
            this.btnWaferTMinus.Tag = InputStageReviewJogAxis.WaferT;
            this.btnWaferTMinus.Text = "T-";
            this.btnWaferTPlus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnWaferTPlus.Name = "btnWaferTPlus";
            this.btnWaferTPlus.Tag = InputStageReviewJogAxis.WaferT;
            this.btnWaferTPlus.Text = "T+";
            this.btnVisionXMinus.MouseDown += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseDown);
            this.btnVisionXMinus.MouseUp += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseUp);
            this.btnVisionXPlus.MouseDown += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseDown);
            this.btnVisionXPlus.MouseUp += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseUp);
            this.btnWaferYMinus.MouseDown += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseDown);
            this.btnWaferYMinus.MouseUp += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseUp);
            this.btnWaferYPlus.MouseDown += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseDown);
            this.btnWaferYPlus.MouseUp += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseUp);
            this.btnWaferTMinus.MouseDown += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseDown);
            this.btnWaferTMinus.MouseUp += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseUp);
            this.btnWaferTPlus.MouseDown += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseDown);
            this.btnWaferTPlus.MouseUp += new System.Windows.Forms.MouseEventHandler(this.JogButton_MouseUp);
            this.btnJogStop.BackColor = System.Drawing.Color.FromArgb(190, 76, 68);
            this.btnJogStop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogStop.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnJogStop.ForeColor = System.Drawing.Color.White;
            this.btnJogStop.Name = "btnJogStop";
            this.btnJogStop.Text = "STOP";
            this.btnJogStop.UseVisualStyleBackColor = false;
            this.btnJogStop.Click += new System.EventHandler(this.BtnJogStop_Click);
            //
            // grpActions
            //
            this.grpActions.Controls.Add(this.actionLayout);
            this.grpActions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpActions.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.grpActions.Margin = new System.Windows.Forms.Padding(0);
            this.grpActions.Name = "grpActions";
            this.grpActions.Padding = new System.Windows.Forms.Padding(8);
            this.grpActions.Text = "ACTION";
            this.actionLayout.ColumnCount = 1;
            this.actionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.actionLayout.Controls.Add(this.btnMoveSelectedDie, 0, 0);
            this.actionLayout.Controls.Add(this.btnThetaCorrection, 0, 1);
            this.actionLayout.Controls.Add(this.btnDieDetection, 0, 2);
            this.actionLayout.Controls.Add(this.btnOffsetApply, 0, 3);
            this.actionLayout.Controls.Add(this.btnVisionTest, 0, 4);
            this.actionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.actionLayout.RowCount = 5;
            this.actionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.actionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.actionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.actionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.actionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.btnMoveSelectedDie.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnMoveSelectedDie.Name = "btnMoveSelectedDie";
            this.btnMoveSelectedDie.Text = "MOVE SELECTED DIE";
            this.btnMoveSelectedDie.Click += new System.EventHandler(this.BtnMoveSelectedDie_Click);
            this.btnThetaCorrection.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnThetaCorrection.Name = "btnThetaCorrection";
            this.btnThetaCorrection.Text = "T CORRECTION";
            this.btnThetaCorrection.Click += new System.EventHandler(this.BtnThetaCorrection_Click);
            this.btnDieDetection.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnDieDetection.Name = "btnDieDetection";
            this.btnDieDetection.Text = "DIE DETECTION";
            this.btnDieDetection.Click += new System.EventHandler(this.BtnDieDetection_Click);
            this.btnOffsetApply.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnOffsetApply.Name = "btnOffsetApply";
            this.btnOffsetApply.Text = "APPLY OFFSET";
            this.btnOffsetApply.Click += new System.EventHandler(this.BtnOffsetApply_Click);
            this.btnVisionTest.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnVisionTest.Name = "btnVisionTest";
            this.btnVisionTest.Text = "VISION TEST";
            this.btnVisionTest.Click += new System.EventHandler(this.BtnVisionTest_Click);
            //
            // rightLayout
            //
            this.rightLayout.ColumnCount = 1;
            this.rightLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rightLayout.Controls.Add(this.grpMapInfo, 0, 0);
            this.rightLayout.Controls.Add(this.grpPickupRoute, 0, 1);
            this.rightLayout.Controls.Add(this.grpWorkflow, 0, 2);
            this.rightLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rightLayout.Margin = new System.Windows.Forms.Padding(0);
            this.rightLayout.Name = "rightLayout";
            this.rightLayout.RowCount = 3;
            this.rightLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 290F));
            this.rightLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 230F));
            this.rightLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            //
            // grpMapInfo
            //
            this.grpMapInfo.Controls.Add(this.mapInfoLayout);
            this.grpMapInfo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpMapInfo.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.grpMapInfo.Margin = new System.Windows.Forms.Padding(0, 0, 0, 6);
            this.grpMapInfo.Name = "grpMapInfo";
            this.grpMapInfo.Padding = new System.Windows.Forms.Padding(8);
            this.grpMapInfo.Text = "DIE MAP INFO";
            this.mapInfoLayout.ColumnCount = 2;
            this.mapInfoLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 44F));
            this.mapInfoLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 56F));
            this.mapInfoLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mapInfoLayout.RowCount = 15;
            for (int infoRow = 0; infoRow < 15; infoRow++)
                this.mapInfoLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6.666667F));
            this.mapInfoLayout.Controls.Add(this.lblMapGridCaption, 0, 0);
            this.mapInfoLayout.Controls.Add(this.lblMapGridValue, 1, 0);
            this.mapInfoLayout.Controls.Add(this.lblMapProgressCaption, 0, 1);
            this.mapInfoLayout.Controls.Add(this.lblMapProgressValue, 1, 1);
            this.mapInfoLayout.Controls.Add(this.lblTargetCountCaption, 0, 2);
            this.mapInfoLayout.Controls.Add(this.lblTargetCountValue, 1, 2);
            this.mapInfoLayout.Controls.Add(this.lblDieSizeXCaption, 0, 3);
            this.mapInfoLayout.Controls.Add(this.lblDieSizeXValue, 1, 3);
            this.mapInfoLayout.Controls.Add(this.lblDieSizeYCaption, 0, 4);
            this.mapInfoLayout.Controls.Add(this.lblDieSizeYValue, 1, 4);
            this.mapInfoLayout.Controls.Add(this.lblPitchGapXCaption, 0, 5);
            this.mapInfoLayout.Controls.Add(this.lblPitchGapXValue, 1, 5);
            this.mapInfoLayout.Controls.Add(this.lblPitchGapYCaption, 0, 6);
            this.mapInfoLayout.Controls.Add(this.lblPitchGapYValue, 1, 6);
            this.mapInfoLayout.Controls.Add(this.lblWaferDiameterCaption, 0, 7);
            this.mapInfoLayout.Controls.Add(this.lblWaferDiameterValue, 1, 7);
            this.mapInfoLayout.Controls.Add(this.lblInputCameraXCaption, 0, 8);
            this.mapInfoLayout.Controls.Add(this.lblInputCameraXValue, 1, 8);
            this.mapInfoLayout.Controls.Add(this.lblInputStageYCaption, 0, 9);
            this.mapInfoLayout.Controls.Add(this.lblInputStageYValue, 1, 9);
            this.mapInfoLayout.Controls.Add(this.lblEquipmentGridCaption, 0, 10);
            this.mapInfoLayout.Controls.Add(this.lblEquipmentGridValue, 1, 10);
            this.mapInfoLayout.Controls.Add(this.lblOriginalMapCaption, 0, 11);
            this.mapInfoLayout.Controls.Add(this.lblOriginalMapValue, 1, 11);
            this.mapInfoLayout.Controls.Add(this.lblMappingOriginCaption, 0, 12);
            this.mapInfoLayout.Controls.Add(this.lblMappingOriginValue, 1, 12);
            this.mapInfoLayout.Controls.Add(this.lblSelectedDieCaption, 0, 13);
            this.mapInfoLayout.Controls.Add(this.lblSelectedDieValue, 1, 13);
            this.mapInfoLayout.Controls.Add(this.lblSelectedSequenceCaption, 0, 14);
            this.mapInfoLayout.Controls.Add(this.lblSelectedSequenceValue, 1, 14);
            this.mapInfoLayout.Controls.Add(this.lblSelectedPositionCaption, 0, 15);
            this.mapInfoLayout.Controls.Add(this.lblSelectedPositionValue, 1, 15);
            this.mapInfoLayout.RowCount = 16;
            this.mapInfoLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6.25F));
            this.lblMapGridCaption.Text = "Grid X/Y";
            this.lblMapProgressCaption.Text = "Progress";
            this.lblTargetCountCaption.Text = "Target Count";
            this.lblDieSizeXCaption.Text = "Die Size X (mm)";
            this.lblDieSizeYCaption.Text = "Die Size Y (mm)";
            this.lblPitchGapXCaption.Text = "Pitch Gap X (mm)";
            this.lblPitchGapYCaption.Text = "Pitch Gap Y (mm)";
            this.lblWaferDiameterCaption.Text = "Wafer Diameter";
            this.lblInputCameraXCaption.Text = "Input Camera X";
            this.lblInputStageYCaption.Text = "Input Stage Y";
            this.lblEquipmentGridCaption.Text = "Equipment Grid";
            this.lblOriginalMapCaption.Text = "Original Map";
            this.lblMappingOriginCaption.Text = "Mapping Origin";
            this.lblSelectedDieCaption.Text = "Selected Die UID";
            this.lblSelectedSequenceCaption.Text = "Selected Sequence";
            this.lblSelectedPositionCaption.Text = "Selected X/Y";
            System.Windows.Forms.Label[] infoCaptions = new System.Windows.Forms.Label[] {
                this.lblMapGridCaption, this.lblMapProgressCaption, this.lblTargetCountCaption,
                this.lblDieSizeXCaption, this.lblDieSizeYCaption, this.lblPitchGapXCaption,
                this.lblPitchGapYCaption, this.lblWaferDiameterCaption, this.lblInputCameraXCaption,
                this.lblInputStageYCaption, this.lblEquipmentGridCaption, this.lblOriginalMapCaption,
                this.lblMappingOriginCaption, this.lblSelectedDieCaption, this.lblSelectedSequenceCaption,
                this.lblSelectedPositionCaption };
            System.Windows.Forms.Label[] infoValues = new System.Windows.Forms.Label[] {
                this.lblMapGridValue, this.lblMapProgressValue, this.lblTargetCountValue,
                this.lblDieSizeXValue, this.lblDieSizeYValue, this.lblPitchGapXValue,
                this.lblPitchGapYValue, this.lblWaferDiameterValue, this.lblInputCameraXValue,
                this.lblInputStageYValue, this.lblEquipmentGridValue, this.lblOriginalMapValue,
                this.lblMappingOriginValue, this.lblSelectedDieValue, this.lblSelectedSequenceValue,
                this.lblSelectedPositionValue };
            for (int labelIndex = 0; labelIndex < infoCaptions.Length; labelIndex++)
            {
                infoCaptions[labelIndex].BackColor = System.Drawing.Color.FromArgb(224, 229, 235);
                infoCaptions[labelIndex].BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
                infoCaptions[labelIndex].Dock = System.Windows.Forms.DockStyle.Fill;
                infoCaptions[labelIndex].Margin = new System.Windows.Forms.Padding(0);
                infoCaptions[labelIndex].TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                infoValues[labelIndex].BackColor = System.Drawing.Color.White;
                infoValues[labelIndex].BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
                infoValues[labelIndex].Dock = System.Windows.Forms.DockStyle.Fill;
                infoValues[labelIndex].Margin = new System.Windows.Forms.Padding(0);
                infoValues[labelIndex].Text = "-";
                infoValues[labelIndex].TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            }
            //
            // grpPickupRoute
            //
            this.grpPickupRoute.Controls.Add(this.pickupRouteLayout);
            this.grpPickupRoute.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpPickupRoute.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.grpPickupRoute.Margin = new System.Windows.Forms.Padding(0, 0, 0, 6);
            this.grpPickupRoute.Name = "grpPickupRoute";
            this.grpPickupRoute.Padding = new System.Windows.Forms.Padding(8);
            this.grpPickupRoute.Text = "PICKUP ROUTE";
            this.pickupRouteLayout.ColumnCount = 2;
            this.pickupRouteLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 82F));
            this.pickupRouteLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.pickupRouteLayout.Controls.Add(this.lblCornerCaption, 0, 0);
            this.pickupRouteLayout.Controls.Add(this.cornerOptions, 1, 0);
            this.pickupRouteLayout.Controls.Add(this.lblDirectionCaption, 0, 1);
            this.pickupRouteLayout.Controls.Add(this.directionOptions, 1, 1);
            this.pickupRouteLayout.Controls.Add(this.lblPatternCaption, 0, 2);
            this.pickupRouteLayout.Controls.Add(this.patternOptions, 1, 2);
            this.pickupRouteLayout.Controls.Add(this.btnPreviewPath, 0, 3);
            this.pickupRouteLayout.Controls.Add(this.btnApplyPickupOrder, 0, 4);
            this.pickupRouteLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pickupRouteLayout.RowCount = 5;
            this.pickupRouteLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 48F));
            this.pickupRouteLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 34F));
            this.pickupRouteLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 34F));
            this.pickupRouteLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.pickupRouteLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.pickupRouteLayout.SetColumnSpan(this.btnPreviewPath, 2);
            this.pickupRouteLayout.SetColumnSpan(this.btnApplyPickupOrder, 2);
            this.lblCornerCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCornerCaption.Text = "Start Corner";
            this.lblCornerCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cornerOptions.Controls.Add(this.rbCornerTopLeft);
            this.cornerOptions.Controls.Add(this.rbCornerTopRight);
            this.cornerOptions.Controls.Add(this.rbCornerBottomLeft);
            this.cornerOptions.Controls.Add(this.rbCornerBottomRight);
            this.cornerOptions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rbCornerTopLeft.AutoSize = true;
            this.rbCornerTopLeft.Text = "TOP LEFT";
            this.rbCornerTopRight.AutoSize = true;
            this.rbCornerTopRight.Checked = true;
            this.rbCornerTopRight.Text = "TOP RIGHT";
            this.rbCornerBottomLeft.AutoSize = true;
            this.rbCornerBottomLeft.Text = "BOTTOM LEFT";
            this.rbCornerBottomRight.AutoSize = true;
            this.rbCornerBottomRight.Text = "BOTTOM RIGHT";
            this.lblDirectionCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDirectionCaption.Text = "Direction";
            this.lblDirectionCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.directionOptions.Controls.Add(this.rbDirectionHorizontal);
            this.directionOptions.Controls.Add(this.rbDirectionVertical);
            this.directionOptions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rbDirectionHorizontal.AutoSize = true;
            this.rbDirectionHorizontal.Text = "HORIZONTAL";
            this.rbDirectionVertical.AutoSize = true;
            this.rbDirectionVertical.Checked = true;
            this.rbDirectionVertical.Text = "VERTICAL";
            this.lblPatternCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPatternCaption.Text = "Pattern";
            this.lblPatternCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.patternOptions.Controls.Add(this.rbPatternStraight);
            this.patternOptions.Controls.Add(this.rbPatternZigZag);
            this.patternOptions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rbPatternStraight.AutoSize = true;
            this.rbPatternStraight.Text = "STRAIGHT";
            this.rbPatternZigZag.AutoSize = true;
            this.rbPatternZigZag.Checked = true;
            this.rbPatternZigZag.Text = "ZIGZAG";
            this.rbCornerTopLeft.CheckedChanged += new System.EventHandler(this.PickupOption_CheckedChanged);
            this.rbCornerTopRight.CheckedChanged += new System.EventHandler(this.PickupOption_CheckedChanged);
            this.rbCornerBottomLeft.CheckedChanged += new System.EventHandler(this.PickupOption_CheckedChanged);
            this.rbCornerBottomRight.CheckedChanged += new System.EventHandler(this.PickupOption_CheckedChanged);
            this.rbDirectionHorizontal.CheckedChanged += new System.EventHandler(this.PickupOption_CheckedChanged);
            this.rbDirectionVertical.CheckedChanged += new System.EventHandler(this.PickupOption_CheckedChanged);
            this.rbPatternStraight.CheckedChanged += new System.EventHandler(this.PickupOption_CheckedChanged);
            this.rbPatternZigZag.CheckedChanged += new System.EventHandler(this.PickupOption_CheckedChanged);
            this.btnPreviewPath.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPreviewPath.Name = "btnPreviewPath";
            this.btnPreviewPath.Text = "PREVIEW PATH";
            this.btnPreviewPath.Click += new System.EventHandler(this.BtnPreviewPath_Click);
            this.btnApplyPickupOrder.BackColor = System.Drawing.Color.FromArgb(52, 123, 184);
            this.btnApplyPickupOrder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnApplyPickupOrder.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnApplyPickupOrder.ForeColor = System.Drawing.Color.White;
            this.btnApplyPickupOrder.Name = "btnApplyPickupOrder";
            this.btnApplyPickupOrder.Text = "APPLY PICKUP ORDER";
            this.btnApplyPickupOrder.UseVisualStyleBackColor = false;
            this.btnApplyPickupOrder.Click += new System.EventHandler(this.BtnApplyPickupOrder_Click);
            //
            // grpWorkflow
            //
            this.grpWorkflow.Controls.Add(this.workflowLayout);
            this.grpWorkflow.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpWorkflow.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.grpWorkflow.Margin = new System.Windows.Forms.Padding(0);
            this.grpWorkflow.Name = "grpWorkflow";
            this.grpWorkflow.Padding = new System.Windows.Forms.Padding(8);
            this.grpWorkflow.Text = "ALIGN / MAPPING / RUN";
            this.workflowLayout.ColumnCount = 2;
            this.workflowLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.workflowLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.workflowLayout.Controls.Add(this.lblRevisionCaption, 0, 0);
            this.workflowLayout.Controls.Add(this.lblMappingRevisionValue, 1, 0);
            this.workflowLayout.Controls.Add(this.txtFailureDetail, 0, 1);
            this.workflowLayout.Controls.Add(this.btnRetryAlign, 0, 2);
            this.workflowLayout.Controls.Add(this.btnRetryMapping, 1, 2);
            this.workflowLayout.Controls.Add(this.btnMappingSetup, 0, 3);
            this.workflowLayout.Controls.Add(this.btnStartRun, 0, 4);
            this.workflowLayout.Controls.Add(this.btnAbortAuto, 1, 4);
            this.workflowLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.workflowLayout.RowCount = 5;
            this.workflowLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.workflowLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.workflowLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 42F));
            this.workflowLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 42F));
            this.workflowLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 54F));
            this.workflowLayout.SetColumnSpan(this.txtFailureDetail, 2);
            this.workflowLayout.SetColumnSpan(this.btnMappingSetup, 2);
            this.lblRevisionCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRevisionCaption.Text = "Mapping Revision";
            this.lblRevisionCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblMappingRevisionValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblMappingRevisionValue.Text = "-";
            this.lblMappingRevisionValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.txtFailureDetail.BackColor = System.Drawing.Color.White;
            this.txtFailureDetail.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtFailureDetail.Multiline = true;
            this.txtFailureDetail.Name = "txtFailureDetail";
            this.txtFailureDetail.ReadOnly = true;
            this.txtFailureDetail.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.btnRetryAlign.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnRetryAlign.Name = "btnRetryAlign";
            this.btnRetryAlign.Text = "RETRY ALIGN";
            this.btnRetryAlign.Click += new System.EventHandler(this.BtnRetryAlign_Click);
            this.btnRetryMapping.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnRetryMapping.Name = "btnRetryMapping";
            this.btnRetryMapping.Text = "RUN DIE MAPPING";
            this.btnRetryMapping.Click += new System.EventHandler(this.BtnRetryMapping_Click);
            this.btnMappingSetup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnMappingSetup.Name = "btnMappingSetup";
            this.btnMappingSetup.Text = "MAPPING SETUP";
            this.btnMappingSetup.Click += new System.EventHandler(this.BtnMappingSetup_Click);
            this.btnStartRun.BackColor = System.Drawing.Color.FromArgb(38, 139, 83);
            this.btnStartRun.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnStartRun.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnStartRun.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.btnStartRun.ForeColor = System.Drawing.Color.White;
            this.btnStartRun.Name = "btnStartRun";
            this.btnStartRun.Text = "CONFIRM && START RUN";
            this.btnStartRun.UseVisualStyleBackColor = false;
            this.btnStartRun.Click += new System.EventHandler(this.BtnStartRun_Click);
            this.btnAbortAuto.BackColor = System.Drawing.Color.FromArgb(185, 70, 65);
            this.btnAbortAuto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnAbortAuto.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAbortAuto.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.btnAbortAuto.ForeColor = System.Drawing.Color.White;
            this.btnAbortAuto.Name = "btnAbortAuto";
            this.btnAbortAuto.Text = "ABORT AUTO";
            this.btnAbortAuto.UseVisualStyleBackColor = false;
            this.btnAbortAuto.Click += new System.EventHandler(this.BtnAbortAuto_Click);
            //
            // footerLayout
            //
            this.footerLayout.BackColor = System.Drawing.Color.FromArgb(42, 48, 58);
            this.footerLayout.ColumnCount = 2;
            this.footerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.footerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 120F));
            this.footerLayout.Controls.Add(this.lblStatus, 0, 0);
            this.footerLayout.Controls.Add(this.btnClose, 1, 0);
            this.footerLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.footerLayout.Margin = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.footerLayout.Name = "footerLayout";
            this.footerLayout.RowCount = 1;
            this.footerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lblStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStatus.Font = new System.Drawing.Font("맑은 고딕", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblStatus.ForeColor = System.Drawing.Color.White;
            this.lblStatus.Padding = new System.Windows.Forms.Padding(14, 0, 0, 0);
            this.lblStatus.Text = "-";
            this.lblStatus.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnClose.Margin = new System.Windows.Forms.Padding(8, 10, 10, 10);
            this.btnClose.Name = "btnClose";
            this.btnClose.Text = "CLOSE";
            this.btnClose.Click += new System.EventHandler(this.BtnClose_Click);
            //
            // InputStageRunReviewDialog
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(238, 241, 245);
            this.ClientSize = new System.Drawing.Size(1740, 940);
            this.Controls.Add(this.rootLayout);
            this.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
            this.KeyPreview = true;
            this.MinimumSize = new System.Drawing.Size(1480, 820);
            this.Name = "InputStageRunReviewDialog";
            this.Padding = new System.Windows.Forms.Padding(8);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Wafer Align / Die Mapping Review";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.InputStageRunReviewDialog_FormClosing);
            this.rootLayout.ResumeLayout(false);
            this.headerLayout.ResumeLayout(false);
            this.bodyLayout.ResumeLayout(false);
            this.leftLayout.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dieGrid)).EndInit();
            this.centerLayout.ResumeLayout(false);
            this.grpDieState.ResumeLayout(false);
            this.dieStateLayout.ResumeLayout(false);
            this.dieStateOptions.ResumeLayout(false);
            this.dieStateOptions.PerformLayout();
            this.grpStartDie.ResumeLayout(false);
            this.startDieLayout.ResumeLayout(false);
            this.startDieLayout.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numStartIndex)).EndInit();
            this.grpJog.ResumeLayout(false);
            this.jogLayout.ResumeLayout(false);
            this.grpActions.ResumeLayout(false);
            this.actionLayout.ResumeLayout(false);
            this.rightLayout.ResumeLayout(false);
            this.grpMapInfo.ResumeLayout(false);
            this.mapInfoLayout.ResumeLayout(false);
            this.grpPickupRoute.ResumeLayout(false);
            this.pickupRouteLayout.ResumeLayout(false);
            this.cornerOptions.ResumeLayout(false);
            this.cornerOptions.PerformLayout();
            this.directionOptions.ResumeLayout(false);
            this.directionOptions.PerformLayout();
            this.patternOptions.ResumeLayout(false);
            this.patternOptions.PerformLayout();
            this.grpWorkflow.ResumeLayout(false);
            this.workflowLayout.ResumeLayout(false);
            this.workflowLayout.PerformLayout();
            this.footerLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
