namespace QMC.CDT_320.Ui.Dialogs
{
    partial class InputPickupOrderDialog
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.TableLayoutPanel layoutRoot;
        private System.Windows.Forms.Panel panelHeader;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label lblWafer;
        private System.Windows.Forms.FlowLayoutPanel panelOptions;
        private System.Windows.Forms.Label lblCornerCaption;
        private System.Windows.Forms.Label lblDirectionCaption;
        private System.Windows.Forms.Label lblPatternCaption;
        private System.Windows.Forms.ComboBox cmbCorner;
        private System.Windows.Forms.ComboBox cmbDirection;
        private System.Windows.Forms.ComboBox cmbPattern;
        private System.Windows.Forms.Label lblStart;
        private System.Windows.Forms.Button btnCornerStart;
        private System.Windows.Forms.TableLayoutPanel layoutBody;
        private System.Windows.Forms.TableLayoutPanel layoutMap;
        private System.Windows.Forms.FlowLayoutPanel panelMapTools;
        private System.Windows.Forms.Label lblMapRange;
        private System.Windows.Forms.ComboBox cmbVisibleCount;
        private System.Windows.Forms.Button btnZoomOut;
        private System.Windows.Forms.Label lblZoom;
        private System.Windows.Forms.Button btnZoomIn;
        private System.Windows.Forms.Button btnFit;
        private System.Windows.Forms.Button btnFocus;
        private QMC.CDT_320.Ui.Controls.PickupRouteMapControl mapRoute;
        private System.Windows.Forms.Label lblLegend;
        private System.Windows.Forms.TableLayoutPanel layoutSide;
        private System.Windows.Forms.Label lblListTitle;
        private System.Windows.Forms.TableLayoutPanel layoutSelected;
        private System.Windows.Forms.Label lblSequence;
        private System.Windows.Forms.Label lblSelectedMap;
        private System.Windows.Forms.Label lblPosition;
        private System.Windows.Forms.Button btnSetStart;
        private System.Windows.Forms.DataGridView gridOrder;
        private System.Windows.Forms.DataGridViewTextBoxColumn colSequence;
        private System.Windows.Forms.DataGridViewTextBoxColumn colMapX;
        private System.Windows.Forms.DataGridViewTextBoxColumn colMapY;
        private System.Windows.Forms.DataGridViewTextBoxColumn colState;
        private System.Windows.Forms.FlowLayoutPanel panelPage;
        private System.Windows.Forms.Label lblPage;
        private System.Windows.Forms.Button btnPagePrevious;
        private System.Windows.Forms.Button btnPageNext;
        private System.Windows.Forms.TableLayoutPanel layoutPlayback;
        private System.Windows.Forms.FlowLayoutPanel panelPlayback;
        private System.Windows.Forms.Button btnFirst;
        private System.Windows.Forms.Button btnPrevious;
        private System.Windows.Forms.Button btnPlay;
        private System.Windows.Forms.Button btnNext;
        private System.Windows.Forms.Button btnLast;
        private System.Windows.Forms.ComboBox cmbSpeed;
        private System.Windows.Forms.Label lblSequenceCaption;
        private System.Windows.Forms.NumericUpDown numSequence;
        private System.Windows.Forms.Label lblTotal;
        private System.Windows.Forms.Button btnJump;
        private System.Windows.Forms.TrackBar trackSequence;
        private System.Windows.Forms.Label lblPlaybackNotice;
        private System.Windows.Forms.TableLayoutPanel layoutFooter;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.Button btnApply;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.Timer timerPlayback;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            layoutRoot = new System.Windows.Forms.TableLayoutPanel();
            panelHeader = new System.Windows.Forms.Panel();
            lblTitle = new System.Windows.Forms.Label();
            lblWafer = new System.Windows.Forms.Label();
            panelOptions = new System.Windows.Forms.FlowLayoutPanel();
            lblCornerCaption = new System.Windows.Forms.Label();
            lblDirectionCaption = new System.Windows.Forms.Label();
            lblPatternCaption = new System.Windows.Forms.Label();
            cmbCorner = new System.Windows.Forms.ComboBox();
            cmbDirection = new System.Windows.Forms.ComboBox();
            cmbPattern = new System.Windows.Forms.ComboBox();
            lblStart = new System.Windows.Forms.Label();
            btnCornerStart = new System.Windows.Forms.Button();
            layoutBody = new System.Windows.Forms.TableLayoutPanel();
            layoutMap = new System.Windows.Forms.TableLayoutPanel();
            panelMapTools = new System.Windows.Forms.FlowLayoutPanel();
            lblMapRange = new System.Windows.Forms.Label();
            cmbVisibleCount = new System.Windows.Forms.ComboBox();
            btnZoomOut = new System.Windows.Forms.Button();
            lblZoom = new System.Windows.Forms.Label();
            btnZoomIn = new System.Windows.Forms.Button();
            btnFit = new System.Windows.Forms.Button();
            btnFocus = new System.Windows.Forms.Button();
            mapRoute = new QMC.CDT_320.Ui.Controls.PickupRouteMapControl();
            lblLegend = new System.Windows.Forms.Label();
            layoutSide = new System.Windows.Forms.TableLayoutPanel();
            lblListTitle = new System.Windows.Forms.Label();
            layoutSelected = new System.Windows.Forms.TableLayoutPanel();
            lblSequence = new System.Windows.Forms.Label();
            lblSelectedMap = new System.Windows.Forms.Label();
            lblPosition = new System.Windows.Forms.Label();
            btnSetStart = new System.Windows.Forms.Button();
            gridOrder = new System.Windows.Forms.DataGridView();
            colSequence = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colMapX = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colMapY = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colState = new System.Windows.Forms.DataGridViewTextBoxColumn();
            panelPage = new System.Windows.Forms.FlowLayoutPanel();
            lblPage = new System.Windows.Forms.Label();
            btnPagePrevious = new System.Windows.Forms.Button();
            btnPageNext = new System.Windows.Forms.Button();
            layoutPlayback = new System.Windows.Forms.TableLayoutPanel();
            panelPlayback = new System.Windows.Forms.FlowLayoutPanel();
            btnFirst = new System.Windows.Forms.Button();
            btnPrevious = new System.Windows.Forms.Button();
            btnPlay = new System.Windows.Forms.Button();
            btnNext = new System.Windows.Forms.Button();
            btnLast = new System.Windows.Forms.Button();
            cmbSpeed = new System.Windows.Forms.ComboBox();
            lblSequenceCaption = new System.Windows.Forms.Label();
            numSequence = new System.Windows.Forms.NumericUpDown();
            lblTotal = new System.Windows.Forms.Label();
            btnJump = new System.Windows.Forms.Button();
            trackSequence = new System.Windows.Forms.TrackBar();
            lblPlaybackNotice = new System.Windows.Forms.Label();
            layoutFooter = new System.Windows.Forms.TableLayoutPanel();
            lblStatus = new System.Windows.Forms.Label();
            btnApply = new System.Windows.Forms.Button();
            btnClose = new System.Windows.Forms.Button();
            timerPlayback = new System.Windows.Forms.Timer(components);
            ((System.ComponentModel.ISupportInitialize)gridOrder).BeginInit();
            ((System.ComponentModel.ISupportInitialize)numSequence).BeginInit();
            ((System.ComponentModel.ISupportInitialize)trackSequence).BeginInit();
            layoutRoot.SuspendLayout();
            SuspendLayout();

            layoutRoot.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutRoot.ColumnCount = 1;
            layoutRoot.RowCount = 5;
            layoutRoot.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 62));
            layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 58));
            layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 104));
            layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 60));
            layoutRoot.Controls.Add(panelHeader, 0, 0);
            layoutRoot.Controls.Add(panelOptions, 0, 1);
            layoutRoot.Controls.Add(layoutBody, 0, 2);
            layoutRoot.Controls.Add(layoutPlayback, 0, 3);
            layoutRoot.Controls.Add(layoutFooter, 0, 4);

            panelHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            panelHeader.Margin = new System.Windows.Forms.Padding(0);
            panelHeader.Padding = new System.Windows.Forms.Padding(16, 8, 16, 8);
            panelHeader.BackColor = System.Drawing.Color.FromArgb(41, 49, 60);
            panelHeader.Controls.Add(lblTitle);
            panelHeader.Controls.Add(lblWafer);
            lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            lblTitle.Text = "WAFER ALIGN / DIE MAP REVIEW  ·  픽업 순서 보기";
            lblTitle.ForeColor = System.Drawing.Color.White;
            lblTitle.Font = new System.Drawing.Font("맑은 고딕", 14F, System.Drawing.FontStyle.Bold);
            lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            lblWafer.Dock = System.Windows.Forms.DockStyle.Right;
            lblWafer.Width = 220;
            lblWafer.ForeColor = System.Drawing.Color.White;
            lblWafer.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            lblWafer.AutoEllipsis = true;

            panelOptions.Dock = System.Windows.Forms.DockStyle.Fill;
            panelOptions.Padding = new System.Windows.Forms.Padding(12, 10, 6, 6);
            panelOptions.BackColor = System.Drawing.Color.White;
            panelOptions.WrapContents = false;
            panelOptions.Controls.Add(lblCornerCaption);
            panelOptions.Controls.Add(cmbCorner);
            panelOptions.Controls.Add(lblDirectionCaption);
            panelOptions.Controls.Add(cmbDirection);
            panelOptions.Controls.Add(lblPatternCaption);
            panelOptions.Controls.Add(cmbPattern);
            panelOptions.Controls.Add(lblStart);
            panelOptions.Controls.Add(btnCornerStart);
            lblCornerCaption.Text = "시작 코너";
            lblCornerCaption.Size = new System.Drawing.Size(66, 30);
            lblCornerCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            cmbCorner.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            cmbCorner.Width = 112;
            cmbCorner.Items.AddRange(new object[] { "우측 상단", "좌측 상단", "우측 하단", "좌측 하단" });
            cmbCorner.SelectedIndexChanged += cmbPickupOption_SelectedIndexChanged;
            lblDirectionCaption.Text = "진행 방향";
            lblDirectionCaption.Size = new System.Drawing.Size(66, 30);
            lblDirectionCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            cmbDirection.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            cmbDirection.Width = 76;
            cmbDirection.Items.AddRange(new object[] { "세로", "가로" });
            cmbDirection.SelectedIndexChanged += cmbPickupOption_SelectedIndexChanged;
            lblPatternCaption.Text = "패턴";
            lblPatternCaption.Size = new System.Drawing.Size(40, 30);
            lblPatternCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            cmbPattern.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            cmbPattern.Width = 104;
            cmbPattern.Items.AddRange(new object[] { "지그재그", "직선" });
            cmbPattern.SelectedIndexChanged += cmbPickupOption_SelectedIndexChanged;
            lblStart.Size = new System.Drawing.Size(242, 30);
            lblStart.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            lblStart.Margin = new System.Windows.Forms.Padding(18, 3, 3, 3);
            lblStart.ForeColor = System.Drawing.Color.FromArgb(142, 84, 17);
            btnCornerStart.Text = "코너 시작";
            btnCornerStart.Size = new System.Drawing.Size(92, 31);
            btnCornerStart.Click += btnCornerStart_Click;

            layoutBody.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutBody.Padding = new System.Windows.Forms.Padding(10);
            layoutBody.ColumnCount = 2;
            layoutBody.RowCount = 1;
            layoutBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 310));
            layoutBody.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutBody.Controls.Add(layoutMap, 0, 0);
            layoutBody.Controls.Add(layoutSide, 1, 0);
            layoutMap.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutMap.BackColor = System.Drawing.Color.White;
            layoutMap.ColumnCount = 1;
            layoutMap.RowCount = 3;
            layoutMap.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutMap.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40));
            layoutMap.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutMap.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32));
            layoutMap.Controls.Add(panelMapTools, 0, 0);
            layoutMap.Controls.Add(mapRoute, 0, 1);
            layoutMap.Controls.Add(lblLegend, 0, 2);
            panelMapTools.Dock = System.Windows.Forms.DockStyle.Fill;
            panelMapTools.WrapContents = false;
            panelMapTools.Controls.Add(lblMapRange);
            panelMapTools.Controls.Add(cmbVisibleCount);
            panelMapTools.Controls.Add(btnZoomOut);
            panelMapTools.Controls.Add(lblZoom);
            panelMapTools.Controls.Add(btnZoomIn);
            panelMapTools.Controls.Add(btnFit);
            panelMapTools.Controls.Add(btnFocus);
            lblMapRange.Size = new System.Drawing.Size(158, 29);
            lblMapRange.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            cmbVisibleCount.Width = 108;
            cmbVisibleCount.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            cmbVisibleCount.Items.AddRange(new object[] { "주변 20개", "주변 50개", "전체 경로" });
            cmbVisibleCount.SelectedIndexChanged += cmbVisibleCount_SelectedIndexChanged;
            btnZoomOut.Text = "−";
            btnZoomOut.Size = new System.Drawing.Size(30, 29);
            btnZoomOut.Click += btnZoomOut_Click;
            lblZoom.Size = new System.Drawing.Size(44, 29);
            lblZoom.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            btnZoomIn.Text = "+";
            btnZoomIn.Size = new System.Drawing.Size(30, 29);
            btnZoomIn.Click += btnZoomIn_Click;
            btnFit.Text = "전체 맵";
            btnFit.Size = new System.Drawing.Size(76, 29);
            btnFit.Click += btnFit_Click;
            btnFocus.Text = "선택 확대";
            btnFocus.Size = new System.Drawing.Size(83, 29);
            btnFocus.Click += btnFocus_Click;
            mapRoute.Dock = System.Windows.Forms.DockStyle.Fill;
            mapRoute.Margin = new System.Windows.Forms.Padding(0);
            mapRoute.SelectedSequenceChanged += mapRoute_SelectedSequenceChanged;
            mapRoute.ViewChanged += mapRoute_ViewChanged;
            lblLegend.Dock = System.Windows.Forms.DockStyle.Fill;
            lblLegend.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            lblLegend.Font = new System.Drawing.Font("맑은 고딕", 8F);

            layoutSide.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutSide.BackColor = System.Drawing.Color.White;
            layoutSide.ColumnCount = 1;
            layoutSide.RowCount = 4;
            layoutSide.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutSide.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 34));
            layoutSide.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 116));
            layoutSide.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutSide.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36));
            layoutSide.Controls.Add(lblListTitle, 0, 0);
            layoutSide.Controls.Add(layoutSelected, 0, 1);
            layoutSide.Controls.Add(gridOrder, 0, 2);
            layoutSide.Controls.Add(panelPage, 0, 3);
            lblListTitle.Text = "실행 순서";
            lblListTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            lblListTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            layoutSelected.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutSelected.Padding = new System.Windows.Forms.Padding(6);
            layoutSelected.BackColor = System.Drawing.Color.FromArgb(245, 247, 250);
            layoutSelected.ColumnCount = 2;
            layoutSelected.RowCount = 3;
            layoutSelected.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 78));
            layoutSelected.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutSelected.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 34));
            layoutSelected.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28));
            layoutSelected.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutSelected.Controls.Add(lblSequence, 0, 0);
            layoutSelected.Controls.Add(lblSelectedMap, 1, 0);
            layoutSelected.Controls.Add(lblPosition, 0, 1);
            layoutSelected.SetColumnSpan(lblPosition, 2);
            layoutSelected.Controls.Add(btnSetStart, 0, 2);
            layoutSelected.SetColumnSpan(btnSetStart, 2);
            lblSequence.Dock = System.Windows.Forms.DockStyle.Fill;
            lblSequence.Font = new System.Drawing.Font("Consolas", 21F);
            lblSequence.ForeColor = System.Drawing.Color.FromArgb(38, 113, 185);
            lblSelectedMap.Dock = System.Windows.Forms.DockStyle.Fill;
            lblSelectedMap.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            lblPosition.Dock = System.Windows.Forms.DockStyle.Fill;
            lblPosition.Font = new System.Drawing.Font("Consolas", 9F);
            lblPosition.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            btnSetStart.Dock = System.Windows.Forms.DockStyle.Fill;
            btnSetStart.Text = "선택 다이를 1번으로 지정";
            btnSetStart.Click += btnSetStart_Click;
            gridOrder.Dock = System.Windows.Forms.DockStyle.Fill;
            gridOrder.AllowUserToAddRows = false;
            gridOrder.AllowUserToDeleteRows = false;
            gridOrder.AllowUserToOrderColumns = false;
            gridOrder.AllowUserToResizeRows = false;
            gridOrder.ReadOnly = true;
            gridOrder.MultiSelect = false;
            gridOrder.RowHeadersVisible = false;
            gridOrder.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            gridOrder.BackgroundColor = System.Drawing.Color.White;
            gridOrder.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            gridOrder.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            gridOrder.ColumnHeadersHeight = 32;
            gridOrder.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            gridOrder.RowTemplate.Height = 29;
            gridOrder.DefaultCellStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            gridOrder.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(223, 238, 251);
            gridOrder.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.FromArgb(27, 48, 69);
            gridOrder.ColumnHeadersDefaultCellStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            gridOrder.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { colSequence, colMapX, colMapY, colState });
            gridOrder.SelectionChanged += gridOrder_SelectionChanged;
            colSequence.Name = "colSequence"; colSequence.HeaderText = "SEQ";
            colSequence.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            colMapX.Name = "colMapX"; colMapX.HeaderText = "MAP X";
            colMapX.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            colMapY.Name = "colMapY"; colMapY.HeaderText = "MAP Y";
            colMapY.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            colState.Name = "colState"; colState.HeaderText = "상태";
            colState.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            panelPage.Dock = System.Windows.Forms.DockStyle.Fill;
            panelPage.WrapContents = false;
            panelPage.Controls.Add(lblPage);
            panelPage.Controls.Add(btnPagePrevious);
            panelPage.Controls.Add(btnPageNext);
            lblPage.Size = new System.Drawing.Size(159, 28);
            lblPage.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            btnPagePrevious.Text = "이전"; btnPagePrevious.Size = new System.Drawing.Size(57, 28);
            btnPagePrevious.Click += btnPagePrevious_Click;
            btnPageNext.Text = "다음"; btnPageNext.Size = new System.Drawing.Size(57, 28);
            btnPageNext.Click += btnPageNext_Click;

            layoutPlayback.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutPlayback.Margin = new System.Windows.Forms.Padding(13, 0, 13, 5);
            layoutPlayback.Padding = new System.Windows.Forms.Padding(8, 4, 8, 4);
            layoutPlayback.BackColor = System.Drawing.Color.White;
            layoutPlayback.ColumnCount = 1;
            layoutPlayback.RowCount = 3;
            layoutPlayback.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutPlayback.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38));
            layoutPlayback.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 29));
            layoutPlayback.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutPlayback.Controls.Add(panelPlayback, 0, 0);
            layoutPlayback.Controls.Add(trackSequence, 0, 1);
            layoutPlayback.Controls.Add(lblPlaybackNotice, 0, 2);
            panelPlayback.Dock = System.Windows.Forms.DockStyle.Fill;
            panelPlayback.WrapContents = false;
            panelPlayback.Controls.Add(btnFirst);
            panelPlayback.Controls.Add(btnPrevious);
            panelPlayback.Controls.Add(btnPlay);
            panelPlayback.Controls.Add(btnNext);
            panelPlayback.Controls.Add(btnLast);
            panelPlayback.Controls.Add(cmbSpeed);
            panelPlayback.Controls.Add(lblSequenceCaption);
            panelPlayback.Controls.Add(numSequence);
            panelPlayback.Controls.Add(lblTotal);
            panelPlayback.Controls.Add(btnJump);
            btnFirst.Text = "처음"; btnFirst.Size = new System.Drawing.Size(53, 30); btnFirst.Click += btnFirst_Click;
            btnPrevious.Text = "이전"; btnPrevious.Size = new System.Drawing.Size(53, 30); btnPrevious.Click += btnPrevious_Click;
            btnPlay.Text = "▶ 순서 재생"; btnPlay.Size = new System.Drawing.Size(116, 30); btnPlay.Click += btnPlay_Click;
            btnPlay.BackColor = System.Drawing.Color.FromArgb(38, 113, 185); btnPlay.ForeColor = System.Drawing.Color.White;
            btnNext.Text = "다음"; btnNext.Size = new System.Drawing.Size(53, 30); btnNext.Click += btnNext_Click;
            btnLast.Text = "끝"; btnLast.Size = new System.Drawing.Size(48, 30); btnLast.Click += btnLast_Click;
            cmbSpeed.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            cmbSpeed.Width = 64; cmbSpeed.Items.AddRange(new object[] { "1×", "2×", "4×" });
            cmbSpeed.SelectedIndexChanged += cmbSpeed_SelectedIndexChanged;
            lblSequenceCaption.Text = "순번"; lblSequenceCaption.Size = new System.Drawing.Size(43, 28);
            lblSequenceCaption.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            lblSequenceCaption.Margin = new System.Windows.Forms.Padding(24, 3, 3, 3);
            numSequence.Size = new System.Drawing.Size(75, 28); numSequence.Minimum = 1; numSequence.Maximum = 100000; numSequence.Value = 1;
            numSequence.KeyDown += numSequence_KeyDown;
            lblTotal.Size = new System.Drawing.Size(82, 28); lblTotal.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            btnJump.Text = "보기"; btnJump.Size = new System.Drawing.Size(55, 30); btnJump.Click += btnJump_Click;
            trackSequence.Dock = System.Windows.Forms.DockStyle.Fill;
            trackSequence.Minimum = 1; trackSequence.Maximum = 100000; trackSequence.Value = 1;
            trackSequence.TickStyle = System.Windows.Forms.TickStyle.None;
            trackSequence.ValueChanged += trackSequence_ValueChanged;
            lblPlaybackNotice.Text = "화면 미리보기 · 장비 이동 없음";
            lblPlaybackNotice.Dock = System.Windows.Forms.DockStyle.Fill;
            lblPlaybackNotice.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;

            layoutFooter.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutFooter.Padding = new System.Windows.Forms.Padding(13, 9, 13, 9);
            layoutFooter.BackColor = System.Drawing.Color.White;
            layoutFooter.ColumnCount = 3;
            layoutFooter.RowCount = 1;
            layoutFooter.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutFooter.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 164));
            layoutFooter.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 84));
            layoutFooter.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100));
            layoutFooter.Controls.Add(lblStatus, 0, 0);
            layoutFooter.Controls.Add(btnApply, 1, 0);
            layoutFooter.Controls.Add(btnClose, 2, 0);
            lblStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            lblStatus.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            lblStatus.AutoEllipsis = true;
            btnApply.Dock = System.Windows.Forms.DockStyle.Fill;
            btnApply.Text = "이 순서로 적용";
            btnApply.BackColor = System.Drawing.Color.FromArgb(38, 113, 185);
            btnApply.ForeColor = System.Drawing.Color.White;
            btnApply.Click += btnApply_Click;
            btnClose.Dock = System.Windows.Forms.DockStyle.Fill;
            btnClose.Text = "닫기";
            btnClose.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            btnClose.Click += btnClose_Click;
            timerPlayback.Interval = 900;
            timerPlayback.Tick += timerPlayback_Tick;

            AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.Color.FromArgb(237, 240, 244);
            Font = new System.Drawing.Font("맑은 고딕", 9F);
            ClientSize = new System.Drawing.Size(1100, 880);
            MinimumSize = new System.Drawing.Size(1020, 800);
            StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            Name = "InputPickupOrderDialog";
            Text = "픽업 순서 보기 / Pickup Order";
            ShowInTaskbar = false;
            CancelButton = btnClose;
            Controls.Add(layoutRoot);
            FormClosed += InputPickupOrderDialog_FormClosed;
            ((System.ComponentModel.ISupportInitialize)gridOrder).EndInit();
            ((System.ComponentModel.ISupportInitialize)numSequence).EndInit();
            ((System.ComponentModel.ISupportInitialize)trackSequence).EndInit();
            layoutRoot.ResumeLayout(false);
            ResumeLayout(false);
        }
    }
}
