namespace QMC.CDT_320.Ui.Dialogs
{
    partial class WaferMapProcessSettingsDialog
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.TableLayoutPanel layout;
        private System.Windows.Forms.TableLayoutPanel options;
        private System.Windows.Forms.FlowLayoutPanel buttons;
        private System.Windows.Forms.Label lblInputSource;
        private System.Windows.Forms.Label lblSourceHint;
        private System.Windows.Forms.ComboBox cmbInputSource;
        private System.Windows.Forms.Label lblRecipe;
        private System.Windows.Forms.Label lblRole;
        private System.Windows.Forms.Label lblFormat;
        private System.Windows.Forms.Label lblRotation;
        private System.Windows.Forms.Label lblOrigin;
        private System.Windows.Forms.Label lblNote;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.Label lblSelected;
        private System.Windows.Forms.ComboBox cmbRole;
        private System.Windows.Forms.ComboBox cmbFormat;
        private System.Windows.Forms.ComboBox cmbRotation;
        private System.Windows.Forms.ComboBox cmbOrigin;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.Button btnCancel;
        private QMC.CDT320.Ui.Controls.DieMapView mapView;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.layout = new System.Windows.Forms.TableLayoutPanel();
            this.options = new System.Windows.Forms.TableLayoutPanel();
            this.buttons = new System.Windows.Forms.FlowLayoutPanel();
            this.lblInputSource = new System.Windows.Forms.Label();
            this.lblSourceHint = new System.Windows.Forms.Label();
            this.cmbInputSource = new System.Windows.Forms.ComboBox();
            this.lblRecipe = new System.Windows.Forms.Label();
            this.lblRole = new System.Windows.Forms.Label();
            this.lblFormat = new System.Windows.Forms.Label();
            this.lblRotation = new System.Windows.Forms.Label();
            this.lblOrigin = new System.Windows.Forms.Label();
            this.lblNote = new System.Windows.Forms.Label();
            this.lblStatus = new System.Windows.Forms.Label();
            this.lblSelected = new System.Windows.Forms.Label();
            this.cmbRole = new System.Windows.Forms.ComboBox();
            this.cmbFormat = new System.Windows.Forms.ComboBox();
            this.cmbRotation = new System.Windows.Forms.ComboBox();
            this.cmbOrigin = new System.Windows.Forms.ComboBox();
            this.btnSave = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.mapView = new QMC.CDT320.Ui.Controls.DieMapView();
            this.layout.SuspendLayout();
            this.options.SuspendLayout();
            this.buttons.SuspendLayout();
            this.SuspendLayout();
            this.layout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.layout.Padding = new System.Windows.Forms.Padding(16);
            this.layout.ColumnCount = 1;
            this.layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.layout.RowCount = 7;
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 120F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 74F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 60F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 52F));
            this.layout.Controls.Add(this.lblRecipe, 0, 0);
            this.layout.Controls.Add(this.options, 0, 1);
            this.layout.Controls.Add(this.lblNote, 0, 2);
            this.layout.Controls.Add(this.mapView, 0, 3);
            this.layout.Controls.Add(this.lblStatus, 0, 4);
            this.layout.Controls.Add(this.lblSelected, 0, 5);
            this.layout.Controls.Add(this.buttons, 0, 6);
            this.options.Dock = System.Windows.Forms.DockStyle.Fill;
            this.options.ColumnCount = 4;
            this.options.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 105F));
            this.options.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.options.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 105F));
            this.options.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.options.RowCount = 3;
            this.options.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.options.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.options.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.options.Controls.Add(this.lblRole, 0, 1);
            this.options.Controls.Add(this.cmbRole, 1, 1);
            this.options.Controls.Add(this.lblFormat, 2, 1);
            this.options.Controls.Add(this.cmbFormat, 3, 1);
            this.options.Controls.Add(this.lblRotation, 0, 2);
            this.options.Controls.Add(this.cmbRotation, 1, 2);
            this.options.Controls.Add(this.lblOrigin, 2, 2);
            this.options.Controls.Add(this.cmbOrigin, 3, 2);
            this.options.Controls.Add(this.lblInputSource, 0, 0);
            this.options.Controls.Add(this.cmbInputSource, 1, 0);
            this.options.Controls.Add(this.lblSourceHint, 2, 0);
            this.options.SetColumnSpan(this.lblSourceHint, 2);
            this.lblInputSource.Text = "입력 맵 사용";
            this.lblInputSource.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInputSource.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblSourceHint.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblSourceHint.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblSourceHint.ForeColor = System.Drawing.Color.FromArgb(78, 91, 108);
            this.cmbInputSource.Name = "cmbInputSource";
            this.cmbInputSource.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbInputSource.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbInputSource.Items.AddRange(new object[] { "원격 맵 다운로드", "등록 맵 사용 (원격 미사용)" });
            this.cmbInputSource.SelectedIndexChanged += new System.EventHandler(this.settings_SelectedIndexChanged);
            this.lblRecipe.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRecipe.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblRecipe.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblRole.Text = "설정 대상";
            this.lblRole.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRole.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblFormat.Text = "원격 맵 구분자";
            this.lblFormat.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFormat.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblRotation.Text = "맵 회전";
            this.lblRotation.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRotation.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblOrigin.Text = "좌표 기준 (1,1)";
            this.lblOrigin.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblOrigin.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cmbRole.Name = "cmbRole";
            this.cmbRole.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbRole.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbRole.Items.AddRange(new object[] { "입력", "출력 · 양품 미리보기", "출력 · 불량 미리보기" });
            this.cmbRole.SelectedIndexChanged += new System.EventHandler(this.cmbRole_SelectedIndexChanged);
            this.cmbFormat.Name = "cmbFormat";
            this.cmbFormat.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbFormat.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFormat.Items.AddRange(new object[] { "기존 설정 사용", "삼성 (RAD)", "CAMTEK", "서클 (등록 생성 맵)", "타업체 (미지원 형식)" });
            this.cmbFormat.SelectedIndexChanged += new System.EventHandler(this.settings_SelectedIndexChanged);
            this.cmbRotation.Name = "cmbRotation";
            this.cmbRotation.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbRotation.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbRotation.Items.AddRange(new object[] { "0° · 등록 맵 방향 유지", "180° 회전" });
            this.cmbRotation.SelectedIndexChanged += new System.EventHandler(this.settings_SelectedIndexChanged);
            this.cmbOrigin.Name = "cmbOrigin";
            this.cmbOrigin.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbOrigin.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbOrigin.Items.AddRange(new object[] { "좌상단 (X→ Y↓)", "좌하단 (X→ Y↑)", "우상단 (X← Y↓)", "우하단 (X← Y↑)", "센터 (X→ Y↑)" });
            this.cmbOrigin.SelectedIndexChanged += new System.EventHandler(this.settings_SelectedIndexChanged);
            this.lblNote.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNote.Text = "입력/출력 등록 맵은 구분자와 관계없이 사용합니다. 구분자는 원격 입력 다운로드 파일만 검사하며, 불일치하면 알람으로 차단합니다.\r\n아래 미리보기는 등록 맵입니다. 회전은 기준 맵에 적용하며 기구 T축은 별도입니다. 90°/270° 맵 공정 사용은 차단됩니다.\r\n화면·결과 X/Y는 1,1 기준입니다. 센터는 격자 중심이며 짝수 격자는 기준점 양옆이 0.5/1.5입니다. 출력 양품/불량는 같은 회전·원점을 사용합니다.";
            this.lblNote.ForeColor = System.Drawing.Color.FromArgb(78, 91, 108);
            this.mapView.Name = "mapView";
            this.mapView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mapView.ShowWaferOutline = true;
            this.mapView.ShowEquipmentAxes = false;
            this.mapView.Caption = "공정 맵 미리보기 · 원점 및 공정 순서";
            this.lblStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStatus.Padding = new System.Windows.Forms.Padding(0, 8, 0, 0);
            this.lblSelected.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblSelected.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttons.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttons.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft;
            this.buttons.Controls.Add(this.btnSave);
            this.buttons.Controls.Add(this.btnCancel);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(275, 38);
            this.btnSave.Text = "설정 저장 및 현재 레시피 적용";
            this.btnSave.BackColor = System.Drawing.Color.FromArgb(230, 88, 31);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            this.btnCancel.Size = new System.Drawing.Size(120, 38);
            this.btnCancel.Text = "취소";
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.AcceptButton = this.btnSave;
            this.CancelButton = this.btnCancel;
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1160, 790);
            this.MinimumSize = new System.Drawing.Size(1050, 720);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "레시피 · 공정 맵 설정";
            this.Controls.Add(this.layout);
            this.layout.ResumeLayout(false);
            this.options.ResumeLayout(false);
            this.buttons.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
