namespace QMC.CDT_320.Ui.Dialogs
{
    partial class WaferMapViewerDialog
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.TableLayoutPanel layoutRoot;
        private System.Windows.Forms.FlowLayoutPanel panelFileTools;
        private System.Windows.Forms.Label lblFormat;
        private System.Windows.Forms.ComboBox cmbFormat;
        private System.Windows.Forms.Button btnOpen;
        private System.Windows.Forms.Button btnCurrent;
        private System.Windows.Forms.Button btnRecent;
        private System.Windows.Forms.TextBox txtFile;
        private System.Windows.Forms.Label lblNotice;
        private System.Windows.Forms.TableLayoutPanel layoutBody;
        private System.Windows.Forms.TableLayoutPanel layoutFiles;
        private System.Windows.Forms.TableLayoutPanel layoutFolder;
        private System.Windows.Forms.TextBox txtFolder;
        private System.Windows.Forms.Button btnFolder;
        private System.Windows.Forms.Button btnRefresh;
        private System.Windows.Forms.Label lblFiles;
        private System.Windows.Forms.ListBox listFiles;
        private System.Windows.Forms.Label lblFileHint;
        private System.Windows.Forms.TableLayoutPanel layoutMap;
        private System.Windows.Forms.FlowLayoutPanel panelMapTools;
        private System.Windows.Forms.Button btnOriginal;
        private System.Windows.Forms.Button btnProcess;
        private System.Windows.Forms.Button btnRotateLeft;
        private System.Windows.Forms.Button btnRotateRight;
        private System.Windows.Forms.Button btnFit;
        private System.Windows.Forms.Label lblRotation;
        private WaferMapViewerView mapViewer;
        private System.Windows.Forms.Label lblMapHint;
        private System.Windows.Forms.TableLayoutPanel layoutDetails;
        private System.Windows.Forms.Label lblSummary;
        private System.Windows.Forms.Label lblHeaderTitle;
        private System.Windows.Forms.DataGridView gridHeaders;
        private System.Windows.Forms.DataGridViewTextBoxColumn colHeaderName;
        private System.Windows.Forms.DataGridViewTextBoxColumn colHeaderValue;
        private System.Windows.Forms.Label lblBinTitle;
        private System.Windows.Forms.DataGridView gridBins;
        private System.Windows.Forms.DataGridViewTextBoxColumn colBinColor;
        private System.Windows.Forms.DataGridViewTextBoxColumn colBinName;
        private System.Windows.Forms.DataGridViewTextBoxColumn colBinCount;
        private System.Windows.Forms.Label lblSelected;
        private System.Windows.Forms.TableLayoutPanel layoutFooter;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.OpenFileDialog openMapDialog;
        private System.Windows.Forms.FolderBrowserDialog folderMapDialog;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            layoutRoot = new System.Windows.Forms.TableLayoutPanel();
            panelFileTools = new System.Windows.Forms.FlowLayoutPanel();
            lblFormat = new System.Windows.Forms.Label();
            cmbFormat = new System.Windows.Forms.ComboBox();
            btnOpen = new System.Windows.Forms.Button();
            btnCurrent = new System.Windows.Forms.Button();
            btnRecent = new System.Windows.Forms.Button();
            txtFile = new System.Windows.Forms.TextBox();
            lblNotice = new System.Windows.Forms.Label();
            layoutBody = new System.Windows.Forms.TableLayoutPanel();
            layoutFiles = new System.Windows.Forms.TableLayoutPanel();
            layoutFolder = new System.Windows.Forms.TableLayoutPanel();
            txtFolder = new System.Windows.Forms.TextBox();
            btnFolder = new System.Windows.Forms.Button();
            btnRefresh = new System.Windows.Forms.Button();
            lblFiles = new System.Windows.Forms.Label();
            listFiles = new System.Windows.Forms.ListBox();
            lblFileHint = new System.Windows.Forms.Label();
            layoutMap = new System.Windows.Forms.TableLayoutPanel();
            panelMapTools = new System.Windows.Forms.FlowLayoutPanel();
            btnOriginal = new System.Windows.Forms.Button();
            btnProcess = new System.Windows.Forms.Button();
            btnRotateLeft = new System.Windows.Forms.Button();
            btnRotateRight = new System.Windows.Forms.Button();
            btnFit = new System.Windows.Forms.Button();
            lblRotation = new System.Windows.Forms.Label();
            mapViewer = new WaferMapViewerView();
            lblMapHint = new System.Windows.Forms.Label();
            layoutDetails = new System.Windows.Forms.TableLayoutPanel();
            lblSummary = new System.Windows.Forms.Label();
            lblHeaderTitle = new System.Windows.Forms.Label();
            gridHeaders = new System.Windows.Forms.DataGridView();
            colHeaderName = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colHeaderValue = new System.Windows.Forms.DataGridViewTextBoxColumn();
            lblBinTitle = new System.Windows.Forms.Label();
            gridBins = new System.Windows.Forms.DataGridView();
            colBinColor = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colBinName = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colBinCount = new System.Windows.Forms.DataGridViewTextBoxColumn();
            lblSelected = new System.Windows.Forms.Label();
            layoutFooter = new System.Windows.Forms.TableLayoutPanel();
            lblStatus = new System.Windows.Forms.Label();
            btnClose = new System.Windows.Forms.Button();
            openMapDialog = new System.Windows.Forms.OpenFileDialog();
            folderMapDialog = new System.Windows.Forms.FolderBrowserDialog();
            components.Add(openMapDialog);
            components.Add(folderMapDialog);
            ((System.ComponentModel.ISupportInitialize)gridHeaders).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gridBins).BeginInit();
            layoutRoot.SuspendLayout();
            panelFileTools.SuspendLayout();
            layoutBody.SuspendLayout();
            layoutFiles.SuspendLayout();
            layoutFolder.SuspendLayout();
            layoutMap.SuspendLayout();
            panelMapTools.SuspendLayout();
            layoutDetails.SuspendLayout();
            layoutFooter.SuspendLayout();
            SuspendLayout();

            layoutRoot.ColumnCount = 1;
            layoutRoot.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutRoot.RowCount = 6;
            layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 46F));
            layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 48F));
            layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 48F));
            layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 44F));
            layoutRoot.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutRoot.Padding = new System.Windows.Forms.Padding(10);
            layoutRoot.Name = "layoutRoot";
            layoutRoot.Controls.Add(panelFileTools, 0, 0);
            layoutRoot.Controls.Add(txtFile, 0, 1);
            layoutRoot.Controls.Add(lblNotice, 0, 2);
            layoutRoot.Controls.Add(layoutBody, 0, 3);
            layoutRoot.Controls.Add(lblSelected, 0, 4);
            layoutRoot.Controls.Add(layoutFooter, 0, 5);

            panelFileTools.Dock = System.Windows.Forms.DockStyle.Fill;
            panelFileTools.WrapContents = false;
            panelFileTools.Margin = new System.Windows.Forms.Padding(0);
            panelFileTools.Controls.Add(lblFormat);
            panelFileTools.Controls.Add(cmbFormat);
            panelFileTools.Controls.Add(btnOpen);
            panelFileTools.Controls.Add(btnCurrent);
            panelFileTools.Controls.Add(btnRecent);
            lblFormat.Text = "열 파일 형식";
            lblFormat.AutoSize = true;
            lblFormat.Margin = new System.Windows.Forms.Padding(3, 12, 6, 3);
            cmbFormat.Name = "cmbFormat";
            cmbFormat.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            cmbFormat.Items.AddRange(new object[] { "삼성 (RAD 좌표형)", "캠택 (CAMTEK RowData)" });
            cmbFormat.Size = new System.Drawing.Size(215, 25);
            cmbFormat.Margin = new System.Windows.Forms.Padding(3, 8, 12, 3);
            cmbFormat.SelectedIndexChanged += new System.EventHandler(cmbFormat_SelectedIndexChanged);
            btnOpen.Name = "btnOpen";
            btnOpen.Text = "파일 열기...";
            btnOpen.Size = new System.Drawing.Size(115, 36);
            btnOpen.BackColor = System.Drawing.Color.FromArgb(36, 93, 154);
            btnOpen.ForeColor = System.Drawing.Color.White;
            btnOpen.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnOpen.Click += new System.EventHandler(btnOpen_Click);
            btnCurrent.Name = "btnCurrent";
            btnCurrent.Text = "현재 / 최근 맵";
            btnCurrent.Size = new System.Drawing.Size(135, 36);
            btnCurrent.Click += new System.EventHandler(btnCurrent_Click);
            btnRecent.Name = "btnRecent";
            btnRecent.Text = "최근 수신 맵";
            btnRecent.Size = new System.Drawing.Size(120, 36);
            btnRecent.Click += new System.EventHandler(btnRecent_Click);

            txtFile.Name = "txtFile";
            txtFile.Dock = System.Windows.Forms.DockStyle.Fill;
            txtFile.ReadOnly = true;
            txtFile.BackColor = System.Drawing.Color.White;
            txtFile.Text = "아직 파일을 열지 않았습니다.";
            lblNotice.Text = "파일 확인용 뷰어 · 보기 방향과 형식 선택은 이 창에만 적용됩니다.";
            lblNotice.Dock = System.Windows.Forms.DockStyle.Fill;
            lblNotice.ForeColor = System.Drawing.Color.FromArgb(110, 70, 20);
            lblNotice.BackColor = System.Drawing.Color.FromArgb(255, 246, 222);
            lblNotice.Padding = new System.Windows.Forms.Padding(8, 4, 8, 3);
            lblNotice.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;

            layoutBody.ColumnCount = 3;
            layoutBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 210F));
            layoutBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 285F));
            layoutBody.RowCount = 1;
            layoutBody.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutBody.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutBody.Margin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            layoutBody.Controls.Add(layoutFiles, 0, 0);
            layoutBody.Controls.Add(layoutMap, 1, 0);
            layoutBody.Controls.Add(layoutDetails, 2, 0);

            layoutFiles.ColumnCount = 1;
            layoutFiles.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutFiles.RowCount = 5;
            layoutFiles.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 33F));
            layoutFiles.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            layoutFiles.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            layoutFiles.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutFiles.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            layoutFiles.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutFiles.Margin = new System.Windows.Forms.Padding(0, 0, 6, 0);
            layoutFiles.Controls.Add(layoutFolder, 0, 0);
            layoutFiles.Controls.Add(btnRefresh, 0, 1);
            layoutFiles.Controls.Add(lblFiles, 0, 2);
            layoutFiles.Controls.Add(listFiles, 0, 3);
            layoutFiles.Controls.Add(lblFileHint, 0, 4);
            layoutFolder.ColumnCount = 2;
            layoutFolder.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutFolder.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 45F));
            layoutFolder.RowCount = 1;
            layoutFolder.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutFolder.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutFolder.Margin = new System.Windows.Forms.Padding(0);
            layoutFolder.Controls.Add(txtFolder, 0, 0);
            layoutFolder.Controls.Add(btnFolder, 1, 0);
            txtFolder.Name = "txtFolder";
            txtFolder.Dock = System.Windows.Forms.DockStyle.Fill;
            txtFolder.KeyDown += new System.Windows.Forms.KeyEventHandler(txtFolder_KeyDown);
            btnFolder.Name = "btnFolder";
            btnFolder.Text = "...";
            btnFolder.Dock = System.Windows.Forms.DockStyle.Fill;
            btnFolder.Margin = new System.Windows.Forms.Padding(0, 1, 0, 2);
            btnFolder.Click += new System.EventHandler(btnFolder_Click);
            btnRefresh.Name = "btnRefresh";
            btnRefresh.Text = "목록 갱신";
            btnRefresh.Dock = System.Windows.Forms.DockStyle.Fill;
            btnRefresh.Click += new System.EventHandler(btnRefresh_Click);
            lblFiles.Text = "파일 목록";
            lblFiles.Dock = System.Windows.Forms.DockStyle.Fill;
            lblFiles.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            listFiles.Name = "listFiles";
            listFiles.Dock = System.Windows.Forms.DockStyle.Fill;
            listFiles.HorizontalScrollbar = true;
            listFiles.IntegralHeight = false;
            listFiles.DoubleClick += new System.EventHandler(listFiles_DoubleClick);
            listFiles.KeyDown += new System.Windows.Forms.KeyEventHandler(listFiles_KeyDown);
            lblFileHint.Text = "두 번 누르기 / Enter로 열기\r\n확장자 없는 맵도 표시합니다.";
            lblFileHint.Dock = System.Windows.Forms.DockStyle.Fill;
            lblFileHint.Font = new System.Drawing.Font("맑은 고딕", 8F);

            layoutMap.ColumnCount = 1;
            layoutMap.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutMap.RowCount = 4;
            layoutMap.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 74F));
            layoutMap.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 27F));
            layoutMap.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutMap.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            layoutMap.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutMap.Margin = new System.Windows.Forms.Padding(0, 0, 6, 0);
            layoutMap.Controls.Add(panelMapTools, 0, 0);
            layoutMap.Controls.Add(lblRotation, 0, 1);
            layoutMap.Controls.Add(mapViewer, 0, 2);
            layoutMap.Controls.Add(lblMapHint, 0, 3);
            panelMapTools.Dock = System.Windows.Forms.DockStyle.Fill;
            panelMapTools.Margin = new System.Windows.Forms.Padding(0);
            panelMapTools.WrapContents = true;
            panelMapTools.Controls.Add(btnOriginal);
            panelMapTools.Controls.Add(btnProcess);
            panelMapTools.Controls.Add(btnRotateLeft);
            panelMapTools.Controls.Add(btnRotateRight);
            panelMapTools.Controls.Add(btnFit);
            btnOriginal.Name = "btnOriginal";
            btnOriginal.Text = "원본 0°";
            btnOriginal.Size = new System.Drawing.Size(84, 31);
            btnOriginal.Click += new System.EventHandler(btnOriginal_Click);
            btnProcess.Name = "btnProcess";
            btnProcess.Text = "공정 방향 참고";
            btnProcess.Size = new System.Drawing.Size(163, 31);
            btnProcess.Click += new System.EventHandler(btnProcess_Click);
            btnRotateLeft.Name = "btnRotateLeft";
            btnRotateLeft.Text = "↶ 왼쪽 90°";
            btnRotateLeft.Size = new System.Drawing.Size(108, 31);
            btnRotateLeft.Click += new System.EventHandler(btnRotateLeft_Click);
            btnRotateRight.Name = "btnRotateRight";
            btnRotateRight.Text = "↷ 오른쪽 90°";
            btnRotateRight.Size = new System.Drawing.Size(108, 31);
            btnRotateRight.Click += new System.EventHandler(btnRotateRight_Click);
            btnFit.Name = "btnFit";
            btnFit.Text = "화면 맞춤";
            btnFit.Size = new System.Drawing.Size(97, 31);
            btnFit.Click += new System.EventHandler(btnFit_Click);
            lblRotation.Text = "맵을 열어 주세요.";
            lblRotation.Dock = System.Windows.Forms.DockStyle.Fill;
            lblRotation.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            mapViewer.Name = "mapViewer";
            mapViewer.Dock = System.Windows.Forms.DockStyle.Fill;
            mapViewer.Margin = new System.Windows.Forms.Padding(0);
            mapViewer.BackColor = System.Drawing.Color.FromArgb(27, 32, 42);
            mapViewer.Caption = "웨이퍼맵 · 확인용";
            mapViewer.CompactUsedBounds = false;
            mapViewer.ShowEquipmentAxes = false;
            mapViewer.ShowWaferOutline = false;
            mapViewer.EnableRectangleSelection = false;
            mapViewer.CellColorResolver = ResolveEntryColor;
            mapViewer.CellTextResolver = ResolveEntryText;
            mapViewer.CellStatusResolver = ResolveEntryStatus;
            mapViewer.LegendItemsResolver = ResolveMapLegend;
            mapViewer.CellClicked += mapViewer_CellClicked;
            mapViewer.EmptyAreaClicked += mapViewer_EmptyAreaClicked;
            lblMapHint.Text = "휠: 확대/축소 · 끌기: 이동 · 클릭: 다이 선택";
            lblMapHint.Dock = System.Windows.Forms.DockStyle.Fill;
            lblMapHint.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            lblMapHint.Font = new System.Drawing.Font("맑은 고딕", 8.5F);

            layoutDetails.ColumnCount = 1;
            layoutDetails.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutDetails.RowCount = 5;
            layoutDetails.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 72F));
            layoutDetails.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            layoutDetails.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            layoutDetails.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            layoutDetails.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            layoutDetails.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutDetails.Margin = new System.Windows.Forms.Padding(0);
            layoutDetails.Controls.Add(lblSummary, 0, 0);
            layoutDetails.Controls.Add(lblHeaderTitle, 0, 1);
            layoutDetails.Controls.Add(gridHeaders, 0, 2);
            layoutDetails.Controls.Add(lblBinTitle, 0, 3);
            layoutDetails.Controls.Add(gridBins, 0, 4);
            lblSummary.Text = "파일 헤더와 BIN 수량\r\n파일을 열면 표시됩니다.";
            lblSummary.Dock = System.Windows.Forms.DockStyle.Fill;
            lblSummary.BackColor = System.Drawing.Color.FromArgb(234, 240, 247);
            lblSummary.Padding = new System.Windows.Forms.Padding(8, 6, 3, 3);
            lblHeaderTitle.Text = "원본 헤더";
            lblHeaderTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            lblHeaderTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            gridHeaders.Name = "gridHeaders";
            gridHeaders.Dock = System.Windows.Forms.DockStyle.Fill;
            gridHeaders.BackgroundColor = System.Drawing.Color.White;
            gridHeaders.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            gridHeaders.ReadOnly = true;
            gridHeaders.AllowUserToAddRows = false;
            gridHeaders.AllowUserToDeleteRows = false;
            gridHeaders.AllowUserToResizeRows = false;
            gridHeaders.RowHeadersVisible = false;
            gridHeaders.MultiSelect = false;
            gridHeaders.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
            gridHeaders.DefaultCellStyle.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            gridHeaders.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            gridHeaders.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { colHeaderName, colHeaderValue });
            colHeaderName.Name = "colHeaderName";
            colHeaderName.HeaderText = "항목";
            colHeaderName.Width = 86;
            colHeaderName.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            colHeaderValue.Name = "colHeaderValue";
            colHeaderValue.HeaderText = "값";
            colHeaderValue.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            colHeaderValue.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            lblBinTitle.Text = "BIN 수량 / 뷰어 구분 색상";
            lblBinTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            lblBinTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            gridBins.Name = "gridBins";
            gridBins.Dock = System.Windows.Forms.DockStyle.Fill;
            gridBins.BackgroundColor = System.Drawing.Color.White;
            gridBins.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            gridBins.ReadOnly = true;
            gridBins.AllowUserToAddRows = false;
            gridBins.AllowUserToDeleteRows = false;
            gridBins.AllowUserToResizeRows = false;
            gridBins.RowHeadersVisible = false;
            gridBins.MultiSelect = false;
            gridBins.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            gridBins.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { colBinColor, colBinName, colBinCount });
            colBinColor.Name = "colBinColor";
            colBinColor.HeaderText = "색";
            colBinColor.Width = 34;
            colBinColor.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            colBinName.Name = "colBinName";
            colBinName.HeaderText = "BIN / 토큰";
            colBinName.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            colBinName.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            colBinCount.Name = "colBinCount";
            colBinCount.HeaderText = "수량";
            colBinCount.Width = 68;
            colBinCount.DefaultCellStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
            colBinCount.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;

            lblSelected.Name = "lblSelected";
            lblSelected.Text = "선택한 다이 없음 · 원본 주소와 현재 보기의 좌하단 1 기준 주소를 표시합니다.";
            lblSelected.Dock = System.Windows.Forms.DockStyle.Fill;
            lblSelected.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            lblSelected.Padding = new System.Windows.Forms.Padding(8, 4, 5, 4);
            lblSelected.BackColor = System.Drawing.Color.FromArgb(231, 239, 249);
            layoutFooter.ColumnCount = 2;
            layoutFooter.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutFooter.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 95F));
            layoutFooter.RowCount = 1;
            layoutFooter.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            layoutFooter.Dock = System.Windows.Forms.DockStyle.Fill;
            layoutFooter.Margin = new System.Windows.Forms.Padding(0);
            layoutFooter.Controls.Add(lblStatus, 0, 0);
            layoutFooter.Controls.Add(btnClose, 1, 0);
            lblStatus.Name = "lblStatus";
            lblStatus.Text = "파일을 열어 웨이퍼맵을 확인하세요.";
            lblStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            lblStatus.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            lblStatus.AutoEllipsis = true;
            btnClose.Name = "btnClose";
            btnClose.Text = "닫기";
            btnClose.Dock = System.Windows.Forms.DockStyle.Fill;
            btnClose.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            btnClose.Click += new System.EventHandler(btnClose_Click);
            openMapDialog.Title = "웨이퍼맵 파일 열기";
            openMapDialog.Filter = "모든 웨이퍼맵 파일 (*.*)|*.*|텍스트 파일 (*.txt)|*.txt";
            openMapDialog.CheckFileExists = true;
            openMapDialog.Multiselect = false;
            openMapDialog.RestoreDirectory = true;
            folderMapDialog.Description = "웨이퍼맵이 있는 폴더를 선택하세요.";
            folderMapDialog.ShowNewFolderButton = false;

            AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.Color.FromArgb(245, 247, 250);
            ClientSize = new System.Drawing.Size(1300, 800);
            MinimumSize = new System.Drawing.Size(1000, 640);
            Font = new System.Drawing.Font("맑은 고딕", 9F);
            StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
            ShowInTaskbar = false;
            Text = "웨이퍼맵 보기";
            Name = "WaferMapViewerDialog";
            CancelButton = btnClose;
            Controls.Add(layoutRoot);
            Shown += new System.EventHandler(WaferMapViewerDialog_Shown);
            ((System.ComponentModel.ISupportInitialize)gridHeaders).EndInit();
            ((System.ComponentModel.ISupportInitialize)gridBins).EndInit();
            layoutFooter.ResumeLayout(false);
            layoutDetails.ResumeLayout(false);
            panelMapTools.ResumeLayout(false);
            layoutMap.ResumeLayout(false);
            layoutFolder.ResumeLayout(false);
            layoutFolder.PerformLayout();
            layoutFiles.ResumeLayout(false);
            layoutBody.ResumeLayout(false);
            panelFileTools.ResumeLayout(false);
            panelFileTools.PerformLayout();
            layoutRoot.ResumeLayout(false);
            layoutRoot.PerformLayout();
            ResumeLayout(false);
        }
    }
}
