namespace QMC.CDT_320.Ui.Dialogs
{
    partial class WaferMapCreateDialog
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel panelRoot;
        private System.Windows.Forms.TableLayoutPanel panelBody;
        private System.Windows.Forms.TableLayoutPanel panelPreview;
        private System.Windows.Forms.Panel panelOptions;
        private System.Windows.Forms.TableLayoutPanel panelOptionsLayout;
        private System.Windows.Forms.TableLayoutPanel panelSettings;
        private System.Windows.Forms.TableLayoutPanel panelEdges;
        private System.Windows.Forms.TableLayoutPanel panelTools;
        private System.Windows.Forms.TableLayoutPanel panelFooter;
        private System.Windows.Forms.GroupBox groupSettings;
        private System.Windows.Forms.GroupBox groupEdges;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label lblDiameter;
        private System.Windows.Forms.Label lblDieX;
        private System.Windows.Forms.Label lblDieY;
        private System.Windows.Forms.Label lblGapX;
        private System.Windows.Forms.Label lblGapY;
        private System.Windows.Forms.Label lblStepX;
        private System.Windows.Forms.Label lblStepY;
        private System.Windows.Forms.Label lblEdgeTop;
        private System.Windows.Forms.Label lblEdgeBottom;
        private System.Windows.Forms.Label lblEdgeLeft;
        private System.Windows.Forms.Label lblEdgeRight;
        private System.Windows.Forms.Label lblCounts;
        private System.Windows.Forms.Label lblSelection;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.NumericUpDown numDiameter;
        private System.Windows.Forms.NumericUpDown numDieX;
        private System.Windows.Forms.NumericUpDown numDieY;
        private System.Windows.Forms.NumericUpDown numGapX;
        private System.Windows.Forms.NumericUpDown numGapY;
        private System.Windows.Forms.NumericUpDown numEdgeTop;
        private System.Windows.Forms.NumericUpDown numEdgeBottom;
        private System.Windows.Forms.NumericUpDown numEdgeLeft;
        private System.Windows.Forms.NumericUpDown numEdgeRight;
        private System.Windows.Forms.TextBox txtStepX;
        private System.Windows.Forms.TextBox txtStepY;
        private System.Windows.Forms.Button btnGenerate;
        private System.Windows.Forms.Button btnApplyEdges;
        private System.Windows.Forms.Button btnRestore;
        private System.Windows.Forms.Button btnFit;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.ToolTip toolTip;
        private WaferMapGenerationView mapView;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.panelRoot = new System.Windows.Forms.TableLayoutPanel();
            this.panelBody = new System.Windows.Forms.TableLayoutPanel();
            this.panelPreview = new System.Windows.Forms.TableLayoutPanel();
            this.panelOptions = new System.Windows.Forms.Panel();
            this.panelOptionsLayout = new System.Windows.Forms.TableLayoutPanel();
            this.panelSettings = new System.Windows.Forms.TableLayoutPanel();
            this.panelEdges = new System.Windows.Forms.TableLayoutPanel();
            this.panelTools = new System.Windows.Forms.TableLayoutPanel();
            this.panelFooter = new System.Windows.Forms.TableLayoutPanel();
            this.groupSettings = new System.Windows.Forms.GroupBox();
            this.groupEdges = new System.Windows.Forms.GroupBox();
            this.lblTitle = new System.Windows.Forms.Label();
            this.lblDiameter = new System.Windows.Forms.Label();
            this.lblDieX = new System.Windows.Forms.Label();
            this.lblDieY = new System.Windows.Forms.Label();
            this.lblGapX = new System.Windows.Forms.Label();
            this.lblGapY = new System.Windows.Forms.Label();
            this.lblStepX = new System.Windows.Forms.Label();
            this.lblStepY = new System.Windows.Forms.Label();
            this.lblEdgeTop = new System.Windows.Forms.Label();
            this.lblEdgeBottom = new System.Windows.Forms.Label();
            this.lblEdgeLeft = new System.Windows.Forms.Label();
            this.lblEdgeRight = new System.Windows.Forms.Label();
            this.lblCounts = new System.Windows.Forms.Label();
            this.lblSelection = new System.Windows.Forms.Label();
            this.lblStatus = new System.Windows.Forms.Label();
            this.numDiameter = new System.Windows.Forms.NumericUpDown();
            this.numDieX = new System.Windows.Forms.NumericUpDown();
            this.numDieY = new System.Windows.Forms.NumericUpDown();
            this.numGapX = new System.Windows.Forms.NumericUpDown();
            this.numGapY = new System.Windows.Forms.NumericUpDown();
            this.numEdgeTop = new System.Windows.Forms.NumericUpDown();
            this.numEdgeBottom = new System.Windows.Forms.NumericUpDown();
            this.numEdgeLeft = new System.Windows.Forms.NumericUpDown();
            this.numEdgeRight = new System.Windows.Forms.NumericUpDown();
            this.txtStepX = new System.Windows.Forms.TextBox();
            this.txtStepY = new System.Windows.Forms.TextBox();
            this.btnGenerate = new System.Windows.Forms.Button();
            this.btnApplyEdges = new System.Windows.Forms.Button();
            this.btnRestore = new System.Windows.Forms.Button();
            this.btnFit = new System.Windows.Forms.Button();
            this.btnClose = new System.Windows.Forms.Button();
            this.toolTip = new System.Windows.Forms.ToolTip(this.components);
            this.mapView = new WaferMapGenerationView();
            this.panelRoot.SuspendLayout();
            this.panelBody.SuspendLayout();
            this.panelPreview.SuspendLayout();
            this.panelOptions.SuspendLayout();
            this.panelOptionsLayout.SuspendLayout();
            this.panelSettings.SuspendLayout();
            this.panelEdges.SuspendLayout();
            this.panelTools.SuspendLayout();
            this.panelFooter.SuspendLayout();
            this.groupSettings.SuspendLayout();
            this.groupEdges.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numDiameter)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDieX)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDieY)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numGapX)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numGapY)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numEdgeTop)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numEdgeBottom)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numEdgeLeft)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numEdgeRight)).BeginInit();
            this.SuspendLayout();
            // panelRoot
            this.panelRoot.ColumnCount = 1;
            this.panelRoot.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.panelRoot.Controls.Add(this.lblTitle, 0, 0);
            this.panelRoot.Controls.Add(this.panelBody, 0, 1);
            this.panelRoot.Controls.Add(this.panelFooter, 0, 2);
            this.panelRoot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelRoot.Name = "panelRoot";
            this.panelRoot.Padding = new System.Windows.Forms.Padding(12);
            this.panelRoot.RowCount = 3;
            this.panelRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 44F));
            this.panelRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.panelRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 76F));
            this.panelRoot.TabIndex = 0;
            // lblTitle
            this.lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitle.Font = new System.Drawing.Font("맑은 고딕", 16F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(31, 52, 71);
            this.lblTitle.Margin = new System.Windows.Forms.Padding(0);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Text = "WAFER MAP CREATE";
            this.lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // panelBody
            this.panelBody.ColumnCount = 2;
            this.panelBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.panelBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 400F));
            this.panelBody.Controls.Add(this.panelPreview, 0, 0);
            this.panelBody.Controls.Add(this.panelOptions, 1, 0);
            this.panelBody.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelBody.Margin = new System.Windows.Forms.Padding(0);
            this.panelBody.Name = "panelBody";
            this.panelBody.RowCount = 1;
            this.panelBody.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.panelBody.TabIndex = 1;
            // panelPreview
            this.panelPreview.ColumnCount = 1;
            this.panelPreview.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.panelPreview.Controls.Add(this.mapView, 0, 0);
            this.panelPreview.Controls.Add(this.lblSelection, 0, 1);
            this.panelPreview.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelPreview.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.panelPreview.Name = "panelPreview";
            this.panelPreview.RowCount = 2;
            this.panelPreview.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.panelPreview.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 60F));
            this.panelPreview.TabIndex = 0;
            // mapView
            this.mapView.BackColor = System.Drawing.Color.Black;
            this.mapView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mapView.ForeColor = System.Drawing.Color.Gainsboro;
            this.mapView.Margin = new System.Windows.Forms.Padding(0);
            this.mapView.Name = "mapView";
            this.mapView.TabIndex = 0;
            this.mapView.TabStop = true;
            this.mapView.DieSelected += new System.Action<QMC.CDT320.DieMaps.GeneratedWaferDie>(this.mapView_DieSelected);
            // lblSelection
            this.lblSelection.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblSelection.ForeColor = System.Drawing.Color.FromArgb(48, 66, 79);
            this.lblSelection.Margin = new System.Windows.Forms.Padding(0);
            this.lblSelection.Name = "lblSelection";
            this.lblSelection.Padding = new System.Windows.Forms.Padding(4, 5, 4, 0);
            this.lblSelection.Text = "다이를 클릭하면 원본 주소와 웨이퍼 중심 기준 위치를 표시합니다.\r\n마우스 휠: 확대/축소 · +Y: 위쪽";
            // panelOptions
            this.panelOptions.AutoScroll = true;
            this.panelOptions.Controls.Add(this.panelOptionsLayout);
            this.panelOptions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelOptions.Margin = new System.Windows.Forms.Padding(0);
            this.panelOptions.Name = "panelOptions";
            this.panelOptions.TabIndex = 1;
            // panelOptionsLayout
            this.panelOptionsLayout.AutoSize = true;
            this.panelOptionsLayout.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.panelOptionsLayout.ColumnCount = 1;
            this.panelOptionsLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.panelOptionsLayout.Controls.Add(this.groupSettings, 0, 0);
            this.panelOptionsLayout.Controls.Add(this.btnGenerate, 0, 1);
            this.panelOptionsLayout.Controls.Add(this.lblCounts, 0, 2);
            this.panelOptionsLayout.Controls.Add(this.groupEdges, 0, 3);
            this.panelOptionsLayout.Controls.Add(this.panelTools, 0, 4);
            this.panelOptionsLayout.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelOptionsLayout.Margin = new System.Windows.Forms.Padding(0);
            this.panelOptionsLayout.Name = "panelOptionsLayout";
            this.panelOptionsLayout.Padding = new System.Windows.Forms.Padding(0, 0, 4, 0);
            this.panelOptionsLayout.RowCount = 5;
            this.panelOptionsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 256F));
            this.panelOptionsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.panelOptionsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 110F));
            this.panelOptionsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 218F));
            this.panelOptionsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 46F));
            this.panelOptionsLayout.TabIndex = 0;
            // groupSettings
            this.groupSettings.Controls.Add(this.panelSettings);
            this.groupSettings.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupSettings.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.groupSettings.Name = "groupSettings";
            this.groupSettings.Padding = new System.Windows.Forms.Padding(8);
            this.groupSettings.TabIndex = 0;
            this.groupSettings.TabStop = false;
            this.groupSettings.Text = "웨이퍼 사양 · mm";
            // panelSettings
            this.panelSettings.ColumnCount = 2;
            this.panelSettings.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 54F));
            this.panelSettings.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 46F));
            this.panelSettings.Controls.Add(this.lblDiameter, 0, 0);
            this.panelSettings.Controls.Add(this.numDiameter, 1, 0);
            this.panelSettings.Controls.Add(this.lblDieX, 0, 1);
            this.panelSettings.Controls.Add(this.numDieX, 1, 1);
            this.panelSettings.Controls.Add(this.lblDieY, 0, 2);
            this.panelSettings.Controls.Add(this.numDieY, 1, 2);
            this.panelSettings.Controls.Add(this.lblGapX, 0, 3);
            this.panelSettings.Controls.Add(this.numGapX, 1, 3);
            this.panelSettings.Controls.Add(this.lblGapY, 0, 4);
            this.panelSettings.Controls.Add(this.numGapY, 1, 4);
            this.panelSettings.Controls.Add(this.lblStepX, 0, 5);
            this.panelSettings.Controls.Add(this.txtStepX, 1, 5);
            this.panelSettings.Controls.Add(this.lblStepY, 0, 6);
            this.panelSettings.Controls.Add(this.txtStepY, 1, 6);
            this.panelSettings.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelSettings.Margin = new System.Windows.Forms.Padding(0);
            this.panelSettings.Name = "panelSettings";
            this.panelSettings.RowCount = 7;
            this.panelSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.panelSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.panelSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.panelSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.panelSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.panelSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.panelSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.panelSettings.TabIndex = 0;
            // labels
            this.lblDiameter.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDiameter.Name = "lblDiameter";
            this.lblDiameter.Text = "WAFER DIAMETER";
            this.lblDiameter.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblDieX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDieX.Name = "lblDieX";
            this.lblDieX.Text = "DIE X";
            this.lblDieX.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblDieY.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDieY.Name = "lblDieY";
            this.lblDieY.Text = "DIE Y";
            this.lblDieY.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblGapX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblGapX.Name = "lblGapX";
            this.lblGapX.Text = "GAP X";
            this.lblGapX.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblGapY.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblGapY.Name = "lblGapY";
            this.lblGapY.Text = "GAP Y";
            this.lblGapY.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblStepX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStepX.Name = "lblStepX";
            this.lblStepX.Text = "CENTER STEP X";
            this.lblStepX.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblStepY.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStepY.Name = "lblStepY";
            this.lblStepY.Text = "CENTER STEP Y";
            this.lblStepY.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // numeric settings
            this.numDiameter.DecimalPlaces = 3;
            this.numDiameter.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numDiameter.Increment = 0.001M;
            this.numDiameter.Maximum = 2147483.647M;
            this.numDiameter.Name = "numDiameter";
            this.numDiameter.TabIndex = 0;
            this.numDiameter.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numDiameter.Value = 200M;
            this.numDiameter.ValueChanged += new System.EventHandler(this.settings_ValueChanged);
            this.numDieX.DecimalPlaces = 3;
            this.numDieX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numDieX.Increment = 0.001M;
            this.numDieX.Maximum = 2147483.647M;
            this.numDieX.Name = "numDieX";
            this.numDieX.TabIndex = 1;
            this.numDieX.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numDieX.Value = 5M;
            this.numDieX.ValueChanged += new System.EventHandler(this.settings_ValueChanged);
            this.numDieY.DecimalPlaces = 3;
            this.numDieY.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numDieY.Increment = 0.001M;
            this.numDieY.Maximum = 2147483.647M;
            this.numDieY.Name = "numDieY";
            this.numDieY.TabIndex = 2;
            this.numDieY.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numDieY.Value = 5M;
            this.numDieY.ValueChanged += new System.EventHandler(this.settings_ValueChanged);
            this.numGapX.DecimalPlaces = 3;
            this.numGapX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numGapX.Increment = 0.001M;
            this.numGapX.Maximum = 2147483.647M;
            this.numGapX.Name = "numGapX";
            this.numGapX.TabIndex = 3;
            this.numGapX.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numGapX.ValueChanged += new System.EventHandler(this.settings_ValueChanged);
            this.numGapY.DecimalPlaces = 3;
            this.numGapY.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numGapY.Increment = 0.001M;
            this.numGapY.Maximum = 2147483.647M;
            this.numGapY.Name = "numGapY";
            this.numGapY.TabIndex = 4;
            this.numGapY.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numGapY.ValueChanged += new System.EventHandler(this.settings_ValueChanged);
            // center step display
            this.txtStepX.BackColor = System.Drawing.Color.FromArgb(230, 235, 239);
            this.txtStepX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtStepX.Name = "txtStepX";
            this.txtStepX.ReadOnly = true;
            this.txtStepX.TabStop = false;
            this.txtStepX.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txtStepY.BackColor = System.Drawing.Color.FromArgb(230, 235, 239);
            this.txtStepY.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtStepY.Name = "txtStepY";
            this.txtStepY.ReadOnly = true;
            this.txtStepY.TabStop = false;
            this.txtStepY.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // btnGenerate
            this.btnGenerate.BackColor = System.Drawing.Color.FromArgb(33, 102, 135);
            this.btnGenerate.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnGenerate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGenerate.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.btnGenerate.ForeColor = System.Drawing.Color.White;
            this.btnGenerate.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.btnGenerate.Name = "btnGenerate";
            this.btnGenerate.TabIndex = 1;
            this.btnGenerate.Text = "AUTO WAFER CREATE";
            this.btnGenerate.UseVisualStyleBackColor = false;
            this.btnGenerate.Click += new System.EventHandler(this.btnGenerate_Click);
            // lblCounts
            this.lblCounts.BackColor = System.Drawing.Color.White;
            this.lblCounts.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblCounts.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCounts.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.lblCounts.Name = "lblCounts";
            this.lblCounts.Padding = new System.Windows.Forms.Padding(8);
            this.lblCounts.Text = "생성 다이: —\r\n사용 영역: —\r\n후보 격자: —\r\n끝줄 실제: —";
            // groupEdges
            this.groupEdges.Controls.Add(this.panelEdges);
            this.groupEdges.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupEdges.Enabled = false;
            this.groupEdges.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.groupEdges.Name = "groupEdges";
            this.groupEdges.Padding = new System.Windows.Forms.Padding(8);
            this.groupEdges.TabIndex = 3;
            this.groupEdges.TabStop = false;
            this.groupEdges.Text = "원본 끝줄에 남길 개수";
            // panelEdges
            this.panelEdges.ColumnCount = 2;
            this.panelEdges.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 54F));
            this.panelEdges.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 46F));
            this.panelEdges.Controls.Add(this.lblEdgeTop, 0, 0);
            this.panelEdges.Controls.Add(this.numEdgeTop, 1, 0);
            this.panelEdges.Controls.Add(this.lblEdgeBottom, 0, 1);
            this.panelEdges.Controls.Add(this.numEdgeBottom, 1, 1);
            this.panelEdges.Controls.Add(this.lblEdgeLeft, 0, 2);
            this.panelEdges.Controls.Add(this.numEdgeLeft, 1, 2);
            this.panelEdges.Controls.Add(this.lblEdgeRight, 0, 3);
            this.panelEdges.Controls.Add(this.numEdgeRight, 1, 3);
            this.panelEdges.Controls.Add(this.btnApplyEdges, 0, 4);
            this.panelEdges.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelEdges.Margin = new System.Windows.Forms.Padding(0);
            this.panelEdges.Name = "panelEdges";
            this.panelEdges.RowCount = 5;
            this.panelEdges.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.panelEdges.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.panelEdges.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.panelEdges.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.panelEdges.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 42F));
            this.panelEdges.TabIndex = 0;
            // edge labels
            this.lblEdgeTop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblEdgeTop.Name = "lblEdgeTop";
            this.lblEdgeTop.Text = "TOP ROW (+Y)";
            this.lblEdgeTop.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblEdgeBottom.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblEdgeBottom.Name = "lblEdgeBottom";
            this.lblEdgeBottom.Text = "BOTTOM ROW (-Y)";
            this.lblEdgeBottom.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblEdgeLeft.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblEdgeLeft.Name = "lblEdgeLeft";
            this.lblEdgeLeft.Text = "LEFT COLUMN (-X)";
            this.lblEdgeLeft.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblEdgeRight.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblEdgeRight.Name = "lblEdgeRight";
            this.lblEdgeRight.Text = "RIGHT COLUMN (+X)";
            this.lblEdgeRight.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // edge count inputs
            this.numEdgeTop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numEdgeTop.Maximum = 0M;
            this.numEdgeTop.Name = "numEdgeTop";
            this.numEdgeTop.TabIndex = 0;
            this.numEdgeTop.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numEdgeTop.ValueChanged += new System.EventHandler(this.edgeCount_ValueChanged);
            this.numEdgeBottom.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numEdgeBottom.Maximum = 0M;
            this.numEdgeBottom.Name = "numEdgeBottom";
            this.numEdgeBottom.TabIndex = 1;
            this.numEdgeBottom.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numEdgeBottom.ValueChanged += new System.EventHandler(this.edgeCount_ValueChanged);
            this.numEdgeLeft.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numEdgeLeft.Maximum = 0M;
            this.numEdgeLeft.Name = "numEdgeLeft";
            this.numEdgeLeft.TabIndex = 2;
            this.numEdgeLeft.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numEdgeLeft.ValueChanged += new System.EventHandler(this.edgeCount_ValueChanged);
            this.numEdgeRight.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numEdgeRight.Maximum = 0M;
            this.numEdgeRight.Name = "numEdgeRight";
            this.numEdgeRight.TabIndex = 3;
            this.numEdgeRight.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.numEdgeRight.ValueChanged += new System.EventHandler(this.edgeCount_ValueChanged);
            // btnApplyEdges
            this.panelEdges.SetColumnSpan(this.btnApplyEdges, 2);
            this.btnApplyEdges.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnApplyEdges.Margin = new System.Windows.Forms.Padding(3, 6, 3, 0);
            this.btnApplyEdges.Name = "btnApplyEdges";
            this.btnApplyEdges.TabIndex = 4;
            this.btnApplyEdges.Text = "외곽 보정 적용";
            this.btnApplyEdges.UseVisualStyleBackColor = true;
            this.btnApplyEdges.Click += new System.EventHandler(this.btnApplyEdges_Click);
            // panelTools
            this.panelTools.ColumnCount = 2;
            this.panelTools.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.panelTools.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.panelTools.Controls.Add(this.btnRestore, 0, 0);
            this.panelTools.Controls.Add(this.btnFit, 1, 0);
            this.panelTools.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelTools.Margin = new System.Windows.Forms.Padding(0);
            this.panelTools.Name = "panelTools";
            this.panelTools.RowCount = 1;
            this.panelTools.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.panelTools.TabIndex = 4;
            this.btnRestore.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnRestore.Enabled = false;
            this.btnRestore.Margin = new System.Windows.Forms.Padding(0, 0, 4, 4);
            this.btnRestore.Name = "btnRestore";
            this.btnRestore.TabIndex = 0;
            this.btnRestore.Text = "원본 복원";
            this.btnRestore.UseVisualStyleBackColor = true;
            this.btnRestore.Click += new System.EventHandler(this.btnRestore_Click);
            this.btnFit.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnFit.Enabled = false;
            this.btnFit.Margin = new System.Windows.Forms.Padding(4, 0, 0, 4);
            this.btnFit.Name = "btnFit";
            this.btnFit.TabIndex = 1;
            this.btnFit.Text = "화면 맞춤";
            this.btnFit.UseVisualStyleBackColor = true;
            this.btnFit.Click += new System.EventHandler(this.btnFit_Click);
            // panelFooter
            this.panelFooter.ColumnCount = 2;
            this.panelFooter.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.panelFooter.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 104F));
            this.panelFooter.Controls.Add(this.lblStatus, 0, 0);
            this.panelFooter.Controls.Add(this.btnClose, 1, 0);
            this.panelFooter.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelFooter.Margin = new System.Windows.Forms.Padding(0);
            this.panelFooter.Name = "panelFooter";
            this.panelFooter.Padding = new System.Windows.Forms.Padding(0, 8, 0, 0);
            this.panelFooter.RowCount = 1;
            this.panelFooter.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.panelFooter.TabIndex = 2;
            this.lblStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStatus.ForeColor = System.Drawing.Color.FromArgb(48, 66, 79);
            this.lblStatus.Margin = new System.Windows.Forms.Padding(0, 0, 8, 0);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Padding = new System.Windows.Forms.Padding(4);
            this.lblStatus.Text = "사양을 확인한 뒤 AUTO WAFER CREATE를 누르세요.";
            this.lblStatus.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnClose.Margin = new System.Windows.Forms.Padding(0, 8, 0, 8);
            this.btnClose.Name = "btnClose";
            this.btnClose.TabIndex = 0;
            this.btnClose.Text = "닫기";
            this.btnClose.UseVisualStyleBackColor = true;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // toolTip
            this.toolTip.SetToolTip(this.numGapX, "다이 사이의 빈 간격(mm)입니다. 중심 간 거리 = DIE X + GAP X.");
            this.toolTip.SetToolTip(this.numGapY, "다이 사이의 빈 간격(mm)입니다. 중심 간 거리 = DIE Y + GAP Y.");
            this.toolTip.SetToolTip(this.btnGenerate, "참고식의 중심 간 거리 사각형과 반경 여유 0.2 mm로 계산합니다. 녹색은 실제 다이 크기입니다.");
            this.toolTip.SetToolTip(this.groupEdges, "항상 최초 원본의 네 끝줄에서 중심에 가까운 다이를 남깁니다. 보정은 누적하지 않습니다.");
            this.toolTip.SetToolTip(this.btnApplyEdges, "입력한 개수를 원본에 적용합니다. 서로 겹치는 끝줄은 동시에 유지할 수 있는 개수여야 합니다.");
            // WaferMapCreateDialog
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(241, 244, 247);
            this.CancelButton = this.btnClose;
            this.ClientSize = new System.Drawing.Size(1280, 900);
            this.Controls.Add(this.panelRoot);
            this.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(1080, 780);
            this.Name = "WaferMapCreateDialog";
            this.ShowIcon = false;
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Wafer Map Create";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.WaferMapCreateDialog_FormClosing);
            this.panelRoot.ResumeLayout(false);
            this.panelBody.ResumeLayout(false);
            this.panelPreview.ResumeLayout(false);
            this.panelOptions.ResumeLayout(false);
            this.panelOptions.PerformLayout();
            this.panelOptionsLayout.ResumeLayout(false);
            this.panelSettings.ResumeLayout(false);
            this.panelSettings.PerformLayout();
            this.panelEdges.ResumeLayout(false);
            this.panelTools.ResumeLayout(false);
            this.panelFooter.ResumeLayout(false);
            this.groupSettings.ResumeLayout(false);
            this.groupEdges.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numDiameter)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDieX)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDieY)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numGapX)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numGapY)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numEdgeTop)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numEdgeBottom)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numEdgeLeft)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numEdgeRight)).EndInit();
            this.ResumeLayout(false);
        }
    }
}
