using System.Drawing;
using System.Windows.Forms;
using QMC.CDT_320.Ui.Localization;

namespace QMC.CDT_320.Ui.Pages.WorkInfo
{
    partial class ActiveLotPage
    {
        private TableLayoutPanel rootLayout;
        private Label lblHeader;
        private TableLayoutPanel contentLayout;
        private GroupBox grpActiveLot;
        private GroupBox grpBin;
        private TableLayoutPanel lotLayout;
        private Panel _binPanel;
        private Label lblIdCaption;
        private Label lblRecipeCaption;
        private Label lblStateCaption;
        private Label lblStartCaption;
        private Label lblProcessedCaption;
        private Label lblGoodCaption;
        private Label lblNgCaption;
        private Label lblYieldCaption;
        private Label _lblId;
        private Label _lblRecipe;
        private Label _lblState;
        private Label _lblStart;
        private Label _lblProcessed;
        private Label _lblGood;
        private Label _lblNg;
        private Label _lblYield;

        private void InitializeComponent()
        {
            this.rootLayout = new TableLayoutPanel();
            this.lblHeader = new Label();
            this.contentLayout = new TableLayoutPanel();
            this.grpActiveLot = new GroupBox();
            this.grpBin = new GroupBox();
            this.lotLayout = new TableLayoutPanel();
            this._binPanel = new Panel();
            this.lblIdCaption = new Label();
            this.lblRecipeCaption = new Label();
            this.lblStateCaption = new Label();
            this.lblStartCaption = new Label();
            this.lblProcessedCaption = new Label();
            this.lblGoodCaption = new Label();
            this.lblNgCaption = new Label();
            this.lblYieldCaption = new Label();
            this._lblId = new Label();
            this._lblRecipe = new Label();
            this._lblState = new Label();
            this._lblStart = new Label();
            this._lblProcessed = new Label();
            this._lblGood = new Label();
            this._lblNg = new Label();
            this._lblYield = new Label();
            this.SuspendLayout();

            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.contentLayout, 0, 1);
            this.rootLayout.Dock = DockStyle.Fill;
            this.rootLayout.RowCount = 2;
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

            this.lblHeader.BackColor = UiTheme.StatusBarBg;
            this.lblHeader.Dock = DockStyle.Fill;
            this.lblHeader.Font = UiTheme.SectionFont;
            this.lblHeader.ForeColor = UiTheme.StatusBarFg;
            this.lblHeader.Padding = new Padding(10, 0, 0, 0);
            this.lblHeader.Tag = "i18n:wi.activeLot";
            this.lblHeader.Text = Lang.T("wi.activeLot");
            this.lblHeader.TextAlign = ContentAlignment.MiddleLeft;

            this.contentLayout.ColumnCount = 2;
            this.contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 43F));
            this.contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 57F));
            this.contentLayout.Controls.Add(this.grpActiveLot, 0, 0);
            this.contentLayout.Controls.Add(this.grpBin, 1, 0);
            this.contentLayout.Dock = DockStyle.Top;
            this.contentLayout.Height = 390;
            this.contentLayout.Padding = new Padding(20);
            this.contentLayout.RowCount = 1;
            this.contentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

            this.grpActiveLot.BackColor = UiTheme.OptionPanelBg;
            this.grpActiveLot.Controls.Add(this.lotLayout);
            this.grpActiveLot.Dock = DockStyle.Fill;
            this.grpActiveLot.Font = UiTheme.SectionFont;
            this.grpActiveLot.Text = "ACTIVE LOT";

            this.lotLayout.ColumnCount = 2;
            this.lotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 190F));
            this.lotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.lotLayout.Dock = DockStyle.Fill;
            this.lotLayout.Padding = new Padding(16, 22, 16, 16);
            this.lotLayout.RowCount = 9;
            this.lotLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            this.lotLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            this.lotLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            this.lotLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            this.lotLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            this.lotLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            this.lotLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            this.lotLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            this.lotLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

            this.lotLayout.Controls.Add(this.lblIdCaption, 0, 0);
            this.lotLayout.Controls.Add(this._lblId, 1, 0);
            this.lotLayout.Controls.Add(this.lblRecipeCaption, 0, 1);
            this.lotLayout.Controls.Add(this._lblRecipe, 1, 1);
            this.lotLayout.Controls.Add(this.lblStateCaption, 0, 2);
            this.lotLayout.Controls.Add(this._lblState, 1, 2);
            this.lotLayout.Controls.Add(this.lblStartCaption, 0, 3);
            this.lotLayout.Controls.Add(this._lblStart, 1, 3);
            this.lotLayout.Controls.Add(this.lblProcessedCaption, 0, 4);
            this.lotLayout.Controls.Add(this._lblProcessed, 1, 4);
            this.lotLayout.Controls.Add(this.lblGoodCaption, 0, 5);
            this.lotLayout.Controls.Add(this._lblGood, 1, 5);
            this.lotLayout.Controls.Add(this.lblNgCaption, 0, 6);
            this.lotLayout.Controls.Add(this._lblNg, 1, 6);
            this.lotLayout.Controls.Add(this.lblYieldCaption, 0, 7);
            this.lotLayout.Controls.Add(this._lblYield, 1, 7);

            this.lblIdCaption.Dock = DockStyle.Fill;
            this.lblIdCaption.Font = UiTheme.ButtonFont;
            this.lblIdCaption.ForeColor = Color.DarkSlateGray;
            this.lblIdCaption.Text = "Lot ID";
            this.lblIdCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblRecipeCaption.Dock = DockStyle.Fill;
            this.lblRecipeCaption.Font = UiTheme.ButtonFont;
            this.lblRecipeCaption.ForeColor = Color.DarkSlateGray;
            this.lblRecipeCaption.Text = "Recipe";
            this.lblRecipeCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblStateCaption.Dock = DockStyle.Fill;
            this.lblStateCaption.Font = UiTheme.ButtonFont;
            this.lblStateCaption.ForeColor = Color.DarkSlateGray;
            this.lblStateCaption.Text = "State";
            this.lblStateCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblStartCaption.Dock = DockStyle.Fill;
            this.lblStartCaption.Font = UiTheme.ButtonFont;
            this.lblStartCaption.ForeColor = Color.DarkSlateGray;
            this.lblStartCaption.Text = "Started";
            this.lblStartCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblProcessedCaption.Dock = DockStyle.Fill;
            this.lblProcessedCaption.Font = UiTheme.ButtonFont;
            this.lblProcessedCaption.ForeColor = Color.DarkSlateGray;
            this.lblProcessedCaption.Text = "Processed / Total";
            this.lblProcessedCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblGoodCaption.Dock = DockStyle.Fill;
            this.lblGoodCaption.Font = UiTheme.ButtonFont;
            this.lblGoodCaption.ForeColor = Color.DarkSlateGray;
            this.lblGoodCaption.Text = "Good";
            this.lblGoodCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblNgCaption.Dock = DockStyle.Fill;
            this.lblNgCaption.Font = UiTheme.ButtonFont;
            this.lblNgCaption.ForeColor = Color.DarkSlateGray;
            this.lblNgCaption.Text = "NG";
            this.lblNgCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblYieldCaption.Dock = DockStyle.Fill;
            this.lblYieldCaption.Font = UiTheme.ButtonFont;
            this.lblYieldCaption.ForeColor = Color.DarkSlateGray;
            this.lblYieldCaption.Text = "Yield %";
            this.lblYieldCaption.TextAlign = ContentAlignment.MiddleLeft;

            this._lblId.BackColor = Color.White;
            this._lblId.BorderStyle = BorderStyle.FixedSingle;
            this._lblId.Dock = DockStyle.Fill;
            this._lblId.Font = new Font("Consolas", 12F, FontStyle.Bold);
            this._lblId.ForeColor = Color.Black;
            this._lblId.Padding = new Padding(8, 0, 0, 0);
            this._lblId.Text = "(none)";
            this._lblId.TextAlign = ContentAlignment.MiddleLeft;
            this._lblRecipe.BackColor = Color.White;
            this._lblRecipe.BorderStyle = BorderStyle.FixedSingle;
            this._lblRecipe.Dock = DockStyle.Fill;
            this._lblRecipe.Font = new Font("Consolas", 12F, FontStyle.Bold);
            this._lblRecipe.ForeColor = Color.Black;
            this._lblRecipe.Padding = new Padding(8, 0, 0, 0);
            this._lblRecipe.Text = "(none)";
            this._lblRecipe.TextAlign = ContentAlignment.MiddleLeft;
            this._lblState.BackColor = Color.White;
            this._lblState.BorderStyle = BorderStyle.FixedSingle;
            this._lblState.Dock = DockStyle.Fill;
            this._lblState.Font = new Font("Consolas", 12F, FontStyle.Bold);
            this._lblState.ForeColor = Color.Black;
            this._lblState.Padding = new Padding(8, 0, 0, 0);
            this._lblState.Text = "(none)";
            this._lblState.TextAlign = ContentAlignment.MiddleLeft;
            this._lblStart.BackColor = Color.White;
            this._lblStart.BorderStyle = BorderStyle.FixedSingle;
            this._lblStart.Dock = DockStyle.Fill;
            this._lblStart.Font = new Font("Consolas", 12F, FontStyle.Bold);
            this._lblStart.ForeColor = Color.Black;
            this._lblStart.Padding = new Padding(8, 0, 0, 0);
            this._lblStart.Text = "(none)";
            this._lblStart.TextAlign = ContentAlignment.MiddleLeft;
            this._lblProcessed.BackColor = Color.White;
            this._lblProcessed.BorderStyle = BorderStyle.FixedSingle;
            this._lblProcessed.Dock = DockStyle.Fill;
            this._lblProcessed.Font = new Font("Consolas", 12F, FontStyle.Bold);
            this._lblProcessed.ForeColor = Color.Black;
            this._lblProcessed.Padding = new Padding(8, 0, 0, 0);
            this._lblProcessed.Text = "(none)";
            this._lblProcessed.TextAlign = ContentAlignment.MiddleLeft;
            this._lblGood.BackColor = Color.White;
            this._lblGood.BorderStyle = BorderStyle.FixedSingle;
            this._lblGood.Dock = DockStyle.Fill;
            this._lblGood.Font = new Font("Consolas", 12F, FontStyle.Bold);
            this._lblGood.ForeColor = Color.Black;
            this._lblGood.Padding = new Padding(8, 0, 0, 0);
            this._lblGood.Text = "(none)";
            this._lblGood.TextAlign = ContentAlignment.MiddleLeft;
            this._lblNg.BackColor = Color.White;
            this._lblNg.BorderStyle = BorderStyle.FixedSingle;
            this._lblNg.Dock = DockStyle.Fill;
            this._lblNg.Font = new Font("Consolas", 12F, FontStyle.Bold);
            this._lblNg.ForeColor = Color.Black;
            this._lblNg.Padding = new Padding(8, 0, 0, 0);
            this._lblNg.Text = "(none)";
            this._lblNg.TextAlign = ContentAlignment.MiddleLeft;
            this._lblYield.BackColor = Color.White;
            this._lblYield.BorderStyle = BorderStyle.FixedSingle;
            this._lblYield.Dock = DockStyle.Fill;
            this._lblYield.Font = new Font("Consolas", 12F, FontStyle.Bold);
            this._lblYield.ForeColor = Color.Black;
            this._lblYield.Padding = new Padding(8, 0, 0, 0);
            this._lblYield.Text = "(none)";
            this._lblYield.TextAlign = ContentAlignment.MiddleLeft;

            this.grpBin.BackColor = UiTheme.OptionPanelBg;
            this.grpBin.Controls.Add(this._binPanel);
            this.grpBin.Dock = DockStyle.Fill;
            this.grpBin.Font = UiTheme.SectionFont;
            this.grpBin.Text = "BIN DISTRIBUTION";

            this._binPanel.BackColor = Color.White;
            this._binPanel.Dock = DockStyle.Fill;
            this._binPanel.Margin = new Padding(8, 24, 8, 8);
            this._binPanel.Paint += new PaintEventHandler(this.OnPaintBin);

            this.Controls.Add(this.rootLayout);
            this.Name = "ActiveLotPage";
            this.Size = new Size(1678, 900);
            this.ResumeLayout(false);
        }
    }
}

