using System.Drawing;
using System.Windows.Forms;
using QMC.CDT_320.Ui.Controls;

namespace QMC.CDT_320.Ui.Pages.WorkInfo
{
    partial class InputStagePage
    {
        private TableLayoutPanel rootLayout;
        private Label lblHeader;
        private TableLayoutPanel contentLayout;
        private GroupBox grpState;
        private GroupBox grpCounters;
        private GroupBox grpCylinder;
        private GroupBox grpInfo;
        private TableLayoutPanel stateLayout;
        private TableLayoutPanel counterLayout;
        private TableLayoutPanel cylinderLayout;
        private TableLayoutPanel infoLayout;
        private FlowLayoutPanel actionsLayout;
        private ActionButton btnWfAlign;
        private ActionButton btnWfBarcode;
        private Label lblStageExistTitle;
        private Label lblStageExistValue;
        private Label lblStageAlignTitle;
        private Label lblStageAlignValue;
        private Label lblStageBarcodeTitle;
        private Label lblStageBarcodeValue;
        private Label lblStageChipAlignTitle;
        private Label lblStageChipAlignValue;
        private Label lblStageFinishTitle;
        private Label lblStageFinishValue;
        private Label lblNeedleUsingTitle;
        private Label lblNeedleUsingValue;
        private Label lblJellPadUsingTitle;
        private Label lblJellPadUsingValue;
        private Label lblExpendingTitle;
        private Label lblExpendingValue;
        private Label lblNeedleUpDownTitle;
        private Label lblNeedleUpDownValue;
        private TableLayoutPanel stageAxisXPanel;
        private Label lblStageAxisXTitle;
        private Label lblStageAxisXValue;
        private TableLayoutPanel stageAxisTPanel;
        private Label lblStageAxisTTitle;
        private Label lblStageAxisTValue;
        private TableLayoutPanel stageAxisYPanel;
        private Label lblStageAxisYTitle;
        private Label lblStageAxisYValue;
        private TableLayoutPanel needleAxisZPanel;
        private Label lblNeedleAxisZTitle;
        private Label lblNeedleAxisZValue;
        private TableLayoutPanel stageRing1Panel;
        private IndicatorDot dotStageRing1;
        private Label lblStageRing1;
        private TableLayoutPanel stageRing2Panel;
        private IndicatorDot dotStageRing2;
        private Label lblStageRing2;
        private TableLayoutPanel needleVacuumPanel;
        private IndicatorDot dotNeedleVacuum;
        private Label lblNeedleVacuum;

        private void InitializeComponent()
        {
            this.rootLayout = new TableLayoutPanel();
            this.lblHeader = new Label();
            this.contentLayout = new TableLayoutPanel();
            this.grpState = new GroupBox();
            this.grpCounters = new GroupBox();
            this.grpCylinder = new GroupBox();
            this.grpInfo = new GroupBox();
            this.stateLayout = new TableLayoutPanel();
            this.counterLayout = new TableLayoutPanel();
            this.cylinderLayout = new TableLayoutPanel();
            this.infoLayout = new TableLayoutPanel();
            this.actionsLayout = new FlowLayoutPanel();
            this.btnWfAlign = new ActionButton();
            this.btnWfBarcode = new ActionButton();
            this.lblStageExistTitle = new Label();
            this.lblStageExistValue = new Label();
            this.lblStageAlignTitle = new Label();
            this.lblStageAlignValue = new Label();
            this.lblStageBarcodeTitle = new Label();
            this.lblStageBarcodeValue = new Label();
            this.lblStageChipAlignTitle = new Label();
            this.lblStageChipAlignValue = new Label();
            this.lblStageFinishTitle = new Label();
            this.lblStageFinishValue = new Label();
            this.lblNeedleUsingTitle = new Label();
            this.lblNeedleUsingValue = new Label();
            this.lblJellPadUsingTitle = new Label();
            this.lblJellPadUsingValue = new Label();
            this.lblExpendingTitle = new Label();
            this.lblExpendingValue = new Label();
            this.lblNeedleUpDownTitle = new Label();
            this.lblNeedleUpDownValue = new Label();
            this.stageAxisXPanel = new TableLayoutPanel();
            this.lblStageAxisXTitle = new Label();
            this.lblStageAxisXValue = new Label();
            this.stageAxisTPanel = new TableLayoutPanel();
            this.lblStageAxisTTitle = new Label();
            this.lblStageAxisTValue = new Label();
            this.stageAxisYPanel = new TableLayoutPanel();
            this.lblStageAxisYTitle = new Label();
            this.lblStageAxisYValue = new Label();
            this.needleAxisZPanel = new TableLayoutPanel();
            this.lblNeedleAxisZTitle = new Label();
            this.lblNeedleAxisZValue = new Label();
            this.stageRing1Panel = new TableLayoutPanel();
            this.dotStageRing1 = new IndicatorDot();
            this.lblStageRing1 = new Label();
            this.stageRing2Panel = new TableLayoutPanel();
            this.dotStageRing2 = new IndicatorDot();
            this.lblStageRing2 = new Label();
            this.needleVacuumPanel = new TableLayoutPanel();
            this.dotNeedleVacuum = new IndicatorDot();
            this.lblNeedleVacuum = new Label();
            this.rootLayout.SuspendLayout();
            this.contentLayout.SuspendLayout();
            this.grpState.SuspendLayout();
            this.grpCounters.SuspendLayout();
            this.grpCylinder.SuspendLayout();
            this.grpInfo.SuspendLayout();
            this.stateLayout.SuspendLayout();
            this.counterLayout.SuspendLayout();
            this.cylinderLayout.SuspendLayout();
            this.infoLayout.SuspendLayout();
            this.stageAxisXPanel.SuspendLayout();
            this.stageAxisTPanel.SuspendLayout();
            this.stageAxisYPanel.SuspendLayout();
            this.needleAxisZPanel.SuspendLayout();
            this.stageRing1Panel.SuspendLayout();
            this.stageRing2Panel.SuspendLayout();
            this.needleVacuumPanel.SuspendLayout();
            this.SuspendLayout();

            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.contentLayout, 0, 1);
            this.rootLayout.Controls.Add(this.actionsLayout, 0, 2);
            this.rootLayout.Dock = DockStyle.Fill;
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 90F));

            this.lblHeader.BackColor = UiTheme.StatusBarBg;
            this.lblHeader.Dock = DockStyle.Fill;
            this.lblHeader.Font = UiTheme.SectionFont;
            this.lblHeader.ForeColor = UiTheme.StatusBarFg;
            this.lblHeader.Padding = new Padding(10, 0, 0, 0);
            this.lblHeader.Tag = "i18n:tab.workInfo";
            this.lblHeader.Text = "WORK INFO";
            this.lblHeader.TextAlign = ContentAlignment.MiddleLeft;

            this.contentLayout.ColumnCount = 3;
            this.contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33F));
            this.contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 27F));
            this.contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 40F));
            this.contentLayout.Controls.Add(this.grpState, 0, 0);
            this.contentLayout.Controls.Add(this.grpCounters, 1, 0);
            this.contentLayout.Controls.Add(this.grpCylinder, 2, 0);
            this.contentLayout.Controls.Add(this.grpInfo, 0, 1);
            this.contentLayout.Dock = DockStyle.Top;
            this.contentLayout.Height = 520;
            this.contentLayout.Padding = new Padding(8);
            this.contentLayout.RowCount = 2;
            this.contentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 190F));
            this.contentLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 300F));
            this.contentLayout.SetColumnSpan(this.grpInfo, 3);

            this.grpState.BackColor = UiTheme.OptionPanelBg;
            this.grpState.Controls.Add(this.stateLayout);
            this.grpState.Dock = DockStyle.Fill;
            this.grpState.Font = UiTheme.SectionFont;
            this.grpState.Text = "WORK INFO";
            this.stateLayout.ColumnCount = 2;
            this.stateLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 48F));
            this.stateLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 52F));
            this.stateLayout.Dock = DockStyle.Fill;
            this.stateLayout.Padding = new Padding(12, 18, 12, 12);
            this.stateLayout.RowCount = 6;
            this.stateLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.stateLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.stateLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.stateLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.stateLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.stateLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));

            this.grpCounters.BackColor = UiTheme.OptionPanelBg;
            this.grpCounters.Controls.Add(this.counterLayout);
            this.grpCounters.Dock = DockStyle.Fill;
            this.grpCounters.Font = UiTheme.SectionFont;
            this.grpCounters.Text = "COUNTER";
            this.counterLayout.ColumnCount = 2;
            this.counterLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 48F));
            this.counterLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 52F));
            this.counterLayout.Dock = DockStyle.Fill;
            this.counterLayout.Padding = new Padding(12, 18, 12, 12);
            this.counterLayout.RowCount = 6;
            this.counterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.counterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.counterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.counterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.counterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.counterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));

            this.grpCylinder.BackColor = UiTheme.OptionPanelBg;
            this.grpCylinder.Controls.Add(this.cylinderLayout);
            this.grpCylinder.Dock = DockStyle.Fill;
            this.grpCylinder.Font = UiTheme.SectionFont;
            this.grpCylinder.Text = "NEEDLE CYLINDER INFO";
            this.cylinderLayout.ColumnCount = 2;
            this.cylinderLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 48F));
            this.cylinderLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 52F));
            this.cylinderLayout.Dock = DockStyle.Fill;
            this.cylinderLayout.Padding = new Padding(12, 18, 12, 12);
            this.cylinderLayout.RowCount = 6;
            this.cylinderLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.cylinderLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.cylinderLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.cylinderLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.cylinderLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.cylinderLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));

            this.grpInfo.BackColor = UiTheme.OptionPanelBg;
            this.grpInfo.Controls.Add(this.infoLayout);
            this.grpInfo.Dock = DockStyle.Fill;
            this.grpInfo.Font = UiTheme.SectionFont;
            this.grpInfo.Text = "INFO";
            this.infoLayout.ColumnCount = 2;
            this.infoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 48F));
            this.infoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 52F));
            this.infoLayout.Dock = DockStyle.Fill;
            this.infoLayout.Padding = new Padding(12, 18, 12, 12);
            this.infoLayout.RowCount = 6;
            this.infoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.infoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.infoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.infoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.infoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.infoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this.stateLayout.Controls.Add(this.lblStageExistTitle, 0, 0);
            this.stateLayout.Controls.Add(this.lblStageExistValue, 1, 0);

            this.lblStageExistTitle.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblStageExistTitle.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageExistTitle.Dock = DockStyle.Fill;
            this.lblStageExistTitle.Font = UiTheme.ButtonFont;
            this.lblStageExistTitle.Padding = new Padding(8, 0, 0, 0);
            this.lblStageExistTitle.Text = "STAGE EXIST";
            this.lblStageExistTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblStageExistValue.BackColor = Color.White;
            this.lblStageExistValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageExistValue.Dock = DockStyle.Fill;
            this.lblStageExistValue.Font = UiTheme.ValueFont;
            this.lblStageExistValue.Text = "EMPTY";
            this.lblStageExistValue.TextAlign = ContentAlignment.MiddleCenter;
            this.stateLayout.Controls.Add(this.lblStageAlignTitle, 0, 1);
            this.stateLayout.Controls.Add(this.lblStageAlignValue, 1, 1);

            this.lblStageAlignTitle.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblStageAlignTitle.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageAlignTitle.Dock = DockStyle.Fill;
            this.lblStageAlignTitle.Font = UiTheme.ButtonFont;
            this.lblStageAlignTitle.Padding = new Padding(8, 0, 0, 0);
            this.lblStageAlignTitle.Text = "STAGE ALIGN";
            this.lblStageAlignTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblStageAlignValue.BackColor = Color.White;
            this.lblStageAlignValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageAlignValue.Dock = DockStyle.Fill;
            this.lblStageAlignValue.Font = UiTheme.ValueFont;
            this.lblStageAlignValue.Text = "INCOMPLETE";
            this.lblStageAlignValue.TextAlign = ContentAlignment.MiddleCenter;
            this.stateLayout.Controls.Add(this.lblStageBarcodeTitle, 0, 2);
            this.stateLayout.Controls.Add(this.lblStageBarcodeValue, 1, 2);

            this.lblStageBarcodeTitle.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblStageBarcodeTitle.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageBarcodeTitle.Dock = DockStyle.Fill;
            this.lblStageBarcodeTitle.Font = UiTheme.ButtonFont;
            this.lblStageBarcodeTitle.Padding = new Padding(8, 0, 0, 0);
            this.lblStageBarcodeTitle.Text = "STAGE BARCODE";
            this.lblStageBarcodeTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblStageBarcodeValue.BackColor = Color.White;
            this.lblStageBarcodeValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageBarcodeValue.Dock = DockStyle.Fill;
            this.lblStageBarcodeValue.Font = UiTheme.ValueFont;
            this.lblStageBarcodeValue.Text = "INCOMPLETE";
            this.lblStageBarcodeValue.TextAlign = ContentAlignment.MiddleCenter;
            this.stateLayout.Controls.Add(this.lblStageChipAlignTitle, 0, 3);
            this.stateLayout.Controls.Add(this.lblStageChipAlignValue, 1, 3);

            this.lblStageChipAlignTitle.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblStageChipAlignTitle.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageChipAlignTitle.Dock = DockStyle.Fill;
            this.lblStageChipAlignTitle.Font = UiTheme.ButtonFont;
            this.lblStageChipAlignTitle.Padding = new Padding(8, 0, 0, 0);
            this.lblStageChipAlignTitle.Text = "STAGE CHIP ALIGN";
            this.lblStageChipAlignTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblStageChipAlignValue.BackColor = Color.White;
            this.lblStageChipAlignValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageChipAlignValue.Dock = DockStyle.Fill;
            this.lblStageChipAlignValue.Font = UiTheme.ValueFont;
            this.lblStageChipAlignValue.Text = "INCOMPLETE";
            this.lblStageChipAlignValue.TextAlign = ContentAlignment.MiddleCenter;
            this.stateLayout.Controls.Add(this.lblStageFinishTitle, 0, 4);
            this.stateLayout.Controls.Add(this.lblStageFinishValue, 1, 4);

            this.lblStageFinishTitle.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblStageFinishTitle.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageFinishTitle.Dock = DockStyle.Fill;
            this.lblStageFinishTitle.Font = UiTheme.ButtonFont;
            this.lblStageFinishTitle.Padding = new Padding(8, 0, 0, 0);
            this.lblStageFinishTitle.Text = "STAGE FINISH";
            this.lblStageFinishTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblStageFinishValue.BackColor = Color.White;
            this.lblStageFinishValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageFinishValue.Dock = DockStyle.Fill;
            this.lblStageFinishValue.Font = UiTheme.ValueFont;
            this.lblStageFinishValue.Text = "INCOMPLETE";
            this.lblStageFinishValue.TextAlign = ContentAlignment.MiddleCenter;
            this.counterLayout.Controls.Add(this.lblNeedleUsingTitle, 0, 0);
            this.counterLayout.Controls.Add(this.lblNeedleUsingValue, 1, 0);

            this.lblNeedleUsingTitle.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblNeedleUsingTitle.BorderStyle = BorderStyle.FixedSingle;
            this.lblNeedleUsingTitle.Dock = DockStyle.Fill;
            this.lblNeedleUsingTitle.Font = UiTheme.ButtonFont;
            this.lblNeedleUsingTitle.Padding = new Padding(8, 0, 0, 0);
            this.lblNeedleUsingTitle.Text = "NEEDLE USING";
            this.lblNeedleUsingTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblNeedleUsingValue.BackColor = Color.White;
            this.lblNeedleUsingValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblNeedleUsingValue.Dock = DockStyle.Fill;
            this.lblNeedleUsingValue.Font = UiTheme.ValueFont;
            this.lblNeedleUsingValue.Text = "0 ea";
            this.lblNeedleUsingValue.TextAlign = ContentAlignment.MiddleCenter;
            this.counterLayout.Controls.Add(this.lblJellPadUsingTitle, 0, 1);
            this.counterLayout.Controls.Add(this.lblJellPadUsingValue, 1, 1);

            this.lblJellPadUsingTitle.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblJellPadUsingTitle.BorderStyle = BorderStyle.FixedSingle;
            this.lblJellPadUsingTitle.Dock = DockStyle.Fill;
            this.lblJellPadUsingTitle.Font = UiTheme.ButtonFont;
            this.lblJellPadUsingTitle.Padding = new Padding(8, 0, 0, 0);
            this.lblJellPadUsingTitle.Text = "JELL PAD USING";
            this.lblJellPadUsingTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblJellPadUsingValue.BackColor = Color.White;
            this.lblJellPadUsingValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblJellPadUsingValue.Dock = DockStyle.Fill;
            this.lblJellPadUsingValue.Font = UiTheme.ValueFont;
            this.lblJellPadUsingValue.Text = "0 ea";
            this.lblJellPadUsingValue.TextAlign = ContentAlignment.MiddleCenter;
            this.cylinderLayout.Controls.Add(this.lblExpendingTitle, 0, 0);
            this.cylinderLayout.Controls.Add(this.lblExpendingValue, 1, 0);

            this.lblExpendingTitle.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblExpendingTitle.BorderStyle = BorderStyle.FixedSingle;
            this.lblExpendingTitle.Dock = DockStyle.Fill;
            this.lblExpendingTitle.Font = UiTheme.ButtonFont;
            this.lblExpendingTitle.Padding = new Padding(8, 0, 0, 0);
            this.lblExpendingTitle.Text = "EXPENDING";
            this.lblExpendingTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblExpendingValue.BackColor = Color.White;
            this.lblExpendingValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblExpendingValue.Dock = DockStyle.Fill;
            this.lblExpendingValue.Font = UiTheme.ValueFont;
            this.lblExpendingValue.Text = "...";
            this.lblExpendingValue.TextAlign = ContentAlignment.MiddleCenter;
            this.cylinderLayout.Controls.Add(this.lblNeedleUpDownTitle, 0, 1);
            this.cylinderLayout.Controls.Add(this.lblNeedleUpDownValue, 1, 1);

            this.lblNeedleUpDownTitle.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblNeedleUpDownTitle.BorderStyle = BorderStyle.FixedSingle;
            this.lblNeedleUpDownTitle.Dock = DockStyle.Fill;
            this.lblNeedleUpDownTitle.Font = UiTheme.ButtonFont;
            this.lblNeedleUpDownTitle.Padding = new Padding(8, 0, 0, 0);
            this.lblNeedleUpDownTitle.Text = "NEEDLE UP/DOWN";
            this.lblNeedleUpDownTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblNeedleUpDownValue.BackColor = Color.White;
            this.lblNeedleUpDownValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblNeedleUpDownValue.Dock = DockStyle.Fill;
            this.lblNeedleUpDownValue.Font = UiTheme.ValueFont;
            this.lblNeedleUpDownValue.Text = "...";
            this.lblNeedleUpDownValue.TextAlign = ContentAlignment.MiddleCenter;

            this.infoLayout.ColumnCount = 4;
            this.infoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.infoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.infoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.infoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.infoLayout.RowCount = 3;
            this.infoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 70F));
            this.infoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            this.infoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            this.infoLayout.Controls.Add(this.stageAxisXPanel, 0, 0);
            this.stageAxisXPanel.ColumnCount = 1;
            this.stageAxisXPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.stageAxisXPanel.Controls.Add(this.lblStageAxisXTitle, 0, 0);
            this.stageAxisXPanel.Controls.Add(this.lblStageAxisXValue, 0, 1);
            this.stageAxisXPanel.Dock = DockStyle.Fill;
            this.stageAxisXPanel.Margin = new Padding(4);
            this.stageAxisXPanel.RowCount = 2;
            this.stageAxisXPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            this.stageAxisXPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.lblStageAxisXTitle.BackColor = Color.Black;
            this.lblStageAxisXTitle.Dock = DockStyle.Fill;
            this.lblStageAxisXTitle.Font = UiTheme.SectionFont;
            this.lblStageAxisXTitle.ForeColor = Color.White;
            this.lblStageAxisXTitle.Padding = new Padding(6, 0, 0, 0);
            this.lblStageAxisXTitle.Text = "STAGE AXIS X";
            this.lblStageAxisXTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblStageAxisXValue.BackColor = Color.White;
            this.lblStageAxisXValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageAxisXValue.Dock = DockStyle.Fill;
            this.lblStageAxisXValue.Font = new Font("Consolas", 10F);
            this.lblStageAxisXValue.Padding = new Padding(0, 0, 6, 0);
            this.lblStageAxisXValue.Text = "0 um";
            this.lblStageAxisXValue.TextAlign = ContentAlignment.MiddleRight;
            this.infoLayout.Controls.Add(this.stageAxisTPanel, 1, 0);
            this.stageAxisTPanel.ColumnCount = 1;
            this.stageAxisTPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.stageAxisTPanel.Controls.Add(this.lblStageAxisTTitle, 0, 0);
            this.stageAxisTPanel.Controls.Add(this.lblStageAxisTValue, 0, 1);
            this.stageAxisTPanel.Dock = DockStyle.Fill;
            this.stageAxisTPanel.Margin = new Padding(4);
            this.stageAxisTPanel.RowCount = 2;
            this.stageAxisTPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            this.stageAxisTPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.lblStageAxisTTitle.BackColor = Color.Black;
            this.lblStageAxisTTitle.Dock = DockStyle.Fill;
            this.lblStageAxisTTitle.Font = UiTheme.SectionFont;
            this.lblStageAxisTTitle.ForeColor = Color.White;
            this.lblStageAxisTTitle.Padding = new Padding(6, 0, 0, 0);
            this.lblStageAxisTTitle.Text = "STAGE AXIS T";
            this.lblStageAxisTTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblStageAxisTValue.BackColor = Color.White;
            this.lblStageAxisTValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageAxisTValue.Dock = DockStyle.Fill;
            this.lblStageAxisTValue.Font = new Font("Consolas", 10F);
            this.lblStageAxisTValue.Padding = new Padding(0, 0, 6, 0);
            this.lblStageAxisTValue.Text = "0 um";
            this.lblStageAxisTValue.TextAlign = ContentAlignment.MiddleRight;
            this.infoLayout.Controls.Add(this.stageAxisYPanel, 2, 0);
            this.stageAxisYPanel.ColumnCount = 1;
            this.stageAxisYPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.stageAxisYPanel.Controls.Add(this.lblStageAxisYTitle, 0, 0);
            this.stageAxisYPanel.Controls.Add(this.lblStageAxisYValue, 0, 1);
            this.stageAxisYPanel.Dock = DockStyle.Fill;
            this.stageAxisYPanel.Margin = new Padding(4);
            this.stageAxisYPanel.RowCount = 2;
            this.stageAxisYPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            this.stageAxisYPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.lblStageAxisYTitle.BackColor = Color.Black;
            this.lblStageAxisYTitle.Dock = DockStyle.Fill;
            this.lblStageAxisYTitle.Font = UiTheme.SectionFont;
            this.lblStageAxisYTitle.ForeColor = Color.White;
            this.lblStageAxisYTitle.Padding = new Padding(6, 0, 0, 0);
            this.lblStageAxisYTitle.Text = "STAGE AXIS Y";
            this.lblStageAxisYTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblStageAxisYValue.BackColor = Color.White;
            this.lblStageAxisYValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblStageAxisYValue.Dock = DockStyle.Fill;
            this.lblStageAxisYValue.Font = new Font("Consolas", 10F);
            this.lblStageAxisYValue.Padding = new Padding(0, 0, 6, 0);
            this.lblStageAxisYValue.Text = "0 um";
            this.lblStageAxisYValue.TextAlign = ContentAlignment.MiddleRight;
            this.infoLayout.Controls.Add(this.needleAxisZPanel, 3, 0);
            this.needleAxisZPanel.ColumnCount = 1;
            this.needleAxisZPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.needleAxisZPanel.Controls.Add(this.lblNeedleAxisZTitle, 0, 0);
            this.needleAxisZPanel.Controls.Add(this.lblNeedleAxisZValue, 0, 1);
            this.needleAxisZPanel.Dock = DockStyle.Fill;
            this.needleAxisZPanel.Margin = new Padding(4);
            this.needleAxisZPanel.RowCount = 2;
            this.needleAxisZPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            this.needleAxisZPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.lblNeedleAxisZTitle.BackColor = Color.Black;
            this.lblNeedleAxisZTitle.Dock = DockStyle.Fill;
            this.lblNeedleAxisZTitle.Font = UiTheme.SectionFont;
            this.lblNeedleAxisZTitle.ForeColor = Color.White;
            this.lblNeedleAxisZTitle.Padding = new Padding(6, 0, 0, 0);
            this.lblNeedleAxisZTitle.Text = "NEEDLE AXIS Z";
            this.lblNeedleAxisZTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.lblNeedleAxisZValue.BackColor = Color.White;
            this.lblNeedleAxisZValue.BorderStyle = BorderStyle.FixedSingle;
            this.lblNeedleAxisZValue.Dock = DockStyle.Fill;
            this.lblNeedleAxisZValue.Font = new Font("Consolas", 10F);
            this.lblNeedleAxisZValue.Padding = new Padding(0, 0, 6, 0);
            this.lblNeedleAxisZValue.Text = "0 um";
            this.lblNeedleAxisZValue.TextAlign = ContentAlignment.MiddleRight;
            this.infoLayout.Controls.Add(this.stageRing1Panel, 0, 1);
            this.stageRing1Panel.ColumnCount = 2;
            this.stageRing1Panel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 24F));
            this.stageRing1Panel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.stageRing1Panel.Controls.Add(this.dotStageRing1, 0, 0);
            this.stageRing1Panel.Controls.Add(this.lblStageRing1, 1, 0);
            this.stageRing1Panel.Dock = DockStyle.Fill;
            this.stageRing1Panel.Margin = new Padding(4);
            this.stageRing1Panel.RowCount = 1;
            this.stageRing1Panel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.dotStageRing1.Dock = DockStyle.Fill;
            this.dotStageRing1.Margin = new Padding(6, 8, 6, 8);
            this.dotStageRing1.OnColor = Color.LimeGreen;
            this.lblStageRing1.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblStageRing1.Dock = DockStyle.Fill;
            this.lblStageRing1.Font = UiTheme.ValueFont;
            this.lblStageRing1.Padding = new Padding(6, 0, 0, 0);
            this.lblStageRing1.Text = "STAGE RING CHECK #1";
            this.lblStageRing1.TextAlign = ContentAlignment.MiddleLeft;
            this.infoLayout.Controls.Add(this.stageRing2Panel, 1, 1);
            this.stageRing2Panel.ColumnCount = 2;
            this.stageRing2Panel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 24F));
            this.stageRing2Panel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.stageRing2Panel.Controls.Add(this.dotStageRing2, 0, 0);
            this.stageRing2Panel.Controls.Add(this.lblStageRing2, 1, 0);
            this.stageRing2Panel.Dock = DockStyle.Fill;
            this.stageRing2Panel.Margin = new Padding(4);
            this.stageRing2Panel.RowCount = 1;
            this.stageRing2Panel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.dotStageRing2.Dock = DockStyle.Fill;
            this.dotStageRing2.Margin = new Padding(6, 8, 6, 8);
            this.dotStageRing2.OnColor = Color.LimeGreen;
            this.lblStageRing2.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblStageRing2.Dock = DockStyle.Fill;
            this.lblStageRing2.Font = UiTheme.ValueFont;
            this.lblStageRing2.Padding = new Padding(6, 0, 0, 0);
            this.lblStageRing2.Text = "STAGE RING CHECK #2";
            this.lblStageRing2.TextAlign = ContentAlignment.MiddleLeft;
            this.infoLayout.Controls.Add(this.needleVacuumPanel, 2, 1);
            this.needleVacuumPanel.ColumnCount = 2;
            this.needleVacuumPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 24F));
            this.needleVacuumPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.needleVacuumPanel.Controls.Add(this.dotNeedleVacuum, 0, 0);
            this.needleVacuumPanel.Controls.Add(this.lblNeedleVacuum, 1, 0);
            this.needleVacuumPanel.Dock = DockStyle.Fill;
            this.needleVacuumPanel.Margin = new Padding(4);
            this.needleVacuumPanel.RowCount = 1;
            this.needleVacuumPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.dotNeedleVacuum.Dock = DockStyle.Fill;
            this.dotNeedleVacuum.Margin = new Padding(6, 8, 6, 8);
            this.dotNeedleVacuum.OnColor = Color.LimeGreen;
            this.lblNeedleVacuum.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblNeedleVacuum.Dock = DockStyle.Fill;
            this.lblNeedleVacuum.Font = UiTheme.ValueFont;
            this.lblNeedleVacuum.Padding = new Padding(6, 0, 0, 0);
            this.lblNeedleVacuum.Text = "NEEDLE VACUUM";
            this.lblNeedleVacuum.TextAlign = ContentAlignment.MiddleLeft;

            this.actionsLayout.BackColor = UiTheme.MainBg;
            this.actionsLayout.Dock = DockStyle.Fill;
            this.actionsLayout.FlowDirection = FlowDirection.LeftToRight;
            this.actionsLayout.Padding = new Padding(12);
            this.btnWfAlign.Text = "WF ALIGN";
            this.btnWfAlign.Tag = "i18n:wi.wfAlign";
            this.btnWfAlign.Width = 160;
            this.btnWfAlign.Margin = new Padding(6);
            this.btnWfBarcode.Text = "WF BARCODE";
            this.btnWfBarcode.Tag = "i18n:wi.wfBarcode";
            this.btnWfBarcode.Width = 160;
            this.btnWfBarcode.Margin = new Padding(6);
            this.actionsLayout.Controls.Add(this.btnWfAlign);
            this.actionsLayout.Controls.Add(this.btnWfBarcode);

            this.Controls.Add(this.rootLayout);
            this.Name = "InputStagePage";
            this.Size = new Size(1400, 900);
            this.needleVacuumPanel.ResumeLayout(false);
            this.stageRing2Panel.ResumeLayout(false);
            this.stageRing1Panel.ResumeLayout(false);
            this.needleAxisZPanel.ResumeLayout(false);
            this.stageAxisYPanel.ResumeLayout(false);
            this.stageAxisTPanel.ResumeLayout(false);
            this.stageAxisXPanel.ResumeLayout(false);
            this.infoLayout.ResumeLayout(false);
            this.cylinderLayout.ResumeLayout(false);
            this.counterLayout.ResumeLayout(false);
            this.stateLayout.ResumeLayout(false);
            this.grpInfo.ResumeLayout(false);
            this.grpCylinder.ResumeLayout(false);
            this.grpCounters.ResumeLayout(false);
            this.grpState.ResumeLayout(false);
            this.contentLayout.ResumeLayout(false);
            this.rootLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
