using System.Drawing;
using System.Windows.Forms;

namespace QMC.CDT_320.Ui.Pages.WorkInfo
{
    partial class PlateStatusPage
    {
        private TableLayoutPanel rootLayout;
        private Label lblHeader;
        private TableLayoutPanel contentLayout;
        private GroupBox grpNg;
        private GroupBox grpGood;
        private TableLayoutPanel ngLayout;
        private TableLayoutPanel goodLayout;
        private TableLayoutPanel ngSlotLayout;
        private TableLayoutPanel goodSlotLayout;
        private FlowLayoutPanel actionLayout;
        private Label _lblNgCount;
        private Label _lblGoodCount;
        private Label[] _ngSlots;
        private Label[] _goodSlots;
        private Button btnReset;

        private void InitializeComponent()
        {
            this.rootLayout = new TableLayoutPanel();
            this.lblHeader = new Label();
            this.contentLayout = new TableLayoutPanel();
            this.grpNg = new GroupBox();
            this.grpGood = new GroupBox();
            this.ngLayout = new TableLayoutPanel();
            this.goodLayout = new TableLayoutPanel();
            this.ngSlotLayout = new TableLayoutPanel();
            this.goodSlotLayout = new TableLayoutPanel();
            this.actionLayout = new FlowLayoutPanel();
            this._lblNgCount = new Label();
            this._lblGoodCount = new Label();
            this.btnReset = new Button();
            this._ngSlots = new Label[25];
            this._goodSlots = new Label[25];
            this._ngSlots[0] = new Label();
            this._ngSlots[1] = new Label();
            this._ngSlots[2] = new Label();
            this._ngSlots[3] = new Label();
            this._ngSlots[4] = new Label();
            this._ngSlots[5] = new Label();
            this._ngSlots[6] = new Label();
            this._ngSlots[7] = new Label();
            this._ngSlots[8] = new Label();
            this._ngSlots[9] = new Label();
            this._ngSlots[10] = new Label();
            this._ngSlots[11] = new Label();
            this._ngSlots[12] = new Label();
            this._ngSlots[13] = new Label();
            this._ngSlots[14] = new Label();
            this._ngSlots[15] = new Label();
            this._ngSlots[16] = new Label();
            this._ngSlots[17] = new Label();
            this._ngSlots[18] = new Label();
            this._ngSlots[19] = new Label();
            this._ngSlots[20] = new Label();
            this._ngSlots[21] = new Label();
            this._ngSlots[22] = new Label();
            this._ngSlots[23] = new Label();
            this._ngSlots[24] = new Label();
            this._goodSlots[0] = new Label();
            this._goodSlots[1] = new Label();
            this._goodSlots[2] = new Label();
            this._goodSlots[3] = new Label();
            this._goodSlots[4] = new Label();
            this._goodSlots[5] = new Label();
            this._goodSlots[6] = new Label();
            this._goodSlots[7] = new Label();
            this._goodSlots[8] = new Label();
            this._goodSlots[9] = new Label();
            this._goodSlots[10] = new Label();
            this._goodSlots[11] = new Label();
            this._goodSlots[12] = new Label();
            this._goodSlots[13] = new Label();
            this._goodSlots[14] = new Label();
            this._goodSlots[15] = new Label();
            this._goodSlots[16] = new Label();
            this._goodSlots[17] = new Label();
            this._goodSlots[18] = new Label();
            this._goodSlots[19] = new Label();
            this._goodSlots[20] = new Label();
            this._goodSlots[21] = new Label();
            this._goodSlots[22] = new Label();
            this._goodSlots[23] = new Label();
            this._goodSlots[24] = new Label();
            this.rootLayout.SuspendLayout();
            this.contentLayout.SuspendLayout();
            this.grpNg.SuspendLayout();
            this.grpGood.SuspendLayout();
            this.ngLayout.SuspendLayout();
            this.goodLayout.SuspendLayout();
            this.ngSlotLayout.SuspendLayout();
            this.goodSlotLayout.SuspendLayout();
            this.SuspendLayout();

            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.contentLayout, 0, 1);
            this.rootLayout.Controls.Add(this.actionLayout, 0, 2);
            this.rootLayout.Dock = DockStyle.Fill;
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 260F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));

            this.lblHeader.BackColor = UiTheme.StatusBarBg;
            this.lblHeader.Dock = DockStyle.Fill;
            this.lblHeader.Font = UiTheme.SectionFont;
            this.lblHeader.ForeColor = UiTheme.StatusBarFg;
            this.lblHeader.Padding = new Padding(10, 0, 0, 0);
            this.lblHeader.Tag = "i18n:wi.plateStatus";
            this.lblHeader.Text = "PLATE STATUS";
            this.lblHeader.TextAlign = ContentAlignment.MiddleLeft;

            this.contentLayout.ColumnCount = 3;
            this.contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 300F));
            this.contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 300F));
            this.contentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.contentLayout.Controls.Add(this.grpNg, 0, 0);
            this.contentLayout.Controls.Add(this.grpGood, 1, 0);
            this.contentLayout.Dock = DockStyle.Fill;
            this.contentLayout.Padding = new Padding(8);
            this.contentLayout.RowCount = 1;
            this.contentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

            this.grpNg.Controls.Add(this.ngLayout);
            this.grpNg.Dock = DockStyle.Fill;
            this.grpNg.Font = UiTheme.SectionFont;
            this.grpNg.Text = "NG PLATE";
            this.ngLayout.ColumnCount = 1;
            this.ngLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.ngLayout.Controls.Add(this._lblNgCount, 0, 0);
            this.ngLayout.Controls.Add(this.ngSlotLayout, 0, 1);
            this.ngLayout.Dock = DockStyle.Fill;
            this.ngLayout.Padding = new Padding(8, 18, 8, 8);
            this.ngLayout.RowCount = 2;
            this.ngLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.ngLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this._lblNgCount.BackColor = Color.LightCoral;
            this._lblNgCount.Dock = DockStyle.Fill;
            this._lblNgCount.Font = new Font("Consolas", 11F, FontStyle.Bold);
            this._lblNgCount.Text = "0 / 25";
            this._lblNgCount.TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.ColumnCount = 5;
            this.ngSlotLayout.Dock = DockStyle.Fill;
            this.ngSlotLayout.RowCount = 5;
            this.ngSlotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            this.ngSlotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            this.ngSlotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            this.ngSlotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            this.ngSlotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            this.ngSlotLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            this.ngSlotLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            this.ngSlotLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            this.ngSlotLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            this.ngSlotLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));

            this.grpGood.Controls.Add(this.goodLayout);
            this.grpGood.Dock = DockStyle.Fill;
            this.grpGood.Font = UiTheme.SectionFont;
            this.grpGood.Text = "GOOD PLATE";
            this.goodLayout.ColumnCount = 1;
            this.goodLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.goodLayout.Controls.Add(this._lblGoodCount, 0, 0);
            this.goodLayout.Controls.Add(this.goodSlotLayout, 0, 1);
            this.goodLayout.Dock = DockStyle.Fill;
            this.goodLayout.Padding = new Padding(8, 18, 8, 8);
            this.goodLayout.RowCount = 2;
            this.goodLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.goodLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this._lblGoodCount.BackColor = Color.LightGreen;
            this._lblGoodCount.Dock = DockStyle.Fill;
            this._lblGoodCount.Font = new Font("Consolas", 11F, FontStyle.Bold);
            this._lblGoodCount.Text = "0 / 25";
            this._lblGoodCount.TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.ColumnCount = 5;
            this.goodSlotLayout.Dock = DockStyle.Fill;
            this.goodSlotLayout.RowCount = 5;
            this.goodSlotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            this.goodSlotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            this.goodSlotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            this.goodSlotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            this.goodSlotLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            this.goodSlotLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            this.goodSlotLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            this.goodSlotLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            this.goodSlotLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            this.goodSlotLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));

            this._ngSlots[0].BackColor = Color.LightGray;
            this._ngSlots[0].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[0].Dock = DockStyle.Fill;
            this._ngSlots[0].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[0].ForeColor = Color.Black;
            this._ngSlots[0].Margin = new Padding(1);
            this._ngSlots[0].Text = "01";
            this._ngSlots[0].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[0], 0, 0);

            this._ngSlots[1].BackColor = Color.LightGray;
            this._ngSlots[1].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[1].Dock = DockStyle.Fill;
            this._ngSlots[1].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[1].ForeColor = Color.Black;
            this._ngSlots[1].Margin = new Padding(1);
            this._ngSlots[1].Text = "02";
            this._ngSlots[1].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[1], 1, 0);

            this._ngSlots[2].BackColor = Color.LightGray;
            this._ngSlots[2].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[2].Dock = DockStyle.Fill;
            this._ngSlots[2].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[2].ForeColor = Color.Black;
            this._ngSlots[2].Margin = new Padding(1);
            this._ngSlots[2].Text = "03";
            this._ngSlots[2].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[2], 2, 0);

            this._ngSlots[3].BackColor = Color.LightGray;
            this._ngSlots[3].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[3].Dock = DockStyle.Fill;
            this._ngSlots[3].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[3].ForeColor = Color.Black;
            this._ngSlots[3].Margin = new Padding(1);
            this._ngSlots[3].Text = "04";
            this._ngSlots[3].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[3], 3, 0);

            this._ngSlots[4].BackColor = Color.LightGray;
            this._ngSlots[4].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[4].Dock = DockStyle.Fill;
            this._ngSlots[4].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[4].ForeColor = Color.Black;
            this._ngSlots[4].Margin = new Padding(1);
            this._ngSlots[4].Text = "05";
            this._ngSlots[4].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[4], 4, 0);

            this._ngSlots[5].BackColor = Color.LightGray;
            this._ngSlots[5].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[5].Dock = DockStyle.Fill;
            this._ngSlots[5].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[5].ForeColor = Color.Black;
            this._ngSlots[5].Margin = new Padding(1);
            this._ngSlots[5].Text = "06";
            this._ngSlots[5].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[5], 0, 1);

            this._ngSlots[6].BackColor = Color.LightGray;
            this._ngSlots[6].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[6].Dock = DockStyle.Fill;
            this._ngSlots[6].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[6].ForeColor = Color.Black;
            this._ngSlots[6].Margin = new Padding(1);
            this._ngSlots[6].Text = "07";
            this._ngSlots[6].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[6], 1, 1);

            this._ngSlots[7].BackColor = Color.LightGray;
            this._ngSlots[7].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[7].Dock = DockStyle.Fill;
            this._ngSlots[7].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[7].ForeColor = Color.Black;
            this._ngSlots[7].Margin = new Padding(1);
            this._ngSlots[7].Text = "08";
            this._ngSlots[7].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[7], 2, 1);

            this._ngSlots[8].BackColor = Color.LightGray;
            this._ngSlots[8].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[8].Dock = DockStyle.Fill;
            this._ngSlots[8].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[8].ForeColor = Color.Black;
            this._ngSlots[8].Margin = new Padding(1);
            this._ngSlots[8].Text = "09";
            this._ngSlots[8].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[8], 3, 1);

            this._ngSlots[9].BackColor = Color.LightGray;
            this._ngSlots[9].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[9].Dock = DockStyle.Fill;
            this._ngSlots[9].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[9].ForeColor = Color.Black;
            this._ngSlots[9].Margin = new Padding(1);
            this._ngSlots[9].Text = "10";
            this._ngSlots[9].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[9], 4, 1);

            this._ngSlots[10].BackColor = Color.LightGray;
            this._ngSlots[10].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[10].Dock = DockStyle.Fill;
            this._ngSlots[10].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[10].ForeColor = Color.Black;
            this._ngSlots[10].Margin = new Padding(1);
            this._ngSlots[10].Text = "11";
            this._ngSlots[10].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[10], 0, 2);

            this._ngSlots[11].BackColor = Color.LightGray;
            this._ngSlots[11].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[11].Dock = DockStyle.Fill;
            this._ngSlots[11].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[11].ForeColor = Color.Black;
            this._ngSlots[11].Margin = new Padding(1);
            this._ngSlots[11].Text = "12";
            this._ngSlots[11].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[11], 1, 2);

            this._ngSlots[12].BackColor = Color.LightGray;
            this._ngSlots[12].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[12].Dock = DockStyle.Fill;
            this._ngSlots[12].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[12].ForeColor = Color.Black;
            this._ngSlots[12].Margin = new Padding(1);
            this._ngSlots[12].Text = "13";
            this._ngSlots[12].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[12], 2, 2);

            this._ngSlots[13].BackColor = Color.LightGray;
            this._ngSlots[13].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[13].Dock = DockStyle.Fill;
            this._ngSlots[13].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[13].ForeColor = Color.Black;
            this._ngSlots[13].Margin = new Padding(1);
            this._ngSlots[13].Text = "14";
            this._ngSlots[13].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[13], 3, 2);

            this._ngSlots[14].BackColor = Color.LightGray;
            this._ngSlots[14].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[14].Dock = DockStyle.Fill;
            this._ngSlots[14].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[14].ForeColor = Color.Black;
            this._ngSlots[14].Margin = new Padding(1);
            this._ngSlots[14].Text = "15";
            this._ngSlots[14].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[14], 4, 2);

            this._ngSlots[15].BackColor = Color.LightGray;
            this._ngSlots[15].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[15].Dock = DockStyle.Fill;
            this._ngSlots[15].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[15].ForeColor = Color.Black;
            this._ngSlots[15].Margin = new Padding(1);
            this._ngSlots[15].Text = "16";
            this._ngSlots[15].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[15], 0, 3);

            this._ngSlots[16].BackColor = Color.LightGray;
            this._ngSlots[16].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[16].Dock = DockStyle.Fill;
            this._ngSlots[16].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[16].ForeColor = Color.Black;
            this._ngSlots[16].Margin = new Padding(1);
            this._ngSlots[16].Text = "17";
            this._ngSlots[16].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[16], 1, 3);

            this._ngSlots[17].BackColor = Color.LightGray;
            this._ngSlots[17].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[17].Dock = DockStyle.Fill;
            this._ngSlots[17].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[17].ForeColor = Color.Black;
            this._ngSlots[17].Margin = new Padding(1);
            this._ngSlots[17].Text = "18";
            this._ngSlots[17].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[17], 2, 3);

            this._ngSlots[18].BackColor = Color.LightGray;
            this._ngSlots[18].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[18].Dock = DockStyle.Fill;
            this._ngSlots[18].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[18].ForeColor = Color.Black;
            this._ngSlots[18].Margin = new Padding(1);
            this._ngSlots[18].Text = "19";
            this._ngSlots[18].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[18], 3, 3);

            this._ngSlots[19].BackColor = Color.LightGray;
            this._ngSlots[19].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[19].Dock = DockStyle.Fill;
            this._ngSlots[19].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[19].ForeColor = Color.Black;
            this._ngSlots[19].Margin = new Padding(1);
            this._ngSlots[19].Text = "20";
            this._ngSlots[19].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[19], 4, 3);

            this._ngSlots[20].BackColor = Color.LightGray;
            this._ngSlots[20].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[20].Dock = DockStyle.Fill;
            this._ngSlots[20].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[20].ForeColor = Color.Black;
            this._ngSlots[20].Margin = new Padding(1);
            this._ngSlots[20].Text = "21";
            this._ngSlots[20].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[20], 0, 4);

            this._ngSlots[21].BackColor = Color.LightGray;
            this._ngSlots[21].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[21].Dock = DockStyle.Fill;
            this._ngSlots[21].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[21].ForeColor = Color.Black;
            this._ngSlots[21].Margin = new Padding(1);
            this._ngSlots[21].Text = "22";
            this._ngSlots[21].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[21], 1, 4);

            this._ngSlots[22].BackColor = Color.LightGray;
            this._ngSlots[22].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[22].Dock = DockStyle.Fill;
            this._ngSlots[22].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[22].ForeColor = Color.Black;
            this._ngSlots[22].Margin = new Padding(1);
            this._ngSlots[22].Text = "23";
            this._ngSlots[22].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[22], 2, 4);

            this._ngSlots[23].BackColor = Color.LightGray;
            this._ngSlots[23].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[23].Dock = DockStyle.Fill;
            this._ngSlots[23].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[23].ForeColor = Color.Black;
            this._ngSlots[23].Margin = new Padding(1);
            this._ngSlots[23].Text = "24";
            this._ngSlots[23].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[23], 3, 4);

            this._ngSlots[24].BackColor = Color.LightGray;
            this._ngSlots[24].BorderStyle = BorderStyle.FixedSingle;
            this._ngSlots[24].Dock = DockStyle.Fill;
            this._ngSlots[24].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._ngSlots[24].ForeColor = Color.Black;
            this._ngSlots[24].Margin = new Padding(1);
            this._ngSlots[24].Text = "25";
            this._ngSlots[24].TextAlign = ContentAlignment.MiddleCenter;
            this.ngSlotLayout.Controls.Add(this._ngSlots[24], 4, 4);

            this._goodSlots[0].BackColor = Color.LightGray;
            this._goodSlots[0].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[0].Dock = DockStyle.Fill;
            this._goodSlots[0].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[0].ForeColor = Color.Black;
            this._goodSlots[0].Margin = new Padding(1);
            this._goodSlots[0].Text = "01";
            this._goodSlots[0].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[0], 0, 0);

            this._goodSlots[1].BackColor = Color.LightGray;
            this._goodSlots[1].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[1].Dock = DockStyle.Fill;
            this._goodSlots[1].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[1].ForeColor = Color.Black;
            this._goodSlots[1].Margin = new Padding(1);
            this._goodSlots[1].Text = "02";
            this._goodSlots[1].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[1], 1, 0);

            this._goodSlots[2].BackColor = Color.LightGray;
            this._goodSlots[2].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[2].Dock = DockStyle.Fill;
            this._goodSlots[2].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[2].ForeColor = Color.Black;
            this._goodSlots[2].Margin = new Padding(1);
            this._goodSlots[2].Text = "03";
            this._goodSlots[2].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[2], 2, 0);

            this._goodSlots[3].BackColor = Color.LightGray;
            this._goodSlots[3].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[3].Dock = DockStyle.Fill;
            this._goodSlots[3].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[3].ForeColor = Color.Black;
            this._goodSlots[3].Margin = new Padding(1);
            this._goodSlots[3].Text = "04";
            this._goodSlots[3].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[3], 3, 0);

            this._goodSlots[4].BackColor = Color.LightGray;
            this._goodSlots[4].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[4].Dock = DockStyle.Fill;
            this._goodSlots[4].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[4].ForeColor = Color.Black;
            this._goodSlots[4].Margin = new Padding(1);
            this._goodSlots[4].Text = "05";
            this._goodSlots[4].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[4], 4, 0);

            this._goodSlots[5].BackColor = Color.LightGray;
            this._goodSlots[5].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[5].Dock = DockStyle.Fill;
            this._goodSlots[5].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[5].ForeColor = Color.Black;
            this._goodSlots[5].Margin = new Padding(1);
            this._goodSlots[5].Text = "06";
            this._goodSlots[5].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[5], 0, 1);

            this._goodSlots[6].BackColor = Color.LightGray;
            this._goodSlots[6].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[6].Dock = DockStyle.Fill;
            this._goodSlots[6].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[6].ForeColor = Color.Black;
            this._goodSlots[6].Margin = new Padding(1);
            this._goodSlots[6].Text = "07";
            this._goodSlots[6].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[6], 1, 1);

            this._goodSlots[7].BackColor = Color.LightGray;
            this._goodSlots[7].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[7].Dock = DockStyle.Fill;
            this._goodSlots[7].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[7].ForeColor = Color.Black;
            this._goodSlots[7].Margin = new Padding(1);
            this._goodSlots[7].Text = "08";
            this._goodSlots[7].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[7], 2, 1);

            this._goodSlots[8].BackColor = Color.LightGray;
            this._goodSlots[8].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[8].Dock = DockStyle.Fill;
            this._goodSlots[8].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[8].ForeColor = Color.Black;
            this._goodSlots[8].Margin = new Padding(1);
            this._goodSlots[8].Text = "09";
            this._goodSlots[8].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[8], 3, 1);

            this._goodSlots[9].BackColor = Color.LightGray;
            this._goodSlots[9].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[9].Dock = DockStyle.Fill;
            this._goodSlots[9].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[9].ForeColor = Color.Black;
            this._goodSlots[9].Margin = new Padding(1);
            this._goodSlots[9].Text = "10";
            this._goodSlots[9].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[9], 4, 1);

            this._goodSlots[10].BackColor = Color.LightGray;
            this._goodSlots[10].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[10].Dock = DockStyle.Fill;
            this._goodSlots[10].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[10].ForeColor = Color.Black;
            this._goodSlots[10].Margin = new Padding(1);
            this._goodSlots[10].Text = "11";
            this._goodSlots[10].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[10], 0, 2);

            this._goodSlots[11].BackColor = Color.LightGray;
            this._goodSlots[11].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[11].Dock = DockStyle.Fill;
            this._goodSlots[11].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[11].ForeColor = Color.Black;
            this._goodSlots[11].Margin = new Padding(1);
            this._goodSlots[11].Text = "12";
            this._goodSlots[11].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[11], 1, 2);

            this._goodSlots[12].BackColor = Color.LightGray;
            this._goodSlots[12].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[12].Dock = DockStyle.Fill;
            this._goodSlots[12].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[12].ForeColor = Color.Black;
            this._goodSlots[12].Margin = new Padding(1);
            this._goodSlots[12].Text = "13";
            this._goodSlots[12].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[12], 2, 2);

            this._goodSlots[13].BackColor = Color.LightGray;
            this._goodSlots[13].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[13].Dock = DockStyle.Fill;
            this._goodSlots[13].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[13].ForeColor = Color.Black;
            this._goodSlots[13].Margin = new Padding(1);
            this._goodSlots[13].Text = "14";
            this._goodSlots[13].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[13], 3, 2);

            this._goodSlots[14].BackColor = Color.LightGray;
            this._goodSlots[14].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[14].Dock = DockStyle.Fill;
            this._goodSlots[14].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[14].ForeColor = Color.Black;
            this._goodSlots[14].Margin = new Padding(1);
            this._goodSlots[14].Text = "15";
            this._goodSlots[14].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[14], 4, 2);

            this._goodSlots[15].BackColor = Color.LightGray;
            this._goodSlots[15].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[15].Dock = DockStyle.Fill;
            this._goodSlots[15].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[15].ForeColor = Color.Black;
            this._goodSlots[15].Margin = new Padding(1);
            this._goodSlots[15].Text = "16";
            this._goodSlots[15].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[15], 0, 3);

            this._goodSlots[16].BackColor = Color.LightGray;
            this._goodSlots[16].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[16].Dock = DockStyle.Fill;
            this._goodSlots[16].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[16].ForeColor = Color.Black;
            this._goodSlots[16].Margin = new Padding(1);
            this._goodSlots[16].Text = "17";
            this._goodSlots[16].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[16], 1, 3);

            this._goodSlots[17].BackColor = Color.LightGray;
            this._goodSlots[17].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[17].Dock = DockStyle.Fill;
            this._goodSlots[17].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[17].ForeColor = Color.Black;
            this._goodSlots[17].Margin = new Padding(1);
            this._goodSlots[17].Text = "18";
            this._goodSlots[17].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[17], 2, 3);

            this._goodSlots[18].BackColor = Color.LightGray;
            this._goodSlots[18].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[18].Dock = DockStyle.Fill;
            this._goodSlots[18].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[18].ForeColor = Color.Black;
            this._goodSlots[18].Margin = new Padding(1);
            this._goodSlots[18].Text = "19";
            this._goodSlots[18].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[18], 3, 3);

            this._goodSlots[19].BackColor = Color.LightGray;
            this._goodSlots[19].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[19].Dock = DockStyle.Fill;
            this._goodSlots[19].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[19].ForeColor = Color.Black;
            this._goodSlots[19].Margin = new Padding(1);
            this._goodSlots[19].Text = "20";
            this._goodSlots[19].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[19], 4, 3);

            this._goodSlots[20].BackColor = Color.LightGray;
            this._goodSlots[20].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[20].Dock = DockStyle.Fill;
            this._goodSlots[20].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[20].ForeColor = Color.Black;
            this._goodSlots[20].Margin = new Padding(1);
            this._goodSlots[20].Text = "21";
            this._goodSlots[20].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[20], 0, 4);

            this._goodSlots[21].BackColor = Color.LightGray;
            this._goodSlots[21].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[21].Dock = DockStyle.Fill;
            this._goodSlots[21].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[21].ForeColor = Color.Black;
            this._goodSlots[21].Margin = new Padding(1);
            this._goodSlots[21].Text = "22";
            this._goodSlots[21].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[21], 1, 4);

            this._goodSlots[22].BackColor = Color.LightGray;
            this._goodSlots[22].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[22].Dock = DockStyle.Fill;
            this._goodSlots[22].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[22].ForeColor = Color.Black;
            this._goodSlots[22].Margin = new Padding(1);
            this._goodSlots[22].Text = "23";
            this._goodSlots[22].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[22], 2, 4);

            this._goodSlots[23].BackColor = Color.LightGray;
            this._goodSlots[23].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[23].Dock = DockStyle.Fill;
            this._goodSlots[23].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[23].ForeColor = Color.Black;
            this._goodSlots[23].Margin = new Padding(1);
            this._goodSlots[23].Text = "24";
            this._goodSlots[23].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[23], 3, 4);

            this._goodSlots[24].BackColor = Color.LightGray;
            this._goodSlots[24].BorderStyle = BorderStyle.FixedSingle;
            this._goodSlots[24].Dock = DockStyle.Fill;
            this._goodSlots[24].Font = new Font("Consolas", 8F, FontStyle.Bold);
            this._goodSlots[24].ForeColor = Color.Black;
            this._goodSlots[24].Margin = new Padding(1);
            this._goodSlots[24].Text = "25";
            this._goodSlots[24].TextAlign = ContentAlignment.MiddleCenter;
            this.goodSlotLayout.Controls.Add(this._goodSlots[24], 4, 4);

            this.actionLayout.Dock = DockStyle.Fill;
            this.actionLayout.FlowDirection = FlowDirection.LeftToRight;
            this.actionLayout.Padding = new Padding(12);
            this.btnReset.BackColor = Color.LightYellow;
            this.btnReset.FlatStyle = FlatStyle.Flat;
            this.btnReset.Font = UiTheme.SectionFont;
            this.btnReset.Height = 50;
            this.btnReset.Text = "PLATE RESET";
            this.btnReset.UseVisualStyleBackColor = false;
            this.btnReset.Width = 180;
            this.actionLayout.Controls.Add(this.btnReset);

            this.Controls.Add(this.rootLayout);
            this.Name = "PlateStatusPage";
            this.Size = new Size(1678, 900);
            this.goodSlotLayout.ResumeLayout(false);
            this.ngSlotLayout.ResumeLayout(false);
            this.goodLayout.ResumeLayout(false);
            this.ngLayout.ResumeLayout(false);
            this.grpGood.ResumeLayout(false);
            this.grpNg.ResumeLayout(false);
            this.contentLayout.ResumeLayout(false);
            this.rootLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}

