namespace QMC.CDT_320.Ui.Pages.Recipe
{
    partial class VisionRecipePage
    {
        private System.ComponentModel.IContainer components = null;

        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.TableLayoutPanel contentLayout;
        private System.Windows.Forms.TableLayoutPanel leftLayout;
        private System.Windows.Forms.TableLayoutPanel centerLayout;
        private System.Windows.Forms.TableLayoutPanel rightLayout;
        private System.Windows.Forms.GroupBox grpCamera;
        private System.Windows.Forms.GroupBox grpMatchResult;
        private System.Windows.Forms.GroupBox grpRoi;
        private System.Windows.Forms.GroupBox grpAction;
        private System.Windows.Forms.GroupBox grpScale;
        private System.Windows.Forms.GroupBox grpJog;
        private System.Windows.Forms.GroupBox grpSpeed;
        private System.Windows.Forms.Panel cameraPanel;
        private System.Windows.Forms.Label lblCameraInfo;
        private System.Windows.Forms.DataGridView gridMatch;
        private System.Windows.Forms.TableLayoutPanel roiLayout;
        private System.Windows.Forms.TableLayoutPanel roiOptionLayout;
        private System.Windows.Forms.Panel thumbPanel;
        private System.Windows.Forms.Label lblThumb;
        private System.Windows.Forms.RadioButton rdoMain;
        private System.Windows.Forms.RadioButton rdoChip;
        private System.Windows.Forms.RadioButton rdoSub;
        private System.Windows.Forms.RadioButton rdoCross;
        private System.Windows.Forms.RadioButton rdoIndex1;
        private System.Windows.Forms.RadioButton rdoIndex2;
        private System.Windows.Forms.RadioButton rdoIndex4;
        private System.Windows.Forms.RadioButton rdoIndex8;
        private QMC.CDT_320.Ui.Controls.ActionCommandPanelControl actionCommandPanel;
        private System.Windows.Forms.TableLayoutPanel scaleLayout;
        private System.Windows.Forms.TableLayoutPanel scaleXPair;
        private System.Windows.Forms.TableLayoutPanel scaleYPair;
        private System.Windows.Forms.TableLayoutPanel pitchPair;
        private System.Windows.Forms.TableLayoutPanel scalePair;
        private System.Windows.Forms.Label lblScaleXKey;
        private System.Windows.Forms.Label lblScaleXValue;
        private System.Windows.Forms.Label lblScaleYKey;
        private System.Windows.Forms.Label lblScaleYValue;
        private System.Windows.Forms.Label lblPitchKey;
        private System.Windows.Forms.Label lblPitchValue;
        private System.Windows.Forms.Label lblScaleKey;
        private System.Windows.Forms.Label lblScaleValue;
        private System.Windows.Forms.Label lblGrayValue;
        private System.Windows.Forms.TableLayoutPanel jogLayout;
        private System.Windows.Forms.TrackBar trkSpeed;
        private System.Windows.Forms.TableLayoutPanel speedLayout;
        private System.Windows.Forms.Label lblSpeedValue;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogYPlus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogXMinus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogStop;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogXPlus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogYMinus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogTMinus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogTPlus;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle gridHeaderStyle = new System.Windows.Forms.DataGridViewCellStyle();
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.contentLayout = new System.Windows.Forms.TableLayoutPanel();
            this.leftLayout = new System.Windows.Forms.TableLayoutPanel();
            this.centerLayout = new System.Windows.Forms.TableLayoutPanel();
            this.rightLayout = new System.Windows.Forms.TableLayoutPanel();
            this.grpCamera = new System.Windows.Forms.GroupBox();
            this.grpMatchResult = new System.Windows.Forms.GroupBox();
            this.grpRoi = new System.Windows.Forms.GroupBox();
            this.grpAction = new System.Windows.Forms.GroupBox();
            this.grpScale = new System.Windows.Forms.GroupBox();
            this.grpJog = new System.Windows.Forms.GroupBox();
            this.grpSpeed = new System.Windows.Forms.GroupBox();
            this.cameraPanel = new System.Windows.Forms.Panel();
            this.lblCameraInfo = new System.Windows.Forms.Label();
            this.gridMatch = new System.Windows.Forms.DataGridView();
            this.roiLayout = new System.Windows.Forms.TableLayoutPanel();
            this.roiOptionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.thumbPanel = new System.Windows.Forms.Panel();
            this.lblThumb = new System.Windows.Forms.Label();
            this.rdoMain = new System.Windows.Forms.RadioButton();
            this.rdoChip = new System.Windows.Forms.RadioButton();
            this.rdoSub = new System.Windows.Forms.RadioButton();
            this.rdoCross = new System.Windows.Forms.RadioButton();
            this.rdoIndex1 = new System.Windows.Forms.RadioButton();
            this.rdoIndex2 = new System.Windows.Forms.RadioButton();
            this.rdoIndex4 = new System.Windows.Forms.RadioButton();
            this.rdoIndex8 = new System.Windows.Forms.RadioButton();
            this.actionCommandPanel = new QMC.CDT_320.Ui.Controls.ActionCommandPanelControl();
            this.scaleLayout = new System.Windows.Forms.TableLayoutPanel();
            this.scaleXPair = new System.Windows.Forms.TableLayoutPanel();
            this.scaleYPair = new System.Windows.Forms.TableLayoutPanel();
            this.pitchPair = new System.Windows.Forms.TableLayoutPanel();
            this.scalePair = new System.Windows.Forms.TableLayoutPanel();
            this.lblScaleXKey = new System.Windows.Forms.Label();
            this.lblScaleXValue = new System.Windows.Forms.Label();
            this.lblScaleYKey = new System.Windows.Forms.Label();
            this.lblScaleYValue = new System.Windows.Forms.Label();
            this.lblPitchKey = new System.Windows.Forms.Label();
            this.lblPitchValue = new System.Windows.Forms.Label();
            this.lblScaleKey = new System.Windows.Forms.Label();
            this.lblScaleValue = new System.Windows.Forms.Label();
            this.lblGrayValue = new System.Windows.Forms.Label();
            this.jogLayout = new System.Windows.Forms.TableLayoutPanel();
            this.speedLayout = new System.Windows.Forms.TableLayoutPanel();
            this.trkSpeed = new System.Windows.Forms.TrackBar();
            this.lblSpeedValue = new System.Windows.Forms.Label();
            this.btnJogYPlus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogXMinus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogStop = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogXPlus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogYMinus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogTMinus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogTPlus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.rootLayout.SuspendLayout();
            this.contentLayout.SuspendLayout();
            this.leftLayout.SuspendLayout();
            this.centerLayout.SuspendLayout();
            this.rightLayout.SuspendLayout();
            this.grpCamera.SuspendLayout();
            this.grpMatchResult.SuspendLayout();
            this.grpRoi.SuspendLayout();
            this.grpAction.SuspendLayout();
            this.grpScale.SuspendLayout();
            this.grpJog.SuspendLayout();
            this.grpSpeed.SuspendLayout();
            this.cameraPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridMatch)).BeginInit();
            this.roiLayout.SuspendLayout();
            this.roiOptionLayout.SuspendLayout();
            this.thumbPanel.SuspendLayout();
            this.scaleLayout.SuspendLayout();
            this.scaleXPair.SuspendLayout();
            this.scaleYPair.SuspendLayout();
            this.pitchPair.SuspendLayout();
            this.scalePair.SuspendLayout();
            this.jogLayout.SuspendLayout();
            this.speedLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.trkSpeed)).BeginInit();
            this.SuspendLayout();
            // 
            // rootLayout
            // 
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.contentLayout, 0, 1);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Margin = new System.Windows.Forms.Padding(0);
            this.rootLayout.Name = "rootLayout";
            this.rootLayout.RowCount = 2;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Size = new System.Drawing.Size(1400, 900);
            this.rootLayout.TabIndex = 0;
            // 
            // lblHeader
            // 
            this.lblHeader.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblHeader.ForeColor = System.Drawing.Color.White;
            this.lblHeader.Margin = new System.Windows.Forms.Padding(0);
            this.lblHeader.Name = "lblHeader";
            this.lblHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblHeader.Tag = "i18n:recipe.inputVision";
            this.lblHeader.Text = "INPUT VISION";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // contentLayout
            // 
            this.contentLayout.ColumnCount = 3;
            this.contentLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 560F));
            this.contentLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.contentLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 170F));
            this.contentLayout.Controls.Add(this.leftLayout, 0, 0);
            this.contentLayout.Controls.Add(this.centerLayout, 1, 0);
            this.contentLayout.Controls.Add(this.rightLayout, 2, 0);
            this.contentLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.contentLayout.Margin = new System.Windows.Forms.Padding(0);
            this.contentLayout.Padding = new System.Windows.Forms.Padding(8);
            this.contentLayout.RowCount = 1;
            this.contentLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            // 
            // column layouts
            // 
            this.leftLayout.ColumnCount = 1;
            this.leftLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.leftLayout.Controls.Add(this.grpCamera, 0, 0);
            this.leftLayout.Controls.Add(this.grpMatchResult, 0, 1);
            this.leftLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.leftLayout.Margin = new System.Windows.Forms.Padding(0);
            this.leftLayout.RowCount = 2;
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 62F));
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 38F));
            this.centerLayout.ColumnCount = 1;
            this.centerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.centerLayout.Controls.Add(this.grpRoi, 0, 0);
            this.centerLayout.Controls.Add(this.grpAction, 0, 1);
            this.centerLayout.Controls.Add(this.grpScale, 0, 2);
            this.centerLayout.Controls.Add(this.grpJog, 0, 3);
            this.centerLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.centerLayout.Margin = new System.Windows.Forms.Padding(0);
            this.centerLayout.RowCount = 4;
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 260F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 180F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 160F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rightLayout.ColumnCount = 1;
            this.rightLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rightLayout.Controls.Add(this.grpSpeed, 0, 0);
            this.rightLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rightLayout.Margin = new System.Windows.Forms.Padding(0);
            this.rightLayout.RowCount = 1;
            this.rightLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            // 
            // group boxes
            // 
            this.grpCamera.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpCamera.Controls.Add(this.cameraPanel);
            this.grpCamera.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpCamera.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpCamera.Margin = new System.Windows.Forms.Padding(4);
            this.grpCamera.Name = "grpCamera";
            this.grpCamera.Text = "VISION";
            this.grpMatchResult.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpMatchResult.Controls.Add(this.gridMatch);
            this.grpMatchResult.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpMatchResult.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpMatchResult.Margin = new System.Windows.Forms.Padding(4);
            this.grpMatchResult.Name = "grpMatchResult";
            this.grpMatchResult.Text = "MATCH RESULT";
            this.grpRoi.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpRoi.Controls.Add(this.roiLayout);
            this.grpRoi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpRoi.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpRoi.Margin = new System.Windows.Forms.Padding(4);
            this.grpRoi.Text = "ROI SETTING";
            this.grpAction.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpAction.Controls.Add(this.actionCommandPanel);
            this.grpAction.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpAction.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpAction.Margin = new System.Windows.Forms.Padding(4);
            this.grpAction.Text = "ACTION";
            this.grpScale.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpScale.Controls.Add(this.scaleLayout);
            this.grpScale.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpScale.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpScale.Margin = new System.Windows.Forms.Padding(4);
            this.grpScale.Text = "AUTO SCALE / GRAY";
            this.grpJog.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpJog.Controls.Add(this.jogLayout);
            this.grpJog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpJog.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpJog.Margin = new System.Windows.Forms.Padding(4);
            this.grpJog.Text = "JOG OPERATION";
            this.grpSpeed.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpSpeed.Controls.Add(this.speedLayout);
            this.grpSpeed.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSpeed.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpSpeed.Margin = new System.Windows.Forms.Padding(4);
            this.grpSpeed.Text = "SPEED";
            // 
            // cameraPanel
            // 
            this.cameraPanel.BackColor = System.Drawing.Color.Black;
            this.cameraPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.cameraPanel.Controls.Add(this.lblCameraInfo);
            this.cameraPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cameraPanel.Margin = new System.Windows.Forms.Padding(10);
            this.lblCameraInfo.AutoSize = true;
            this.lblCameraInfo.BackColor = System.Drawing.Color.Black;
            this.lblCameraInfo.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblCameraInfo.ForeColor = System.Drawing.Color.Lime;
            this.lblCameraInfo.Location = new System.Drawing.Point(10, 10);
            this.lblCameraInfo.Text = "VISION\r\nW : 640\r\nH : 480\r\nX : 0\r\nY : 0";
            // 
            // gridMatch
            // 
            gridHeaderStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            gridHeaderStyle.BackColor = System.Drawing.Color.FromArgb(80, 80, 80);
            gridHeaderStyle.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            gridHeaderStyle.ForeColor = System.Drawing.Color.White;
            this.gridMatch.AllowUserToAddRows = false;
            this.gridMatch.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.gridMatch.BackgroundColor = System.Drawing.Color.White;
            this.gridMatch.ColumnHeadersDefaultCellStyle = gridHeaderStyle;
            this.gridMatch.Columns.Add("NO", "No");
            this.gridMatch.Columns.Add("PX", "Pos X");
            this.gridMatch.Columns.Add("PY", "Pos Y");
            this.gridMatch.Columns.Add("ANG", "Angle");
            this.gridMatch.Columns.Add("SC", "Score");
            this.gridMatch.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridMatch.EnableHeadersVisualStyles = false;
            this.gridMatch.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.gridMatch.ReadOnly = true;
            this.gridMatch.RowHeadersVisible = false;
            this.gridMatch.Rows.Add("1", "", "", "", "");
            // 
            // roiLayout
            // 
            this.roiLayout.ColumnCount = 2;
            this.roiLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48F));
            this.roiLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 52F));
            this.roiLayout.Controls.Add(this.roiOptionLayout, 0, 0);
            this.roiLayout.Controls.Add(this.thumbPanel, 1, 0);
            this.roiLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.roiLayout.Padding = new System.Windows.Forms.Padding(10, 18, 10, 10);
            this.roiLayout.RowCount = 1;
            this.roiLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.roiOptionLayout.ColumnCount = 2;
            this.roiOptionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.roiOptionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.roiOptionLayout.Controls.Add(this.rdoMain, 0, 0);
            this.roiOptionLayout.Controls.Add(this.rdoChip, 1, 0);
            this.roiOptionLayout.Controls.Add(this.rdoSub, 0, 1);
            this.roiOptionLayout.Controls.Add(this.rdoCross, 1, 1);
            this.roiOptionLayout.Controls.Add(this.rdoIndex1, 0, 3);
            this.roiOptionLayout.Controls.Add(this.rdoIndex2, 1, 3);
            this.roiOptionLayout.Controls.Add(this.rdoIndex4, 0, 4);
            this.roiOptionLayout.Controls.Add(this.rdoIndex8, 1, 4);
            this.roiOptionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.roiOptionLayout.RowCount = 6;
            this.roiOptionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66F));
            this.roiOptionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66F));
            this.roiOptionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66F));
            this.roiOptionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66F));
            this.roiOptionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66F));
            this.roiOptionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.7F));
            this.rdoMain.Checked = true;
            this.rdoMain.Text = "Main";
            this.rdoChip.Text = "Chip";
            this.rdoSub.Text = "Sub";
            this.rdoCross.Text = "Cross";
            this.rdoIndex1.Checked = true;
            this.rdoIndex1.Text = "Index 1";
            this.rdoIndex2.Text = "Index 2";
            this.rdoIndex4.Text = "Index 4";
            this.rdoIndex8.Text = "Index 8";
            this.rdoMain.AutoSize = true;
            this.rdoChip.AutoSize = true;
            this.rdoSub.AutoSize = true;
            this.rdoCross.AutoSize = true;
            this.rdoIndex1.AutoSize = true;
            this.rdoIndex2.AutoSize = true;
            this.rdoIndex4.AutoSize = true;
            this.rdoIndex8.AutoSize = true;
            this.rdoMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rdoChip.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rdoSub.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rdoCross.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rdoIndex1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rdoIndex2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rdoIndex4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rdoIndex8.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rdoMain.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.rdoChip.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.rdoSub.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.rdoCross.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.rdoIndex1.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.rdoIndex2.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.rdoIndex4.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.rdoIndex8.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.thumbPanel.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.thumbPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.thumbPanel.Controls.Add(this.lblThumb);
            this.thumbPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblThumb.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblThumb.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.lblThumb.ForeColor = System.Drawing.Color.White;
            this.lblThumb.Text = "1# Match Image";
            this.lblThumb.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // actionCommandPanel
            //
            this.actionCommandPanel.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.actionCommandPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.actionCommandPanel.Location = new System.Drawing.Point(3, 26);
            this.actionCommandPanel.Margin = new System.Windows.Forms.Padding(0);
            this.actionCommandPanel.Name = "actionCommandPanel";
            this.actionCommandPanel.Size = new System.Drawing.Size(486, 147);
            this.actionCommandPanel.TabIndex = 0;
            //
            // scaleLayout
            // 
            this.scaleLayout.ColumnCount = 3;
            this.scaleLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 36F));
            this.scaleLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 36F));
            this.scaleLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 28F));
            this.scaleLayout.Controls.Add(this.scaleXPair, 0, 0);
            this.scaleLayout.Controls.Add(this.scaleYPair, 0, 1);
            this.scaleLayout.Controls.Add(this.pitchPair, 1, 0);
            this.scaleLayout.Controls.Add(this.scalePair, 1, 1);
            this.scaleLayout.Controls.Add(this.lblGrayValue, 2, 0);
            this.scaleLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.scaleLayout.Padding = new System.Windows.Forms.Padding(10, 18, 10, 10);
            this.scaleLayout.RowCount = 3;
            this.scaleLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.scaleLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.34F));
            this.scaleLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.scaleLayout.SetRowSpan(this.lblGrayValue, 3);
            this.scaleXPair.ColumnCount = 2;
            this.scaleYPair.ColumnCount = 2;
            this.pitchPair.ColumnCount = 2;
            this.scalePair.ColumnCount = 2;
            this.scaleXPair.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 52F));
            this.scaleXPair.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48F));
            this.scaleYPair.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 52F));
            this.scaleYPair.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48F));
            this.pitchPair.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 52F));
            this.pitchPair.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48F));
            this.scalePair.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 52F));
            this.scalePair.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48F));
            this.scaleXPair.Controls.Add(this.lblScaleXKey, 0, 0);
            this.scaleXPair.Controls.Add(this.lblScaleXValue, 1, 0);
            this.scaleYPair.Controls.Add(this.lblScaleYKey, 0, 0);
            this.scaleYPair.Controls.Add(this.lblScaleYValue, 1, 0);
            this.pitchPair.Controls.Add(this.lblPitchKey, 0, 0);
            this.pitchPair.Controls.Add(this.lblPitchValue, 1, 0);
            this.scalePair.Controls.Add(this.lblScaleKey, 0, 0);
            this.scalePair.Controls.Add(this.lblScaleValue, 1, 0);
            this.scaleXPair.Dock = System.Windows.Forms.DockStyle.Fill;
            this.scaleYPair.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pitchPair.Dock = System.Windows.Forms.DockStyle.Fill;
            this.scalePair.Dock = System.Windows.Forms.DockStyle.Fill;
            this.scaleXPair.RowCount = 1;
            this.scaleYPair.RowCount = 1;
            this.pitchPair.RowCount = 1;
            this.scalePair.RowCount = 1;
            this.scaleXPair.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.scaleYPair.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.pitchPair.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.scalePair.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lblScaleXKey.Text = "CALC SCALE X";
            this.lblScaleXValue.Text = "0.00000";
            this.lblScaleYKey.Text = "CALC SCALE Y";
            this.lblScaleYValue.Text = "0.00000";
            this.lblPitchKey.Text = "PITCH";
            this.lblPitchValue.Text = "1000";
            this.lblScaleKey.Text = "SCALE";
            this.lblScaleValue.Text = "0.22x";
            this.lblGrayValue.BackColor = System.Drawing.Color.White;
            this.lblGrayValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblGrayValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblGrayValue.Font = new System.Drawing.Font("맑은 고딕", 26F, System.Drawing.FontStyle.Bold);
            this.lblGrayValue.Text = "255";
            this.lblGrayValue.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // jogLayout
            // 
            this.jogLayout.ColumnCount = 3;
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.34F));
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogLayout.Controls.Add(this.btnJogYPlus, 1, 0);
            this.jogLayout.Controls.Add(this.btnJogXMinus, 0, 1);
            this.jogLayout.Controls.Add(this.btnJogStop, 1, 1);
            this.jogLayout.Controls.Add(this.btnJogXPlus, 2, 1);
            this.jogLayout.Controls.Add(this.btnJogTMinus, 0, 2);
            this.jogLayout.Controls.Add(this.btnJogYMinus, 1, 2);
            this.jogLayout.Controls.Add(this.btnJogTPlus, 2, 2);
            this.jogLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.jogLayout.Padding = new System.Windows.Forms.Padding(18, 24, 18, 18);
            this.jogLayout.RowCount = 3;
            this.jogLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.34F));
            this.jogLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.btnJogYPlus.Text = "+Y";
            this.btnJogXMinus.Text = "-X";
            this.btnJogStop.Text = "STOP";
            this.btnJogXPlus.Text = "+X";
            this.btnJogYMinus.Text = "-Y";
            this.btnJogTMinus.Text = "-T";
            this.btnJogTPlus.Text = "+T";
            // 
            // speedLayout
            // 
            this.speedLayout.ColumnCount = 1;
            this.speedLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.speedLayout.Controls.Add(this.trkSpeed, 0, 0);
            this.speedLayout.Controls.Add(this.lblSpeedValue, 0, 1);
            this.speedLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.speedLayout.Padding = new System.Windows.Forms.Padding(12, 18, 12, 12);
            this.speedLayout.RowCount = 2;
            this.speedLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.speedLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.trkSpeed.Dock = System.Windows.Forms.DockStyle.Fill;
            this.trkSpeed.Maximum = 100;
            this.trkSpeed.Orientation = System.Windows.Forms.Orientation.Vertical;
            this.trkSpeed.TickFrequency = 10;
            this.trkSpeed.Value = 50;
            this.lblSpeedValue.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblSpeedValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSpeedValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblSpeedValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblSpeedValue.Text = "50%";
            this.lblSpeedValue.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // common styling
            // 
            this.lblScaleXKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblScaleYKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPitchKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblScaleKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblScaleXValue.BackColor = System.Drawing.Color.White;
            this.lblScaleYValue.BackColor = System.Drawing.Color.White;
            this.lblPitchValue.BackColor = System.Drawing.Color.White;
            this.lblScaleValue.BackColor = System.Drawing.Color.White;
            this.lblScaleXKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblScaleYKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPitchKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblScaleKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblScaleXValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblScaleYValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPitchValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblScaleValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblScaleXKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblScaleYKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPitchKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblScaleKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblScaleXValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblScaleYValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPitchValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblScaleValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblScaleXKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblScaleYKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblPitchKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblScaleKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblScaleXValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblScaleYValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblPitchValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblScaleValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblScaleXKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblScaleYKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPitchKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblScaleKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblScaleXValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblScaleYValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblPitchValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblScaleValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnJogYPlus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogXMinus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogStop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogXPlus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogYMinus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogTMinus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogTPlus.Dock = System.Windows.Forms.DockStyle.Fill;            this.btnJogYPlus.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogXMinus.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogStop.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogXPlus.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogYMinus.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogTMinus.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogTPlus.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogYPlus.Margin = new System.Windows.Forms.Padding(4);
            this.btnJogXMinus.Margin = new System.Windows.Forms.Padding(4);
            this.btnJogStop.Margin = new System.Windows.Forms.Padding(4);
            this.btnJogXPlus.Margin = new System.Windows.Forms.Padding(4);
            this.btnJogYMinus.Margin = new System.Windows.Forms.Padding(4);
            this.btnJogTMinus.Margin = new System.Windows.Forms.Padding(4);
            this.btnJogTPlus.Margin = new System.Windows.Forms.Padding(4);
            // 
            // VisionRecipePage
            // 
            this.Controls.Add(this.rootLayout);
            this.Name = "VisionRecipePage";
            this.Size = new System.Drawing.Size(1678, 900);
            this.rootLayout.ResumeLayout(false);
            this.contentLayout.ResumeLayout(false);
            this.leftLayout.ResumeLayout(false);
            this.centerLayout.ResumeLayout(false);
            this.rightLayout.ResumeLayout(false);
            this.grpCamera.ResumeLayout(false);
            this.grpMatchResult.ResumeLayout(false);
            this.grpRoi.ResumeLayout(false);
            this.grpAction.ResumeLayout(false);
            this.grpScale.ResumeLayout(false);
            this.grpJog.ResumeLayout(false);
            this.grpSpeed.ResumeLayout(false);
            this.cameraPanel.ResumeLayout(false);
            this.cameraPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridMatch)).EndInit();
            this.roiLayout.ResumeLayout(false);
            this.roiOptionLayout.ResumeLayout(false);
            this.roiOptionLayout.PerformLayout();
            this.thumbPanel.ResumeLayout(false);
            this.scaleLayout.ResumeLayout(false);
            this.scaleXPair.ResumeLayout(false);
            this.scaleYPair.ResumeLayout(false);
            this.pitchPair.ResumeLayout(false);
            this.scalePair.ResumeLayout(false);
            this.jogLayout.ResumeLayout(false);
            this.speedLayout.ResumeLayout(false);
            this.speedLayout.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.trkSpeed)).EndInit();
            this.ResumeLayout(false);
        }
    }
}

