namespace QMC.CDT_320.Ui.Pages.Recipe
{
    partial class HeadRecipePage
    {
        private System.ComponentModel.IContainer components = null;

        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.TableLayoutPanel contentLayout;
        private System.Windows.Forms.TableLayoutPanel leftLayout;
        private System.Windows.Forms.TableLayoutPanel centerLayout;
        private System.Windows.Forms.TableLayoutPanel rightLayout;
        private System.Windows.Forms.GroupBox grpOptions;
        private System.Windows.Forms.GroupBox grpWait;
        private System.Windows.Forms.GroupBox grpManual;
        private System.Windows.Forms.GroupBox grpIo;
        private System.Windows.Forms.GroupBox grpCamera;
        private System.Windows.Forms.GroupBox grpJog;
        private System.Windows.Forms.GroupBox grpSpeed;
        private System.Windows.Forms.TableLayoutPanel optionLayout;
        private System.Windows.Forms.TableLayoutPanel waitLayout;
        private System.Windows.Forms.TableLayoutPanel manualLayout;
        private System.Windows.Forms.TableLayoutPanel ioLayout;
        private System.Windows.Forms.Panel cameraPanel;
        private System.Windows.Forms.Label lblCameraInfo;
        private System.Windows.Forms.TableLayoutPanel jogLayout;
        private System.Windows.Forms.TableLayoutPanel jogAxisLayout;
        private System.Windows.Forms.TableLayoutPanel jogThetaLayout;
        private System.Windows.Forms.TableLayoutPanel jogZLayout;
        private System.Windows.Forms.TableLayoutPanel speedLayout;
        private System.Windows.Forms.TrackBar trkSpeed;
        private System.Windows.Forms.Label lblSpeedValue;

        private System.Windows.Forms.Label lblBaseStrokeKey;
        private System.Windows.Forms.Label lblBaseStrokeValue;
        private System.Windows.Forms.Label lblPickPositionKey;
        private System.Windows.Forms.Label lblPickPositionValue;
        private System.Windows.Forms.Label lblPlacePositionKey;
        private System.Windows.Forms.Label lblPlacePositionValue;
        private System.Windows.Forms.Label lblSequenceSettingKey;
        private System.Windows.Forms.Label lblSequenceSettingValue;
        private System.Windows.Forms.Label lblPickZOffsetKey;
        private System.Windows.Forms.Label lblPickZOffsetValue;
        private System.Windows.Forms.Label lblPlaceZOffsetKey;
        private System.Windows.Forms.Label lblPlaceZOffsetValue;
        private System.Windows.Forms.Label lblHeadUseKey;
        private System.Windows.Forms.Label lblHeadUseValue;
        private System.Windows.Forms.Label lblVacuumCheckKey;
        private System.Windows.Forms.Label lblVacuumCheckValue;
        private System.Windows.Forms.Label lblColletCheckKey;
        private System.Windows.Forms.Label lblColletCheckValue;
        private System.Windows.Forms.Label lblHeadTPowerKey;
        private System.Windows.Forms.Label lblHeadTPowerValue;

        private System.Windows.Forms.Label lblHeadMoveWaitKey;
        private System.Windows.Forms.Label lblHeadMoveWaitValue;
        private System.Windows.Forms.Label lblVacuumOnPickKey;
        private System.Windows.Forms.Label lblVacuumOnPickValue;
        private System.Windows.Forms.Label lblVacuumOnPlaceKey;
        private System.Windows.Forms.Label lblVacuumOnPlaceValue;
        private System.Windows.Forms.Label lblBlowWaitKey;
        private System.Windows.Forms.Label lblBlowWaitValue;
        private System.Windows.Forms.Label lblPickPlaceUpDownKey;
        private System.Windows.Forms.Label lblPickPlaceUpDownValue;

        private QMC.CDT_320.Ui.Controls.ActionButton btnPickUpTest;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPick;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPickDown;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPickUp;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPlaceMove;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPlace;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPlaceDown;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPlaceUp;

        private QMC.CDT_320.Ui.Controls.IndicatorDot dotVacuumBlow1;
        private QMC.CDT_320.Ui.Controls.IndicatorDot dotVacuumBlow2;
        private QMC.CDT_320.Ui.Controls.IndicatorDot dotFlowSensor1;
        private QMC.CDT_320.Ui.Controls.IndicatorDot dotBreakSensor1;
        private QMC.CDT_320.Ui.Controls.IndicatorDot dotFlowSensor2;
        private QMC.CDT_320.Ui.Controls.IndicatorDot dotBreakSensor2;
        private System.Windows.Forms.Label lblVacuumBlow1Key;
        private System.Windows.Forms.Label lblVacuumBlow1Value;
        private System.Windows.Forms.Label lblVacuumBlow2Key;
        private System.Windows.Forms.Label lblVacuumBlow2Value;
        private System.Windows.Forms.Label lblFlowSensor1Key;
        private System.Windows.Forms.Label lblFlowSensor1Value;
        private System.Windows.Forms.Label lblBreakSensor1Key;
        private System.Windows.Forms.Label lblBreakSensor1Value;
        private System.Windows.Forms.Label lblFlowSensor2Key;
        private System.Windows.Forms.Label lblFlowSensor2Value;
        private System.Windows.Forms.Label lblBreakSensor2Key;
        private System.Windows.Forms.Label lblBreakSensor2Value;

        private System.Windows.Forms.Label lblTAxisKey;
        private System.Windows.Forms.Label lblTAxisValue;
        private System.Windows.Forms.Label lblPickZKey;
        private System.Windows.Forms.Label lblPickZValue;
        private System.Windows.Forms.Label lblAlignTKey;
        private System.Windows.Forms.Label lblAlignTValue;
        private System.Windows.Forms.Label lblPlaceZKey;
        private System.Windows.Forms.Label lblPlaceZValue;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogMode;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogTMinus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogStop;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogTPlus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogMove;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPickZUp;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPickZDown;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPlaceZUp;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPlaceZDown;
        private System.Windows.Forms.Label lblPickZAxis;
        private System.Windows.Forms.Label lblPlaceZAxis;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.contentLayout = new System.Windows.Forms.TableLayoutPanel();
            this.leftLayout = new System.Windows.Forms.TableLayoutPanel();
            this.centerLayout = new System.Windows.Forms.TableLayoutPanel();
            this.rightLayout = new System.Windows.Forms.TableLayoutPanel();
            this.grpOptions = new System.Windows.Forms.GroupBox();
            this.grpWait = new System.Windows.Forms.GroupBox();
            this.grpManual = new System.Windows.Forms.GroupBox();
            this.grpIo = new System.Windows.Forms.GroupBox();
            this.grpCamera = new System.Windows.Forms.GroupBox();
            this.grpJog = new System.Windows.Forms.GroupBox();
            this.grpSpeed = new System.Windows.Forms.GroupBox();
            this.optionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.waitLayout = new System.Windows.Forms.TableLayoutPanel();
            this.manualLayout = new System.Windows.Forms.TableLayoutPanel();
            this.ioLayout = new System.Windows.Forms.TableLayoutPanel();
            this.cameraPanel = new System.Windows.Forms.Panel();
            this.lblCameraInfo = new System.Windows.Forms.Label();
            this.jogLayout = new System.Windows.Forms.TableLayoutPanel();
            this.jogAxisLayout = new System.Windows.Forms.TableLayoutPanel();
            this.jogThetaLayout = new System.Windows.Forms.TableLayoutPanel();
            this.jogZLayout = new System.Windows.Forms.TableLayoutPanel();
            this.speedLayout = new System.Windows.Forms.TableLayoutPanel();
            this.trkSpeed = new System.Windows.Forms.TrackBar();
            this.lblSpeedValue = new System.Windows.Forms.Label();
            this.lblBaseStrokeKey = new System.Windows.Forms.Label();
            this.lblBaseStrokeValue = new System.Windows.Forms.Label();
            this.lblPickPositionKey = new System.Windows.Forms.Label();
            this.lblPickPositionValue = new System.Windows.Forms.Label();
            this.lblPlacePositionKey = new System.Windows.Forms.Label();
            this.lblPlacePositionValue = new System.Windows.Forms.Label();
            this.lblSequenceSettingKey = new System.Windows.Forms.Label();
            this.lblSequenceSettingValue = new System.Windows.Forms.Label();
            this.lblPickZOffsetKey = new System.Windows.Forms.Label();
            this.lblPickZOffsetValue = new System.Windows.Forms.Label();
            this.lblPlaceZOffsetKey = new System.Windows.Forms.Label();
            this.lblPlaceZOffsetValue = new System.Windows.Forms.Label();
            this.lblHeadUseKey = new System.Windows.Forms.Label();
            this.lblHeadUseValue = new System.Windows.Forms.Label();
            this.lblVacuumCheckKey = new System.Windows.Forms.Label();
            this.lblVacuumCheckValue = new System.Windows.Forms.Label();
            this.lblColletCheckKey = new System.Windows.Forms.Label();
            this.lblColletCheckValue = new System.Windows.Forms.Label();
            this.lblHeadTPowerKey = new System.Windows.Forms.Label();
            this.lblHeadTPowerValue = new System.Windows.Forms.Label();
            this.lblHeadMoveWaitKey = new System.Windows.Forms.Label();
            this.lblHeadMoveWaitValue = new System.Windows.Forms.Label();
            this.lblVacuumOnPickKey = new System.Windows.Forms.Label();
            this.lblVacuumOnPickValue = new System.Windows.Forms.Label();
            this.lblVacuumOnPlaceKey = new System.Windows.Forms.Label();
            this.lblVacuumOnPlaceValue = new System.Windows.Forms.Label();
            this.lblBlowWaitKey = new System.Windows.Forms.Label();
            this.lblBlowWaitValue = new System.Windows.Forms.Label();
            this.lblPickPlaceUpDownKey = new System.Windows.Forms.Label();
            this.lblPickPlaceUpDownValue = new System.Windows.Forms.Label();
            this.btnPickUpTest = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPick = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPickDown = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPickUp = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPlaceMove = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPlace = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPlaceDown = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPlaceUp = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.dotVacuumBlow1 = new QMC.CDT_320.Ui.Controls.IndicatorDot();
            this.dotVacuumBlow2 = new QMC.CDT_320.Ui.Controls.IndicatorDot();
            this.dotFlowSensor1 = new QMC.CDT_320.Ui.Controls.IndicatorDot();
            this.dotBreakSensor1 = new QMC.CDT_320.Ui.Controls.IndicatorDot();
            this.dotFlowSensor2 = new QMC.CDT_320.Ui.Controls.IndicatorDot();
            this.dotBreakSensor2 = new QMC.CDT_320.Ui.Controls.IndicatorDot();
            this.lblVacuumBlow1Key = new System.Windows.Forms.Label();
            this.lblVacuumBlow1Value = new System.Windows.Forms.Label();
            this.lblVacuumBlow2Key = new System.Windows.Forms.Label();
            this.lblVacuumBlow2Value = new System.Windows.Forms.Label();
            this.lblFlowSensor1Key = new System.Windows.Forms.Label();
            this.lblFlowSensor1Value = new System.Windows.Forms.Label();
            this.lblBreakSensor1Key = new System.Windows.Forms.Label();
            this.lblBreakSensor1Value = new System.Windows.Forms.Label();
            this.lblFlowSensor2Key = new System.Windows.Forms.Label();
            this.lblFlowSensor2Value = new System.Windows.Forms.Label();
            this.lblBreakSensor2Key = new System.Windows.Forms.Label();
            this.lblBreakSensor2Value = new System.Windows.Forms.Label();
            this.lblTAxisKey = new System.Windows.Forms.Label();
            this.lblTAxisValue = new System.Windows.Forms.Label();
            this.lblPickZKey = new System.Windows.Forms.Label();
            this.lblPickZValue = new System.Windows.Forms.Label();
            this.lblAlignTKey = new System.Windows.Forms.Label();
            this.lblAlignTValue = new System.Windows.Forms.Label();
            this.lblPlaceZKey = new System.Windows.Forms.Label();
            this.lblPlaceZValue = new System.Windows.Forms.Label();
            this.btnJogMode = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogTMinus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogStop = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogTPlus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogMove = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPickZUp = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPickZDown = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPlaceZUp = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPlaceZDown = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.lblPickZAxis = new System.Windows.Forms.Label();
            this.lblPlaceZAxis = new System.Windows.Forms.Label();
            this.rootLayout.SuspendLayout();
            this.contentLayout.SuspendLayout();
            this.leftLayout.SuspendLayout();
            this.centerLayout.SuspendLayout();
            this.rightLayout.SuspendLayout();
            this.grpOptions.SuspendLayout();
            this.grpWait.SuspendLayout();
            this.grpManual.SuspendLayout();
            this.grpIo.SuspendLayout();
            this.grpCamera.SuspendLayout();
            this.grpJog.SuspendLayout();
            this.grpSpeed.SuspendLayout();
            this.optionLayout.SuspendLayout();
            this.waitLayout.SuspendLayout();
            this.manualLayout.SuspendLayout();
            this.ioLayout.SuspendLayout();
            this.cameraPanel.SuspendLayout();
            this.jogLayout.SuspendLayout();
            this.jogAxisLayout.SuspendLayout();
            this.jogThetaLayout.SuspendLayout();
            this.jogZLayout.SuspendLayout();
            this.speedLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.trkSpeed)).BeginInit();
            this.SuspendLayout();
            // 
            // rootLayout
            // 
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.contentLayout, 0, 1);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Margin = new System.Windows.Forms.Padding(0);
            this.rootLayout.Name = "rootLayout";
            this.rootLayout.RowCount = 2;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Size = new System.Drawing.Size(1400, 900);
            // 
            // lblHeader
            // 
            this.lblHeader.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblHeader.ForeColor = System.Drawing.Color.White;
            this.lblHeader.Margin = new System.Windows.Forms.Padding(0);
            this.lblHeader.Name = "lblHeader";
            this.lblHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblHeader.Tag = "i18n:recipe.frontHead";
            this.lblHeader.Text = "FRONT HEAD";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // contentLayout
            // 
            this.contentLayout.ColumnCount = 3;
            this.contentLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 420F));
            this.contentLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.contentLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 170F));
            this.contentLayout.Controls.Add(this.leftLayout, 0, 0);
            this.contentLayout.Controls.Add(this.centerLayout, 1, 0);
            this.contentLayout.Controls.Add(this.rightLayout, 2, 0);
            this.contentLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.contentLayout.Margin = new System.Windows.Forms.Padding(0);
            this.contentLayout.Padding = new System.Windows.Forms.Padding(8);
            this.contentLayout.RowCount = 1;
            this.contentLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            // 
            // columns
            // 
            this.leftLayout.ColumnCount = 1;
            this.leftLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.leftLayout.Controls.Add(this.grpOptions, 0, 0);
            this.leftLayout.Controls.Add(this.grpWait, 0, 1);
            this.leftLayout.Controls.Add(this.grpManual, 0, 2);
            this.leftLayout.Controls.Add(this.grpIo, 0, 3);
            this.leftLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.leftLayout.Margin = new System.Windows.Forms.Padding(0);
            this.leftLayout.RowCount = 4;
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 340F));
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 180F));
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 230F));
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.centerLayout.ColumnCount = 1;
            this.centerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.centerLayout.Controls.Add(this.grpCamera, 0, 0);
            this.centerLayout.Controls.Add(this.grpJog, 0, 1);
            this.centerLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.centerLayout.Margin = new System.Windows.Forms.Padding(0);
            this.centerLayout.RowCount = 2;
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 62F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 38F));
            this.rightLayout.ColumnCount = 1;
            this.rightLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rightLayout.Controls.Add(this.grpSpeed, 0, 0);
            this.rightLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rightLayout.Margin = new System.Windows.Forms.Padding(0);
            this.rightLayout.RowCount = 1;
            this.rightLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            // 
            // group boxes
            // 
            this.grpOptions.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpOptions.Controls.Add(this.optionLayout);
            this.grpOptions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpOptions.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpOptions.Margin = new System.Windows.Forms.Padding(4);
            this.grpOptions.Text = "OPTION";
            this.grpWait.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpWait.Controls.Add(this.waitLayout);
            this.grpWait.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpWait.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpWait.Margin = new System.Windows.Forms.Padding(4);
            this.grpWait.Text = "WAIT TIME";
            this.grpManual.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpManual.Controls.Add(this.manualLayout);
            this.grpManual.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpManual.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpManual.Margin = new System.Windows.Forms.Padding(4);
            this.grpManual.Text = "MANUAL ACTION";
            this.grpIo.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpIo.Controls.Add(this.ioLayout);
            this.grpIo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpIo.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpIo.Margin = new System.Windows.Forms.Padding(4);
            this.grpIo.Text = "CYLINDER && I/O";
            this.grpCamera.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpCamera.Controls.Add(this.cameraPanel);
            this.grpCamera.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpCamera.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpCamera.Margin = new System.Windows.Forms.Padding(4);
            this.grpCamera.Text = "HEAD CAMERA";
            this.grpJog.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpJog.Controls.Add(this.jogLayout);
            this.grpJog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpJog.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpJog.Margin = new System.Windows.Forms.Padding(4);
            this.grpJog.Text = "JOG OPERATION";
            this.grpSpeed.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpSpeed.Controls.Add(this.speedLayout);
            this.grpSpeed.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSpeed.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpSpeed.Margin = new System.Windows.Forms.Padding(4);
            this.grpSpeed.Text = "SPEED";
            // 
            // optionLayout
            // 
            this.optionLayout.ColumnCount = 2;
            this.optionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 55F));
            this.optionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.optionLayout.Controls.Add(this.lblBaseStrokeKey, 0, 0);
            this.optionLayout.Controls.Add(this.lblBaseStrokeValue, 1, 0);
            this.optionLayout.Controls.Add(this.lblPickPositionKey, 0, 1);
            this.optionLayout.Controls.Add(this.lblPickPositionValue, 1, 1);
            this.optionLayout.Controls.Add(this.lblPlacePositionKey, 0, 2);
            this.optionLayout.Controls.Add(this.lblPlacePositionValue, 1, 2);
            this.optionLayout.Controls.Add(this.lblSequenceSettingKey, 0, 3);
            this.optionLayout.Controls.Add(this.lblSequenceSettingValue, 1, 3);
            this.optionLayout.Controls.Add(this.lblPickZOffsetKey, 0, 4);
            this.optionLayout.Controls.Add(this.lblPickZOffsetValue, 1, 4);
            this.optionLayout.Controls.Add(this.lblPlaceZOffsetKey, 0, 5);
            this.optionLayout.Controls.Add(this.lblPlaceZOffsetValue, 1, 5);
            this.optionLayout.Controls.Add(this.lblHeadUseKey, 0, 6);
            this.optionLayout.Controls.Add(this.lblHeadUseValue, 1, 6);
            this.optionLayout.Controls.Add(this.lblVacuumCheckKey, 0, 7);
            this.optionLayout.Controls.Add(this.lblVacuumCheckValue, 1, 7);
            this.optionLayout.Controls.Add(this.lblColletCheckKey, 0, 8);
            this.optionLayout.Controls.Add(this.lblColletCheckValue, 1, 8);
            this.optionLayout.Controls.Add(this.lblHeadTPowerKey, 0, 9);
            this.optionLayout.Controls.Add(this.lblHeadTPowerValue, 1, 9);
            this.optionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.optionLayout.Padding = new System.Windows.Forms.Padding(10, 18, 10, 8);
            this.optionLayout.RowCount = 10;
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            // 
            // waitLayout
            // 
            this.waitLayout.ColumnCount = 2;
            this.waitLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 55F));
            this.waitLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.waitLayout.Controls.Add(this.lblHeadMoveWaitKey, 0, 0);
            this.waitLayout.Controls.Add(this.lblHeadMoveWaitValue, 1, 0);
            this.waitLayout.Controls.Add(this.lblVacuumOnPickKey, 0, 1);
            this.waitLayout.Controls.Add(this.lblVacuumOnPickValue, 1, 1);
            this.waitLayout.Controls.Add(this.lblVacuumOnPlaceKey, 0, 2);
            this.waitLayout.Controls.Add(this.lblVacuumOnPlaceValue, 1, 2);
            this.waitLayout.Controls.Add(this.lblBlowWaitKey, 0, 3);
            this.waitLayout.Controls.Add(this.lblBlowWaitValue, 1, 3);
            this.waitLayout.Controls.Add(this.lblPickPlaceUpDownKey, 0, 4);
            this.waitLayout.Controls.Add(this.lblPickPlaceUpDownValue, 1, 4);
            this.waitLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.waitLayout.Padding = new System.Windows.Forms.Padding(10, 18, 10, 8);
            this.waitLayout.RowCount = 5;
            this.waitLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.waitLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.waitLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.waitLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.waitLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            // 
            // manualLayout
            // 
            this.manualLayout.ColumnCount = 2;
            this.manualLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.manualLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.manualLayout.Controls.Add(this.btnPickUpTest, 0, 0);
            this.manualLayout.Controls.Add(this.btnPick, 1, 0);
            this.manualLayout.Controls.Add(this.btnPickDown, 0, 1);
            this.manualLayout.Controls.Add(this.btnPickUp, 1, 1);
            this.manualLayout.Controls.Add(this.btnPlaceMove, 0, 2);
            this.manualLayout.Controls.Add(this.btnPlace, 1, 2);
            this.manualLayout.Controls.Add(this.btnPlaceDown, 0, 3);
            this.manualLayout.Controls.Add(this.btnPlaceUp, 1, 3);
            this.manualLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.manualLayout.Padding = new System.Windows.Forms.Padding(8, 18, 8, 8);
            this.manualLayout.RowCount = 4;
            this.manualLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.manualLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.manualLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.manualLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            // 
            // ioLayout
            // 
            this.ioLayout.ColumnCount = 3;
            this.ioLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.ioLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 58F));
            this.ioLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 42F));
            this.ioLayout.Controls.Add(this.dotVacuumBlow1, 0, 0);
            this.ioLayout.Controls.Add(this.lblVacuumBlow1Key, 1, 0);
            this.ioLayout.Controls.Add(this.lblVacuumBlow1Value, 2, 0);
            this.ioLayout.Controls.Add(this.dotVacuumBlow2, 0, 1);
            this.ioLayout.Controls.Add(this.lblVacuumBlow2Key, 1, 1);
            this.ioLayout.Controls.Add(this.lblVacuumBlow2Value, 2, 1);
            this.ioLayout.Controls.Add(this.dotFlowSensor1, 0, 2);
            this.ioLayout.Controls.Add(this.lblFlowSensor1Key, 1, 2);
            this.ioLayout.Controls.Add(this.lblFlowSensor1Value, 2, 2);
            this.ioLayout.Controls.Add(this.dotBreakSensor1, 0, 3);
            this.ioLayout.Controls.Add(this.lblBreakSensor1Key, 1, 3);
            this.ioLayout.Controls.Add(this.lblBreakSensor1Value, 2, 3);
            this.ioLayout.Controls.Add(this.dotFlowSensor2, 0, 4);
            this.ioLayout.Controls.Add(this.lblFlowSensor2Key, 1, 4);
            this.ioLayout.Controls.Add(this.lblFlowSensor2Value, 2, 4);
            this.ioLayout.Controls.Add(this.dotBreakSensor2, 0, 5);
            this.ioLayout.Controls.Add(this.lblBreakSensor2Key, 1, 5);
            this.ioLayout.Controls.Add(this.lblBreakSensor2Value, 2, 5);
            this.ioLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ioLayout.Padding = new System.Windows.Forms.Padding(8, 18, 8, 8);
            this.ioLayout.RowCount = 6;
            this.ioLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.ioLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.ioLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.ioLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.ioLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.ioLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            // 
            // cameraPanel
            // 
            this.cameraPanel.BackColor = System.Drawing.Color.Black;
            this.cameraPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.cameraPanel.Controls.Add(this.lblCameraInfo);
            this.cameraPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cameraPanel.Margin = new System.Windows.Forms.Padding(10);
            this.lblCameraInfo.AutoSize = true;
            this.lblCameraInfo.BackColor = System.Drawing.Color.Black;
            this.lblCameraInfo.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblCameraInfo.ForeColor = System.Drawing.Color.Lime;
            this.lblCameraInfo.Location = new System.Drawing.Point(10, 10);
            this.lblCameraInfo.Text = "HEAD\r\nW : 640\r\nH : 480\r\nX : 0\r\nY : 0\r\nT : 0";
            // 
            // jogLayout
            // 
            this.jogLayout.ColumnCount = 3;
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 36F));
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 34F));
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.jogLayout.Controls.Add(this.jogAxisLayout, 0, 0);
            this.jogLayout.Controls.Add(this.jogThetaLayout, 1, 0);
            this.jogLayout.Controls.Add(this.jogZLayout, 2, 0);
            this.jogLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.jogLayout.Padding = new System.Windows.Forms.Padding(10, 18, 10, 10);
            this.jogLayout.RowCount = 1;
            this.jogLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.jogAxisLayout.ColumnCount = 2;
            this.jogAxisLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.jogAxisLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.jogAxisLayout.Controls.Add(this.lblTAxisKey, 0, 0);
            this.jogAxisLayout.Controls.Add(this.lblTAxisValue, 1, 0);
            this.jogAxisLayout.Controls.Add(this.lblPickZKey, 0, 1);
            this.jogAxisLayout.Controls.Add(this.lblPickZValue, 1, 1);
            this.jogAxisLayout.Controls.Add(this.lblAlignTKey, 0, 2);
            this.jogAxisLayout.Controls.Add(this.lblAlignTValue, 1, 2);
            this.jogAxisLayout.Controls.Add(this.lblPlaceZKey, 0, 3);
            this.jogAxisLayout.Controls.Add(this.lblPlaceZValue, 1, 3);
            this.jogAxisLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.jogAxisLayout.RowCount = 4;
            this.jogAxisLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.jogAxisLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.jogAxisLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.jogAxisLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.jogThetaLayout.ColumnCount = 3;
            this.jogThetaLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogThetaLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.34F));
            this.jogThetaLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogThetaLayout.Controls.Add(this.btnJogMode, 1, 0);
            this.jogThetaLayout.Controls.Add(this.btnJogTMinus, 0, 1);
            this.jogThetaLayout.Controls.Add(this.btnJogStop, 1, 1);
            this.jogThetaLayout.Controls.Add(this.btnJogTPlus, 2, 1);
            this.jogThetaLayout.Controls.Add(this.btnJogMove, 1, 2);
            this.jogThetaLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.jogThetaLayout.RowCount = 3;
            this.jogThetaLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogThetaLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.34F));
            this.jogThetaLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogZLayout.ColumnCount = 2;
            this.jogZLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.jogZLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.jogZLayout.Controls.Add(this.btnPickZUp, 0, 0);
            this.jogZLayout.Controls.Add(this.btnPlaceZUp, 1, 0);
            this.jogZLayout.Controls.Add(this.lblPickZAxis, 0, 1);
            this.jogZLayout.Controls.Add(this.lblPlaceZAxis, 1, 1);
            this.jogZLayout.Controls.Add(this.btnPickZDown, 0, 2);
            this.jogZLayout.Controls.Add(this.btnPlaceZDown, 1, 2);
            this.jogZLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.jogZLayout.RowCount = 3;
            this.jogZLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.jogZLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.jogZLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            // 
            // speedLayout
            // 
            this.speedLayout.ColumnCount = 1;
            this.speedLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.speedLayout.Controls.Add(this.trkSpeed, 0, 0);
            this.speedLayout.Controls.Add(this.lblSpeedValue, 0, 1);
            this.speedLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.speedLayout.Padding = new System.Windows.Forms.Padding(12, 18, 12, 12);
            this.speedLayout.RowCount = 2;
            this.speedLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.speedLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.trkSpeed.Dock = System.Windows.Forms.DockStyle.Fill;
            this.trkSpeed.Maximum = 100;
            this.trkSpeed.Orientation = System.Windows.Forms.Orientation.Vertical;
            this.trkSpeed.TickFrequency = 10;
            this.trkSpeed.Value = 50;
            this.lblSpeedValue.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblSpeedValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSpeedValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblSpeedValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblSpeedValue.Text = "50%";
            this.lblSpeedValue.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // text
            // 
            this.lblBaseStrokeKey.Text = "BASE / STROKE SETTING";
            this.lblBaseStrokeValue.Text = "SET";
            this.lblPickPositionKey.Text = "PICK POSITION";
            this.lblPickPositionValue.Text = "SET";
            this.lblPlacePositionKey.Text = "PLACE POSITION";
            this.lblPlacePositionValue.Text = "SET";
            this.lblSequenceSettingKey.Text = "SEQUENCE SETTING";
            this.lblSequenceSettingValue.Text = "SET";
            this.lblPickZOffsetKey.Text = "PICK Z OFFSET";
            this.lblPickZOffsetValue.Text = "SET";
            this.lblPlaceZOffsetKey.Text = "PLACE Z OFFSET";
            this.lblPlaceZOffsetValue.Text = "SET";
            this.lblHeadUseKey.Text = "HEAD USE";
            this.lblHeadUseValue.Text = "ALL USE";
            this.lblVacuumCheckKey.Text = "VACUUM CHECK";
            this.lblVacuumCheckValue.Text = "ENABLE";
            this.lblColletCheckKey.Text = "COLLET CHECK";
            this.lblColletCheckValue.Text = "DISABLE";
            this.lblHeadTPowerKey.Text = "HEAD T POWER";
            this.lblHeadTPowerValue.Text = "50%";
            this.lblHeadMoveWaitKey.Text = "HEAD MOVE WAIT";
            this.lblHeadMoveWaitValue.Text = "0 ms";
            this.lblVacuumOnPickKey.Text = "VACUUM ON PICK";
            this.lblVacuumOnPickValue.Text = "40 ms";
            this.lblVacuumOnPlaceKey.Text = "VACUUM ON PLACE";
            this.lblVacuumOnPlaceValue.Text = "0 ms";
            this.lblBlowWaitKey.Text = "BLOW PICK/PLACE";
            this.lblBlowWaitValue.Text = "0 / 40 ms";
            this.lblPickPlaceUpDownKey.Text = "PICK/PLACE UP DOWN";
            this.lblPickPlaceUpDownValue.Text = "0 ms";
            this.btnPickUpTest.Text = "PICK UP TEST";
            this.btnPick.Text = "PICK";
            this.btnPickDown.Text = "PICK DOWN";
            this.btnPickUp.Text = "PICK UP";
            this.btnPlaceMove.Text = "PLACE MOVE";
            this.btnPlace.Text = "PLACE";
            this.btnPlaceDown.Text = "PLACE DOWN";
            this.btnPlaceUp.Text = "PLACE UP";
            this.lblVacuumBlow1Key.Text = "VACUUM BLOW #1";
            this.lblVacuumBlow1Value.Text = "VACUUM";
            this.lblVacuumBlow2Key.Text = "VACUUM BLOW #2";
            this.lblVacuumBlow2Value.Text = "BLOW";
            this.lblFlowSensor1Key.Text = "FLOW SENSOR #1";
            this.lblFlowSensor1Value.Text = "OFF";
            this.lblBreakSensor1Key.Text = "BREAK SENSOR #1";
            this.lblBreakSensor1Value.Text = "OFF";
            this.lblFlowSensor2Key.Text = "FLOW SENSOR #2";
            this.lblFlowSensor2Value.Text = "OFF";
            this.lblBreakSensor2Key.Text = "BREAK SENSOR #2";
            this.lblBreakSensor2Value.Text = "OFF";
            this.lblTAxisKey.Text = "T AXIS";
            this.lblTAxisValue.Text = "0 deg";
            this.lblPickZKey.Text = "PICK Z";
            this.lblPickZValue.Text = "0 um";
            this.lblAlignTKey.Text = "ALIGN T";
            this.lblAlignTValue.Text = "0 deg";
            this.lblPlaceZKey.Text = "PLACE Z";
            this.lblPlaceZValue.Text = "0 um";
            this.btnJogMode.Text = "JOG";
            this.btnJogTMinus.Text = "-T";
            this.btnJogStop.Text = "STOP";
            this.btnJogTPlus.Text = "+T";
            this.btnJogMove.Text = "MOVE";
            this.btnPickZUp.Text = "UP";
            this.btnPickZDown.Text = "DOWN";
            this.btnPlaceZUp.Text = "UP";
            this.btnPlaceZDown.Text = "DOWN";
            this.lblPickZAxis.Text = "PICK Z";
            this.lblPlaceZAxis.Text = "PLACE Z";
            // 
            // common styling
            this.dotVacuumBlow1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dotVacuumBlow1.Margin = new System.Windows.Forms.Padding(7);
            this.dotVacuumBlow1.OnColor = System.Drawing.Color.LimeGreen;
            this.dotVacuumBlow2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dotVacuumBlow2.Margin = new System.Windows.Forms.Padding(7);
            this.dotVacuumBlow2.OnColor = System.Drawing.Color.LimeGreen;
            this.dotFlowSensor1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dotFlowSensor1.Margin = new System.Windows.Forms.Padding(7);
            this.dotFlowSensor1.OnColor = System.Drawing.Color.LimeGreen;
            this.dotBreakSensor1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dotBreakSensor1.Margin = new System.Windows.Forms.Padding(7);
            this.dotBreakSensor1.OnColor = System.Drawing.Color.LimeGreen;
            this.dotFlowSensor2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dotFlowSensor2.Margin = new System.Windows.Forms.Padding(7);
            this.dotFlowSensor2.OnColor = System.Drawing.Color.LimeGreen;
            this.dotBreakSensor2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dotBreakSensor2.Margin = new System.Windows.Forms.Padding(7);
            this.dotBreakSensor2.OnColor = System.Drawing.Color.LimeGreen;
            this.lblBaseStrokeKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblBaseStrokeKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBaseStrokeKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBaseStrokeKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblPickPositionKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPickPositionKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPickPositionKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPickPositionKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblPlacePositionKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPlacePositionKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPlacePositionKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPlacePositionKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblSequenceSettingKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblSequenceSettingKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSequenceSettingKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblSequenceSettingKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblPickZOffsetKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPickZOffsetKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPickZOffsetKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPickZOffsetKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblPlaceZOffsetKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPlaceZOffsetKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPlaceZOffsetKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPlaceZOffsetKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblHeadUseKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblHeadUseKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblHeadUseKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeadUseKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblVacuumCheckKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblVacuumCheckKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblVacuumCheckKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVacuumCheckKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblColletCheckKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblColletCheckKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblColletCheckKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblColletCheckKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblHeadTPowerKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblHeadTPowerKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblHeadTPowerKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeadTPowerKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblHeadMoveWaitKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblHeadMoveWaitKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblHeadMoveWaitKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeadMoveWaitKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblVacuumOnPickKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblVacuumOnPickKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblVacuumOnPickKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVacuumOnPickKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblVacuumOnPlaceKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblVacuumOnPlaceKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblVacuumOnPlaceKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVacuumOnPlaceKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblBlowWaitKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblBlowWaitKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBlowWaitKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBlowWaitKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblPickPlaceUpDownKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPickPlaceUpDownKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPickPlaceUpDownKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPickPlaceUpDownKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblVacuumBlow1Key.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblVacuumBlow1Key.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblVacuumBlow1Key.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVacuumBlow1Key.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblVacuumBlow2Key.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblVacuumBlow2Key.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblVacuumBlow2Key.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVacuumBlow2Key.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblFlowSensor1Key.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblFlowSensor1Key.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblFlowSensor1Key.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFlowSensor1Key.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblBreakSensor1Key.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblBreakSensor1Key.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBreakSensor1Key.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBreakSensor1Key.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblFlowSensor2Key.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblFlowSensor2Key.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblFlowSensor2Key.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFlowSensor2Key.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblBreakSensor2Key.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblBreakSensor2Key.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBreakSensor2Key.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBreakSensor2Key.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblTAxisKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblTAxisKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTAxisKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTAxisKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblPickZKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPickZKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPickZKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPickZKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblAlignTKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblAlignTKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblAlignTKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAlignTKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblPlaceZKey.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPlaceZKey.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPlaceZKey.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPlaceZKey.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblPickZAxis.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPickZAxis.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPickZAxis.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPickZAxis.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblPlaceZAxis.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPlaceZAxis.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPlaceZAxis.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPlaceZAxis.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblBaseStrokeValue.BackColor = System.Drawing.Color.White;
            this.lblBaseStrokeValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBaseStrokeValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBaseStrokeValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblPickPositionValue.BackColor = System.Drawing.Color.White;
            this.lblPickPositionValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPickPositionValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPickPositionValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblPlacePositionValue.BackColor = System.Drawing.Color.White;
            this.lblPlacePositionValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPlacePositionValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPlacePositionValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblSequenceSettingValue.BackColor = System.Drawing.Color.White;
            this.lblSequenceSettingValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSequenceSettingValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblSequenceSettingValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblPickZOffsetValue.BackColor = System.Drawing.Color.White;
            this.lblPickZOffsetValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPickZOffsetValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPickZOffsetValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblPlaceZOffsetValue.BackColor = System.Drawing.Color.White;
            this.lblPlaceZOffsetValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPlaceZOffsetValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPlaceZOffsetValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblHeadUseValue.BackColor = System.Drawing.Color.White;
            this.lblHeadUseValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblHeadUseValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeadUseValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblVacuumCheckValue.BackColor = System.Drawing.Color.White;
            this.lblVacuumCheckValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblVacuumCheckValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVacuumCheckValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblColletCheckValue.BackColor = System.Drawing.Color.White;
            this.lblColletCheckValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblColletCheckValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblColletCheckValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblHeadTPowerValue.BackColor = System.Drawing.Color.White;
            this.lblHeadTPowerValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblHeadTPowerValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeadTPowerValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblHeadMoveWaitValue.BackColor = System.Drawing.Color.White;
            this.lblHeadMoveWaitValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblHeadMoveWaitValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeadMoveWaitValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblVacuumOnPickValue.BackColor = System.Drawing.Color.White;
            this.lblVacuumOnPickValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblVacuumOnPickValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVacuumOnPickValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblVacuumOnPlaceValue.BackColor = System.Drawing.Color.White;
            this.lblVacuumOnPlaceValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblVacuumOnPlaceValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVacuumOnPlaceValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblBlowWaitValue.BackColor = System.Drawing.Color.White;
            this.lblBlowWaitValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBlowWaitValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBlowWaitValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblPickPlaceUpDownValue.BackColor = System.Drawing.Color.White;
            this.lblPickPlaceUpDownValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPickPlaceUpDownValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPickPlaceUpDownValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblVacuumBlow1Value.BackColor = System.Drawing.Color.White;
            this.lblVacuumBlow1Value.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblVacuumBlow1Value.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVacuumBlow1Value.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblVacuumBlow2Value.BackColor = System.Drawing.Color.White;
            this.lblVacuumBlow2Value.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblVacuumBlow2Value.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVacuumBlow2Value.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblFlowSensor1Value.BackColor = System.Drawing.Color.White;
            this.lblFlowSensor1Value.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblFlowSensor1Value.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFlowSensor1Value.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblBreakSensor1Value.BackColor = System.Drawing.Color.White;
            this.lblBreakSensor1Value.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBreakSensor1Value.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBreakSensor1Value.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblFlowSensor2Value.BackColor = System.Drawing.Color.White;
            this.lblFlowSensor2Value.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblFlowSensor2Value.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFlowSensor2Value.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblBreakSensor2Value.BackColor = System.Drawing.Color.White;
            this.lblBreakSensor2Value.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBreakSensor2Value.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBreakSensor2Value.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblTAxisValue.BackColor = System.Drawing.Color.White;
            this.lblTAxisValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTAxisValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTAxisValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblPickZValue.BackColor = System.Drawing.Color.White;
            this.lblPickZValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPickZValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPickZValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblAlignTValue.BackColor = System.Drawing.Color.White;
            this.lblAlignTValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblAlignTValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAlignTValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblPlaceZValue.BackColor = System.Drawing.Color.White;
            this.lblPlaceZValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPlaceZValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPlaceZValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblBaseStrokeKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPickPositionKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPlacePositionKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblSequenceSettingKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPickZOffsetKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPlaceZOffsetKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblHeadUseKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblVacuumCheckKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblColletCheckKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblHeadTPowerKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblHeadMoveWaitKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblVacuumOnPickKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblVacuumOnPlaceKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblBlowWaitKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPickPlaceUpDownKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblVacuumBlow1Key.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblVacuumBlow2Key.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblFlowSensor1Key.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblBreakSensor1Key.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblFlowSensor2Key.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblBreakSensor2Key.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblTAxisKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPickZKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblAlignTKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPlaceZKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPickZAxis.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblPlaceZAxis.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblBaseStrokeValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblPickPositionValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblPlacePositionValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblSequenceSettingValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblPickZOffsetValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblPlaceZOffsetValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblHeadUseValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblVacuumCheckValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblColletCheckValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblHeadTPowerValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblHeadMoveWaitValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblVacuumOnPickValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblVacuumOnPlaceValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblBlowWaitValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblPickPlaceUpDownValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblVacuumBlow1Value.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblVacuumBlow2Value.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblFlowSensor1Value.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblBreakSensor1Value.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblFlowSensor2Value.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblBreakSensor2Value.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblTAxisValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblPickZValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblAlignTValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblPlaceZValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPickUpTest.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPickUpTest.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPickUpTest.Margin = new System.Windows.Forms.Padding(4);
            this.btnPick.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPick.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPick.Margin = new System.Windows.Forms.Padding(4);
            this.btnPickDown.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPickDown.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPickDown.Margin = new System.Windows.Forms.Padding(4);
            this.btnPickUp.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPickUp.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPickUp.Margin = new System.Windows.Forms.Padding(4);
            this.btnPlaceMove.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPlaceMove.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPlaceMove.Margin = new System.Windows.Forms.Padding(4);
            this.btnPlace.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPlace.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPlace.Margin = new System.Windows.Forms.Padding(4);
            this.btnPlaceDown.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPlaceDown.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPlaceDown.Margin = new System.Windows.Forms.Padding(4);
            this.btnPlaceUp.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPlaceUp.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPlaceUp.Margin = new System.Windows.Forms.Padding(4);
            this.btnJogMode.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogMode.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogMode.Margin = new System.Windows.Forms.Padding(4);
            this.btnJogTMinus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogTMinus.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogTMinus.Margin = new System.Windows.Forms.Padding(4);
            this.btnJogStop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogStop.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogStop.Margin = new System.Windows.Forms.Padding(4);
            this.btnJogTPlus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogTPlus.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogTPlus.Margin = new System.Windows.Forms.Padding(4);
            this.btnJogMove.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJogMove.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnJogMove.Margin = new System.Windows.Forms.Padding(4);
            this.btnPickZUp.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPickZUp.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPickZUp.Margin = new System.Windows.Forms.Padding(4);
            this.btnPickZDown.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPickZDown.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPickZDown.Margin = new System.Windows.Forms.Padding(4);
            this.btnPlaceZUp.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPlaceZUp.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPlaceZUp.Margin = new System.Windows.Forms.Padding(4);
            this.btnPlaceZDown.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPlaceZDown.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnPlaceZDown.Margin = new System.Windows.Forms.Padding(4);
            // HeadRecipePage
            // 
            this.Controls.Add(this.rootLayout);
            this.Name = "HeadRecipePage";
            this.Size = new System.Drawing.Size(1678, 900);
            this.rootLayout.ResumeLayout(false);
            this.contentLayout.ResumeLayout(false);
            this.leftLayout.ResumeLayout(false);
            this.centerLayout.ResumeLayout(false);
            this.rightLayout.ResumeLayout(false);
            this.grpOptions.ResumeLayout(false);
            this.grpWait.ResumeLayout(false);
            this.grpManual.ResumeLayout(false);
            this.grpIo.ResumeLayout(false);
            this.grpCamera.ResumeLayout(false);
            this.grpJog.ResumeLayout(false);
            this.grpSpeed.ResumeLayout(false);
            this.optionLayout.ResumeLayout(false);
            this.waitLayout.ResumeLayout(false);
            this.manualLayout.ResumeLayout(false);
            this.ioLayout.ResumeLayout(false);
            this.cameraPanel.ResumeLayout(false);
            this.cameraPanel.PerformLayout();
            this.jogLayout.ResumeLayout(false);
            this.jogAxisLayout.ResumeLayout(false);
            this.jogThetaLayout.ResumeLayout(false);
            this.jogZLayout.ResumeLayout(false);
            this.speedLayout.ResumeLayout(false);
            this.speedLayout.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.trkSpeed)).EndInit();
            this.ResumeLayout(false);
        }
    }
}


