namespace QMC.CDT_320.Ui.Pages.Recipe
{
    partial class ProjectPage
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.TableLayoutPanel contentLayout;
        private System.Windows.Forms.TableLayoutPanel leftLayout;
        private System.Windows.Forms.TableLayoutPanel listButtonLayout;
        private System.Windows.Forms.TableLayoutPanel centerLayout;
        private System.Windows.Forms.TableLayoutPanel rightLayout;
        private System.Windows.Forms.TableLayoutPanel footerLayout;
        private System.Windows.Forms.TableLayoutPanel projectInfoLayout;
        private System.Windows.Forms.TableLayoutPanel mapSettingsLayout;
        private System.Windows.Forms.TableLayoutPanel advancedLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.Label lblCurrentProject;
        private System.Windows.Forms.Label lblFooterHint;
        private System.Windows.Forms.GroupBox grpProjects;
        private System.Windows.Forms.GroupBox grpSummary;
        private System.Windows.Forms.GroupBox grpGlobal;
        private System.Windows.Forms.GroupBox grpProjectOption;
        private System.Windows.Forms.GroupBox grpMap;
        private System.Windows.Forms.GroupBox grpXml;
        private System.Windows.Forms.GroupBox grpStatus;
        private System.Windows.Forms.GroupBox grpInputMap;
        private System.Windows.Forms.GroupBox grpOutputMap;
        private System.Windows.Forms.GroupBox grpMapApproval;
        private System.Windows.Forms.ListBox listProjects;
        private System.Windows.Forms.DataGridView gridSummary;
        private System.Windows.Forms.DataGridView gridGlobal;
        private System.Windows.Forms.DataGridView gridProject;
        private System.Windows.Forms.DataGridView gridMap;
        private System.Windows.Forms.DataGridView gridXml;
        private System.Windows.Forms.DataGridView gridStatus;
        private System.Windows.Forms.DataGridView gridInputMap;
        private System.Windows.Forms.DataGridView gridOutputMap;
        private System.Windows.Forms.DataGridView gridMapApproval;
        private System.Windows.Forms.Button btnCopy;
        private System.Windows.Forms.Button btnManage;
        private System.Windows.Forms.Button btnReload;
        private System.Windows.Forms.Button btnBrowseMap;
        private System.Windows.Forms.Button btnApplyCurrent;
        private System.Windows.Forms.Button btnSaveRecipe;
        private System.Windows.Forms.TabControl tabsRecipe;
        private System.Windows.Forms.TabPage tabBasic;
        private System.Windows.Forms.TabPage tabDetails;
        private System.Windows.Forms.TabPage tabAdvanced;
        private System.Windows.Forms.ContextMenuStrip menuManagement;
        private System.Windows.Forms.ToolStripMenuItem menuNewRecipe;
        private System.Windows.Forms.ToolStripMenuItem menuDeleteRecipe;
        private System.Windows.Forms.ToolStripMenuItem menuProjectFolder;
        private System.Windows.Forms.ToolStripMenuItem menuRecipeFolder;
        private System.Windows.Forms.ToolStripMenuItem menuMapFolder;
        private System.Windows.Forms.ToolStripMenuItem menuXmlPath;
        private System.Windows.Forms.ToolStripSeparator menuFolderSeparator;
        private System.Windows.Forms.ToolStripSeparator menuAdvancedSeparator;
        private System.Windows.Forms.Timer timerSettingsMonitor;
        private System.Windows.Forms.ToolTip toolTipSettings;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.contentLayout = new System.Windows.Forms.TableLayoutPanel();
            this.leftLayout = new System.Windows.Forms.TableLayoutPanel();
            this.listButtonLayout = new System.Windows.Forms.TableLayoutPanel();
            this.centerLayout = new System.Windows.Forms.TableLayoutPanel();
            this.rightLayout = new System.Windows.Forms.TableLayoutPanel();
            this.footerLayout = new System.Windows.Forms.TableLayoutPanel();
            this.projectInfoLayout = new System.Windows.Forms.TableLayoutPanel();
            this.mapSettingsLayout = new System.Windows.Forms.TableLayoutPanel();
            this.advancedLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.lblCurrentProject = new System.Windows.Forms.Label();
            this.lblFooterHint = new System.Windows.Forms.Label();
            this.grpProjects = new System.Windows.Forms.GroupBox();
            this.grpSummary = new System.Windows.Forms.GroupBox();
            this.grpGlobal = new System.Windows.Forms.GroupBox();
            this.grpProjectOption = new System.Windows.Forms.GroupBox();
            this.grpMap = new System.Windows.Forms.GroupBox();
            this.grpXml = new System.Windows.Forms.GroupBox();
            this.grpStatus = new System.Windows.Forms.GroupBox();
            this.grpInputMap = new System.Windows.Forms.GroupBox();
            this.grpOutputMap = new System.Windows.Forms.GroupBox();
            this.grpMapApproval = new System.Windows.Forms.GroupBox();
            this.listProjects = new System.Windows.Forms.ListBox();
            this.gridSummary = new System.Windows.Forms.DataGridView();
            this.gridGlobal = new System.Windows.Forms.DataGridView();
            this.gridProject = new System.Windows.Forms.DataGridView();
            this.gridMap = new System.Windows.Forms.DataGridView();
            this.gridXml = new System.Windows.Forms.DataGridView();
            this.gridStatus = new System.Windows.Forms.DataGridView();
            this.gridInputMap = new System.Windows.Forms.DataGridView();
            this.gridOutputMap = new System.Windows.Forms.DataGridView();
            this.gridMapApproval = new System.Windows.Forms.DataGridView();
            this.btnCopy = new System.Windows.Forms.Button();
            this.btnManage = new System.Windows.Forms.Button();
            this.btnReload = new System.Windows.Forms.Button();
            this.btnBrowseMap = new System.Windows.Forms.Button();
            this.btnApplyCurrent = new System.Windows.Forms.Button();
            this.btnSaveRecipe = new System.Windows.Forms.Button();
            this.tabsRecipe = new System.Windows.Forms.TabControl();
            this.tabBasic = new System.Windows.Forms.TabPage();
            this.tabDetails = new System.Windows.Forms.TabPage();
            this.tabAdvanced = new System.Windows.Forms.TabPage();
            this.menuManagement = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.menuNewRecipe = new System.Windows.Forms.ToolStripMenuItem();
            this.menuDeleteRecipe = new System.Windows.Forms.ToolStripMenuItem();
            this.menuProjectFolder = new System.Windows.Forms.ToolStripMenuItem();
            this.menuRecipeFolder = new System.Windows.Forms.ToolStripMenuItem();
            this.menuMapFolder = new System.Windows.Forms.ToolStripMenuItem();
            this.menuXmlPath = new System.Windows.Forms.ToolStripMenuItem();
            this.menuFolderSeparator = new System.Windows.Forms.ToolStripSeparator();
            this.menuAdvancedSeparator = new System.Windows.Forms.ToolStripSeparator();
            this.timerSettingsMonitor = new System.Windows.Forms.Timer(this.components);
            this.toolTipSettings = new System.Windows.Forms.ToolTip(this.components);
            this.rootLayout.SuspendLayout();
            this.contentLayout.SuspendLayout();
            this.leftLayout.SuspendLayout();
            this.listButtonLayout.SuspendLayout();
            this.centerLayout.SuspendLayout();
            this.rightLayout.SuspendLayout();
            this.footerLayout.SuspendLayout();
            this.projectInfoLayout.SuspendLayout();
            this.mapSettingsLayout.SuspendLayout();
            this.advancedLayout.SuspendLayout();
            this.grpProjects.SuspendLayout();
            this.grpSummary.SuspendLayout();
            this.grpGlobal.SuspendLayout();
            this.grpProjectOption.SuspendLayout();
            this.grpMap.SuspendLayout();
            this.grpXml.SuspendLayout();
            this.grpStatus.SuspendLayout();
            this.grpInputMap.SuspendLayout();
            this.grpOutputMap.SuspendLayout();
            this.grpMapApproval.SuspendLayout();
            this.tabsRecipe.SuspendLayout();
            this.tabBasic.SuspendLayout();
            this.tabDetails.SuspendLayout();
            this.tabAdvanced.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridSummary)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridGlobal)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridProject)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridMap)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridXml)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridStatus)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridInputMap)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridOutputMap)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridMapApproval)).BeginInit();
            this.SuspendLayout();
            this.rootLayout.Name = "rootLayout";
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Margin = new System.Windows.Forms.Padding(4);
            this.contentLayout.Name = "contentLayout";
            this.contentLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.contentLayout.Margin = new System.Windows.Forms.Padding(4);
            this.leftLayout.Name = "leftLayout";
            this.leftLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.leftLayout.Margin = new System.Windows.Forms.Padding(4);
            this.listButtonLayout.Name = "listButtonLayout";
            this.listButtonLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.listButtonLayout.Margin = new System.Windows.Forms.Padding(4);
            this.centerLayout.Name = "centerLayout";
            this.centerLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.centerLayout.Margin = new System.Windows.Forms.Padding(4);
            this.rightLayout.Name = "rightLayout";
            this.rightLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rightLayout.Margin = new System.Windows.Forms.Padding(4);
            this.footerLayout.Name = "footerLayout";
            this.footerLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.footerLayout.Margin = new System.Windows.Forms.Padding(4);
            this.projectInfoLayout.Name = "projectInfoLayout";
            this.projectInfoLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.projectInfoLayout.Margin = new System.Windows.Forms.Padding(4);
            this.mapSettingsLayout.Name = "mapSettingsLayout";
            this.mapSettingsLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mapSettingsLayout.Margin = new System.Windows.Forms.Padding(4);
            this.advancedLayout.Name = "advancedLayout";
            this.advancedLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.advancedLayout.Margin = new System.Windows.Forms.Padding(4);
            this.lblHeader.Name = "lblHeader";
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Margin = new System.Windows.Forms.Padding(4);
            this.lblCurrentProject.Name = "lblCurrentProject";
            this.lblCurrentProject.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCurrentProject.Margin = new System.Windows.Forms.Padding(4);
            this.lblFooterHint.Name = "lblFooterHint";
            this.lblFooterHint.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFooterHint.Margin = new System.Windows.Forms.Padding(4);
            this.grpProjects.Name = "grpProjects";
            this.grpProjects.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpProjects.Margin = new System.Windows.Forms.Padding(4);
            this.grpSummary.Name = "grpSummary";
            this.grpSummary.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSummary.Margin = new System.Windows.Forms.Padding(4);
            this.grpGlobal.Name = "grpGlobal";
            this.grpGlobal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpGlobal.Margin = new System.Windows.Forms.Padding(4);
            this.grpProjectOption.Name = "grpProjectOption";
            this.grpProjectOption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpProjectOption.Margin = new System.Windows.Forms.Padding(4);
            this.grpMap.Name = "grpMap";
            this.grpMap.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpMap.Margin = new System.Windows.Forms.Padding(4);
            this.grpXml.Name = "grpXml";
            this.grpXml.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpXml.Margin = new System.Windows.Forms.Padding(4);
            this.grpStatus.Name = "grpStatus";
            this.grpStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpStatus.Margin = new System.Windows.Forms.Padding(4);
            this.grpInputMap.Name = "grpInputMap";
            this.grpInputMap.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpInputMap.Margin = new System.Windows.Forms.Padding(4);
            this.grpOutputMap.Name = "grpOutputMap";
            this.grpOutputMap.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpOutputMap.Margin = new System.Windows.Forms.Padding(4);
            this.grpMapApproval.Name = "grpMapApproval";
            this.grpMapApproval.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpMapApproval.Margin = new System.Windows.Forms.Padding(4);
            this.listProjects.Name = "listProjects";
            this.listProjects.Dock = System.Windows.Forms.DockStyle.Fill;
            this.listProjects.Margin = new System.Windows.Forms.Padding(4);
            this.gridSummary.Name = "gridSummary";
            this.gridSummary.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridSummary.Margin = new System.Windows.Forms.Padding(4);
            this.gridGlobal.Name = "gridGlobal";
            this.gridGlobal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridGlobal.Margin = new System.Windows.Forms.Padding(4);
            this.gridProject.Name = "gridProject";
            this.gridProject.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridProject.Margin = new System.Windows.Forms.Padding(4);
            this.gridMap.Name = "gridMap";
            this.gridMap.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridMap.Margin = new System.Windows.Forms.Padding(4);
            this.gridXml.Name = "gridXml";
            this.gridXml.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridXml.Margin = new System.Windows.Forms.Padding(4);
            this.gridStatus.Name = "gridStatus";
            this.gridStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridStatus.Margin = new System.Windows.Forms.Padding(4);
            this.gridInputMap.Name = "gridInputMap";
            this.gridInputMap.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridInputMap.Margin = new System.Windows.Forms.Padding(4);
            this.gridOutputMap.Name = "gridOutputMap";
            this.gridOutputMap.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridOutputMap.Margin = new System.Windows.Forms.Padding(4);
            this.gridMapApproval.Name = "gridMapApproval";
            this.gridMapApproval.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridMapApproval.Margin = new System.Windows.Forms.Padding(4);
            this.btnCopy.Name = "btnCopy";
            this.btnCopy.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnCopy.Margin = new System.Windows.Forms.Padding(4);
            this.btnManage.Name = "btnManage";
            this.btnManage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnManage.Margin = new System.Windows.Forms.Padding(4);
            this.btnReload.Name = "btnReload";
            this.btnReload.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnReload.Margin = new System.Windows.Forms.Padding(4);
            this.btnBrowseMap.Name = "btnBrowseMap";
            this.btnBrowseMap.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnBrowseMap.Margin = new System.Windows.Forms.Padding(4);
            this.btnApplyCurrent.Name = "btnApplyCurrent";
            this.btnApplyCurrent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnApplyCurrent.Margin = new System.Windows.Forms.Padding(4);
            this.btnSaveRecipe.Name = "btnSaveRecipe";
            this.btnSaveRecipe.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnSaveRecipe.Margin = new System.Windows.Forms.Padding(4);
            this.tabsRecipe.Name = "tabsRecipe";
            this.tabsRecipe.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabsRecipe.Margin = new System.Windows.Forms.Padding(4);
            this.tabBasic.Name = "tabBasic";
            this.tabBasic.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabBasic.Margin = new System.Windows.Forms.Padding(4);
            this.tabDetails.Name = "tabDetails";
            this.tabDetails.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabDetails.Margin = new System.Windows.Forms.Padding(4);
            this.tabAdvanced.Name = "tabAdvanced";
            this.tabAdvanced.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabAdvanced.Margin = new System.Windows.Forms.Padding(4);
            this.menuManagement.Name = "menuManagement";
            this.menuNewRecipe.Name = "menuNewRecipe";
            this.menuDeleteRecipe.Name = "menuDeleteRecipe";
            this.menuProjectFolder.Name = "menuProjectFolder";
            this.menuRecipeFolder.Name = "menuRecipeFolder";
            this.menuMapFolder.Name = "menuMapFolder";
            this.menuXmlPath.Name = "menuXmlPath";
            this.menuFolderSeparator.Name = "menuFolderSeparator";
            this.menuAdvancedSeparator.Name = "menuAdvancedSeparator";
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.RowCount = 4;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 62F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 64F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.lblCurrentProject, 0, 1);
            this.rootLayout.Controls.Add(this.contentLayout, 0, 2);
            this.rootLayout.Controls.Add(this.footerLayout, 0, 3);
            this.rootLayout.Padding = new System.Windows.Forms.Padding(8);
            this.rootLayout.BackColor = System.Drawing.Color.FromArgb(245, 247, 250);
            this.lblHeader.Text = "레시피 · 프로젝트";
            this.lblHeader.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblCurrentProject.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblCurrentProject.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblCurrentProject.Padding = new System.Windows.Forms.Padding(12, 0, 8, 0);
            this.lblCurrentProject.BackColor = System.Drawing.Color.FromArgb(234, 242, 248);
            this.contentLayout.ColumnCount = 2;
            this.contentLayout.RowCount = 1;
            this.contentLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 258F));
            this.contentLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.contentLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.contentLayout.Controls.Add(this.grpProjects, 0, 0);
            this.contentLayout.Controls.Add(this.tabsRecipe, 1, 0);
            this.leftLayout.ColumnCount = 1;
            this.leftLayout.RowCount = 2;
            this.leftLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.grpProjects.Controls.Add(this.leftLayout);
            this.leftLayout.Controls.Add(this.listProjects, 0, 0);
            this.leftLayout.Controls.Add(this.listButtonLayout, 0, 1);
            this.listButtonLayout.ColumnCount = 2;
            this.listButtonLayout.RowCount = 1;
            this.listButtonLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.listButtonLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.listButtonLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.listButtonLayout.Controls.Add(this.btnCopy, 0, 0);
            this.listButtonLayout.Controls.Add(this.btnManage, 1, 0);
            this.listProjects.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Regular);
            this.listProjects.IntegralHeight = false;
            this.listProjects.HorizontalScrollbar = true;
            this.tabBasic.Text = "기본 확인";
            this.tabsRecipe.Controls.Add(this.tabBasic);
            this.tabBasic.BackColor = System.Drawing.Color.FromArgb(245, 247, 250);
            this.tabDetails.Text = "파일·상태 상세";
            this.tabsRecipe.Controls.Add(this.tabDetails);
            this.tabDetails.BackColor = System.Drawing.Color.FromArgb(245, 247, 250);
            this.tabAdvanced.Text = "고급 설정";
            this.tabsRecipe.Controls.Add(this.tabAdvanced);
            this.tabAdvanced.BackColor = System.Drawing.Color.FromArgb(245, 247, 250);
            this.tabsRecipe.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.tabsRecipe.ItemSize = new System.Drawing.Size(170, 38);
            this.tabsRecipe.SizeMode = System.Windows.Forms.TabSizeMode.Fixed;
            this.tabBasic.Controls.Add(this.centerLayout);
            this.tabDetails.Controls.Add(this.rightLayout);
            this.tabAdvanced.Controls.Add(this.advancedLayout);
            this.centerLayout.ColumnCount = 1;
            this.centerLayout.RowCount = 4;
            this.centerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 230F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 155F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 48F));
            this.centerLayout.Controls.Add(this.projectInfoLayout, 0, 0);
            this.centerLayout.Controls.Add(this.mapSettingsLayout, 0, 1);
            this.centerLayout.Controls.Add(this.grpMapApproval, 0, 2);
            this.centerLayout.Controls.Add(this.btnBrowseMap, 0, 3);
            this.projectInfoLayout.ColumnCount = 2;
            this.projectInfoLayout.RowCount = 1;
            this.projectInfoLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 46F));
            this.projectInfoLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 54F));
            this.projectInfoLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.projectInfoLayout.Controls.Add(this.grpSummary, 0, 0);
            this.projectInfoLayout.Controls.Add(this.grpProjectOption, 1, 0);
            this.mapSettingsLayout.ColumnCount = 2;
            this.mapSettingsLayout.RowCount = 1;
            this.mapSettingsLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.mapSettingsLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.mapSettingsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.mapSettingsLayout.Controls.Add(this.grpInputMap, 0, 0);
            this.mapSettingsLayout.Controls.Add(this.grpOutputMap, 1, 0);
            this.rightLayout.ColumnCount = 1;
            this.rightLayout.RowCount = 2;
            this.rightLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rightLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 38F));
            this.rightLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 62F));
            this.rightLayout.Controls.Add(this.grpMap, 0, 0);
            this.rightLayout.Controls.Add(this.grpStatus, 0, 1);
            this.advancedLayout.ColumnCount = 2;
            this.advancedLayout.RowCount = 1;
            this.advancedLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 55F));
            this.advancedLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.advancedLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.advancedLayout.Controls.Add(this.grpGlobal, 0, 0);
            this.advancedLayout.Controls.Add(this.grpXml, 1, 0);
            this.grpProjects.Text = "레시피 목록";
            this.grpProjects.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.grpProjects.Padding = new System.Windows.Forms.Padding(6);
            this.grpSummary.Text = "프로젝트 정보 · 편집 가능";
            this.grpSummary.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.grpSummary.Padding = new System.Windows.Forms.Padding(6);
            this.grpProjectOption.Text = "다이 / 웨이퍼 사양 · 확인용";
            this.grpProjectOption.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.grpProjectOption.Padding = new System.Windows.Forms.Padding(6);
            this.grpInputMap.Text = "입력 맵 · 레시피 설정";
            this.grpInputMap.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.grpInputMap.Padding = new System.Windows.Forms.Padding(6);
            this.grpOutputMap.Text = "출력 맵 · 레시피 설정";
            this.grpOutputMap.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.grpOutputMap.Padding = new System.Windows.Forms.Padding(6);
            this.grpMapApproval.Text = "등록 맵 확인 · 실제 운전 조건은 시작 시 별도 검사";
            this.grpMapApproval.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.grpMapApproval.Padding = new System.Windows.Forms.Padding(6);
            this.grpMap.Text = "기준 맵 / 공정 맵 파일";
            this.grpMap.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.grpMap.Padding = new System.Windows.Forms.Padding(6);
            this.grpStatus.Text = "레시피 파일 및 사양 점검";
            this.grpStatus.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.grpStatus.Padding = new System.Windows.Forms.Padding(6);
            this.grpGlobal.Text = "기타 / 고급 설정";
            this.grpGlobal.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.grpGlobal.Padding = new System.Windows.Forms.Padding(6);
            this.grpXml.Text = "XML 추적 정보 · 고급";
            this.grpXml.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.grpXml.Padding = new System.Windows.Forms.Padding(6);
            this.grpSummary.Controls.Add(this.gridSummary);
            this.grpProjectOption.Controls.Add(this.gridProject);
            this.grpInputMap.Controls.Add(this.gridInputMap);
            this.grpOutputMap.Controls.Add(this.gridOutputMap);
            this.grpMapApproval.Controls.Add(this.gridMapApproval);
            this.grpMap.Controls.Add(this.gridMap);
            this.grpStatus.Controls.Add(this.gridStatus);
            this.grpGlobal.Controls.Add(this.gridGlobal);
            this.grpXml.Controls.Add(this.gridXml);
            this.gridSummary.AllowUserToAddRows = false;
            this.gridSummary.AllowUserToDeleteRows = false;
            this.gridSummary.AllowUserToResizeRows = false;
            this.gridSummary.RowHeadersVisible = false;
            this.gridSummary.MultiSelect = false;
            this.gridSummary.AutoGenerateColumns = false;
            this.gridSummary.BackgroundColor = System.Drawing.Color.White;
            this.gridSummary.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.gridSummary.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.gridSummary.DefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.gridSummary.DefaultCellStyle.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.gridSummary.RowTemplate.Height = 29;
            this.gridSummary.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridGlobal.AllowUserToAddRows = false;
            this.gridGlobal.AllowUserToDeleteRows = false;
            this.gridGlobal.AllowUserToResizeRows = false;
            this.gridGlobal.RowHeadersVisible = false;
            this.gridGlobal.MultiSelect = false;
            this.gridGlobal.AutoGenerateColumns = false;
            this.gridGlobal.BackgroundColor = System.Drawing.Color.White;
            this.gridGlobal.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.gridGlobal.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.gridGlobal.DefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.gridGlobal.DefaultCellStyle.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.gridGlobal.RowTemplate.Height = 28;
            this.gridGlobal.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridProject.AllowUserToAddRows = false;
            this.gridProject.AllowUserToDeleteRows = false;
            this.gridProject.AllowUserToResizeRows = false;
            this.gridProject.RowHeadersVisible = false;
            this.gridProject.MultiSelect = false;
            this.gridProject.AutoGenerateColumns = false;
            this.gridProject.BackgroundColor = System.Drawing.Color.White;
            this.gridProject.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.gridProject.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.gridProject.DefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.gridProject.DefaultCellStyle.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.gridProject.RowTemplate.Height = 29;
            this.gridProject.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridProject.ReadOnly = true;
            this.gridProject.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(226, 237, 244);
            this.gridProject.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.gridMap.AllowUserToAddRows = false;
            this.gridMap.AllowUserToDeleteRows = false;
            this.gridMap.AllowUserToResizeRows = false;
            this.gridMap.RowHeadersVisible = false;
            this.gridMap.MultiSelect = false;
            this.gridMap.AutoGenerateColumns = false;
            this.gridMap.BackgroundColor = System.Drawing.Color.White;
            this.gridMap.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.gridMap.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.gridMap.DefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.gridMap.DefaultCellStyle.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.gridMap.RowTemplate.Height = 28;
            this.gridMap.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridMap.ReadOnly = true;
            this.gridXml.AllowUserToAddRows = false;
            this.gridXml.AllowUserToDeleteRows = false;
            this.gridXml.AllowUserToResizeRows = false;
            this.gridXml.RowHeadersVisible = false;
            this.gridXml.MultiSelect = false;
            this.gridXml.AutoGenerateColumns = false;
            this.gridXml.BackgroundColor = System.Drawing.Color.White;
            this.gridXml.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.gridXml.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.gridXml.DefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.gridXml.DefaultCellStyle.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.gridXml.RowTemplate.Height = 28;
            this.gridXml.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridStatus.AllowUserToAddRows = false;
            this.gridStatus.AllowUserToDeleteRows = false;
            this.gridStatus.AllowUserToResizeRows = false;
            this.gridStatus.RowHeadersVisible = false;
            this.gridStatus.MultiSelect = false;
            this.gridStatus.AutoGenerateColumns = false;
            this.gridStatus.BackgroundColor = System.Drawing.Color.White;
            this.gridStatus.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.gridStatus.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.gridStatus.DefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.gridStatus.DefaultCellStyle.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.gridStatus.RowTemplate.Height = 28;
            this.gridStatus.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridStatus.ReadOnly = true;
            this.gridInputMap.AllowUserToAddRows = false;
            this.gridInputMap.AllowUserToDeleteRows = false;
            this.gridInputMap.AllowUserToResizeRows = false;
            this.gridInputMap.RowHeadersVisible = false;
            this.gridInputMap.MultiSelect = false;
            this.gridInputMap.AutoGenerateColumns = false;
            this.gridInputMap.BackgroundColor = System.Drawing.Color.White;
            this.gridInputMap.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.gridInputMap.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.gridInputMap.DefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.gridInputMap.DefaultCellStyle.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.gridInputMap.RowTemplate.Height = 29;
            this.gridInputMap.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridInputMap.ReadOnly = true;
            this.gridInputMap.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(226, 237, 244);
            this.gridInputMap.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.gridOutputMap.AllowUserToAddRows = false;
            this.gridOutputMap.AllowUserToDeleteRows = false;
            this.gridOutputMap.AllowUserToResizeRows = false;
            this.gridOutputMap.RowHeadersVisible = false;
            this.gridOutputMap.MultiSelect = false;
            this.gridOutputMap.AutoGenerateColumns = false;
            this.gridOutputMap.BackgroundColor = System.Drawing.Color.White;
            this.gridOutputMap.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.gridOutputMap.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.gridOutputMap.DefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.gridOutputMap.DefaultCellStyle.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.gridOutputMap.RowTemplate.Height = 29;
            this.gridOutputMap.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridOutputMap.ReadOnly = true;
            this.gridOutputMap.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(226, 237, 244);
            this.gridOutputMap.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.gridMapApproval.AllowUserToAddRows = false;
            this.gridMapApproval.AllowUserToDeleteRows = false;
            this.gridMapApproval.AllowUserToResizeRows = false;
            this.gridMapApproval.RowHeadersVisible = false;
            this.gridMapApproval.MultiSelect = false;
            this.gridMapApproval.AutoGenerateColumns = false;
            this.gridMapApproval.BackgroundColor = System.Drawing.Color.White;
            this.gridMapApproval.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.gridMapApproval.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.gridMapApproval.DefaultCellStyle.Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.gridMapApproval.DefaultCellStyle.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.gridMapApproval.RowTemplate.Height = 28;
            this.gridMapApproval.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridMapApproval.ReadOnly = true;
            this.gridMapApproval.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(226, 237, 244);
            this.gridMapApproval.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.footerLayout.ColumnCount = 4;
            this.footerLayout.RowCount = 1;
            this.footerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.footerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 140F));
            this.footerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 200F));
            this.footerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 250F));
            this.footerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.footerLayout.Controls.Add(this.lblFooterHint, 0, 0);
            this.footerLayout.Controls.Add(this.btnReload, 1, 0);
            this.footerLayout.Controls.Add(this.btnSaveRecipe, 2, 0);
            this.footerLayout.Controls.Add(this.btnApplyCurrent, 3, 0);
            this.lblFooterHint.Text = "프로젝트 저장과 장비 적용은 별도입니다.";
            this.lblFooterHint.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Regular);
            this.lblFooterHint.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCopy.Text = "레시피 복사";
            this.btnCopy.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.btnCopy.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCopy.UseVisualStyleBackColor = false;
            this.btnCopy.BackColor = System.Drawing.Color.FromArgb(246, 248, 250);
            this.btnCopy.ForeColor = System.Drawing.Color.Black;
            this.btnCopy.Click += new System.EventHandler(this.btnCopy_Click);
            this.btnManage.Text = "관리 ▾";
            this.btnManage.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.btnManage.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnManage.UseVisualStyleBackColor = false;
            this.btnManage.BackColor = System.Drawing.Color.FromArgb(246, 248, 250);
            this.btnManage.ForeColor = System.Drawing.Color.Black;
            this.btnManage.Click += new System.EventHandler(this.btnManage_Click);
            this.btnReload.Text = "새로고침";
            this.btnReload.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.btnReload.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReload.UseVisualStyleBackColor = false;
            this.btnReload.BackColor = System.Drawing.Color.FromArgb(246, 248, 250);
            this.btnReload.ForeColor = System.Drawing.Color.Black;
            this.btnReload.Click += new System.EventHandler(this.btnReload_Click);
            this.btnSaveRecipe.Text = "프로젝트 정보 저장";
            this.btnSaveRecipe.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.btnSaveRecipe.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSaveRecipe.UseVisualStyleBackColor = false;
            this.btnSaveRecipe.BackColor = System.Drawing.Color.FromArgb(64, 79, 96);
            this.btnSaveRecipe.ForeColor = System.Drawing.Color.White;
            this.btnSaveRecipe.Click += new System.EventHandler(this.btnSaveRecipe_Click);
            this.btnApplyCurrent.Text = "선택 레시피 장비 적용";
            this.btnApplyCurrent.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.btnApplyCurrent.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnApplyCurrent.UseVisualStyleBackColor = false;
            this.btnApplyCurrent.BackColor = System.Drawing.Color.FromArgb(234, 86, 24);
            this.btnApplyCurrent.ForeColor = System.Drawing.Color.White;
            this.btnApplyCurrent.Click += new System.EventHandler(this.btnApplyCurrent_Click);
            this.btnBrowseMap.Text = "웨이퍼·맵 설정 열기";
            this.btnBrowseMap.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.btnBrowseMap.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBrowseMap.UseVisualStyleBackColor = false;
            this.btnBrowseMap.BackColor = System.Drawing.Color.FromArgb(38, 101, 125);
            this.btnBrowseMap.ForeColor = System.Drawing.Color.White;
            this.btnBrowseMap.Click += new System.EventHandler(this.btnBrowseMap_Click);
            this.menuManagement.Items.Add(this.menuNewRecipe);
            this.menuNewRecipe.Text = "기본 레시피 생성…";
            this.menuNewRecipe.Click += new System.EventHandler(this.menuNewRecipe_Click);
            this.menuManagement.Items.Add(this.menuDeleteRecipe);
            this.menuDeleteRecipe.Text = "선택 레시피 삭제…";
            this.menuDeleteRecipe.Click += new System.EventHandler(this.menuDeleteRecipe_Click);
            this.menuManagement.Items.Add(this.menuFolderSeparator);
            this.menuManagement.Items.Add(this.menuProjectFolder);
            this.menuProjectFolder.Text = "전체 레시피 폴더 열기";
            this.menuProjectFolder.Click += new System.EventHandler(this.menuProjectFolder_Click);
            this.menuManagement.Items.Add(this.menuRecipeFolder);
            this.menuRecipeFolder.Text = "선택 레시피 폴더 열기";
            this.menuRecipeFolder.Click += new System.EventHandler(this.menuRecipeFolder_Click);
            this.menuManagement.Items.Add(this.menuMapFolder);
            this.menuMapFolder.Text = "선택 맵 폴더 열기";
            this.menuMapFolder.Click += new System.EventHandler(this.menuMapFolder_Click);
            this.menuManagement.Items.Add(this.menuAdvancedSeparator);
            this.menuManagement.Items.Add(this.menuXmlPath);
            this.menuXmlPath.Text = "고급: XML 저장 경로 선택…";
            this.menuXmlPath.Click += new System.EventHandler(this.menuXmlPath_Click);
            this.menuManagement.Opening += new System.ComponentModel.CancelEventHandler(this.menuManagement_Opening);
            this.listProjects.SelectedIndexChanged += new System.EventHandler(this.listProjects_SelectedIndexChanged);
            this.gridSummary.CellValueChanged += new System.Windows.Forms.DataGridViewCellEventHandler(this.gridProjectEdit_CellValueChanged);
            this.gridGlobal.CellValueChanged += new System.Windows.Forms.DataGridViewCellEventHandler(this.gridProjectEdit_CellValueChanged);
            this.gridXml.CellValueChanged += new System.Windows.Forms.DataGridViewCellEventHandler(this.gridProjectEdit_CellValueChanged);
            this.timerSettingsMonitor.Interval = 2000;
            this.timerSettingsMonitor.Tick += new System.EventHandler(this.timerSettingsMonitor_Tick);
            this.toolTipSettings.AutoPopDelay = 20000;
            this.toolTipSettings.ShowAlways = true;
            this.toolTipSettings.SetToolTip(this.btnCopy, "현재 화면의 프로젝트 정보와 기존 장치별 레시피·맵 파일을 새 이름으로 복사합니다. 복사 후 장비 적용은 별도로 진행하세요.");
            this.toolTipSettings.SetToolTip(this.btnManage, "기본 생성, 삭제, 폴더 열기, 고급 XML 경로 기능을 모았습니다.");
            this.toolTipSettings.SetToolTip(this.btnBrowseMap, "현재 선택한 레시피와 장비 적용 레시피가 같을 때 웨이퍼 사양 화면을 엽니다. 이 버튼이 레시피를 자동 적용하지는 않습니다.");
            this.toolTipSettings.SetToolTip(this.grpSummary, "맵 항목은 선택 레시피의 저장값을 읽기 전용으로 표시합니다. 항목명이나 값 위에 마우스를 올리면 변경 위치와 방법을 안내합니다.");
            this.toolTipSettings.SetToolTip(this.lblCurrentProject, "선택 레시피와 현재 장비에 적용 중인 레시피를 구분합니다. 목록 선택만으로 장비 레시피가 바뀌지 않습니다.");
            this.toolTipSettings.SetToolTip(this.btnReload, "선택 레시피의 저장값을 다시 불러옵니다. 이 화면에서 저장하지 않은 편집값은 사라집니다.");
            this.toolTipSettings.SetToolTip(this.btnSaveRecipe, "이 화면에서 편집한 프로젝트 정보를 파일에 저장합니다. 장비 적용은 [선택 레시피 장비 적용]에서 진행합니다.");
            this.toolTipSettings.SetToolTip(this.btnApplyCurrent, "선택 레시피를 검증한 뒤 장비에 적용하고 저장합니다. 다른 레시피로 변경할 때는 기존 자재 초기화 확인과 인터락을 따릅니다.");
            this.toolTipSettings.SetToolTip(this.grpMapApproval, "저장된 등록 맵의 지원 여부·사양·승인을 확인합니다. 원격 입력 맵은 실제 수신 후 검사합니다. 자재·인터락·운전 준비 완료를 뜻하지 않습니다.");
            this.Controls.Add(this.rootLayout);
            this.Name = "ProjectPage";
            this.Size = new System.Drawing.Size(1678, 900);
            ((System.ComponentModel.ISupportInitialize)(this.gridSummary)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridGlobal)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridProject)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridMap)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridXml)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridStatus)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridInputMap)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridOutputMap)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridMapApproval)).EndInit();
            this.tabAdvanced.ResumeLayout(false);
            this.tabDetails.ResumeLayout(false);
            this.tabBasic.ResumeLayout(false);
            this.tabsRecipe.ResumeLayout(false);
            this.grpMapApproval.ResumeLayout(false);
            this.grpOutputMap.ResumeLayout(false);
            this.grpInputMap.ResumeLayout(false);
            this.grpStatus.ResumeLayout(false);
            this.grpXml.ResumeLayout(false);
            this.grpMap.ResumeLayout(false);
            this.grpProjectOption.ResumeLayout(false);
            this.grpGlobal.ResumeLayout(false);
            this.grpSummary.ResumeLayout(false);
            this.grpProjects.ResumeLayout(false);
            this.advancedLayout.ResumeLayout(false);
            this.mapSettingsLayout.ResumeLayout(false);
            this.projectInfoLayout.ResumeLayout(false);
            this.footerLayout.ResumeLayout(false);
            this.rightLayout.ResumeLayout(false);
            this.centerLayout.ResumeLayout(false);
            this.listButtonLayout.ResumeLayout(false);
            this.leftLayout.ResumeLayout(false);
            this.contentLayout.ResumeLayout(false);
            this.rootLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
