namespace QMC.CDT_320.Ui.Pages.Recipe
{
    partial class StageRecipePage
    {
        private System.ComponentModel.IContainer components = null;

        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.TableLayoutPanel contentLayout;
        private System.Windows.Forms.TableLayoutPanel leftLayout;
        private System.Windows.Forms.TableLayoutPanel centerLayout;
        private System.Windows.Forms.TableLayoutPanel rightLayout;
        private System.Windows.Forms.GroupBox grpOptions;
        private System.Windows.Forms.GroupBox grpWait;
        private System.Windows.Forms.GroupBox grpManual;
        private System.Windows.Forms.GroupBox grpIo;
        private System.Windows.Forms.GroupBox grpVision;
        private System.Windows.Forms.GroupBox grpJog;
        private System.Windows.Forms.GroupBox grpSpeed;
        private System.Windows.Forms.TableLayoutPanel optionLayout;
        private System.Windows.Forms.TableLayoutPanel waitLayout;
        private System.Windows.Forms.TableLayoutPanel manualLayout;
        private System.Windows.Forms.TableLayoutPanel ioLayout;
        private System.Windows.Forms.Panel visionPanel;
        private System.Windows.Forms.Label lblVisionInfo;
        private System.Windows.Forms.TableLayoutPanel jogLayout;
        private System.Windows.Forms.TableLayoutPanel jogAxisLayout;
        private System.Windows.Forms.TableLayoutPanel jogXyLayout;
        private System.Windows.Forms.TableLayoutPanel jogZLayout;
        private System.Windows.Forms.TableLayoutPanel speedLayout;
        private System.Windows.Forms.TrackBar trkSpeed;
        private System.Windows.Forms.Label lblSpeedValue;

        private System.Windows.Forms.Label lblLoadingPositionKey;
        private System.Windows.Forms.Label lblLoadingPositionValue;
        private System.Windows.Forms.Label lblCenterPositionKey;
        private System.Windows.Forms.Label lblCenterPositionValue;
        private System.Windows.Forms.Label lblNeedlePositionKey;
        private System.Windows.Forms.Label lblNeedlePositionValue;
        private System.Windows.Forms.Label lblTestBedPositionKey;
        private System.Windows.Forms.Label lblTestBedPositionValue;
        private System.Windows.Forms.Label lblBarcodePositionKey;
        private System.Windows.Forms.Label lblBarcodePositionValue;
        private System.Windows.Forms.Label lblVisionAlignKey;
        private System.Windows.Forms.Label lblVisionAlignValue;
        private System.Windows.Forms.Label lblWorkRadiusKey;
        private System.Windows.Forms.Label lblWorkRadiusValue;
        private System.Windows.Forms.Label lblFirstDiePositionKey;
        private System.Windows.Forms.Label lblFirstDiePositionValue;
        private System.Windows.Forms.Label lblNeedleMeasurePositionKey;
        private System.Windows.Forms.Label lblNeedleMeasurePositionValue;

        private System.Windows.Forms.Label lblNeedleUpWaitKey;
        private System.Windows.Forms.Label lblNeedleUpWaitValue;
        private System.Windows.Forms.Label lblVacuumOnWaitKey;
        private System.Windows.Forms.Label lblVacuumOnWaitValue;
        private System.Windows.Forms.Label lblNeedleDownWaitKey;
        private System.Windows.Forms.Label lblNeedleDownWaitValue;
        private System.Windows.Forms.Label lblVacuumOffWaitKey;
        private System.Windows.Forms.Label lblVacuumOffWaitValue;
        private System.Windows.Forms.Label lblMovingWaitKey;
        private System.Windows.Forms.Label lblMovingWaitValue;

        private QMC.CDT_320.Ui.Controls.ActionButton btnLoadingMove;
        private QMC.CDT_320.Ui.Controls.ActionButton btnCenterMove;
        private QMC.CDT_320.Ui.Controls.ActionButton btnBarcodeMove;
        private QMC.CDT_320.Ui.Controls.ActionButton btnFirstDieMove;
        private QMC.CDT_320.Ui.Controls.ActionButton btnPickUpTest;
        private QMC.CDT_320.Ui.Controls.ActionButton btnNeedleUpMove;
        private QMC.CDT_320.Ui.Controls.ActionButton btnNeedleDownMove;
        private QMC.CDT_320.Ui.Controls.ActionButton btnNeedleReadyMove;
        private QMC.CDT_320.Ui.Controls.ActionButton btnNeedleBlockReady;
        private QMC.CDT_320.Ui.Controls.ActionButton btnNeedleBlockWork;
        private QMC.CDT_320.Ui.Controls.ActionButton btnAutoSettingMove;
        private QMC.CDT_320.Ui.Controls.ActionButton btnInputConversion;
        private QMC.CDT_320.Ui.Controls.ActionButton btnExpandWorkMove;

        private QMC.CDT_320.Ui.Controls.IndicatorDot dotNeedleVacuum;
        private QMC.CDT_320.Ui.Controls.IndicatorDot dotRingSensor;
        private QMC.CDT_320.Ui.Controls.IndicatorDot dotExpandCylinder;
        private QMC.CDT_320.Ui.Controls.IndicatorDot dotNeedleBlock;
        private System.Windows.Forms.Label lblNeedleVacuumKey;
        private System.Windows.Forms.Label lblNeedleVacuumValue;
        private System.Windows.Forms.Label lblRingSensorKey;
        private System.Windows.Forms.Label lblRingSensorValue;
        private System.Windows.Forms.Label lblExpandCylinderKey;
        private System.Windows.Forms.Label lblExpandCylinderValue;
        private System.Windows.Forms.Label lblNeedleBlockKey;
        private System.Windows.Forms.Label lblNeedleBlockValue;

        private System.Windows.Forms.Label lblAxisXKey;
        private System.Windows.Forms.Label lblAxisXValue;
        private System.Windows.Forms.Label lblAxisYKey;
        private System.Windows.Forms.Label lblAxisYValue;
        private System.Windows.Forms.Label lblAxisTKey;
        private System.Windows.Forms.Label lblAxisTValue;
        private System.Windows.Forms.Label lblExpandZKey;
        private System.Windows.Forms.Label lblExpandZValue;
        private System.Windows.Forms.Label lblNeedleZKey;
        private System.Windows.Forms.Label lblNeedleZValue;
        private System.Windows.Forms.Label lblNeedleBlockZKey;
        private System.Windows.Forms.Label lblNeedleBlockZValue;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogYPlus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogXMinus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogStop;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogXPlus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogYMinus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogTMinus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnJogTPlus;
        private QMC.CDT_320.Ui.Controls.ActionButton btnExpandUp;
        private QMC.CDT_320.Ui.Controls.ActionButton btnExpandDown;
        private QMC.CDT_320.Ui.Controls.ActionButton btnNeedleUp;
        private QMC.CDT_320.Ui.Controls.ActionButton btnNeedleDown;
        private QMC.CDT_320.Ui.Controls.ActionButton btnBlockUp;
        private QMC.CDT_320.Ui.Controls.ActionButton btnBlockDown;
        private System.Windows.Forms.Label lblExpandAxis;
        private System.Windows.Forms.Label lblNeedleAxis;
        private System.Windows.Forms.Label lblBlockAxis;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.contentLayout = new System.Windows.Forms.TableLayoutPanel();
            this.leftLayout = new System.Windows.Forms.TableLayoutPanel();
            this.centerLayout = new System.Windows.Forms.TableLayoutPanel();
            this.rightLayout = new System.Windows.Forms.TableLayoutPanel();
            this.grpOptions = new System.Windows.Forms.GroupBox();
            this.grpWait = new System.Windows.Forms.GroupBox();
            this.grpManual = new System.Windows.Forms.GroupBox();
            this.grpIo = new System.Windows.Forms.GroupBox();
            this.grpVision = new System.Windows.Forms.GroupBox();
            this.grpJog = new System.Windows.Forms.GroupBox();
            this.grpSpeed = new System.Windows.Forms.GroupBox();
            this.optionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.waitLayout = new System.Windows.Forms.TableLayoutPanel();
            this.manualLayout = new System.Windows.Forms.TableLayoutPanel();
            this.ioLayout = new System.Windows.Forms.TableLayoutPanel();
            this.visionPanel = new System.Windows.Forms.Panel();
            this.lblVisionInfo = new System.Windows.Forms.Label();
            this.jogLayout = new System.Windows.Forms.TableLayoutPanel();
            this.jogAxisLayout = new System.Windows.Forms.TableLayoutPanel();
            this.jogXyLayout = new System.Windows.Forms.TableLayoutPanel();
            this.jogZLayout = new System.Windows.Forms.TableLayoutPanel();
            this.speedLayout = new System.Windows.Forms.TableLayoutPanel();
            this.trkSpeed = new System.Windows.Forms.TrackBar();
            this.lblSpeedValue = new System.Windows.Forms.Label();
            this.lblLoadingPositionKey = new System.Windows.Forms.Label();
            this.lblLoadingPositionValue = new System.Windows.Forms.Label();
            this.lblCenterPositionKey = new System.Windows.Forms.Label();
            this.lblCenterPositionValue = new System.Windows.Forms.Label();
            this.lblNeedlePositionKey = new System.Windows.Forms.Label();
            this.lblNeedlePositionValue = new System.Windows.Forms.Label();
            this.lblTestBedPositionKey = new System.Windows.Forms.Label();
            this.lblTestBedPositionValue = new System.Windows.Forms.Label();
            this.lblBarcodePositionKey = new System.Windows.Forms.Label();
            this.lblBarcodePositionValue = new System.Windows.Forms.Label();
            this.lblVisionAlignKey = new System.Windows.Forms.Label();
            this.lblVisionAlignValue = new System.Windows.Forms.Label();
            this.lblWorkRadiusKey = new System.Windows.Forms.Label();
            this.lblWorkRadiusValue = new System.Windows.Forms.Label();
            this.lblFirstDiePositionKey = new System.Windows.Forms.Label();
            this.lblFirstDiePositionValue = new System.Windows.Forms.Label();
            this.lblNeedleMeasurePositionKey = new System.Windows.Forms.Label();
            this.lblNeedleMeasurePositionValue = new System.Windows.Forms.Label();
            this.lblNeedleUpWaitKey = new System.Windows.Forms.Label();
            this.lblNeedleUpWaitValue = new System.Windows.Forms.Label();
            this.lblVacuumOnWaitKey = new System.Windows.Forms.Label();
            this.lblVacuumOnWaitValue = new System.Windows.Forms.Label();
            this.lblNeedleDownWaitKey = new System.Windows.Forms.Label();
            this.lblNeedleDownWaitValue = new System.Windows.Forms.Label();
            this.lblVacuumOffWaitKey = new System.Windows.Forms.Label();
            this.lblVacuumOffWaitValue = new System.Windows.Forms.Label();
            this.lblMovingWaitKey = new System.Windows.Forms.Label();
            this.lblMovingWaitValue = new System.Windows.Forms.Label();
            this.btnLoadingMove = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnCenterMove = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnBarcodeMove = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnFirstDieMove = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnPickUpTest = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnNeedleUpMove = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnNeedleDownMove = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnNeedleReadyMove = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnNeedleBlockReady = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnNeedleBlockWork = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnAutoSettingMove = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnInputConversion = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnExpandWorkMove = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.dotNeedleVacuum = new QMC.CDT_320.Ui.Controls.IndicatorDot();
            this.dotRingSensor = new QMC.CDT_320.Ui.Controls.IndicatorDot();
            this.dotExpandCylinder = new QMC.CDT_320.Ui.Controls.IndicatorDot();
            this.dotNeedleBlock = new QMC.CDT_320.Ui.Controls.IndicatorDot();
            this.lblNeedleVacuumKey = new System.Windows.Forms.Label();
            this.lblNeedleVacuumValue = new System.Windows.Forms.Label();
            this.lblRingSensorKey = new System.Windows.Forms.Label();
            this.lblRingSensorValue = new System.Windows.Forms.Label();
            this.lblExpandCylinderKey = new System.Windows.Forms.Label();
            this.lblExpandCylinderValue = new System.Windows.Forms.Label();
            this.lblNeedleBlockKey = new System.Windows.Forms.Label();
            this.lblNeedleBlockValue = new System.Windows.Forms.Label();
            this.lblAxisXKey = new System.Windows.Forms.Label();
            this.lblAxisXValue = new System.Windows.Forms.Label();
            this.lblAxisYKey = new System.Windows.Forms.Label();
            this.lblAxisYValue = new System.Windows.Forms.Label();
            this.lblAxisTKey = new System.Windows.Forms.Label();
            this.lblAxisTValue = new System.Windows.Forms.Label();
            this.lblExpandZKey = new System.Windows.Forms.Label();
            this.lblExpandZValue = new System.Windows.Forms.Label();
            this.lblNeedleZKey = new System.Windows.Forms.Label();
            this.lblNeedleZValue = new System.Windows.Forms.Label();
            this.lblNeedleBlockZKey = new System.Windows.Forms.Label();
            this.lblNeedleBlockZValue = new System.Windows.Forms.Label();
            this.btnJogYPlus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogXMinus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogStop = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogXPlus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogYMinus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogTMinus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnJogTPlus = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnExpandUp = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnExpandDown = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnNeedleUp = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnNeedleDown = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnBlockUp = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnBlockDown = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.lblExpandAxis = new System.Windows.Forms.Label();
            this.lblNeedleAxis = new System.Windows.Forms.Label();
            this.lblBlockAxis = new System.Windows.Forms.Label();
            this.rootLayout.SuspendLayout();
            this.contentLayout.SuspendLayout();
            this.leftLayout.SuspendLayout();
            this.centerLayout.SuspendLayout();
            this.rightLayout.SuspendLayout();
            this.grpOptions.SuspendLayout();
            this.grpWait.SuspendLayout();
            this.grpManual.SuspendLayout();
            this.grpIo.SuspendLayout();
            this.grpVision.SuspendLayout();
            this.grpJog.SuspendLayout();
            this.grpSpeed.SuspendLayout();
            this.optionLayout.SuspendLayout();
            this.waitLayout.SuspendLayout();
            this.manualLayout.SuspendLayout();
            this.ioLayout.SuspendLayout();
            this.visionPanel.SuspendLayout();
            this.jogLayout.SuspendLayout();
            this.jogAxisLayout.SuspendLayout();
            this.jogXyLayout.SuspendLayout();
            this.jogZLayout.SuspendLayout();
            this.speedLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.trkSpeed)).BeginInit();
            this.SuspendLayout();
            // 
            // rootLayout
            // 
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.contentLayout, 0, 1);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Margin = new System.Windows.Forms.Padding(0);
            this.rootLayout.Name = "rootLayout";
            this.rootLayout.RowCount = 2;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Size = new System.Drawing.Size(1400, 900);
            this.rootLayout.TabIndex = 0;
            // 
            // lblHeader
            // 
            this.lblHeader.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblHeader.ForeColor = System.Drawing.Color.White;
            this.lblHeader.Margin = new System.Windows.Forms.Padding(0);
            this.lblHeader.Name = "lblHeader";
            this.lblHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblHeader.Size = new System.Drawing.Size(1400, 30);
            this.lblHeader.TabIndex = 0;
            this.lblHeader.Tag = "i18n:recipe.inputStage";
            this.lblHeader.Text = "INPUT STAGE";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // contentLayout
            // 
            this.contentLayout.ColumnCount = 3;
            this.contentLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 420F));
            this.contentLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.contentLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 170F));
            this.contentLayout.Controls.Add(this.leftLayout, 0, 0);
            this.contentLayout.Controls.Add(this.centerLayout, 1, 0);
            this.contentLayout.Controls.Add(this.rightLayout, 2, 0);
            this.contentLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.contentLayout.Margin = new System.Windows.Forms.Padding(0);
            this.contentLayout.Name = "contentLayout";
            this.contentLayout.Padding = new System.Windows.Forms.Padding(8);
            this.contentLayout.RowCount = 1;
            this.contentLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.contentLayout.Size = new System.Drawing.Size(1400, 870);
            this.contentLayout.TabIndex = 1;
            // 
            // column layouts
            // 
            this.leftLayout.ColumnCount = 1;
            this.leftLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.leftLayout.Controls.Add(this.grpOptions, 0, 0);
            this.leftLayout.Controls.Add(this.grpWait, 0, 1);
            this.leftLayout.Controls.Add(this.grpManual, 0, 2);
            this.leftLayout.Controls.Add(this.grpIo, 0, 3);
            this.leftLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.leftLayout.Margin = new System.Windows.Forms.Padding(0);
            this.leftLayout.Name = "leftLayout";
            this.leftLayout.RowCount = 4;
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 340F));
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 300F));
            this.leftLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.centerLayout.ColumnCount = 1;
            this.centerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.centerLayout.Controls.Add(this.grpVision, 0, 0);
            this.centerLayout.Controls.Add(this.grpJog, 0, 1);
            this.centerLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.centerLayout.Margin = new System.Windows.Forms.Padding(0);
            this.centerLayout.Name = "centerLayout";
            this.centerLayout.RowCount = 2;
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 62F));
            this.centerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 38F));
            this.rightLayout.ColumnCount = 1;
            this.rightLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rightLayout.Controls.Add(this.grpSpeed, 0, 0);
            this.rightLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rightLayout.Margin = new System.Windows.Forms.Padding(0);
            this.rightLayout.Name = "rightLayout";
            this.rightLayout.RowCount = 1;
            this.rightLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            // 
            // group boxes
            // 
            this.grpOptions.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpOptions.Controls.Add(this.optionLayout);
            this.grpOptions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpOptions.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpOptions.Margin = new System.Windows.Forms.Padding(4);
            this.grpOptions.Name = "grpOptions";
            this.grpOptions.TabStop = false;
            this.grpOptions.Text = "OPTION";
            this.grpWait.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpWait.Controls.Add(this.waitLayout);
            this.grpWait.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpWait.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpWait.Margin = new System.Windows.Forms.Padding(4);
            this.grpWait.Name = "grpWait";
            this.grpWait.TabStop = false;
            this.grpWait.Text = "WAIT TIME";
            this.grpManual.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpManual.Controls.Add(this.manualLayout);
            this.grpManual.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpManual.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpManual.Margin = new System.Windows.Forms.Padding(4);
            this.grpManual.Name = "grpManual";
            this.grpManual.TabStop = false;
            this.grpManual.Text = "MANUAL ACTION";
            this.grpIo.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpIo.Controls.Add(this.ioLayout);
            this.grpIo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpIo.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpIo.Margin = new System.Windows.Forms.Padding(4);
            this.grpIo.Name = "grpIo";
            this.grpIo.TabStop = false;
            this.grpIo.Text = "CYLINDER && I/O";
            this.grpVision.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpVision.Controls.Add(this.visionPanel);
            this.grpVision.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpVision.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpVision.Margin = new System.Windows.Forms.Padding(4);
            this.grpVision.Name = "grpVision";
            this.grpVision.TabStop = false;
            this.grpVision.Text = "STAGE VISION";
            this.grpJog.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpJog.Controls.Add(this.jogLayout);
            this.grpJog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpJog.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpJog.Margin = new System.Windows.Forms.Padding(4);
            this.grpJog.Name = "grpJog";
            this.grpJog.TabStop = false;
            this.grpJog.Text = "JOG OPERATION";
            this.grpSpeed.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            this.grpSpeed.Controls.Add(this.speedLayout);
            this.grpSpeed.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSpeed.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpSpeed.Margin = new System.Windows.Forms.Padding(4);
            this.grpSpeed.Name = "grpSpeed";
            this.grpSpeed.TabStop = false;
            this.grpSpeed.Text = "SPEED";
            // 
            // optionLayout
            // 
            this.optionLayout.ColumnCount = 2;
            this.optionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 55F));
            this.optionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.optionLayout.Controls.Add(this.lblLoadingPositionKey, 0, 0);
            this.optionLayout.Controls.Add(this.lblLoadingPositionValue, 1, 0);
            this.optionLayout.Controls.Add(this.lblCenterPositionKey, 0, 1);
            this.optionLayout.Controls.Add(this.lblCenterPositionValue, 1, 1);
            this.optionLayout.Controls.Add(this.lblNeedlePositionKey, 0, 2);
            this.optionLayout.Controls.Add(this.lblNeedlePositionValue, 1, 2);
            this.optionLayout.Controls.Add(this.lblTestBedPositionKey, 0, 3);
            this.optionLayout.Controls.Add(this.lblTestBedPositionValue, 1, 3);
            this.optionLayout.Controls.Add(this.lblBarcodePositionKey, 0, 4);
            this.optionLayout.Controls.Add(this.lblBarcodePositionValue, 1, 4);
            this.optionLayout.Controls.Add(this.lblVisionAlignKey, 0, 5);
            this.optionLayout.Controls.Add(this.lblVisionAlignValue, 1, 5);
            this.optionLayout.Controls.Add(this.lblWorkRadiusKey, 0, 6);
            this.optionLayout.Controls.Add(this.lblWorkRadiusValue, 1, 6);
            this.optionLayout.Controls.Add(this.lblFirstDiePositionKey, 0, 7);
            this.optionLayout.Controls.Add(this.lblFirstDiePositionValue, 1, 7);
            this.optionLayout.Controls.Add(this.lblNeedleMeasurePositionKey, 0, 8);
            this.optionLayout.Controls.Add(this.lblNeedleMeasurePositionValue, 1, 8);
            this.optionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.optionLayout.Padding = new System.Windows.Forms.Padding(10, 18, 10, 8);
            this.optionLayout.RowCount = 9;
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            // 
            // waitLayout
            // 
            this.waitLayout.ColumnCount = 2;
            this.waitLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 55F));
            this.waitLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.waitLayout.Controls.Add(this.lblNeedleUpWaitKey, 0, 0);
            this.waitLayout.Controls.Add(this.lblNeedleUpWaitValue, 1, 0);
            this.waitLayout.Controls.Add(this.lblVacuumOnWaitKey, 0, 1);
            this.waitLayout.Controls.Add(this.lblVacuumOnWaitValue, 1, 1);
            this.waitLayout.Controls.Add(this.lblNeedleDownWaitKey, 0, 2);
            this.waitLayout.Controls.Add(this.lblNeedleDownWaitValue, 1, 2);
            this.waitLayout.Controls.Add(this.lblVacuumOffWaitKey, 0, 3);
            this.waitLayout.Controls.Add(this.lblVacuumOffWaitValue, 1, 3);
            this.waitLayout.Controls.Add(this.lblMovingWaitKey, 0, 4);
            this.waitLayout.Controls.Add(this.lblMovingWaitValue, 1, 4);
            this.waitLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.waitLayout.Padding = new System.Windows.Forms.Padding(10, 18, 10, 8);
            this.waitLayout.RowCount = 5;
            this.waitLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.waitLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.waitLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.waitLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.waitLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            // 
            // manualLayout
            // 
            this.manualLayout.ColumnCount = 2;
            this.manualLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.manualLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.manualLayout.Controls.Add(this.btnLoadingMove, 0, 0);
            this.manualLayout.Controls.Add(this.btnCenterMove, 1, 0);
            this.manualLayout.Controls.Add(this.btnBarcodeMove, 0, 1);
            this.manualLayout.Controls.Add(this.btnFirstDieMove, 1, 1);
            this.manualLayout.Controls.Add(this.btnPickUpTest, 0, 2);
            this.manualLayout.Controls.Add(this.btnNeedleUpMove, 1, 2);
            this.manualLayout.Controls.Add(this.btnNeedleDownMove, 0, 3);
            this.manualLayout.Controls.Add(this.btnNeedleReadyMove, 1, 3);
            this.manualLayout.Controls.Add(this.btnNeedleBlockReady, 0, 4);
            this.manualLayout.Controls.Add(this.btnNeedleBlockWork, 1, 4);
            this.manualLayout.Controls.Add(this.btnAutoSettingMove, 0, 5);
            this.manualLayout.Controls.Add(this.btnInputConversion, 1, 5);
            this.manualLayout.Controls.Add(this.btnExpandWorkMove, 0, 6);
            this.manualLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.manualLayout.Padding = new System.Windows.Forms.Padding(8, 18, 8, 8);
            this.manualLayout.RowCount = 7;
            this.manualLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.285F));
            this.manualLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.285F));
            this.manualLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.285F));
            this.manualLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.285F));
            this.manualLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.285F));
            this.manualLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.285F));
            this.manualLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.29F));
            // 
            // ioLayout
            // 
            this.ioLayout.ColumnCount = 3;
            this.ioLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.ioLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 58F));
            this.ioLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 42F));
            this.ioLayout.Controls.Add(this.dotNeedleVacuum, 0, 0);
            this.ioLayout.Controls.Add(this.lblNeedleVacuumKey, 1, 0);
            this.ioLayout.Controls.Add(this.lblNeedleVacuumValue, 2, 0);
            this.ioLayout.Controls.Add(this.dotRingSensor, 0, 1);
            this.ioLayout.Controls.Add(this.lblRingSensorKey, 1, 1);
            this.ioLayout.Controls.Add(this.lblRingSensorValue, 2, 1);
            this.ioLayout.Controls.Add(this.dotExpandCylinder, 0, 2);
            this.ioLayout.Controls.Add(this.lblExpandCylinderKey, 1, 2);
            this.ioLayout.Controls.Add(this.lblExpandCylinderValue, 2, 2);
            this.ioLayout.Controls.Add(this.dotNeedleBlock, 0, 3);
            this.ioLayout.Controls.Add(this.lblNeedleBlockKey, 1, 3);
            this.ioLayout.Controls.Add(this.lblNeedleBlockValue, 2, 3);
            this.ioLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ioLayout.Padding = new System.Windows.Forms.Padding(8, 18, 8, 8);
            this.ioLayout.RowCount = 4;
            this.ioLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.ioLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.ioLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.ioLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            // 
            // visionPanel
            // 
            this.visionPanel.BackColor = System.Drawing.Color.Black;
            this.visionPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.visionPanel.Controls.Add(this.lblVisionInfo);
            this.visionPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.visionPanel.Margin = new System.Windows.Forms.Padding(10);
            this.lblVisionInfo.AutoSize = true;
            this.lblVisionInfo.BackColor = System.Drawing.Color.Black;
            this.lblVisionInfo.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblVisionInfo.ForeColor = System.Drawing.Color.Lime;
            this.lblVisionInfo.Location = new System.Drawing.Point(10, 10);
            this.lblVisionInfo.Text = "STAGE\r\nW : 640\r\nH : 480\r\nX : 0\r\nY : 0\r\nT : 0";
            // 
            // jogLayout
            // 
            this.jogLayout.ColumnCount = 3;
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 36F));
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 34F));
            this.jogLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.jogLayout.Controls.Add(this.jogAxisLayout, 0, 0);
            this.jogLayout.Controls.Add(this.jogXyLayout, 1, 0);
            this.jogLayout.Controls.Add(this.jogZLayout, 2, 0);
            this.jogLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.jogLayout.Padding = new System.Windows.Forms.Padding(10, 18, 10, 10);
            this.jogLayout.RowCount = 1;
            this.jogLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.jogAxisLayout.ColumnCount = 2;
            this.jogAxisLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.jogAxisLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.jogAxisLayout.Controls.Add(this.lblAxisXKey, 0, 0);
            this.jogAxisLayout.Controls.Add(this.lblAxisXValue, 1, 0);
            this.jogAxisLayout.Controls.Add(this.lblAxisYKey, 0, 1);
            this.jogAxisLayout.Controls.Add(this.lblAxisYValue, 1, 1);
            this.jogAxisLayout.Controls.Add(this.lblAxisTKey, 0, 2);
            this.jogAxisLayout.Controls.Add(this.lblAxisTValue, 1, 2);
            this.jogAxisLayout.Controls.Add(this.lblExpandZKey, 0, 3);
            this.jogAxisLayout.Controls.Add(this.lblExpandZValue, 1, 3);
            this.jogAxisLayout.Controls.Add(this.lblNeedleZKey, 0, 4);
            this.jogAxisLayout.Controls.Add(this.lblNeedleZValue, 1, 4);
            this.jogAxisLayout.Controls.Add(this.lblNeedleBlockZKey, 0, 5);
            this.jogAxisLayout.Controls.Add(this.lblNeedleBlockZValue, 1, 5);
            this.jogAxisLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.jogAxisLayout.RowCount = 6;
            this.jogAxisLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66F));
            this.jogAxisLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66F));
            this.jogAxisLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66F));
            this.jogAxisLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66F));
            this.jogAxisLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66F));
            this.jogAxisLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.7F));
            this.jogXyLayout.ColumnCount = 3;
            this.jogXyLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogXyLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.34F));
            this.jogXyLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogXyLayout.Controls.Add(this.btnJogYPlus, 1, 0);
            this.jogXyLayout.Controls.Add(this.btnJogXMinus, 0, 1);
            this.jogXyLayout.Controls.Add(this.btnJogStop, 1, 1);
            this.jogXyLayout.Controls.Add(this.btnJogXPlus, 2, 1);
            this.jogXyLayout.Controls.Add(this.btnJogTMinus, 0, 2);
            this.jogXyLayout.Controls.Add(this.btnJogYMinus, 1, 2);
            this.jogXyLayout.Controls.Add(this.btnJogTPlus, 2, 2);
            this.jogXyLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.jogXyLayout.RowCount = 3;
            this.jogXyLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogXyLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.34F));
            this.jogXyLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogZLayout.ColumnCount = 3;
            this.jogZLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogZLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.34F));
            this.jogZLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            this.jogZLayout.Controls.Add(this.btnExpandUp, 0, 0);
            this.jogZLayout.Controls.Add(this.btnNeedleUp, 1, 0);
            this.jogZLayout.Controls.Add(this.btnBlockUp, 2, 0);
            this.jogZLayout.Controls.Add(this.lblExpandAxis, 0, 1);
            this.jogZLayout.Controls.Add(this.lblNeedleAxis, 1, 1);
            this.jogZLayout.Controls.Add(this.lblBlockAxis, 2, 1);
            this.jogZLayout.Controls.Add(this.btnExpandDown, 0, 2);
            this.jogZLayout.Controls.Add(this.btnNeedleDown, 1, 2);
            this.jogZLayout.Controls.Add(this.btnBlockDown, 2, 2);
            this.jogZLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.jogZLayout.RowCount = 3;
            this.jogZLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.jogZLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.jogZLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            // 
            // speedLayout
            // 
            this.speedLayout.ColumnCount = 1;
            this.speedLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.speedLayout.Controls.Add(this.trkSpeed, 0, 0);
            this.speedLayout.Controls.Add(this.lblSpeedValue, 0, 1);
            this.speedLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.speedLayout.Padding = new System.Windows.Forms.Padding(12, 18, 12, 12);
            this.speedLayout.RowCount = 2;
            this.speedLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.speedLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.trkSpeed.Dock = System.Windows.Forms.DockStyle.Fill;
            this.trkSpeed.Maximum = 100;
            this.trkSpeed.Orientation = System.Windows.Forms.Orientation.Vertical;
            this.trkSpeed.TickFrequency = 10;
            this.trkSpeed.Value = 50;
            this.lblSpeedValue.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblSpeedValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSpeedValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblSpeedValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblSpeedValue.Text = "50%";
            this.lblSpeedValue.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // text
            // 
            this.lblLoadingPositionKey.Text = "LOADING POSITION";
            this.lblLoadingPositionValue.Text = "SET";
            this.lblCenterPositionKey.Text = "CENTER POSITION";
            this.lblCenterPositionValue.Text = "SET";
            this.lblNeedlePositionKey.Text = "NEEDLE POSITION";
            this.lblNeedlePositionValue.Text = "SET";
            this.lblTestBedPositionKey.Text = "TEST BED POSITION";
            this.lblTestBedPositionValue.Text = "SET";
            this.lblBarcodePositionKey.Text = "BARCODE POSITION";
            this.lblBarcodePositionValue.Text = "SET";
            this.lblVisionAlignKey.Text = "VISION ALIGN";
            this.lblVisionAlignValue.Text = "SET";
            this.lblWorkRadiusKey.Text = "WORK RADIUS";
            this.lblWorkRadiusValue.Text = "SET";
            this.lblFirstDiePositionKey.Text = "FIRST DIE POSITION";
            this.lblFirstDiePositionValue.Text = "SET";
            this.lblNeedleMeasurePositionKey.Text = "NEEDLE MEASURE POSITION";
            this.lblNeedleMeasurePositionValue.Text = "SET";
            this.lblNeedleUpWaitKey.Text = "NEEDLE UP";
            this.lblNeedleUpWaitValue.Text = "0 ms";
            this.lblVacuumOnWaitKey.Text = "VACUUM ON";
            this.lblVacuumOnWaitValue.Text = "0 ms";
            this.lblNeedleDownWaitKey.Text = "NEEDLE DOWN";
            this.lblNeedleDownWaitValue.Text = "0 ms";
            this.lblVacuumOffWaitKey.Text = "VACUUM OFF";
            this.lblVacuumOffWaitValue.Text = "0 ms";
            this.lblMovingWaitKey.Text = "MOVING";
            this.lblMovingWaitValue.Text = "0 ms";
            this.btnLoadingMove.Text = "LOADING MOVE";
            this.btnCenterMove.Text = "CENTER MOVE";
            this.btnBarcodeMove.Text = "BARCODE MOVE";
            this.btnFirstDieMove.Text = "FIRST DIE MOVE";
            this.btnPickUpTest.Text = "PICK UP TEST";
            this.btnNeedleUpMove.Text = "NEEDLE UP MOVE";
            this.btnNeedleDownMove.Text = "NEEDLE DOWN MOVE";
            this.btnNeedleReadyMove.Text = "NEEDLE READY MOVE";
            this.btnNeedleBlockReady.Text = "NEEDLE BLOCK READY";
            this.btnNeedleBlockWork.Text = "NEEDLE BLOCK WORK";
            this.btnAutoSettingMove.Text = "AUTO SETTING MOVE";
            this.btnInputConversion.Text = "INPUT CONVERSION";
            this.btnExpandWorkMove.Text = "EXPAND WORK MOVE";
            this.lblNeedleVacuumKey.Text = "NEEDLE VACUUM";
            this.lblNeedleVacuumValue.Text = "VACUUM";
            this.lblRingSensorKey.Text = "RING SENSOR";
            this.lblRingSensorValue.Text = "OFF";
            this.lblExpandCylinderKey.Text = "EXPAND CYLINDER";
            this.lblExpandCylinderValue.Text = "READY";
            this.lblNeedleBlockKey.Text = "NEEDLE BLOCK";
            this.lblNeedleBlockValue.Text = "READY";
            this.lblAxisXKey.Text = "AXIS X";
            this.lblAxisXValue.Text = "0 um";
            this.lblAxisYKey.Text = "AXIS Y";
            this.lblAxisYValue.Text = "0 um";
            this.lblAxisTKey.Text = "AXIS T";
            this.lblAxisTValue.Text = "0 deg";
            this.lblExpandZKey.Text = "EXPAND Z";
            this.lblExpandZValue.Text = "0 um";
            this.lblNeedleZKey.Text = "NEEDLE Z";
            this.lblNeedleZValue.Text = "0 um";
            this.lblNeedleBlockZKey.Text = "NEEDLE BLOCK Z";
            this.lblNeedleBlockZValue.Text = "0 um";
            this.btnJogYPlus.Text = "+Y";
            this.btnJogXMinus.Text = "-X";
            this.btnJogStop.Text = "STOP";
            this.btnJogXPlus.Text = "+X";
            this.btnJogYMinus.Text = "-Y";
            this.btnJogTMinus.Text = "-T";
            this.btnJogTPlus.Text = "+T";
            this.btnExpandUp.Text = "UP";
            this.btnExpandDown.Text = "DOWN";
            this.btnNeedleUp.Text = "UP";
            this.btnNeedleDown.Text = "DOWN";
            this.btnBlockUp.Text = "UP";
            this.btnBlockDown.Text = "DOWN";
            this.lblExpandAxis.Text = "EXPAND";
            this.lblNeedleAxis.Text = "NEEDLE";
            this.lblBlockAxis.Text = "BLOCK";
            // 
            // common styling
            // 
            this.dotNeedleVacuum.Dock = this.dotRingSensor.Dock = this.dotExpandCylinder.Dock = this.dotNeedleBlock.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dotNeedleVacuum.Margin = this.dotRingSensor.Margin = this.dotExpandCylinder.Margin = this.dotNeedleBlock.Margin = new System.Windows.Forms.Padding(7);
            this.dotNeedleVacuum.OnColor = this.dotRingSensor.OnColor = this.dotExpandCylinder.OnColor = this.dotNeedleBlock.OnColor = System.Drawing.Color.LimeGreen;
            this.lblLoadingPositionKey.BackColor = this.lblCenterPositionKey.BackColor = this.lblNeedlePositionKey.BackColor = this.lblTestBedPositionKey.BackColor = this.lblBarcodePositionKey.BackColor = this.lblVisionAlignKey.BackColor = this.lblWorkRadiusKey.BackColor = this.lblFirstDiePositionKey.BackColor = this.lblNeedleMeasurePositionKey.BackColor = this.lblNeedleUpWaitKey.BackColor = this.lblVacuumOnWaitKey.BackColor = this.lblNeedleDownWaitKey.BackColor = this.lblVacuumOffWaitKey.BackColor = this.lblMovingWaitKey.BackColor = this.lblNeedleVacuumKey.BackColor = this.lblRingSensorKey.BackColor = this.lblExpandCylinderKey.BackColor = this.lblNeedleBlockKey.BackColor = this.lblAxisXKey.BackColor = this.lblAxisYKey.BackColor = this.lblAxisTKey.BackColor = this.lblExpandZKey.BackColor = this.lblNeedleZKey.BackColor = this.lblNeedleBlockZKey.BackColor = this.lblExpandAxis.BackColor = this.lblNeedleAxis.BackColor = this.lblBlockAxis.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblLoadingPositionValue.BackColor = this.lblCenterPositionValue.BackColor = this.lblNeedlePositionValue.BackColor = this.lblTestBedPositionValue.BackColor = this.lblBarcodePositionValue.BackColor = this.lblVisionAlignValue.BackColor = this.lblWorkRadiusValue.BackColor = this.lblFirstDiePositionValue.BackColor = this.lblNeedleMeasurePositionValue.BackColor = this.lblNeedleUpWaitValue.BackColor = this.lblVacuumOnWaitValue.BackColor = this.lblNeedleDownWaitValue.BackColor = this.lblVacuumOffWaitValue.BackColor = this.lblMovingWaitValue.BackColor = this.lblNeedleVacuumValue.BackColor = this.lblRingSensorValue.BackColor = this.lblExpandCylinderValue.BackColor = this.lblNeedleBlockValue.BackColor = this.lblAxisXValue.BackColor = this.lblAxisYValue.BackColor = this.lblAxisTValue.BackColor = this.lblExpandZValue.BackColor = this.lblNeedleZValue.BackColor = this.lblNeedleBlockZValue.BackColor = System.Drawing.Color.White;
            this.lblLoadingPositionKey.BorderStyle = this.lblCenterPositionKey.BorderStyle = this.lblNeedlePositionKey.BorderStyle = this.lblTestBedPositionKey.BorderStyle = this.lblBarcodePositionKey.BorderStyle = this.lblVisionAlignKey.BorderStyle = this.lblWorkRadiusKey.BorderStyle = this.lblFirstDiePositionKey.BorderStyle = this.lblNeedleMeasurePositionKey.BorderStyle = this.lblNeedleUpWaitKey.BorderStyle = this.lblVacuumOnWaitKey.BorderStyle = this.lblNeedleDownWaitKey.BorderStyle = this.lblVacuumOffWaitKey.BorderStyle = this.lblMovingWaitKey.BorderStyle = this.lblNeedleVacuumKey.BorderStyle = this.lblRingSensorKey.BorderStyle = this.lblExpandCylinderKey.BorderStyle = this.lblNeedleBlockKey.BorderStyle = this.lblAxisXKey.BorderStyle = this.lblAxisYKey.BorderStyle = this.lblAxisTKey.BorderStyle = this.lblExpandZKey.BorderStyle = this.lblNeedleZKey.BorderStyle = this.lblNeedleBlockZKey.BorderStyle = this.lblExpandAxis.BorderStyle = this.lblNeedleAxis.BorderStyle = this.lblBlockAxis.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblLoadingPositionValue.BorderStyle = this.lblCenterPositionValue.BorderStyle = this.lblNeedlePositionValue.BorderStyle = this.lblTestBedPositionValue.BorderStyle = this.lblBarcodePositionValue.BorderStyle = this.lblVisionAlignValue.BorderStyle = this.lblWorkRadiusValue.BorderStyle = this.lblFirstDiePositionValue.BorderStyle = this.lblNeedleMeasurePositionValue.BorderStyle = this.lblNeedleUpWaitValue.BorderStyle = this.lblVacuumOnWaitValue.BorderStyle = this.lblNeedleDownWaitValue.BorderStyle = this.lblVacuumOffWaitValue.BorderStyle = this.lblMovingWaitValue.BorderStyle = this.lblNeedleVacuumValue.BorderStyle = this.lblRingSensorValue.BorderStyle = this.lblExpandCylinderValue.BorderStyle = this.lblNeedleBlockValue.BorderStyle = this.lblAxisXValue.BorderStyle = this.lblAxisYValue.BorderStyle = this.lblAxisTValue.BorderStyle = this.lblExpandZValue.BorderStyle = this.lblNeedleZValue.BorderStyle = this.lblNeedleBlockZValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblLoadingPositionKey.Dock = this.lblCenterPositionKey.Dock = this.lblNeedlePositionKey.Dock = this.lblTestBedPositionKey.Dock = this.lblBarcodePositionKey.Dock = this.lblVisionAlignKey.Dock = this.lblWorkRadiusKey.Dock = this.lblFirstDiePositionKey.Dock = this.lblNeedleMeasurePositionKey.Dock = this.lblNeedleUpWaitKey.Dock = this.lblVacuumOnWaitKey.Dock = this.lblNeedleDownWaitKey.Dock = this.lblVacuumOffWaitKey.Dock = this.lblMovingWaitKey.Dock = this.lblNeedleVacuumKey.Dock = this.lblRingSensorKey.Dock = this.lblExpandCylinderKey.Dock = this.lblNeedleBlockKey.Dock = this.lblAxisXKey.Dock = this.lblAxisYKey.Dock = this.lblAxisTKey.Dock = this.lblExpandZKey.Dock = this.lblNeedleZKey.Dock = this.lblNeedleBlockZKey.Dock = this.lblExpandAxis.Dock = this.lblNeedleAxis.Dock = this.lblBlockAxis.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblLoadingPositionValue.Dock = this.lblCenterPositionValue.Dock = this.lblNeedlePositionValue.Dock = this.lblTestBedPositionValue.Dock = this.lblBarcodePositionValue.Dock = this.lblVisionAlignValue.Dock = this.lblWorkRadiusValue.Dock = this.lblFirstDiePositionValue.Dock = this.lblNeedleMeasurePositionValue.Dock = this.lblNeedleUpWaitValue.Dock = this.lblVacuumOnWaitValue.Dock = this.lblNeedleDownWaitValue.Dock = this.lblVacuumOffWaitValue.Dock = this.lblMovingWaitValue.Dock = this.lblNeedleVacuumValue.Dock = this.lblRingSensorValue.Dock = this.lblExpandCylinderValue.Dock = this.lblNeedleBlockValue.Dock = this.lblAxisXValue.Dock = this.lblAxisYValue.Dock = this.lblAxisTValue.Dock = this.lblExpandZValue.Dock = this.lblNeedleZValue.Dock = this.lblNeedleBlockZValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblLoadingPositionKey.TextAlign = this.lblCenterPositionKey.TextAlign = this.lblNeedlePositionKey.TextAlign = this.lblTestBedPositionKey.TextAlign = this.lblBarcodePositionKey.TextAlign = this.lblVisionAlignKey.TextAlign = this.lblWorkRadiusKey.TextAlign = this.lblFirstDiePositionKey.TextAlign = this.lblNeedleMeasurePositionKey.TextAlign = this.lblNeedleUpWaitKey.TextAlign = this.lblVacuumOnWaitKey.TextAlign = this.lblNeedleDownWaitKey.TextAlign = this.lblVacuumOffWaitKey.TextAlign = this.lblMovingWaitKey.TextAlign = this.lblNeedleVacuumKey.TextAlign = this.lblRingSensorKey.TextAlign = this.lblExpandCylinderKey.TextAlign = this.lblNeedleBlockKey.TextAlign = this.lblAxisXKey.TextAlign = this.lblAxisYKey.TextAlign = this.lblAxisTKey.TextAlign = this.lblExpandZKey.TextAlign = this.lblNeedleZKey.TextAlign = this.lblNeedleBlockZKey.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblLoadingPositionValue.TextAlign = this.lblCenterPositionValue.TextAlign = this.lblNeedlePositionValue.TextAlign = this.lblTestBedPositionValue.TextAlign = this.lblBarcodePositionValue.TextAlign = this.lblVisionAlignValue.TextAlign = this.lblWorkRadiusValue.TextAlign = this.lblFirstDiePositionValue.TextAlign = this.lblNeedleMeasurePositionValue.TextAlign = this.lblNeedleUpWaitValue.TextAlign = this.lblVacuumOnWaitValue.TextAlign = this.lblNeedleDownWaitValue.TextAlign = this.lblVacuumOffWaitValue.TextAlign = this.lblMovingWaitValue.TextAlign = this.lblNeedleVacuumValue.TextAlign = this.lblRingSensorValue.TextAlign = this.lblExpandCylinderValue.TextAlign = this.lblNeedleBlockValue.TextAlign = this.lblAxisXValue.TextAlign = this.lblAxisYValue.TextAlign = this.lblAxisTValue.TextAlign = this.lblExpandZValue.TextAlign = this.lblNeedleZValue.TextAlign = this.lblNeedleBlockZValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblExpandAxis.TextAlign = this.lblNeedleAxis.TextAlign = this.lblBlockAxis.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblLoadingPositionKey.Font = this.lblCenterPositionKey.Font = this.lblNeedlePositionKey.Font = this.lblTestBedPositionKey.Font = this.lblBarcodePositionKey.Font = this.lblVisionAlignKey.Font = this.lblWorkRadiusKey.Font = this.lblFirstDiePositionKey.Font = this.lblNeedleMeasurePositionKey.Font = this.lblNeedleUpWaitKey.Font = this.lblVacuumOnWaitKey.Font = this.lblNeedleDownWaitKey.Font = this.lblVacuumOffWaitKey.Font = this.lblMovingWaitKey.Font = this.lblNeedleVacuumKey.Font = this.lblRingSensorKey.Font = this.lblExpandCylinderKey.Font = this.lblNeedleBlockKey.Font = this.lblAxisXKey.Font = this.lblAxisYKey.Font = this.lblAxisTKey.Font = this.lblExpandZKey.Font = this.lblNeedleZKey.Font = this.lblNeedleBlockZKey.Font = this.lblExpandAxis.Font = this.lblNeedleAxis.Font = this.lblBlockAxis.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.lblLoadingPositionValue.Font = this.lblCenterPositionValue.Font = this.lblNeedlePositionValue.Font = this.lblTestBedPositionValue.Font = this.lblBarcodePositionValue.Font = this.lblVisionAlignValue.Font = this.lblWorkRadiusValue.Font = this.lblFirstDiePositionValue.Font = this.lblNeedleMeasurePositionValue.Font = this.lblNeedleUpWaitValue.Font = this.lblVacuumOnWaitValue.Font = this.lblNeedleDownWaitValue.Font = this.lblVacuumOffWaitValue.Font = this.lblMovingWaitValue.Font = this.lblNeedleVacuumValue.Font = this.lblRingSensorValue.Font = this.lblExpandCylinderValue.Font = this.lblNeedleBlockValue.Font = this.lblAxisXValue.Font = this.lblAxisYValue.Font = this.lblAxisTValue.Font = this.lblExpandZValue.Font = this.lblNeedleZValue.Font = this.lblNeedleBlockZValue.Font = new System.Drawing.Font("Consolas", 9.5F, System.Drawing.FontStyle.Bold);
            this.btnLoadingMove.Dock = this.btnCenterMove.Dock = this.btnBarcodeMove.Dock = this.btnFirstDieMove.Dock = this.btnPickUpTest.Dock = this.btnNeedleUpMove.Dock = this.btnNeedleDownMove.Dock = this.btnNeedleReadyMove.Dock = this.btnNeedleBlockReady.Dock = this.btnNeedleBlockWork.Dock = this.btnAutoSettingMove.Dock = this.btnInputConversion.Dock = this.btnExpandWorkMove.Dock = this.btnJogYPlus.Dock = this.btnJogXMinus.Dock = this.btnJogStop.Dock = this.btnJogXPlus.Dock = this.btnJogYMinus.Dock = this.btnJogTMinus.Dock = this.btnJogTPlus.Dock = this.btnExpandUp.Dock = this.btnExpandDown.Dock = this.btnNeedleUp.Dock = this.btnNeedleDown.Dock = this.btnBlockUp.Dock = this.btnBlockDown.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnLoadingMove.Font = this.btnCenterMove.Font = this.btnBarcodeMove.Font = this.btnFirstDieMove.Font = this.btnPickUpTest.Font = this.btnNeedleUpMove.Font = this.btnNeedleDownMove.Font = this.btnNeedleReadyMove.Font = this.btnNeedleBlockReady.Font = this.btnNeedleBlockWork.Font = this.btnAutoSettingMove.Font = this.btnInputConversion.Font = this.btnExpandWorkMove.Font = this.btnJogYPlus.Font = this.btnJogXMinus.Font = this.btnJogStop.Font = this.btnJogXPlus.Font = this.btnJogYMinus.Font = this.btnJogTMinus.Font = this.btnJogTPlus.Font = this.btnExpandUp.Font = this.btnExpandDown.Font = this.btnNeedleUp.Font = this.btnNeedleDown.Font = this.btnBlockUp.Font = this.btnBlockDown.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.btnLoadingMove.Margin = this.btnCenterMove.Margin = this.btnBarcodeMove.Margin = this.btnFirstDieMove.Margin = this.btnPickUpTest.Margin = this.btnNeedleUpMove.Margin = this.btnNeedleDownMove.Margin = this.btnNeedleReadyMove.Margin = this.btnNeedleBlockReady.Margin = this.btnNeedleBlockWork.Margin = this.btnAutoSettingMove.Margin = this.btnInputConversion.Margin = this.btnExpandWorkMove.Margin = this.btnJogYPlus.Margin = this.btnJogXMinus.Margin = this.btnJogStop.Margin = this.btnJogXPlus.Margin = this.btnJogYMinus.Margin = this.btnJogTMinus.Margin = this.btnJogTPlus.Margin = this.btnExpandUp.Margin = this.btnExpandDown.Margin = this.btnNeedleUp.Margin = this.btnNeedleDown.Margin = this.btnBlockUp.Margin = this.btnBlockDown.Margin = new System.Windows.Forms.Padding(4);
            // 
            // StageRecipePage
            // 
            this.Controls.Add(this.rootLayout);
            this.Name = "StageRecipePage";
            this.Size = new System.Drawing.Size(1400, 900);
            this.rootLayout.ResumeLayout(false);
            this.contentLayout.ResumeLayout(false);
            this.leftLayout.ResumeLayout(false);
            this.centerLayout.ResumeLayout(false);
            this.rightLayout.ResumeLayout(false);
            this.grpOptions.ResumeLayout(false);
            this.grpWait.ResumeLayout(false);
            this.grpManual.ResumeLayout(false);
            this.grpIo.ResumeLayout(false);
            this.grpVision.ResumeLayout(false);
            this.grpJog.ResumeLayout(false);
            this.grpSpeed.ResumeLayout(false);
            this.optionLayout.ResumeLayout(false);
            this.waitLayout.ResumeLayout(false);
            this.manualLayout.ResumeLayout(false);
            this.ioLayout.ResumeLayout(false);
            this.visionPanel.ResumeLayout(false);
            this.visionPanel.PerformLayout();
            this.jogLayout.ResumeLayout(false);
            this.jogAxisLayout.ResumeLayout(false);
            this.jogXyLayout.ResumeLayout(false);
            this.jogZLayout.ResumeLayout(false);
            this.speedLayout.ResumeLayout(false);
            this.speedLayout.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.trkSpeed)).EndInit();
            this.ResumeLayout(false);
        }
    }
}
