namespace QMC.CDT_320.Ui.Dialogs
{
    partial class BoardScanDialog
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label lblDescription;
        private System.Windows.Forms.DataGridView _grid;
        private System.Windows.Forms.ProgressBar _pb;
        private System.Windows.Forms.TableLayoutPanel bottomLayout;
        private System.Windows.Forms.Button _btnStart;
        private System.Windows.Forms.Button _btnCancel;
        private System.Windows.Forms.DataGridViewTextBoxColumn colIdx;
        private System.Windows.Forms.DataGridViewTextBoxColumn colName;
        private System.Windows.Forms.DataGridViewTextBoxColumn colServo;
        private System.Windows.Forms.DataGridViewTextBoxColumn colMove;
        private System.Windows.Forms.DataGridViewTextBoxColumn colAlarm;
        private System.Windows.Forms.DataGridViewTextBoxColumn colPos;
        private System.Windows.Forms.DataGridViewTextBoxColumn colResult;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.lblDescription = new System.Windows.Forms.Label();
            this._grid = new System.Windows.Forms.DataGridView();
            this.colIdx = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colName = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colServo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colMove = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colAlarm = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colPos = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colResult = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this._pb = new System.Windows.Forms.ProgressBar();
            this.bottomLayout = new System.Windows.Forms.TableLayoutPanel();
            this._btnStart = new System.Windows.Forms.Button();
            this._btnCancel = new System.Windows.Forms.Button();
            this.rootLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this._grid)).BeginInit();
            this.bottomLayout.SuspendLayout();
            this.SuspendLayout();
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblTitle, 0, 0);
            this.rootLayout.Controls.Add(this.lblDescription, 0, 1);
            this.rootLayout.Controls.Add(this._grid, 0, 2);
            this.rootLayout.Controls.Add(this._pb, 0, 3);
            this.rootLayout.Controls.Add(this.bottomLayout, 0, 4);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.RowCount = 5;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 58F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 52F));
            this.lblTitle.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Text = "BOARD SCAN TEST";
            this.lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblDescription.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDescription.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDescription.ForeColor = System.Drawing.Color.DimGray;
            this.lblDescription.Padding = new System.Windows.Forms.Padding(10);
            this.lblDescription.Text = "Each axis is checked by servo status, small motion, position return, and alarm state.";
            this.lblDescription.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this._grid.AllowUserToAddRows = false;
            this._grid.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this._grid.BackgroundColor = System.Drawing.Color.White;
            this._grid.ColumnHeadersDefaultCellStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this._grid.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(80, 80, 80);
            this._grid.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this._grid.ColumnHeadersDefaultCellStyle.ForeColor = System.Drawing.Color.White;
            this._grid.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.colIdx, this.colName, this.colServo, this.colMove, this.colAlarm, this.colPos, this.colResult });
            this._grid.Dock = System.Windows.Forms.DockStyle.Fill;
            this._grid.EnableHeadersVisualStyles = false;
            this._grid.Font = new System.Drawing.Font("Segoe UI", 9F);
            this._grid.MultiSelect = false;
            this._grid.ReadOnly = true;
            this._grid.RowHeadersVisible = false;
            this._grid.RowTemplate.Height = 24;
            this._grid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.colIdx.HeaderText = "#";
            this.colIdx.Name = "IDX";
            this.colIdx.ReadOnly = true;
            this.colName.HeaderText = "AXIS";
            this.colName.Name = "NAME";
            this.colName.ReadOnly = true;
            this.colServo.HeaderText = "SERVO";
            this.colServo.Name = "SERVO";
            this.colServo.ReadOnly = true;
            this.colMove.HeaderText = "MOVE";
            this.colMove.Name = "MOVE";
            this.colMove.ReadOnly = true;
            this.colAlarm.HeaderText = "ALARM";
            this.colAlarm.Name = "ALARM";
            this.colAlarm.ReadOnly = true;
            this.colPos.HeaderText = "POS";
            this.colPos.Name = "POS";
            this.colPos.ReadOnly = true;
            this.colResult.HeaderText = "RESULT";
            this.colResult.Name = "RESULT";
            this.colResult.ReadOnly = true;
            this._pb.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bottomLayout.ColumnCount = 4;
            this.bottomLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.bottomLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 108F));
            this.bottomLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 108F));
            this.bottomLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 8F));
            this.bottomLayout.Controls.Add(this._btnStart, 1, 0);
            this.bottomLayout.Controls.Add(this._btnCancel, 2, 0);
            this.bottomLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bottomLayout.Padding = new System.Windows.Forms.Padding(0, 9, 0, 9);
            this.bottomLayout.RowCount = 1;
            this.bottomLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this._btnStart.Dock = System.Windows.Forms.DockStyle.Fill;
            this._btnStart.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this._btnStart.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this._btnStart.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this._btnStart.Text = "START";
            this._btnCancel.Dock = System.Windows.Forms.DockStyle.Fill;
            this._btnCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this._btnCancel.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this._btnCancel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this._btnCancel.Text = "CLOSE";
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.ClientSize = new System.Drawing.Size(760, 620);
            this.Controls.Add(this.rootLayout);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "BoardScanDialog";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "BOARD SCAN TEST";
            this.rootLayout.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this._grid)).EndInit();
            this.bottomLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
