using System.Drawing;
using System.Windows.Forms;
using QMC.CDT320.Ui.Controls;
using QMC.CDT_320.Ui.Controls;
using QMC.CDT_320.Ui.Localization;

namespace QMC.CDT_320.Ui.Pages.Work
{
    partial class MapTransferPage
    {
        private TableLayoutPanel rootLayout;
        private Label lblHeader;
        private TableLayoutPanel statusLayout;
        private Label lblProjectCaption;
        private Label lblProjectValue;
        private Label lblBarcodeCaption;
        private Label lblBarcodeValue;
        private Label lblBinCaption;
        private Label lblBinValue;
        private TableLayoutPanel bodyLayout;
        private TableLayoutPanel mapLayout;
        private Label lblMapTitle;
        private DieMapView mapView;
        private TableLayoutPanel sideLayout;
        private GroupBox grpMapInfo;
        private TableLayoutPanel mapInfoLayout;
        private Label lblChipWCaption;
        private Label lblChipW;
        private Label lblChipHCaption;
        private Label lblChipH;
        private Label lblPitchXCaption;
        private Label lblPitchX;
        private Label lblPitchYCaption;
        private Label lblPitchY;
        private Label lblWaferDiaCaption;
        private Label lblWaferDia;
        private Label lblAxisXCaption;
        private Label lblAxisX;
        private Label lblAxisYCaption;
        private Label lblAxisY;
        private Label lblBinRankCaption;
        private Label lblBinRank;
        private Label lblDieNumCaption;
        private Label lblDieNum;
        private GroupBox grpMode;
        private TableLayoutPanel modeLayout;
        private RadioButton rbStandard;
        private RadioButton rbStartIndex;
        private RadioButton rbSelectPickStatus;
        private RadioButton rbDragPickStatus;
        private ActionButton btnPickStatusSave;
        private GroupBox grpJog;
        private TableLayoutPanel jogLayout;
        private Button btnJogUp;
        private Button btnJogLeft;
        private Button btnJogCenter;
        private Button btnJogRight;
        private Button btnJogDown;
        private Button btnJogThetaCcw;
        private Button btnJogThetaCw;
        private TableLayoutPanel actionLayout;
        private ActionButton btnManualAlignComplete;
        private ActionButton btnNeedleBlockDown;
        private ActionButton btnThetaMatchMove;
        private ActionButton btnXyMatchMove;
        private Button btnClose;

        private void InitializeComponent()
        {
            this.rootLayout = new TableLayoutPanel();
            this.lblHeader = new Label();
            this.statusLayout = new TableLayoutPanel();
            this.lblProjectCaption = new Label();
            this.lblProjectValue = new Label();
            this.lblBarcodeCaption = new Label();
            this.lblBarcodeValue = new Label();
            this.lblBinCaption = new Label();
            this.lblBinValue = new Label();
            this.bodyLayout = new TableLayoutPanel();
            this.mapLayout = new TableLayoutPanel();
            this.lblMapTitle = new Label();
            this.mapView = new DieMapView();
            this.sideLayout = new TableLayoutPanel();
            this.grpMapInfo = new GroupBox();
            this.mapInfoLayout = new TableLayoutPanel();
            this.lblChipWCaption = new Label();
            this.lblChipW = new Label();
            this.lblChipHCaption = new Label();
            this.lblChipH = new Label();
            this.lblPitchXCaption = new Label();
            this.lblPitchX = new Label();
            this.lblPitchYCaption = new Label();
            this.lblPitchY = new Label();
            this.lblWaferDiaCaption = new Label();
            this.lblWaferDia = new Label();
            this.lblAxisXCaption = new Label();
            this.lblAxisX = new Label();
            this.lblAxisYCaption = new Label();
            this.lblAxisY = new Label();
            this.lblBinRankCaption = new Label();
            this.lblBinRank = new Label();
            this.lblDieNumCaption = new Label();
            this.lblDieNum = new Label();
            this.grpMode = new GroupBox();
            this.modeLayout = new TableLayoutPanel();
            this.rbStandard = new RadioButton();
            this.rbStartIndex = new RadioButton();
            this.rbSelectPickStatus = new RadioButton();
            this.rbDragPickStatus = new RadioButton();
            this.btnPickStatusSave = new ActionButton();
            this.grpJog = new GroupBox();
            this.jogLayout = new TableLayoutPanel();
            this.btnJogUp = new Button();
            this.btnJogLeft = new Button();
            this.btnJogCenter = new Button();
            this.btnJogRight = new Button();
            this.btnJogDown = new Button();
            this.btnJogThetaCcw = new Button();
            this.btnJogThetaCw = new Button();
            this.actionLayout = new TableLayoutPanel();
            this.btnManualAlignComplete = new ActionButton();
            this.btnNeedleBlockDown = new ActionButton();
            this.btnThetaMatchMove = new ActionButton();
            this.btnXyMatchMove = new ActionButton();
            this.btnClose = new Button();
            this.SuspendLayout();

            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.statusLayout, 0, 1);
            this.rootLayout.Controls.Add(this.bodyLayout, 0, 2);
            this.rootLayout.Dock = DockStyle.Fill;
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

            this.lblHeader.BackColor = UiTheme.StatusBarBg;
            this.lblHeader.Dock = DockStyle.Fill;
            this.lblHeader.Font = UiTheme.SectionFont;
            this.lblHeader.ForeColor = UiTheme.StatusBarFg;
            this.lblHeader.Padding = new Padding(10, 0, 0, 0);
            this.lblHeader.Tag = "i18n:work.page.inputMap";
            this.lblHeader.Text = Lang.T("work.page.inputMap");
            this.lblHeader.TextAlign = ContentAlignment.MiddleLeft;

            this.statusLayout.BackColor = UiTheme.StatusBarBg;
            this.statusLayout.ColumnCount = 8;
            this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 80F));
            this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 260F));
            this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90F));
            this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 220F));
            this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 60F));
            this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120F));
            this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 80F));
            this.statusLayout.Controls.Add(this.lblProjectCaption, 0, 0);
            this.statusLayout.Controls.Add(this.lblProjectValue, 1, 0);
            this.statusLayout.Controls.Add(this.lblBarcodeCaption, 2, 0);
            this.statusLayout.Controls.Add(this.lblBarcodeValue, 3, 0);
            this.statusLayout.Controls.Add(this.lblBinCaption, 4, 0);
            this.statusLayout.Controls.Add(this.lblBinValue, 5, 0);
            this.statusLayout.Dock = DockStyle.Fill;
            this.statusLayout.RowCount = 1;
            this.statusLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

            this.lblProjectCaption.Dock = DockStyle.Fill;
            this.lblProjectCaption.Font = UiTheme.StatusBarFont;
            this.lblProjectCaption.ForeColor = Color.White;
            this.lblProjectCaption.Text = Lang.T("status.project");
            this.lblProjectCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblProjectValue.Dock = DockStyle.Fill;
            this.lblProjectValue.Font = UiTheme.StatusBarFont;
            this.lblProjectValue.ForeColor = Color.White;
            this.lblProjectValue.Text = "--";
            this.lblProjectValue.TextAlign = ContentAlignment.MiddleLeft;
            this.lblBarcodeCaption.Dock = DockStyle.Fill;
            this.lblBarcodeCaption.Font = UiTheme.StatusBarFont;
            this.lblBarcodeCaption.ForeColor = Color.White;
            this.lblBarcodeCaption.Text = Lang.T("status.barcode");
            this.lblBarcodeCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblBarcodeValue.Dock = DockStyle.Fill;
            this.lblBarcodeValue.Font = UiTheme.StatusBarFont;
            this.lblBarcodeValue.ForeColor = Color.White;
            this.lblBarcodeValue.Text = "--";
            this.lblBarcodeValue.TextAlign = ContentAlignment.MiddleLeft;
            this.lblBinCaption.Dock = DockStyle.Fill;
            this.lblBinCaption.Font = UiTheme.StatusBarFont;
            this.lblBinCaption.ForeColor = Color.White;
            this.lblBinCaption.Text = Lang.T("status.bin");
            this.lblBinCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblBinValue.Dock = DockStyle.Fill;
            this.lblBinValue.Font = UiTheme.StatusBarFont;
            this.lblBinValue.ForeColor = Color.White;
            this.lblBinValue.Text = "--";
            this.lblBinValue.TextAlign = ContentAlignment.MiddleLeft;

            this.bodyLayout.ColumnCount = 2;
            this.bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 300F));
            this.bodyLayout.Controls.Add(this.mapLayout, 0, 0);
            this.bodyLayout.Controls.Add(this.sideLayout, 1, 0);
            this.bodyLayout.Dock = DockStyle.Fill;
            this.bodyLayout.Padding = new Padding(8);
            this.bodyLayout.RowCount = 1;
            this.bodyLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

            this.mapLayout.ColumnCount = 1;
            this.mapLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.mapLayout.Controls.Add(this.lblMapTitle, 0, 0);
            this.mapLayout.Controls.Add(this.mapView, 0, 1);
            this.mapLayout.Dock = DockStyle.Fill;
            this.mapLayout.RowCount = 2;
            this.mapLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            this.mapLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

            this.lblMapTitle.BackColor = UiTheme.StatusBarBg;
            this.lblMapTitle.Dock = DockStyle.Fill;
            this.lblMapTitle.Font = UiTheme.SectionFont;
            this.lblMapTitle.ForeColor = Color.White;
            this.lblMapTitle.Padding = new Padding(10, 0, 0, 0);
            this.lblMapTitle.Tag = "i18n:recipe.inputMapCreate";
            this.lblMapTitle.Text = Lang.T("recipe.inputMapCreate");
            this.lblMapTitle.TextAlign = ContentAlignment.MiddleLeft;
            this.mapView.Caption = "Map Transfer";
            this.mapView.Dock = DockStyle.Fill;

            this.sideLayout.ColumnCount = 1;
            this.sideLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.sideLayout.Controls.Add(this.grpMapInfo, 0, 0);
            this.sideLayout.Controls.Add(this.grpMode, 0, 1);
            this.sideLayout.Controls.Add(this.grpJog, 0, 2);
            this.sideLayout.Controls.Add(this.actionLayout, 0, 3);
            this.sideLayout.Dock = DockStyle.Fill;
            this.sideLayout.RowCount = 4;
            this.sideLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 310F));
            this.sideLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 190F));
            this.sideLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 230F));
            this.sideLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

            this.grpMapInfo.BackColor = UiTheme.OptionPanelBg;
            this.grpMapInfo.Controls.Add(this.mapInfoLayout);
            this.grpMapInfo.Dock = DockStyle.Fill;
            this.grpMapInfo.Font = UiTheme.SectionFont;
            this.grpMapInfo.Margin = new Padding(4);
            this.grpMapInfo.Text = "MAP INFO";

            this.mapInfoLayout.ColumnCount = 2;
            this.mapInfoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 48F));
            this.mapInfoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 52F));
            this.mapInfoLayout.Controls.Add(this.lblChipWCaption, 0, 0);
            this.mapInfoLayout.Controls.Add(this.lblChipW, 1, 0);
            this.mapInfoLayout.Controls.Add(this.lblChipHCaption, 0, 1);
            this.mapInfoLayout.Controls.Add(this.lblChipH, 1, 1);
            this.mapInfoLayout.Controls.Add(this.lblPitchXCaption, 0, 2);
            this.mapInfoLayout.Controls.Add(this.lblPitchX, 1, 2);
            this.mapInfoLayout.Controls.Add(this.lblPitchYCaption, 0, 3);
            this.mapInfoLayout.Controls.Add(this.lblPitchY, 1, 3);
            this.mapInfoLayout.Controls.Add(this.lblWaferDiaCaption, 0, 4);
            this.mapInfoLayout.Controls.Add(this.lblWaferDia, 1, 4);
            this.mapInfoLayout.Controls.Add(this.lblAxisXCaption, 0, 5);
            this.mapInfoLayout.Controls.Add(this.lblAxisX, 1, 5);
            this.mapInfoLayout.Controls.Add(this.lblAxisYCaption, 0, 6);
            this.mapInfoLayout.Controls.Add(this.lblAxisY, 1, 6);
            this.mapInfoLayout.Controls.Add(this.lblBinRankCaption, 0, 7);
            this.mapInfoLayout.Controls.Add(this.lblBinRank, 1, 7);
            this.mapInfoLayout.Controls.Add(this.lblDieNumCaption, 0, 8);
            this.mapInfoLayout.Controls.Add(this.lblDieNum, 1, 8);
            this.mapInfoLayout.Dock = DockStyle.Fill;
            this.mapInfoLayout.Padding = new Padding(10, 16, 10, 10);
            this.mapInfoLayout.RowCount = 9;
            this.mapInfoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.mapInfoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.mapInfoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.mapInfoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.mapInfoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.mapInfoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.mapInfoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.mapInfoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.mapInfoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));

            this.lblChipWCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblChipWCaption.BorderStyle = BorderStyle.FixedSingle;
            this.lblChipWCaption.Dock = DockStyle.Fill;
            this.lblChipWCaption.Font = UiTheme.ButtonFont;
            this.lblChipWCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblChipWCaption.Text = "Chip Width";
            this.lblChipWCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblChipW.BackColor = Color.White;
            this.lblChipW.BorderStyle = BorderStyle.FixedSingle;
            this.lblChipW.Dock = DockStyle.Fill;
            this.lblChipW.Font = UiTheme.ValueFont;
            this.lblChipW.Padding = new Padding(0, 0, 6, 0);
            this.lblChipW.Text = "0";
            this.lblChipW.TextAlign = ContentAlignment.MiddleRight;
            this.lblChipHCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblChipHCaption.BorderStyle = BorderStyle.FixedSingle;
            this.lblChipHCaption.Dock = DockStyle.Fill;
            this.lblChipHCaption.Font = UiTheme.ButtonFont;
            this.lblChipHCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblChipHCaption.Text = "Chip Height";
            this.lblChipHCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblChipH.BackColor = Color.White;
            this.lblChipH.BorderStyle = BorderStyle.FixedSingle;
            this.lblChipH.Dock = DockStyle.Fill;
            this.lblChipH.Font = UiTheme.ValueFont;
            this.lblChipH.Padding = new Padding(0, 0, 6, 0);
            this.lblChipH.Text = "0";
            this.lblChipH.TextAlign = ContentAlignment.MiddleRight;
            this.lblPitchXCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblPitchXCaption.BorderStyle = BorderStyle.FixedSingle;
            this.lblPitchXCaption.Dock = DockStyle.Fill;
            this.lblPitchXCaption.Font = UiTheme.ButtonFont;
            this.lblPitchXCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblPitchXCaption.Text = "Pitch X";
            this.lblPitchXCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblPitchX.BackColor = Color.White;
            this.lblPitchX.BorderStyle = BorderStyle.FixedSingle;
            this.lblPitchX.Dock = DockStyle.Fill;
            this.lblPitchX.Font = UiTheme.ValueFont;
            this.lblPitchX.Padding = new Padding(0, 0, 6, 0);
            this.lblPitchX.Text = "0";
            this.lblPitchX.TextAlign = ContentAlignment.MiddleRight;
            this.lblPitchYCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblPitchYCaption.BorderStyle = BorderStyle.FixedSingle;
            this.lblPitchYCaption.Dock = DockStyle.Fill;
            this.lblPitchYCaption.Font = UiTheme.ButtonFont;
            this.lblPitchYCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblPitchYCaption.Text = "Pitch Y";
            this.lblPitchYCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblPitchY.BackColor = Color.White;
            this.lblPitchY.BorderStyle = BorderStyle.FixedSingle;
            this.lblPitchY.Dock = DockStyle.Fill;
            this.lblPitchY.Font = UiTheme.ValueFont;
            this.lblPitchY.Padding = new Padding(0, 0, 6, 0);
            this.lblPitchY.Text = "0";
            this.lblPitchY.TextAlign = ContentAlignment.MiddleRight;
            this.lblWaferDiaCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblWaferDiaCaption.BorderStyle = BorderStyle.FixedSingle;
            this.lblWaferDiaCaption.Dock = DockStyle.Fill;
            this.lblWaferDiaCaption.Font = UiTheme.ButtonFont;
            this.lblWaferDiaCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblWaferDiaCaption.Text = "Wafer Dia";
            this.lblWaferDiaCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblWaferDia.BackColor = Color.White;
            this.lblWaferDia.BorderStyle = BorderStyle.FixedSingle;
            this.lblWaferDia.Dock = DockStyle.Fill;
            this.lblWaferDia.Font = UiTheme.ValueFont;
            this.lblWaferDia.Padding = new Padding(0, 0, 6, 0);
            this.lblWaferDia.Text = "0";
            this.lblWaferDia.TextAlign = ContentAlignment.MiddleRight;
            this.lblAxisXCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblAxisXCaption.BorderStyle = BorderStyle.FixedSingle;
            this.lblAxisXCaption.Dock = DockStyle.Fill;
            this.lblAxisXCaption.Font = UiTheme.ButtonFont;
            this.lblAxisXCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblAxisXCaption.Text = "Axis X";
            this.lblAxisXCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblAxisX.BackColor = Color.White;
            this.lblAxisX.BorderStyle = BorderStyle.FixedSingle;
            this.lblAxisX.Dock = DockStyle.Fill;
            this.lblAxisX.Font = UiTheme.ValueFont;
            this.lblAxisX.Padding = new Padding(0, 0, 6, 0);
            this.lblAxisX.Text = "0";
            this.lblAxisX.TextAlign = ContentAlignment.MiddleRight;
            this.lblAxisYCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblAxisYCaption.BorderStyle = BorderStyle.FixedSingle;
            this.lblAxisYCaption.Dock = DockStyle.Fill;
            this.lblAxisYCaption.Font = UiTheme.ButtonFont;
            this.lblAxisYCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblAxisYCaption.Text = "Axis Y";
            this.lblAxisYCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblAxisY.BackColor = Color.White;
            this.lblAxisY.BorderStyle = BorderStyle.FixedSingle;
            this.lblAxisY.Dock = DockStyle.Fill;
            this.lblAxisY.Font = UiTheme.ValueFont;
            this.lblAxisY.Padding = new Padding(0, 0, 6, 0);
            this.lblAxisY.Text = "0";
            this.lblAxisY.TextAlign = ContentAlignment.MiddleRight;
            this.lblBinRankCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblBinRankCaption.BorderStyle = BorderStyle.FixedSingle;
            this.lblBinRankCaption.Dock = DockStyle.Fill;
            this.lblBinRankCaption.Font = UiTheme.ButtonFont;
            this.lblBinRankCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblBinRankCaption.Text = "BIN RANK";
            this.lblBinRankCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblBinRank.BackColor = Color.White;
            this.lblBinRank.BorderStyle = BorderStyle.FixedSingle;
            this.lblBinRank.Dock = DockStyle.Fill;
            this.lblBinRank.Font = UiTheme.ValueFont;
            this.lblBinRank.Padding = new Padding(0, 0, 6, 0);
            this.lblBinRank.Text = "0";
            this.lblBinRank.TextAlign = ContentAlignment.MiddleRight;
            this.lblDieNumCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblDieNumCaption.BorderStyle = BorderStyle.FixedSingle;
            this.lblDieNumCaption.Dock = DockStyle.Fill;
            this.lblDieNumCaption.Font = UiTheme.ButtonFont;
            this.lblDieNumCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblDieNumCaption.Text = "Die Number";
            this.lblDieNumCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblDieNum.BackColor = Color.White;
            this.lblDieNum.BorderStyle = BorderStyle.FixedSingle;
            this.lblDieNum.Dock = DockStyle.Fill;
            this.lblDieNum.Font = UiTheme.ValueFont;
            this.lblDieNum.Padding = new Padding(0, 0, 6, 0);
            this.lblDieNum.Text = "0/0";
            this.lblDieNum.TextAlign = ContentAlignment.MiddleRight;

            this.grpMode.BackColor = UiTheme.OptionPanelBg;
            this.grpMode.Controls.Add(this.modeLayout);
            this.grpMode.Dock = DockStyle.Fill;
            this.grpMode.Font = UiTheme.SectionFont;
            this.grpMode.Margin = new Padding(4);
            this.grpMode.Text = "MODE";
            this.modeLayout.ColumnCount = 1;
            this.modeLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.modeLayout.Controls.Add(this.rbStandard, 0, 0);
            this.modeLayout.Controls.Add(this.rbStartIndex, 0, 1);
            this.modeLayout.Controls.Add(this.rbSelectPickStatus, 0, 2);
            this.modeLayout.Controls.Add(this.rbDragPickStatus, 0, 3);
            this.modeLayout.Controls.Add(this.btnPickStatusSave, 0, 4);
            this.modeLayout.Dock = DockStyle.Fill;
            this.modeLayout.Padding = new Padding(12, 16, 12, 8);
            this.modeLayout.RowCount = 5;
            this.modeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            this.modeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            this.modeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            this.modeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            this.modeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            this.rbStandard.AutoSize = true;
            this.rbStandard.Checked = true;
            this.rbStandard.Dock = DockStyle.Fill;
            this.rbStandard.Font = UiTheme.ButtonFont;
            this.rbStandard.Text = "STANDARD";
            this.rbStartIndex.AutoSize = true;
            this.rbStartIndex.Dock = DockStyle.Fill;
            this.rbStartIndex.Font = UiTheme.ButtonFont;
            this.rbStartIndex.Text = "START INDEX";
            this.rbSelectPickStatus.AutoSize = true;
            this.rbSelectPickStatus.Dock = DockStyle.Fill;
            this.rbSelectPickStatus.Font = UiTheme.ButtonFont;
            this.rbSelectPickStatus.Text = "SELECT PICK STATUS";
            this.rbDragPickStatus.AutoSize = true;
            this.rbDragPickStatus.Dock = DockStyle.Fill;
            this.rbDragPickStatus.Font = UiTheme.ButtonFont;
            this.rbDragPickStatus.Text = "DRAG PICK STATUS";
            this.btnPickStatusSave.Dock = DockStyle.Fill;
            this.btnPickStatusSave.Font = UiTheme.ButtonFont;
            this.btnPickStatusSave.Margin = new Padding(4);
            this.btnPickStatusSave.Text = "SELECT PICK STATUS SAVE";

            this.grpJog.BackColor = UiTheme.OptionPanelBg;
            this.grpJog.Controls.Add(this.jogLayout);
            this.grpJog.Dock = DockStyle.Fill;
            this.grpJog.Font = UiTheme.SectionFont;
            this.grpJog.Margin = new Padding(4);
            this.grpJog.Text = "JOG";
            this.jogLayout.ColumnCount = 3;
            this.jogLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33F));
            this.jogLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33F));
            this.jogLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33F));
            this.jogLayout.Controls.Add(this.btnJogThetaCcw, 0, 0);
            this.jogLayout.Controls.Add(this.btnJogUp, 1, 0);
            this.jogLayout.Controls.Add(this.btnJogThetaCw, 2, 0);
            this.jogLayout.Controls.Add(this.btnJogLeft, 0, 1);
            this.jogLayout.Controls.Add(this.btnJogCenter, 1, 1);
            this.jogLayout.Controls.Add(this.btnJogRight, 2, 1);
            this.jogLayout.Controls.Add(this.btnJogDown, 1, 2);
            this.jogLayout.Dock = DockStyle.Fill;
            this.jogLayout.Padding = new Padding(12, 18, 12, 12);
            this.jogLayout.RowCount = 3;
            this.jogLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 33.33F));
            this.jogLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 33.33F));
            this.jogLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 33.33F));
            this.btnJogThetaCcw.Dock = DockStyle.Fill;
            this.btnJogThetaCcw.FlatStyle = FlatStyle.Flat;
            this.btnJogThetaCcw.Font = UiTheme.ButtonFont;
            this.btnJogThetaCcw.Margin = new Padding(3);
            this.btnJogThetaCcw.Text = "CCW";
            this.btnJogUp.Dock = DockStyle.Fill;
            this.btnJogUp.FlatStyle = FlatStyle.Flat;
            this.btnJogUp.Font = UiTheme.ButtonFont;
            this.btnJogUp.Margin = new Padding(3);
            this.btnJogUp.Text = "+Y";
            this.btnJogThetaCw.Dock = DockStyle.Fill;
            this.btnJogThetaCw.FlatStyle = FlatStyle.Flat;
            this.btnJogThetaCw.Font = UiTheme.ButtonFont;
            this.btnJogThetaCw.Margin = new Padding(3);
            this.btnJogThetaCw.Text = "CW";
            this.btnJogLeft.Dock = DockStyle.Fill;
            this.btnJogLeft.FlatStyle = FlatStyle.Flat;
            this.btnJogLeft.Font = UiTheme.ButtonFont;
            this.btnJogLeft.Margin = new Padding(3);
            this.btnJogLeft.Text = "-X";
            this.btnJogCenter.Dock = DockStyle.Fill;
            this.btnJogCenter.FlatStyle = FlatStyle.Flat;
            this.btnJogCenter.Font = UiTheme.ButtonFont;
            this.btnJogCenter.Margin = new Padding(3);
            this.btnJogCenter.Text = "STOP";
            this.btnJogRight.Dock = DockStyle.Fill;
            this.btnJogRight.FlatStyle = FlatStyle.Flat;
            this.btnJogRight.Font = UiTheme.ButtonFont;
            this.btnJogRight.Margin = new Padding(3);
            this.btnJogRight.Text = "+X";
            this.btnJogDown.Dock = DockStyle.Fill;
            this.btnJogDown.FlatStyle = FlatStyle.Flat;
            this.btnJogDown.Font = UiTheme.ButtonFont;
            this.btnJogDown.Margin = new Padding(3);
            this.btnJogDown.Text = "-Y";

            this.actionLayout.ColumnCount = 1;
            this.actionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.actionLayout.Controls.Add(this.btnManualAlignComplete, 0, 0);
            this.actionLayout.Controls.Add(this.btnNeedleBlockDown, 0, 1);
            this.actionLayout.Controls.Add(this.btnThetaMatchMove, 0, 2);
            this.actionLayout.Controls.Add(this.btnXyMatchMove, 0, 3);
            this.actionLayout.Controls.Add(this.btnClose, 0, 4);
            this.actionLayout.Dock = DockStyle.Top;
            this.actionLayout.RowCount = 5;
            this.actionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            this.actionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            this.actionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            this.actionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            this.actionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            this.btnManualAlignComplete.Dock = DockStyle.Fill;
            this.btnManualAlignComplete.Font = UiTheme.ButtonFont;
            this.btnManualAlignComplete.Margin = new Padding(4);
            this.btnManualAlignComplete.Text = "MANUAL ALIGN COMPLETE";
            this.btnNeedleBlockDown.Dock = DockStyle.Fill;
            this.btnNeedleBlockDown.Font = UiTheme.ButtonFont;
            this.btnNeedleBlockDown.Margin = new Padding(4);
            this.btnNeedleBlockDown.Text = "NEEDLE BLOCK DOWN";
            this.btnThetaMatchMove.Dock = DockStyle.Fill;
            this.btnThetaMatchMove.Font = UiTheme.ButtonFont;
            this.btnThetaMatchMove.Margin = new Padding(4);
            this.btnThetaMatchMove.Text = "THETA MATCH MOVE";
            this.btnXyMatchMove.Dock = DockStyle.Fill;
            this.btnXyMatchMove.Font = UiTheme.ButtonFont;
            this.btnXyMatchMove.Margin = new Padding(4);
            this.btnXyMatchMove.Text = "X_Y_MATCH MOVE";
            this.btnClose.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.btnClose.Dock = DockStyle.Fill;
            this.btnClose.FlatStyle = FlatStyle.Flat;
            this.btnClose.Font = UiTheme.ButtonFont;
            this.btnClose.Margin = new Padding(4);
            this.btnClose.Text = "CLOSE";

            this.Controls.Add(this.rootLayout);
            this.Name = "MapTransferPage";
            this.Size = new Size(1678, 900);
            this.ResumeLayout(false);
        }
    }
}

