namespace QMC.CDT_320.Ui.Pages.Work
{
    partial class VisionAlignPage
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.Panel camPanel;
        private System.Windows.Forms.Label lblCameraInfo;
        private System.Windows.Forms.Label lblLive;
        private System.Windows.Forms.TableLayoutPanel sideLayout;
        private System.Windows.Forms.Label lblActionHeader;
        private QMC.CDT_320.Ui.Controls.ActionButton btnAutoAlign;
        private QMC.CDT_320.Ui.Controls.ActionButton btnManualAlign;
        private QMC.CDT_320.Ui.Controls.ActionButton btnFirstMark;
        private QMC.CDT_320.Ui.Controls.ActionButton btnSecondMark;
        private QMC.CDT_320.Ui.Controls.ActionButton btnThetaMatch;
        private QMC.CDT_320.Ui.Controls.ActionButton btnXyMatch;
        private QMC.CDT_320.Ui.Controls.ActionButton btnSave;
        private QMC.CDT_320.Ui.Controls.ActionButton btnClose;
        private System.Windows.Forms.Label lblResultHeader;
        private System.Windows.Forms.TableLayoutPanel resultLayout;
        private System.Windows.Forms.Label lblDeltaXCaption;
        private System.Windows.Forms.Label lblDeltaXValue;
        private System.Windows.Forms.Label lblDeltaYCaption;
        private System.Windows.Forms.Label lblDeltaYValue;
        private System.Windows.Forms.Label lblDeltaThetaCaption;
        private System.Windows.Forms.Label lblDeltaThetaValue;
        private System.Windows.Forms.Label lblScoreCaption;
        private System.Windows.Forms.Label lblScoreValue;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.camPanel = new System.Windows.Forms.Panel();
            this.lblCameraInfo = new System.Windows.Forms.Label();
            this.lblLive = new System.Windows.Forms.Label();
            this.sideLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblActionHeader = new System.Windows.Forms.Label();
            this.btnAutoAlign = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnManualAlign = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnFirstMark = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnSecondMark = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnThetaMatch = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnXyMatch = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnSave = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnClose = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.lblResultHeader = new System.Windows.Forms.Label();
            this.resultLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblDeltaXCaption = new System.Windows.Forms.Label();
            this.lblDeltaXValue = new System.Windows.Forms.Label();
            this.lblDeltaYCaption = new System.Windows.Forms.Label();
            this.lblDeltaYValue = new System.Windows.Forms.Label();
            this.lblDeltaThetaCaption = new System.Windows.Forms.Label();
            this.lblDeltaThetaValue = new System.Windows.Forms.Label();
            this.lblScoreCaption = new System.Windows.Forms.Label();
            this.lblScoreValue = new System.Windows.Forms.Label();
            this.rootLayout.SuspendLayout();
            this.camPanel.SuspendLayout();
            this.sideLayout.SuspendLayout();
            this.resultLayout.SuspendLayout();
            this.SuspendLayout();
            this.rootLayout.ColumnCount = 2;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 330F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.camPanel, 0, 1);
            this.rootLayout.Controls.Add(this.sideLayout, 1, 1);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Padding = new System.Windows.Forms.Padding(8);
            this.rootLayout.RowCount = 2;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.SetColumnSpan(this.lblHeader, 2);
            this.lblHeader.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblHeader.ForeColor = System.Drawing.Color.White;
            this.lblHeader.Margin = new System.Windows.Forms.Padding(0, 0, 0, 6);
            this.lblHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblHeader.Text = "VISION ALIGN";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.camPanel.BackColor = System.Drawing.Color.Black;
            this.camPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.camPanel.Controls.Add(this.lblCameraInfo);
            this.camPanel.Controls.Add(this.lblLive);
            this.camPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.camPanel.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.lblCameraInfo.AutoSize = true;
            this.lblCameraInfo.BackColor = System.Drawing.Color.Black;
            this.lblCameraInfo.Font = new System.Drawing.Font("Consolas", 9F);
            this.lblCameraInfo.ForeColor = System.Drawing.Color.LightGreen;
            this.lblCameraInfo.Location = new System.Drawing.Point(8, 8);
            this.lblCameraInfo.Text = "STAGE\r\nW : 640\r\nH : 480";
            this.lblLive.BackColor = System.Drawing.Color.Black;
            this.lblLive.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.lblLive.Font = new System.Drawing.Font("Consolas", 9F);
            this.lblLive.ForeColor = System.Drawing.Color.LightGreen;
            this.lblLive.Height = 22;
            this.lblLive.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblLive.Text = "Live";
            this.lblLive.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.sideLayout.ColumnCount = 1;
            this.sideLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.sideLayout.Controls.Add(this.lblActionHeader, 0, 0);
            this.sideLayout.Controls.Add(this.btnAutoAlign, 0, 1);
            this.sideLayout.Controls.Add(this.btnManualAlign, 0, 2);
            this.sideLayout.Controls.Add(this.btnFirstMark, 0, 3);
            this.sideLayout.Controls.Add(this.btnSecondMark, 0, 4);
            this.sideLayout.Controls.Add(this.btnThetaMatch, 0, 5);
            this.sideLayout.Controls.Add(this.btnXyMatch, 0, 6);
            this.sideLayout.Controls.Add(this.btnSave, 0, 7);
            this.sideLayout.Controls.Add(this.btnClose, 0, 8);
            this.sideLayout.Controls.Add(this.lblResultHeader, 0, 10);
            this.sideLayout.Controls.Add(this.resultLayout, 0, 11);
            this.sideLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sideLayout.RowCount = 13;
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 14F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 132F));
            this.sideLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lblActionHeader.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.lblActionHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblActionHeader.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblActionHeader.ForeColor = System.Drawing.Color.White;
            this.lblActionHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblActionHeader.Text = "ACTION";
            this.lblActionHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAutoAlign.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnAutoAlign.Margin = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.btnAutoAlign.Text = "AUTO ALIGN";
            this.btnManualAlign.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnManualAlign.Margin = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.btnManualAlign.Text = "MANUAL ALIGN";
            this.btnFirstMark.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnFirstMark.Margin = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.btnFirstMark.Text = "FIRST MARK";
            this.btnSecondMark.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnSecondMark.Margin = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.btnSecondMark.Text = "SECOND MARK";
            this.btnThetaMatch.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnThetaMatch.Margin = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.btnThetaMatch.Text = "THETA MATCH";
            this.btnXyMatch.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnXyMatch.Margin = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.btnXyMatch.Text = "X_Y MATCH";
            this.btnSave.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnSave.Margin = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.btnSave.Text = "SAVE";
            this.btnClose.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnClose.Margin = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.btnClose.Text = "CLOSE";
            this.lblResultHeader.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.lblResultHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblResultHeader.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblResultHeader.ForeColor = System.Drawing.Color.White;
            this.lblResultHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblResultHeader.Text = "RESULT";
            this.lblResultHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.resultLayout.ColumnCount = 2;
            this.resultLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 132F));
            this.resultLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.resultLayout.Controls.Add(this.lblDeltaXCaption, 0, 0);
            this.resultLayout.Controls.Add(this.lblDeltaXValue, 1, 0);
            this.resultLayout.Controls.Add(this.lblDeltaYCaption, 0, 1);
            this.resultLayout.Controls.Add(this.lblDeltaYValue, 1, 1);
            this.resultLayout.Controls.Add(this.lblDeltaThetaCaption, 0, 2);
            this.resultLayout.Controls.Add(this.lblDeltaThetaValue, 1, 2);
            this.resultLayout.Controls.Add(this.lblScoreCaption, 0, 3);
            this.resultLayout.Controls.Add(this.lblScoreValue, 1, 3);
            this.resultLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.resultLayout.RowCount = 4;
            this.resultLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.resultLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.resultLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.resultLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.lblDeltaXCaption.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblDeltaXCaption.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDeltaXCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDeltaXCaption.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDeltaXCaption.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblDeltaXCaption.Text = "Delta X";
            this.lblDeltaXCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblDeltaXValue.BackColor = System.Drawing.Color.White;
            this.lblDeltaXValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDeltaXValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDeltaXValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblDeltaXValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblDeltaXValue.Text = "0.000";
            this.lblDeltaXValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblDeltaYCaption.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblDeltaYCaption.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDeltaYCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDeltaYCaption.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDeltaYCaption.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblDeltaYCaption.Text = "Delta Y";
            this.lblDeltaYCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblDeltaYValue.BackColor = System.Drawing.Color.White;
            this.lblDeltaYValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDeltaYValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDeltaYValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblDeltaYValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblDeltaYValue.Text = "0.000";
            this.lblDeltaYValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblDeltaThetaCaption.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblDeltaThetaCaption.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDeltaThetaCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDeltaThetaCaption.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDeltaThetaCaption.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblDeltaThetaCaption.Text = "Delta Theta";
            this.lblDeltaThetaCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblDeltaThetaValue.BackColor = System.Drawing.Color.White;
            this.lblDeltaThetaValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDeltaThetaValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDeltaThetaValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblDeltaThetaValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblDeltaThetaValue.Text = "0.000 deg";
            this.lblDeltaThetaValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblScoreCaption.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblScoreCaption.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblScoreCaption.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblScoreCaption.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblScoreCaption.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblScoreCaption.Text = "Score";
            this.lblScoreCaption.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblScoreValue.BackColor = System.Drawing.Color.White;
            this.lblScoreValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblScoreValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblScoreValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblScoreValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblScoreValue.Text = "0.0";
            this.lblScoreValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.rootLayout);
            this.Name = "VisionAlignPage";
            this.Size = new System.Drawing.Size(1416, 980);
            this.resultLayout.ResumeLayout(false);
            this.sideLayout.ResumeLayout(false);
            this.camPanel.ResumeLayout(false);
            this.camPanel.PerformLayout();
            this.rootLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }

    partial class WaferMapOpenPage
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.Label lblListHeader;
        private System.Windows.Forms.ListBox lbMapFiles;
        private System.Windows.Forms.Label lblMapHeader;
        private System.Windows.Forms.Panel mapPanel;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.lblListHeader = new System.Windows.Forms.Label();
            this.lbMapFiles = new System.Windows.Forms.ListBox();
            this.lblMapHeader = new System.Windows.Forms.Label();
            this.mapPanel = new System.Windows.Forms.Panel();
            this.rootLayout.SuspendLayout();
            this.SuspendLayout();
            this.rootLayout.ColumnCount = 2;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 372F));
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.lblListHeader, 0, 1);
            this.rootLayout.Controls.Add(this.lbMapFiles, 0, 2);
            this.rootLayout.Controls.Add(this.lblMapHeader, 1, 1);
            this.rootLayout.Controls.Add(this.mapPanel, 1, 2);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Padding = new System.Windows.Forms.Padding(8);
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.SetColumnSpan(this.lblHeader, 2);
            this.lblHeader.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblHeader.ForeColor = System.Drawing.Color.White;
            this.lblHeader.Margin = new System.Windows.Forms.Padding(0, 0, 0, 6);
            this.lblHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblHeader.Text = "WAFER MAP OPEN";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblListHeader.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.lblListHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblListHeader.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblListHeader.ForeColor = System.Drawing.Color.White;
            this.lblListHeader.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.lblListHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblListHeader.Text = "MAP FILE LIST";
            this.lblListHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lbMapFiles.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lbMapFiles.Font = new System.Drawing.Font("Consolas", 9F);
            this.lbMapFiles.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.lblMapHeader.BackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            this.lblMapHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblMapHeader.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblMapHeader.ForeColor = System.Drawing.Color.White;
            this.lblMapHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblMapHeader.Text = "MAP VIEW";
            this.lblMapHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mapPanel.BackColor = System.Drawing.Color.Black;
            this.mapPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.mapPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.rootLayout);
            this.Name = "WaferMapOpenPage";
            this.Size = new System.Drawing.Size(1416, 980);
            this.rootLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
