using System.Drawing;
using System.Windows.Forms;
using QMC.CDT_320.Ui.Controls;
using QMC.CDT_320.Ui.Localization;

namespace QMC.CDT_320.Ui.Pages.Work
{
    partial class WorkMainPage
    {
        private TableLayoutPanel rootLayout;
        private TableLayoutPanel visionLayout;
        private TableLayoutPanel mapLayout;
        private TableLayoutPanel infoLayout;
        private TableLayoutPanel timeLayout;
        private Label lblVisionHeader;
        private Label lblMapHeader;
        private Label lblInfoHeader;
        private Label lblTimeHeader;
        private Panel visionPanel;
        private LiveLotMapView lotMapView;
        private TableLayoutPanel mapHeaderLayout;
        private Label lblTotalChipCaption;
        private Label lblTotalChip;
        private Label lblBinNumCaption;
        private Label lblBinNum;
        private Label lblVisionCaption;
        private Label lblPickCaption;
        private Label lblPlaceCaption;
        private Label lblStageInfo;
        private Label lblLive;
        private TableLayoutPanel workInfoBody;
        private TableLayoutPanel workTimeBody;
        private Label lblProjectCaption;
        private Label lblProject;
        private Label lblPickFailCaption;
        private Label lblPickFail;
        private Label lblBinQtyCaption;
        private Label lblBinQty;
        private Label lblCollet1Caption;
        private Label lblCollet1;
        private Label lblPlaceFailCaption;
        private Label lblPlaceFail;
        private Label lblNeedleCaption;
        private Label lblNeedle;
        private Label lblCollet2Caption;
        private Label lblCollet2;
        private Label lblBinArrMonCaption;
        private Label lblBinArrMon;
        private Label lblLoadCaption;
        private Label lblLoad;
        private Label lblUpCaption;
        private Label lblUp;
        private Label lblContUpCaption;
        private Label lblContUp;
        private Label lblNormDownCaption;
        private Label lblNormDown;
        private Label lblErrDownCaption;
        private Label lblErrDown;
        private Label lblErrCntCaption;
        private Label lblErrCnt;
        private Label lblRecoveryCaption;
        private Label lblRecovery;
        private Label lblUphCaption;
        private Label lblUph;
        private Label lblMtbfCaption;
        private Label lblMtbf;
        private Label lblMttrCaption;
        private Label lblMttr;
        private Label lblCycleCaption;
        private Label lblCycle;
        private Label lblRateCaption;
        private Label lblRate;
        private Label lblLotCaption;
        private Label lblLot;
        private Button btnCcs;

        private void InitializeComponent()
        {
            this.rootLayout = new TableLayoutPanel();
            this.visionLayout = new TableLayoutPanel();
            this.mapLayout = new TableLayoutPanel();
            this.infoLayout = new TableLayoutPanel();
            this.timeLayout = new TableLayoutPanel();
            this.lblVisionHeader = new Label();
            this.lblMapHeader = new Label();
            this.lblInfoHeader = new Label();
            this.lblTimeHeader = new Label();
            this.visionPanel = new Panel();
            this.lotMapView = new LiveLotMapView();
            this.mapHeaderLayout = new TableLayoutPanel();
            this.lblTotalChipCaption = new Label();
            this.lblTotalChip = new Label();
            this.lblBinNumCaption = new Label();
            this.lblBinNum = new Label();
            this.lblVisionCaption = new Label();
            this.lblPickCaption = new Label();
            this.lblPlaceCaption = new Label();
            this.lblStageInfo = new Label();
            this.lblLive = new Label();
            this.workInfoBody = new TableLayoutPanel();
            this.workTimeBody = new TableLayoutPanel();
            this.lblProjectCaption = new Label();
            this.lblProject = new Label();
            this.lblPickFailCaption = new Label();
            this.lblPickFail = new Label();
            this.lblBinQtyCaption = new Label();
            this.lblBinQty = new Label();
            this.lblCollet1Caption = new Label();
            this.lblCollet1 = new Label();
            this.lblPlaceFailCaption = new Label();
            this.lblPlaceFail = new Label();
            this.lblNeedleCaption = new Label();
            this.lblNeedle = new Label();
            this.lblCollet2Caption = new Label();
            this.lblCollet2 = new Label();
            this.lblBinArrMonCaption = new Label();
            this.lblBinArrMon = new Label();
            this.lblLoadCaption = new Label();
            this.lblLoad = new Label();
            this.lblUpCaption = new Label();
            this.lblUp = new Label();
            this.lblContUpCaption = new Label();
            this.lblContUp = new Label();
            this.lblNormDownCaption = new Label();
            this.lblNormDown = new Label();
            this.lblErrDownCaption = new Label();
            this.lblErrDown = new Label();
            this.lblErrCntCaption = new Label();
            this.lblErrCnt = new Label();
            this.lblRecoveryCaption = new Label();
            this.lblRecovery = new Label();
            this.lblUphCaption = new Label();
            this.lblUph = new Label();
            this.lblMtbfCaption = new Label();
            this.lblMtbf = new Label();
            this.lblMttrCaption = new Label();
            this.lblMttr = new Label();
            this.lblCycleCaption = new Label();
            this.lblCycle = new Label();
            this.lblRateCaption = new Label();
            this.lblRate = new Label();
            this.lblLotCaption = new Label();
            this.lblLot = new Label();
            this.btnCcs = new Button();
            this.SuspendLayout();

            this.rootLayout.BackColor = UiTheme.MainBg;
            this.rootLayout.CellBorderStyle = TableLayoutPanelCellBorderStyle.Single;
            this.rootLayout.ColumnCount = 2;
            this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this.rootLayout.Controls.Add(this.visionLayout, 0, 0);
            this.rootLayout.Controls.Add(this.mapLayout, 1, 0);
            this.rootLayout.Controls.Add(this.infoLayout, 0, 1);
            this.rootLayout.Controls.Add(this.timeLayout, 1, 1);
            this.rootLayout.Dock = DockStyle.Fill;
            this.rootLayout.RowCount = 2;
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 55F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 45F));

            this.visionLayout.BackColor = UiTheme.MainBg;
            this.visionLayout.ColumnCount = 1;
            this.visionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.visionLayout.Controls.Add(this.lblVisionHeader, 0, 0);
            this.visionLayout.Controls.Add(this.visionPanel, 0, 1);
            this.visionLayout.Dock = DockStyle.Fill;
            this.visionLayout.RowCount = 2;
            this.visionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.visionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.lblVisionHeader.BackColor = UiTheme.StatusBarBg;
            this.lblVisionHeader.Dock = DockStyle.Fill;
            this.lblVisionHeader.Font = UiTheme.SectionFont;
            this.lblVisionHeader.ForeColor = UiTheme.StatusBarFg;
            this.lblVisionHeader.Padding = new Padding(10, 0, 0, 0);
            this.lblVisionHeader.Tag = "i18n:work.sec.visionView";
            this.lblVisionHeader.Text = Lang.T("work.sec.visionView");
            this.lblVisionHeader.TextAlign = ContentAlignment.MiddleLeft;

            this.visionPanel.BackColor = Color.Black;
            this.visionPanel.Controls.Add(this.lblStageInfo);
            this.visionPanel.Controls.Add(this.lblLive);
            this.visionPanel.Dock = DockStyle.Fill;
            this.lblStageInfo.AutoSize = true;
            this.lblStageInfo.BackColor = Color.Black;
            this.lblStageInfo.Font = new Font("Consolas", 9F);
            this.lblStageInfo.ForeColor = UiTheme.VisionInfoFg;
            this.lblStageInfo.Location = new Point(8, 8);
            this.lblStageInfo.Text = "STAGE\r\nW : 640\r\nH : 480\r\nframe : 0";
            this.lblLive.BackColor = Color.Black;
            this.lblLive.Dock = DockStyle.Bottom;
            this.lblLive.Font = new Font("Consolas", 9F);
            this.lblLive.ForeColor = UiTheme.VisionInfoFg;
            this.lblLive.Height = 18;
            this.lblLive.Padding = new Padding(6, 0, 0, 0);
            this.lblLive.Text = "Live";
            this.lblLive.TextAlign = ContentAlignment.MiddleLeft;

            this.mapLayout.BackColor = UiTheme.MainBg;
            this.mapLayout.ColumnCount = 1;
            this.mapLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.mapLayout.Controls.Add(this.lblMapHeader, 0, 0);
            this.mapLayout.Controls.Add(this.mapHeaderLayout, 0, 1);
            this.mapLayout.Controls.Add(this.lotMapView, 0, 2);
            this.mapLayout.Dock = DockStyle.Fill;
            this.mapLayout.RowCount = 3;
            this.mapLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.mapLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            this.mapLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.lblMapHeader.BackColor = UiTheme.StatusBarBg;
            this.lblMapHeader.Dock = DockStyle.Fill;
            this.lblMapHeader.Font = UiTheme.SectionFont;
            this.lblMapHeader.ForeColor = UiTheme.StatusBarFg;
            this.lblMapHeader.Padding = new Padding(10, 0, 0, 0);
            this.lblMapHeader.Tag = "i18n:work.sec.workMap";
            this.lblMapHeader.Text = Lang.T("work.sec.workMap");
            this.lblMapHeader.TextAlign = ContentAlignment.MiddleLeft;
            this.lotMapView.Dock = DockStyle.Fill;

            this.mapHeaderLayout.BackColor = UiTheme.StatusBarBg;
            this.mapHeaderLayout.ColumnCount = 8;
            this.mapHeaderLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90F));
            this.mapHeaderLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 80F));
            this.mapHeaderLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 60F));
            this.mapHeaderLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 80F));
            this.mapHeaderLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.mapHeaderLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 80F));
            this.mapHeaderLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 70F));
            this.mapHeaderLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 70F));
            this.mapHeaderLayout.Controls.Add(this.lblTotalChipCaption, 0, 0);
            this.mapHeaderLayout.Controls.Add(this.lblTotalChip, 1, 0);
            this.mapHeaderLayout.Controls.Add(this.lblBinNumCaption, 2, 0);
            this.mapHeaderLayout.Controls.Add(this.lblBinNum, 3, 0);
            this.mapHeaderLayout.Controls.Add(this.lblVisionCaption, 5, 0);
            this.mapHeaderLayout.Controls.Add(this.lblPickCaption, 6, 0);
            this.mapHeaderLayout.Controls.Add(this.lblPlaceCaption, 7, 0);
            this.mapHeaderLayout.Dock = DockStyle.Fill;
            this.mapHeaderLayout.RowCount = 1;
            this.mapHeaderLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.lblTotalChipCaption.Dock = DockStyle.Fill;
            this.lblTotalChipCaption.Font = UiTheme.StatusBarFont;
            this.lblTotalChipCaption.ForeColor = UiTheme.StatusBarFg;
            this.lblTotalChipCaption.Text = "Total Chip :";
            this.lblTotalChipCaption.TextAlign = ContentAlignment.MiddleCenter;
            this.lblTotalChip.Dock = DockStyle.Fill;
            this.lblTotalChip.Font = new Font("Consolas", 10F, FontStyle.Bold);
            this.lblTotalChip.ForeColor = UiTheme.StatusBarFg;
            this.lblTotalChip.Text = "0";
            this.lblTotalChip.TextAlign = ContentAlignment.MiddleLeft;
            this.lblBinNumCaption.Dock = DockStyle.Fill;
            this.lblBinNumCaption.Font = UiTheme.StatusBarFont;
            this.lblBinNumCaption.ForeColor = UiTheme.StatusBarFg;
            this.lblBinNumCaption.Text = "Bin # :";
            this.lblBinNumCaption.TextAlign = ContentAlignment.MiddleCenter;
            this.lblBinNum.Dock = DockStyle.Fill;
            this.lblBinNum.Font = new Font("Consolas", 10F, FontStyle.Bold);
            this.lblBinNum.ForeColor = UiTheme.StatusBarFg;
            this.lblBinNum.Text = "--";
            this.lblBinNum.TextAlign = ContentAlignment.MiddleLeft;
            this.lblVisionCaption.Dock = DockStyle.Fill;
            this.lblVisionCaption.Font = UiTheme.StatusBarFont;
            this.lblVisionCaption.ForeColor = UiTheme.StatusBarFg;
            this.lblVisionCaption.Text = "VISION";
            this.lblVisionCaption.TextAlign = ContentAlignment.MiddleCenter;
            this.lblPickCaption.Dock = DockStyle.Fill;
            this.lblPickCaption.Font = UiTheme.StatusBarFont;
            this.lblPickCaption.ForeColor = UiTheme.StatusBarFg;
            this.lblPickCaption.Text = "PICK";
            this.lblPickCaption.TextAlign = ContentAlignment.MiddleCenter;
            this.lblPlaceCaption.Dock = DockStyle.Fill;
            this.lblPlaceCaption.Font = UiTheme.StatusBarFont;
            this.lblPlaceCaption.ForeColor = UiTheme.StatusBarFg;
            this.lblPlaceCaption.Text = "PLACE";
            this.lblPlaceCaption.TextAlign = ContentAlignment.MiddleCenter;

            this.infoLayout.BackColor = UiTheme.MainBg;
            this.infoLayout.ColumnCount = 1;
            this.infoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.infoLayout.Controls.Add(this.lblInfoHeader, 0, 0);
            this.infoLayout.Controls.Add(this.workInfoBody, 0, 1);
            this.infoLayout.Dock = DockStyle.Fill;
            this.infoLayout.RowCount = 2;
            this.infoLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.infoLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.lblInfoHeader.BackColor = UiTheme.StatusBarBg;
            this.lblInfoHeader.Dock = DockStyle.Fill;
            this.lblInfoHeader.Font = UiTheme.SectionFont;
            this.lblInfoHeader.ForeColor = UiTheme.StatusBarFg;
            this.lblInfoHeader.Padding = new Padding(10, 0, 0, 0);
            this.lblInfoHeader.Tag = "i18n:work.sec.workInfo";
            this.lblInfoHeader.Text = Lang.T("work.sec.workInfo");
            this.lblInfoHeader.TextAlign = ContentAlignment.MiddleLeft;
            this.workInfoBody.BackColor = UiTheme.OptionPanelBg;
            this.workInfoBody.ColumnCount = 4;
            this.workInfoBody.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.workInfoBody.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.workInfoBody.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.workInfoBody.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.workInfoBody.Controls.Add(this.lblProjectCaption, 0, 0);
            this.workInfoBody.Controls.Add(this.lblProject, 1, 0);
            this.workInfoBody.Controls.Add(this.lblPickFailCaption, 0, 1);
            this.workInfoBody.Controls.Add(this.lblPickFail, 1, 1);
            this.workInfoBody.Controls.Add(this.lblBinQtyCaption, 2, 1);
            this.workInfoBody.Controls.Add(this.lblBinQty, 3, 1);
            this.workInfoBody.Controls.Add(this.lblCollet1Caption, 0, 2);
            this.workInfoBody.Controls.Add(this.lblCollet1, 1, 2);
            this.workInfoBody.Controls.Add(this.lblPlaceFailCaption, 2, 2);
            this.workInfoBody.Controls.Add(this.lblPlaceFail, 3, 2);
            this.workInfoBody.Controls.Add(this.lblNeedleCaption, 0, 3);
            this.workInfoBody.Controls.Add(this.lblNeedle, 1, 3);
            this.workInfoBody.Controls.Add(this.lblCollet2Caption, 2, 3);
            this.workInfoBody.Controls.Add(this.lblCollet2, 3, 3);
            this.workInfoBody.Controls.Add(this.lblBinArrMonCaption, 0, 4);
            this.workInfoBody.Controls.Add(this.lblBinArrMon, 1, 4);
            this.workInfoBody.Dock = DockStyle.Fill;
            this.workInfoBody.Padding = new Padding(6);
            this.workInfoBody.RowCount = 5;
            this.workInfoBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.workInfoBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.workInfoBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.workInfoBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.workInfoBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));

            this.timeLayout.BackColor = UiTheme.MainBg;
            this.timeLayout.ColumnCount = 1;
            this.timeLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.timeLayout.Controls.Add(this.lblTimeHeader, 0, 0);
            this.timeLayout.Controls.Add(this.workTimeBody, 0, 1);
            this.timeLayout.Dock = DockStyle.Fill;
            this.timeLayout.RowCount = 2;
            this.timeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.timeLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.lblTimeHeader.BackColor = UiTheme.StatusBarBg;
            this.lblTimeHeader.Dock = DockStyle.Fill;
            this.lblTimeHeader.Font = UiTheme.SectionFont;
            this.lblTimeHeader.ForeColor = UiTheme.StatusBarFg;
            this.lblTimeHeader.Padding = new Padding(10, 0, 0, 0);
            this.lblTimeHeader.Tag = "i18n:work.sec.workTime";
            this.lblTimeHeader.Text = Lang.T("work.sec.workTime");
            this.lblTimeHeader.TextAlign = ContentAlignment.MiddleLeft;
            this.workTimeBody.BackColor = UiTheme.OptionPanelBg;
            this.workTimeBody.ColumnCount = 4;
            this.workTimeBody.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.workTimeBody.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.workTimeBody.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.workTimeBody.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.workTimeBody.Controls.Add(this.lblLoadCaption, 0, 0);
            this.workTimeBody.Controls.Add(this.lblLoad, 1, 0);
            this.workTimeBody.Controls.Add(this.lblUpCaption, 2, 0);
            this.workTimeBody.Controls.Add(this.lblUp, 3, 0);
            this.workTimeBody.Controls.Add(this.lblContUpCaption, 0, 1);
            this.workTimeBody.Controls.Add(this.lblContUp, 1, 1);
            this.workTimeBody.Controls.Add(this.lblNormDownCaption, 2, 1);
            this.workTimeBody.Controls.Add(this.lblNormDown, 3, 1);
            this.workTimeBody.Controls.Add(this.lblErrDownCaption, 0, 2);
            this.workTimeBody.Controls.Add(this.lblErrDown, 1, 2);
            this.workTimeBody.Controls.Add(this.lblErrCntCaption, 2, 2);
            this.workTimeBody.Controls.Add(this.lblErrCnt, 3, 2);
            this.workTimeBody.Controls.Add(this.lblRecoveryCaption, 0, 3);
            this.workTimeBody.Controls.Add(this.lblRecovery, 1, 3);
            this.workTimeBody.Controls.Add(this.lblUphCaption, 2, 3);
            this.workTimeBody.Controls.Add(this.lblUph, 3, 3);
            this.workTimeBody.Controls.Add(this.lblMtbfCaption, 0, 4);
            this.workTimeBody.Controls.Add(this.lblMtbf, 1, 4);
            this.workTimeBody.Controls.Add(this.lblMttrCaption, 2, 4);
            this.workTimeBody.Controls.Add(this.lblMttr, 3, 4);
            this.workTimeBody.Controls.Add(this.lblCycleCaption, 0, 5);
            this.workTimeBody.Controls.Add(this.lblCycle, 1, 5);
            this.workTimeBody.Controls.Add(this.lblRateCaption, 2, 5);
            this.workTimeBody.Controls.Add(this.lblRate, 3, 5);
            this.workTimeBody.Controls.Add(this.lblLotCaption, 0, 6);
            this.workTimeBody.Controls.Add(this.lblLot, 1, 6);
            this.workTimeBody.Controls.Add(this.btnCcs, 2, 6);
            this.workTimeBody.Dock = DockStyle.Fill;
            this.workTimeBody.Padding = new Padding(6);
            this.workTimeBody.RowCount = 7;
            this.workTimeBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.workTimeBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.workTimeBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.workTimeBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.workTimeBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.workTimeBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.workTimeBody.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            this.workTimeBody.SetColumnSpan(this.btnCcs, 2);

            this.lblProjectCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblProjectCaption.Dock = DockStyle.Fill;
            this.lblProjectCaption.Font = UiTheme.ButtonFont;
            this.lblProjectCaption.Margin = new Padding(1);
            this.lblProjectCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblProjectCaption.Tag = "i18n:work.workInfo.project";
            this.lblProjectCaption.Text = Lang.T("work.workInfo.project");
            this.lblProjectCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblPickFailCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblPickFailCaption.Dock = DockStyle.Fill;
            this.lblPickFailCaption.Font = UiTheme.ButtonFont;
            this.lblPickFailCaption.Margin = new Padding(1);
            this.lblPickFailCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblPickFailCaption.Tag = "i18n:work.workInfo.pickFail";
            this.lblPickFailCaption.Text = Lang.T("work.workInfo.pickFail");
            this.lblPickFailCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblBinQtyCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblBinQtyCaption.Dock = DockStyle.Fill;
            this.lblBinQtyCaption.Font = UiTheme.ButtonFont;
            this.lblBinQtyCaption.Margin = new Padding(1);
            this.lblBinQtyCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblBinQtyCaption.Tag = "i18n:work.workInfo.workBinQty";
            this.lblBinQtyCaption.Text = Lang.T("work.workInfo.workBinQty");
            this.lblBinQtyCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblCollet1Caption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblCollet1Caption.Dock = DockStyle.Fill;
            this.lblCollet1Caption.Font = UiTheme.ButtonFont;
            this.lblCollet1Caption.Margin = new Padding(1);
            this.lblCollet1Caption.Padding = new Padding(6, 0, 0, 0);
            this.lblCollet1Caption.Tag = "i18n:work.workInfo.collet1Use";
            this.lblCollet1Caption.Text = Lang.T("work.workInfo.collet1Use");
            this.lblCollet1Caption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblPlaceFailCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblPlaceFailCaption.Dock = DockStyle.Fill;
            this.lblPlaceFailCaption.Font = UiTheme.ButtonFont;
            this.lblPlaceFailCaption.Margin = new Padding(1);
            this.lblPlaceFailCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblPlaceFailCaption.Tag = "i18n:work.workInfo.placeFail";
            this.lblPlaceFailCaption.Text = Lang.T("work.workInfo.placeFail");
            this.lblPlaceFailCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblNeedleCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblNeedleCaption.Dock = DockStyle.Fill;
            this.lblNeedleCaption.Font = UiTheme.ButtonFont;
            this.lblNeedleCaption.Margin = new Padding(1);
            this.lblNeedleCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblNeedleCaption.Tag = "i18n:work.workInfo.needleUse";
            this.lblNeedleCaption.Text = Lang.T("work.workInfo.needleUse");
            this.lblNeedleCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblCollet2Caption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblCollet2Caption.Dock = DockStyle.Fill;
            this.lblCollet2Caption.Font = UiTheme.ButtonFont;
            this.lblCollet2Caption.Margin = new Padding(1);
            this.lblCollet2Caption.Padding = new Padding(6, 0, 0, 0);
            this.lblCollet2Caption.Tag = "i18n:work.workInfo.collet2Use";
            this.lblCollet2Caption.Text = Lang.T("work.workInfo.collet2Use");
            this.lblCollet2Caption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblBinArrMonCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblBinArrMonCaption.Dock = DockStyle.Fill;
            this.lblBinArrMonCaption.Font = UiTheme.ButtonFont;
            this.lblBinArrMonCaption.Margin = new Padding(1);
            this.lblBinArrMonCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblBinArrMonCaption.Tag = "i18n:work.workInfo.binArrMon";
            this.lblBinArrMonCaption.Text = Lang.T("work.workInfo.binArrMon");
            this.lblBinArrMonCaption.TextAlign = ContentAlignment.MiddleLeft;

            this.lblLoadCaption.Tag = "i18n:work.workTime.load";
            this.lblLoadCaption.Text = Lang.T("work.workTime.load");
            this.lblUpCaption.Tag = "i18n:work.workTime.up";
            this.lblUpCaption.Text = Lang.T("work.workTime.up");
            this.lblContUpCaption.Tag = "i18n:work.workTime.contUp";
            this.lblContUpCaption.Text = Lang.T("work.workTime.contUp");
            this.lblNormDownCaption.Tag = "i18n:work.workTime.normDown";
            this.lblNormDownCaption.Text = Lang.T("work.workTime.normDown");
            this.lblErrDownCaption.Tag = "i18n:work.workTime.errDown";
            this.lblErrDownCaption.Text = Lang.T("work.workTime.errDown");
            this.lblErrCntCaption.Tag = "i18n:work.workTime.errCnt";
            this.lblErrCntCaption.Text = Lang.T("work.workTime.errCnt");
            this.lblRecoveryCaption.Tag = "i18n:work.workTime.recovery";
            this.lblRecoveryCaption.Text = Lang.T("work.workTime.recovery");
            this.lblUphCaption.Tag = "i18n:work.workTime.uph";
            this.lblUphCaption.Text = Lang.T("work.workTime.uph");
            this.lblMtbfCaption.Tag = "i18n:work.workTime.mtbf";
            this.lblMtbfCaption.Text = Lang.T("work.workTime.mtbf");
            this.lblMttrCaption.Tag = "i18n:work.workTime.mttr";
            this.lblMttrCaption.Text = Lang.T("work.workTime.mttr");
            this.lblCycleCaption.Tag = "i18n:work.workTime.cycle";
            this.lblCycleCaption.Text = Lang.T("work.workTime.cycle");
            this.lblRateCaption.Tag = "i18n:work.workTime.rate";
            this.lblRateCaption.Text = Lang.T("work.workTime.rate");
            this.lblLotCaption.Tag = "i18n:work.workTime.lotId";
            this.lblLotCaption.Text = Lang.T("work.workTime.lotId");

            this.lblProject.Text = "--";
            this.lblPickFail.Text = "0 ea";
            this.lblBinQty.Text = "0 ea";
            this.lblCollet1.Text = "0";
            this.lblPlaceFail.Text = "0 ea";
            this.lblNeedle.Text = "0";
            this.lblCollet2.Text = "0";
            this.lblBinArrMon.Text = "";
            this.lblLoad.Text = "00:00:00";
            this.lblUp.Text = "00:00:00";
            this.lblContUp.Text = "00:00:00";
            this.lblNormDown.Text = "00:00:00";
            this.lblErrDown.Text = "00:00:00";
            this.lblErrCnt.Text = "0 ea";
            this.lblRecovery.Text = "00:00:00";
            this.lblUph.Text = "0.00";
            this.lblMtbf.Text = "00:00:00";
            this.lblMttr.Text = "00:00:00";
            this.lblCycle.Text = "0 ms";
            this.lblRate.Text = "0.00 %";
            this.lblLot.Text = "";

            this.lblProject.BackColor = Color.White;
            this.lblPickFail.BackColor = Color.White;
            this.lblBinQty.BackColor = Color.White;
            this.lblCollet1.BackColor = Color.White;
            this.lblPlaceFail.BackColor = Color.White;
            this.lblNeedle.BackColor = Color.White;
            this.lblCollet2.BackColor = Color.White;
            this.lblBinArrMon.BackColor = Color.White;
            this.lblLoad.BackColor = Color.White;
            this.lblUp.BackColor = Color.White;
            this.lblContUp.BackColor = Color.White;
            this.lblNormDown.BackColor = Color.White;
            this.lblErrDown.BackColor = Color.White;
            this.lblErrCnt.BackColor = Color.White;
            this.lblRecovery.BackColor = Color.White;
            this.lblUph.BackColor = Color.White;
            this.lblMtbf.BackColor = Color.White;
            this.lblMttr.BackColor = Color.White;
            this.lblCycle.BackColor = Color.White;
            this.lblRate.BackColor = Color.White;
            this.lblLot.BackColor = Color.White;

            this.lblProject.Dock = DockStyle.Fill;
            this.lblProject.Font = UiTheme.ValueFont;
            this.lblProject.Margin = new Padding(1);
            this.lblProject.Padding = new Padding(0, 0, 6, 0);
            this.lblProject.TextAlign = ContentAlignment.MiddleRight;
            this.lblPickFail.Dock = DockStyle.Fill;
            this.lblPickFail.Font = UiTheme.ValueFont;
            this.lblPickFail.Margin = new Padding(1);
            this.lblPickFail.Padding = new Padding(0, 0, 6, 0);
            this.lblPickFail.TextAlign = ContentAlignment.MiddleRight;
            this.lblBinQty.Dock = DockStyle.Fill;
            this.lblBinQty.Font = UiTheme.ValueFont;
            this.lblBinQty.Margin = new Padding(1);
            this.lblBinQty.Padding = new Padding(0, 0, 6, 0);
            this.lblBinQty.TextAlign = ContentAlignment.MiddleRight;
            this.lblCollet1.Dock = DockStyle.Fill;
            this.lblCollet1.Font = UiTheme.ValueFont;
            this.lblCollet1.Margin = new Padding(1);
            this.lblCollet1.Padding = new Padding(0, 0, 6, 0);
            this.lblCollet1.TextAlign = ContentAlignment.MiddleRight;
            this.lblPlaceFail.Dock = DockStyle.Fill;
            this.lblPlaceFail.Font = UiTheme.ValueFont;
            this.lblPlaceFail.Margin = new Padding(1);
            this.lblPlaceFail.Padding = new Padding(0, 0, 6, 0);
            this.lblPlaceFail.TextAlign = ContentAlignment.MiddleRight;
            this.lblNeedle.Dock = DockStyle.Fill;
            this.lblNeedle.Font = UiTheme.ValueFont;
            this.lblNeedle.Margin = new Padding(1);
            this.lblNeedle.Padding = new Padding(0, 0, 6, 0);
            this.lblNeedle.TextAlign = ContentAlignment.MiddleRight;
            this.lblCollet2.Dock = DockStyle.Fill;
            this.lblCollet2.Font = UiTheme.ValueFont;
            this.lblCollet2.Margin = new Padding(1);
            this.lblCollet2.Padding = new Padding(0, 0, 6, 0);
            this.lblCollet2.TextAlign = ContentAlignment.MiddleRight;
            this.lblBinArrMon.Dock = DockStyle.Fill;
            this.lblBinArrMon.Font = UiTheme.ValueFont;
            this.lblBinArrMon.Margin = new Padding(1);
            this.lblBinArrMon.Padding = new Padding(0, 0, 6, 0);
            this.lblBinArrMon.TextAlign = ContentAlignment.MiddleRight;
            this.lblLoad.Dock = DockStyle.Fill;
            this.lblLoad.Font = UiTheme.ValueFont;
            this.lblLoad.Margin = new Padding(1);
            this.lblLoad.Padding = new Padding(0, 0, 6, 0);
            this.lblLoad.TextAlign = ContentAlignment.MiddleRight;
            this.lblUp.Dock = DockStyle.Fill;
            this.lblUp.Font = UiTheme.ValueFont;
            this.lblUp.Margin = new Padding(1);
            this.lblUp.Padding = new Padding(0, 0, 6, 0);
            this.lblUp.TextAlign = ContentAlignment.MiddleRight;
            this.lblContUp.Dock = DockStyle.Fill;
            this.lblContUp.Font = UiTheme.ValueFont;
            this.lblContUp.Margin = new Padding(1);
            this.lblContUp.Padding = new Padding(0, 0, 6, 0);
            this.lblContUp.TextAlign = ContentAlignment.MiddleRight;
            this.lblNormDown.Dock = DockStyle.Fill;
            this.lblNormDown.Font = UiTheme.ValueFont;
            this.lblNormDown.Margin = new Padding(1);
            this.lblNormDown.Padding = new Padding(0, 0, 6, 0);
            this.lblNormDown.TextAlign = ContentAlignment.MiddleRight;
            this.lblErrDown.Dock = DockStyle.Fill;
            this.lblErrDown.Font = UiTheme.ValueFont;
            this.lblErrDown.Margin = new Padding(1);
            this.lblErrDown.Padding = new Padding(0, 0, 6, 0);
            this.lblErrDown.TextAlign = ContentAlignment.MiddleRight;
            this.lblErrCnt.Dock = DockStyle.Fill;
            this.lblErrCnt.Font = UiTheme.ValueFont;
            this.lblErrCnt.Margin = new Padding(1);
            this.lblErrCnt.Padding = new Padding(0, 0, 6, 0);
            this.lblErrCnt.TextAlign = ContentAlignment.MiddleRight;
            this.lblRecovery.Dock = DockStyle.Fill;
            this.lblRecovery.Font = UiTheme.ValueFont;
            this.lblRecovery.Margin = new Padding(1);
            this.lblRecovery.Padding = new Padding(0, 0, 6, 0);
            this.lblRecovery.TextAlign = ContentAlignment.MiddleRight;
            this.lblUph.Dock = DockStyle.Fill;
            this.lblUph.Font = UiTheme.ValueFont;
            this.lblUph.Margin = new Padding(1);
            this.lblUph.Padding = new Padding(0, 0, 6, 0);
            this.lblUph.TextAlign = ContentAlignment.MiddleRight;
            this.lblMtbf.Dock = DockStyle.Fill;
            this.lblMtbf.Font = UiTheme.ValueFont;
            this.lblMtbf.Margin = new Padding(1);
            this.lblMtbf.Padding = new Padding(0, 0, 6, 0);
            this.lblMtbf.TextAlign = ContentAlignment.MiddleRight;
            this.lblMttr.Dock = DockStyle.Fill;
            this.lblMttr.Font = UiTheme.ValueFont;
            this.lblMttr.Margin = new Padding(1);
            this.lblMttr.Padding = new Padding(0, 0, 6, 0);
            this.lblMttr.TextAlign = ContentAlignment.MiddleRight;
            this.lblCycle.Dock = DockStyle.Fill;
            this.lblCycle.Font = UiTheme.ValueFont;
            this.lblCycle.Margin = new Padding(1);
            this.lblCycle.Padding = new Padding(0, 0, 6, 0);
            this.lblCycle.TextAlign = ContentAlignment.MiddleRight;
            this.lblRate.Dock = DockStyle.Fill;
            this.lblRate.Font = UiTheme.ValueFont;
            this.lblRate.Margin = new Padding(1);
            this.lblRate.Padding = new Padding(0, 0, 6, 0);
            this.lblRate.TextAlign = ContentAlignment.MiddleRight;
            this.lblLot.Dock = DockStyle.Fill;
            this.lblLot.Font = UiTheme.ValueFont;
            this.lblLot.Margin = new Padding(1);
            this.lblLot.Padding = new Padding(0, 0, 6, 0);
            this.lblLot.TextAlign = ContentAlignment.MiddleRight;

            this.lblLoadCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblLoadCaption.Dock = DockStyle.Fill;
            this.lblLoadCaption.Font = UiTheme.ButtonFont;
            this.lblLoadCaption.Margin = new Padding(1);
            this.lblLoadCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblLoadCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblUpCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblUpCaption.Dock = DockStyle.Fill;
            this.lblUpCaption.Font = UiTheme.ButtonFont;
            this.lblUpCaption.Margin = new Padding(1);
            this.lblUpCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblUpCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblContUpCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblContUpCaption.Dock = DockStyle.Fill;
            this.lblContUpCaption.Font = UiTheme.ButtonFont;
            this.lblContUpCaption.Margin = new Padding(1);
            this.lblContUpCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblContUpCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblNormDownCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblNormDownCaption.Dock = DockStyle.Fill;
            this.lblNormDownCaption.Font = UiTheme.ButtonFont;
            this.lblNormDownCaption.Margin = new Padding(1);
            this.lblNormDownCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblNormDownCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblErrDownCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblErrDownCaption.Dock = DockStyle.Fill;
            this.lblErrDownCaption.Font = UiTheme.ButtonFont;
            this.lblErrDownCaption.Margin = new Padding(1);
            this.lblErrDownCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblErrDownCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblErrCntCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblErrCntCaption.Dock = DockStyle.Fill;
            this.lblErrCntCaption.Font = UiTheme.ButtonFont;
            this.lblErrCntCaption.Margin = new Padding(1);
            this.lblErrCntCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblErrCntCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblRecoveryCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblRecoveryCaption.Dock = DockStyle.Fill;
            this.lblRecoveryCaption.Font = UiTheme.ButtonFont;
            this.lblRecoveryCaption.Margin = new Padding(1);
            this.lblRecoveryCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblRecoveryCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblUphCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblUphCaption.Dock = DockStyle.Fill;
            this.lblUphCaption.Font = UiTheme.ButtonFont;
            this.lblUphCaption.Margin = new Padding(1);
            this.lblUphCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblUphCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblMtbfCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblMtbfCaption.Dock = DockStyle.Fill;
            this.lblMtbfCaption.Font = UiTheme.ButtonFont;
            this.lblMtbfCaption.Margin = new Padding(1);
            this.lblMtbfCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblMtbfCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblMttrCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblMttrCaption.Dock = DockStyle.Fill;
            this.lblMttrCaption.Font = UiTheme.ButtonFont;
            this.lblMttrCaption.Margin = new Padding(1);
            this.lblMttrCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblMttrCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblCycleCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblCycleCaption.Dock = DockStyle.Fill;
            this.lblCycleCaption.Font = UiTheme.ButtonFont;
            this.lblCycleCaption.Margin = new Padding(1);
            this.lblCycleCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblCycleCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblRateCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblRateCaption.Dock = DockStyle.Fill;
            this.lblRateCaption.Font = UiTheme.ButtonFont;
            this.lblRateCaption.Margin = new Padding(1);
            this.lblRateCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblRateCaption.TextAlign = ContentAlignment.MiddleLeft;
            this.lblLotCaption.BackColor = Color.FromArgb(0xD0, 0xD0, 0xD0);
            this.lblLotCaption.Dock = DockStyle.Fill;
            this.lblLotCaption.Font = UiTheme.ButtonFont;
            this.lblLotCaption.Margin = new Padding(1);
            this.lblLotCaption.Padding = new Padding(6, 0, 0, 0);
            this.lblLotCaption.TextAlign = ContentAlignment.MiddleLeft;

            this.btnCcs.BackColor = Color.FromArgb(0x59, 0x59, 0x59);
            this.btnCcs.Dock = DockStyle.Fill;
            this.btnCcs.FlatStyle = FlatStyle.Flat;
            this.btnCcs.Font = UiTheme.ButtonFont;
            this.btnCcs.ForeColor = Color.White;
            this.btnCcs.Tag = "i18n:work.workTime.ccs";
            this.btnCcs.Text = Lang.T("work.workTime.ccs");

            this.Controls.Add(this.rootLayout);
            this.Name = "WorkMainPage";
            this.Size = new Size(1400, 900);
            this.ResumeLayout(false);
        }
    }
}
