namespace QMC.CDT_320.Ui.Pages.Settings
{
    partial class BarcodeReaderPage
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.TableLayoutPanel optionLayout;
        private System.Windows.Forms.Label lblPortTitle;
        private System.Windows.Forms.Label lblPortValue;
        private System.Windows.Forms.Label lblBaudTitle;
        private System.Windows.Forms.Label lblBaudValue;
        private System.Windows.Forms.Label lblDataBitsTitle;
        private System.Windows.Forms.Label lblDataBitsValue;
        private System.Windows.Forms.Label lblParityTitle;
        private System.Windows.Forms.Label lblParityValue;
        private System.Windows.Forms.Label lblStopBitsTitle;
        private System.Windows.Forms.Label lblStopBitsValue;
        private System.Windows.Forms.Label lblHeadCharTitle;
        private System.Windows.Forms.Label lblHeadCharValue;
        private System.Windows.Forms.Label lblTailCharTitle;
        private System.Windows.Forms.Label lblTailCharValue;
        private System.Windows.Forms.Label lblTimeoutTitle;
        private System.Windows.Forms.Label lblTimeoutValue;
        private System.Windows.Forms.Label lblRetryTitle;
        private System.Windows.Forms.Label lblRetryValue;
        private QMC.CDT_320.Ui.Controls.ActionButton btnConnect;
        private QMC.CDT_320.Ui.Controls.ActionButton btnTestRead;
        private System.Windows.Forms.Label lblLastResult;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.optionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblPortTitle = new System.Windows.Forms.Label();
            this.lblPortValue = new System.Windows.Forms.Label();
            this.lblBaudTitle = new System.Windows.Forms.Label();
            this.lblBaudValue = new System.Windows.Forms.Label();
            this.lblDataBitsTitle = new System.Windows.Forms.Label();
            this.lblDataBitsValue = new System.Windows.Forms.Label();
            this.lblParityTitle = new System.Windows.Forms.Label();
            this.lblParityValue = new System.Windows.Forms.Label();
            this.lblStopBitsTitle = new System.Windows.Forms.Label();
            this.lblStopBitsValue = new System.Windows.Forms.Label();
            this.lblHeadCharTitle = new System.Windows.Forms.Label();
            this.lblHeadCharValue = new System.Windows.Forms.Label();
            this.lblTailCharTitle = new System.Windows.Forms.Label();
            this.lblTailCharValue = new System.Windows.Forms.Label();
            this.lblTimeoutTitle = new System.Windows.Forms.Label();
            this.lblTimeoutValue = new System.Windows.Forms.Label();
            this.lblRetryTitle = new System.Windows.Forms.Label();
            this.lblRetryValue = new System.Windows.Forms.Label();
            this.btnConnect = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnTestRead = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.lblLastResult = new System.Windows.Forms.Label();
            this.rootLayout.SuspendLayout();
            this.optionLayout.SuspendLayout();
            this.SuspendLayout();
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.optionLayout, 0, 1);
            this.rootLayout.Controls.Add(this.lblLastResult, 0, 2);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Padding = new System.Windows.Forms.Padding(8);
            this.rootLayout.RowCount = 4;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 340F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 44F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblHeader.Margin = new System.Windows.Forms.Padding(0, 0, 0, 4);
            this.lblHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblHeader.Text = "BARCODE";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.optionLayout.ColumnCount = 2;
            this.optionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 210F));
            this.optionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 280F));
            this.optionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.optionLayout.RowCount = 11;
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 34F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.optionLayout.Controls.Add(this.lblPortTitle, 0, 0);
            this.optionLayout.Controls.Add(this.lblPortValue, 1, 0);
            this.optionLayout.Controls.Add(this.lblBaudTitle, 0, 1);
            this.optionLayout.Controls.Add(this.lblBaudValue, 1, 1);
            this.optionLayout.Controls.Add(this.lblDataBitsTitle, 0, 2);
            this.optionLayout.Controls.Add(this.lblDataBitsValue, 1, 2);
            this.optionLayout.Controls.Add(this.lblParityTitle, 0, 3);
            this.optionLayout.Controls.Add(this.lblParityValue, 1, 3);
            this.optionLayout.Controls.Add(this.lblStopBitsTitle, 0, 4);
            this.optionLayout.Controls.Add(this.lblStopBitsValue, 1, 4);
            this.optionLayout.Controls.Add(this.lblHeadCharTitle, 0, 5);
            this.optionLayout.Controls.Add(this.lblHeadCharValue, 1, 5);
            this.optionLayout.Controls.Add(this.lblTailCharTitle, 0, 6);
            this.optionLayout.Controls.Add(this.lblTailCharValue, 1, 6);
            this.optionLayout.Controls.Add(this.lblTimeoutTitle, 0, 7);
            this.optionLayout.Controls.Add(this.lblTimeoutValue, 1, 7);
            this.optionLayout.Controls.Add(this.lblRetryTitle, 0, 8);
            this.optionLayout.Controls.Add(this.lblRetryValue, 1, 8);
            this.optionLayout.Controls.Add(this.btnConnect, 0, 9);
            this.optionLayout.Controls.Add(this.btnTestRead, 1, 9);
            this.lblPortTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPortTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPortTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPortTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblPortTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblPortTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblPortTitle.Text = "PORT";
            this.lblPortTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPortValue.BackColor = System.Drawing.Color.White;
            this.lblPortValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPortValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPortValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblPortValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblPortValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblPortValue.Text = "COM3";
            this.lblPortValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblBaudTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblBaudTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBaudTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBaudTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblBaudTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblBaudTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblBaudTitle.Text = "BAUD RATE";
            this.lblBaudTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblBaudValue.BackColor = System.Drawing.Color.White;
            this.lblBaudValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBaudValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBaudValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblBaudValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblBaudValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblBaudValue.Text = "9600";
            this.lblBaudValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblDataBitsTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblDataBitsTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDataBitsTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataBitsTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDataBitsTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblDataBitsTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblDataBitsTitle.Text = "DATA BITS";
            this.lblDataBitsTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblDataBitsValue.BackColor = System.Drawing.Color.White;
            this.lblDataBitsValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDataBitsValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataBitsValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblDataBitsValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblDataBitsValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblDataBitsValue.Text = "8";
            this.lblDataBitsValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblParityTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblParityTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblParityTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblParityTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblParityTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblParityTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblParityTitle.Text = "PARITY";
            this.lblParityTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblParityValue.BackColor = System.Drawing.Color.White;
            this.lblParityValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblParityValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblParityValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblParityValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblParityValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblParityValue.Text = "NONE";
            this.lblParityValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblStopBitsTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblStopBitsTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblStopBitsTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStopBitsTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblStopBitsTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblStopBitsTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblStopBitsTitle.Text = "STOP BITS";
            this.lblStopBitsTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblStopBitsValue.BackColor = System.Drawing.Color.White;
            this.lblStopBitsValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblStopBitsValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStopBitsValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblStopBitsValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblStopBitsValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblStopBitsValue.Text = "1";
            this.lblStopBitsValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblHeadCharTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblHeadCharTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblHeadCharTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeadCharTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblHeadCharTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblHeadCharTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblHeadCharTitle.Text = "HEAD CHAR";
            this.lblHeadCharTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblHeadCharValue.BackColor = System.Drawing.Color.White;
            this.lblHeadCharValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblHeadCharValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeadCharValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblHeadCharValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblHeadCharValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblHeadCharValue.Text = "STX";
            this.lblHeadCharValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblTailCharTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblTailCharTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTailCharTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTailCharTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblTailCharTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblTailCharTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblTailCharTitle.Text = "TAIL CHAR";
            this.lblTailCharTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblTailCharValue.BackColor = System.Drawing.Color.White;
            this.lblTailCharValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTailCharValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTailCharValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblTailCharValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblTailCharValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblTailCharValue.Text = "ETX";
            this.lblTailCharValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblTimeoutTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblTimeoutTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTimeoutTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTimeoutTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblTimeoutTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblTimeoutTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblTimeoutTitle.Text = "READ TIMEOUT";
            this.lblTimeoutTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblTimeoutValue.BackColor = System.Drawing.Color.White;
            this.lblTimeoutValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTimeoutValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTimeoutValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblTimeoutValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblTimeoutValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblTimeoutValue.Text = "3000 ms";
            this.lblTimeoutValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblRetryTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblRetryTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblRetryTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRetryTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblRetryTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblRetryTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblRetryTitle.Text = "RETRY COUNT";
            this.lblRetryTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblRetryValue.BackColor = System.Drawing.Color.White;
            this.lblRetryValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblRetryValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRetryValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblRetryValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblRetryValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblRetryValue.Text = "3";
            this.lblRetryValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnConnect.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnConnect.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.btnConnect.Margin = new System.Windows.Forms.Padding(2);
            this.btnConnect.Text = "CONNECT";
            this.btnTestRead.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnTestRead.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.btnTestRead.Margin = new System.Windows.Forms.Padding(2);
            this.btnTestRead.Text = "TEST READ";
            this.lblLastResult.BackColor = System.Drawing.Color.Black;
            this.lblLastResult.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblLastResult.Font = new System.Drawing.Font("Consolas", 12F);
            this.lblLastResult.ForeColor = System.Drawing.Color.LimeGreen;
            this.lblLastResult.Margin = new System.Windows.Forms.Padding(0, 8, 0, 0);
            this.lblLastResult.Padding = new System.Windows.Forms.Padding(8, 0, 0, 0);
            this.lblLastResult.Text = "Last Result : ";
            this.lblLastResult.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.rootLayout);
            this.Name = "BarcodeReaderPage";
            this.Size = new System.Drawing.Size(1678, 900);
            this.rootLayout.ResumeLayout(false);
            this.optionLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }

    partial class ZoomLensPage
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.TableLayoutPanel lensLayout;
        private System.Windows.Forms.GroupBox grpInputVision;
        private System.Windows.Forms.GroupBox grpOutputVision;
        private System.Windows.Forms.GroupBox grpLowerVision;
        private System.Windows.Forms.GroupBox grpBottomVision;
        private System.Windows.Forms.GroupBox grpSideVisionFront;
        private System.Windows.Forms.GroupBox grpSideVisionRear;
        private System.Windows.Forms.TableLayoutPanel inputVisionLayout;
        private System.Windows.Forms.TableLayoutPanel outputVisionLayout;
        private System.Windows.Forms.TableLayoutPanel lowerVisionLayout;
        private System.Windows.Forms.TableLayoutPanel bottomVisionLayout;
        private System.Windows.Forms.TableLayoutPanel sideVisionFrontLayout;
        private System.Windows.Forms.TableLayoutPanel sideVisionRearLayout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.lensLayout = new System.Windows.Forms.TableLayoutPanel();
            this.grpInputVision = new System.Windows.Forms.GroupBox();
            this.grpOutputVision = new System.Windows.Forms.GroupBox();
            this.grpLowerVision = new System.Windows.Forms.GroupBox();
            this.grpBottomVision = new System.Windows.Forms.GroupBox();
            this.grpSideVisionFront = new System.Windows.Forms.GroupBox();
            this.grpSideVisionRear = new System.Windows.Forms.GroupBox();
            this.inputVisionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.outputVisionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lowerVisionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.bottomVisionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.sideVisionFrontLayout = new System.Windows.Forms.TableLayoutPanel();
            this.sideVisionRearLayout = new System.Windows.Forms.TableLayoutPanel();
            this.rootLayout.SuspendLayout();
            this.lensLayout.SuspendLayout();
            this.grpInputVision.SuspendLayout();
            this.grpOutputVision.SuspendLayout();
            this.grpLowerVision.SuspendLayout();
            this.grpBottomVision.SuspendLayout();
            this.grpSideVisionFront.SuspendLayout();
            this.grpSideVisionRear.SuspendLayout();
            this.SuspendLayout();
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.lensLayout, 0, 1);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Padding = new System.Windows.Forms.Padding(8);
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 540F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblHeader.Margin = new System.Windows.Forms.Padding(0, 0, 0, 4);
            this.lblHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblHeader.Text = "ZOOM LENS";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lensLayout.ColumnCount = 1;
            this.lensLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lensLayout.Controls.Add(this.grpInputVision, 0, 0);
            this.lensLayout.Controls.Add(this.grpOutputVision, 0, 1);
            this.lensLayout.Controls.Add(this.grpLowerVision, 0, 2);
            this.lensLayout.Controls.Add(this.grpBottomVision, 0, 3);
            this.lensLayout.Controls.Add(this.grpSideVisionFront, 0, 4);
            this.lensLayout.Controls.Add(this.grpSideVisionRear, 0, 5);
            this.lensLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lensLayout.RowCount = 6;
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.grpInputVision.Controls.Add(this.inputVisionLayout);
            this.grpInputVision.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpInputVision.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpInputVision.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpInputVision.Text = "INPUT VISION";
            this.grpOutputVision.Controls.Add(this.outputVisionLayout);
            this.grpOutputVision.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpOutputVision.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpOutputVision.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpOutputVision.Text = "OUTPUT VISION";
            this.grpLowerVision.Controls.Add(this.lowerVisionLayout);
            this.grpLowerVision.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpLowerVision.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpLowerVision.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpLowerVision.Text = "LOWER VISION";
            this.grpBottomVision.Controls.Add(this.bottomVisionLayout);
            this.grpBottomVision.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpBottomVision.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpBottomVision.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpBottomVision.Text = "BOTTOM VISION";
            this.grpSideVisionFront.Controls.Add(this.sideVisionFrontLayout);
            this.grpSideVisionFront.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSideVisionFront.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpSideVisionFront.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpSideVisionFront.Text = "SIDE VISION (FRONT)";
            this.grpSideVisionRear.Controls.Add(this.sideVisionRearLayout);
            this.grpSideVisionRear.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSideVisionRear.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpSideVisionRear.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpSideVisionRear.Text = "SIDE VISION (REAR)";
            this.inputVisionLayout.ColumnCount = 7;
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.inputVisionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.inputVisionLayout.Padding = new System.Windows.Forms.Padding(8);
            this.outputVisionLayout.ColumnCount = 7;
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.outputVisionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.outputVisionLayout.Padding = new System.Windows.Forms.Padding(8);
            this.lowerVisionLayout.ColumnCount = 7;
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.lowerVisionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lowerVisionLayout.Padding = new System.Windows.Forms.Padding(8);
            this.bottomVisionLayout.ColumnCount = 7;
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.bottomVisionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bottomVisionLayout.Padding = new System.Windows.Forms.Padding(8);
            this.sideVisionFrontLayout.ColumnCount = 7;
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.sideVisionFrontLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sideVisionFrontLayout.Padding = new System.Windows.Forms.Padding(8);
            this.sideVisionRearLayout.ColumnCount = 7;
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.sideVisionRearLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sideVisionRearLayout.Padding = new System.Windows.Forms.Padding(8);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.rootLayout);
            this.Name = "ZoomLensPage";
            this.Size = new System.Drawing.Size(1678, 900);
            this.grpSideVisionRear.ResumeLayout(false);
            this.grpSideVisionFront.ResumeLayout(false);
            this.grpBottomVision.ResumeLayout(false);
            this.grpLowerVision.ResumeLayout(false);
            this.grpOutputVision.ResumeLayout(false);
            this.grpInputVision.ResumeLayout(false);
            this.lensLayout.ResumeLayout(false);
            this.rootLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }

    partial class HeightSensorPage
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.TableLayoutPanel sensorLayout;
        private System.Windows.Forms.GroupBox grpSensor1;
        private System.Windows.Forms.GroupBox grpSensor2;
        private System.Windows.Forms.TableLayoutPanel sensor1Layout;
        private System.Windows.Forms.TableLayoutPanel sensor2Layout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.sensorLayout = new System.Windows.Forms.TableLayoutPanel();
            this.grpSensor1 = new System.Windows.Forms.GroupBox();
            this.grpSensor2 = new System.Windows.Forms.GroupBox();
            this.sensor1Layout = new System.Windows.Forms.TableLayoutPanel();
            this.sensor2Layout = new System.Windows.Forms.TableLayoutPanel();
            this.rootLayout.SuspendLayout();
            this.sensorLayout.SuspendLayout();
            this.grpSensor1.SuspendLayout();
            this.grpSensor2.SuspendLayout();
            this.SuspendLayout();
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.sensorLayout, 0, 1);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Padding = new System.Windows.Forms.Padding(8);
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 240F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblHeader.Margin = new System.Windows.Forms.Padding(0, 0, 0, 4);
            this.lblHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblHeader.Text = "HEIGHT SENSOR";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.sensorLayout.ColumnCount = 1;
            this.sensorLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.sensorLayout.Controls.Add(this.grpSensor1, 0, 0);
            this.sensorLayout.Controls.Add(this.grpSensor2, 0, 1);
            this.sensorLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sensorLayout.RowCount = 2;
            this.sensorLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.sensorLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.grpSensor1.Controls.Add(this.sensor1Layout);
            this.grpSensor1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSensor1.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.grpSensor1.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpSensor1.Text = "SENSOR #1";
            this.grpSensor2.Controls.Add(this.sensor2Layout);
            this.grpSensor2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSensor2.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.grpSensor2.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpSensor2.Text = "SENSOR #2";
            this.sensor1Layout.ColumnCount = 6;
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM5", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZERO", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "0.00", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "LIMIT MIN", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 1);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "-10.00", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 1);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "LIMIT MAX", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 1);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "10.00", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 1);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "VALUE", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 1);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "0.000 mm", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 1);
            this.sensor1Layout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sensor1Layout.Padding = new System.Windows.Forms.Padding(8);
            this.sensor1Layout.RowCount = 2;
            this.sensor1Layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.sensor1Layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.sensor2Layout.ColumnCount = 6;
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM5", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZERO", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "0.00", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "LIMIT MIN", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 1);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "-10.00", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 1);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "LIMIT MAX", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 1);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "10.00", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 1);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "VALUE", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 1);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "0.000 mm", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 1);
            this.sensor2Layout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sensor2Layout.Padding = new System.Windows.Forms.Padding(8);
            this.sensor2Layout.RowCount = 2;
            this.sensor2Layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.sensor2Layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.rootLayout);
            this.Name = "HeightSensorPage";
            this.Size = new System.Drawing.Size(1678, 900);
            this.grpSensor2.ResumeLayout(false);
            this.grpSensor1.ResumeLayout(false);
            this.sensorLayout.ResumeLayout(false);
            this.rootLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
