namespace QMC.CDT_320.Ui.Pages.Settings
{
    partial class BarcodeReaderPage
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.TableLayoutPanel optionLayout;
        private System.Windows.Forms.Label lblPortTitle;
        private System.Windows.Forms.Label lblPortValue;
        private System.Windows.Forms.Label lblBaudTitle;
        private System.Windows.Forms.Label lblBaudValue;
        private System.Windows.Forms.Label lblDataBitsTitle;
        private System.Windows.Forms.Label lblDataBitsValue;
        private System.Windows.Forms.Label lblParityTitle;
        private System.Windows.Forms.Label lblParityValue;
        private System.Windows.Forms.Label lblStopBitsTitle;
        private System.Windows.Forms.Label lblStopBitsValue;
        private System.Windows.Forms.Label lblHeadCharTitle;
        private System.Windows.Forms.Label lblHeadCharValue;
        private System.Windows.Forms.Label lblTailCharTitle;
        private System.Windows.Forms.Label lblTailCharValue;
        private System.Windows.Forms.Label lblTimeoutTitle;
        private System.Windows.Forms.Label lblTimeoutValue;
        private System.Windows.Forms.Label lblRetryTitle;
        private System.Windows.Forms.Label lblRetryValue;
        private QMC.CDT_320.Ui.Controls.ActionButton btnConnect;
        private QMC.CDT_320.Ui.Controls.ActionButton btnTestRead;
        private System.Windows.Forms.Label lblLastResult;
        private System.Windows.Forms.TableLayoutPanel channelLayout;
        private System.Windows.Forms.GroupBox grpInputBarcode;
        private System.Windows.Forms.GroupBox grpOutputBarcode;
        private System.Windows.Forms.TableLayoutPanel inputBarcodeLayout;
        private System.Windows.Forms.TableLayoutPanel outputBarcodeLayout;
        private System.Windows.Forms.TableLayoutPanel inputButtonLayout;
        private System.Windows.Forms.TableLayoutPanel outputButtonLayout;
        private System.Windows.Forms.CheckBox chkInputUse;
        private System.Windows.Forms.CheckBox chkOutputUse;
        private System.Windows.Forms.Label lblInputPort;
        private System.Windows.Forms.Label lblOutputPort;
        private System.Windows.Forms.Label lblInputBaud;
        private System.Windows.Forms.Label lblOutputBaud;
        private System.Windows.Forms.Label lblInputTimeout;
        private System.Windows.Forms.Label lblOutputTimeout;
        private System.Windows.Forms.Label lblInputRetry;
        private System.Windows.Forms.Label lblOutputRetry;
        private System.Windows.Forms.Label lblInputRetryStep;
        private System.Windows.Forms.Label lblOutputRetryStep;
        private System.Windows.Forms.Label lblInputTrigger;
        private System.Windows.Forms.Label lblOutputTrigger;
        private System.Windows.Forms.NumericUpDown numInputPort;
        private System.Windows.Forms.NumericUpDown numOutputPort;
        private System.Windows.Forms.NumericUpDown numInputBaud;
        private System.Windows.Forms.NumericUpDown numOutputBaud;
        private System.Windows.Forms.NumericUpDown numInputTimeout;
        private System.Windows.Forms.NumericUpDown numOutputTimeout;
        private System.Windows.Forms.NumericUpDown numInputRetry;
        private System.Windows.Forms.NumericUpDown numOutputRetry;
        private System.Windows.Forms.NumericUpDown numInputRetryStep;
        private System.Windows.Forms.NumericUpDown numOutputRetryStep;
        private System.Windows.Forms.TextBox txtInputTrigger;
        private System.Windows.Forms.TextBox txtOutputTrigger;
        private QMC.CDT_320.Ui.Controls.ActionButton btnInputConnect;
        private QMC.CDT_320.Ui.Controls.ActionButton btnOutputConnect;
        private QMC.CDT_320.Ui.Controls.ActionButton btnInputTest;
        private QMC.CDT_320.Ui.Controls.ActionButton btnOutputTest;
        private QMC.CDT_320.Ui.Controls.ActionButton btnSaveBarcode;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.optionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblPortTitle = new System.Windows.Forms.Label();
            this.lblPortValue = new System.Windows.Forms.Label();
            this.lblBaudTitle = new System.Windows.Forms.Label();
            this.lblBaudValue = new System.Windows.Forms.Label();
            this.lblDataBitsTitle = new System.Windows.Forms.Label();
            this.lblDataBitsValue = new System.Windows.Forms.Label();
            this.lblParityTitle = new System.Windows.Forms.Label();
            this.lblParityValue = new System.Windows.Forms.Label();
            this.lblStopBitsTitle = new System.Windows.Forms.Label();
            this.lblStopBitsValue = new System.Windows.Forms.Label();
            this.lblHeadCharTitle = new System.Windows.Forms.Label();
            this.lblHeadCharValue = new System.Windows.Forms.Label();
            this.lblTailCharTitle = new System.Windows.Forms.Label();
            this.lblTailCharValue = new System.Windows.Forms.Label();
            this.lblTimeoutTitle = new System.Windows.Forms.Label();
            this.lblTimeoutValue = new System.Windows.Forms.Label();
            this.lblRetryTitle = new System.Windows.Forms.Label();
            this.lblRetryValue = new System.Windows.Forms.Label();
            this.btnConnect = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnTestRead = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.lblLastResult = new System.Windows.Forms.Label();
            this.channelLayout = new System.Windows.Forms.TableLayoutPanel();
            this.grpInputBarcode = new System.Windows.Forms.GroupBox();
            this.grpOutputBarcode = new System.Windows.Forms.GroupBox();
            this.inputBarcodeLayout = new System.Windows.Forms.TableLayoutPanel();
            this.outputBarcodeLayout = new System.Windows.Forms.TableLayoutPanel();
            this.inputButtonLayout = new System.Windows.Forms.TableLayoutPanel();
            this.outputButtonLayout = new System.Windows.Forms.TableLayoutPanel();
            this.chkInputUse = new System.Windows.Forms.CheckBox();
            this.chkOutputUse = new System.Windows.Forms.CheckBox();
            this.lblInputPort = new System.Windows.Forms.Label();
            this.lblOutputPort = new System.Windows.Forms.Label();
            this.lblInputBaud = new System.Windows.Forms.Label();
            this.lblOutputBaud = new System.Windows.Forms.Label();
            this.lblInputTimeout = new System.Windows.Forms.Label();
            this.lblOutputTimeout = new System.Windows.Forms.Label();
            this.lblInputRetry = new System.Windows.Forms.Label();
            this.lblOutputRetry = new System.Windows.Forms.Label();
            this.lblInputRetryStep = new System.Windows.Forms.Label();
            this.lblOutputRetryStep = new System.Windows.Forms.Label();
            this.lblInputTrigger = new System.Windows.Forms.Label();
            this.lblOutputTrigger = new System.Windows.Forms.Label();
            this.numInputPort = new System.Windows.Forms.NumericUpDown();
            this.numOutputPort = new System.Windows.Forms.NumericUpDown();
            this.numInputBaud = new System.Windows.Forms.NumericUpDown();
            this.numOutputBaud = new System.Windows.Forms.NumericUpDown();
            this.numInputTimeout = new System.Windows.Forms.NumericUpDown();
            this.numOutputTimeout = new System.Windows.Forms.NumericUpDown();
            this.numInputRetry = new System.Windows.Forms.NumericUpDown();
            this.numOutputRetry = new System.Windows.Forms.NumericUpDown();
            this.numInputRetryStep = new System.Windows.Forms.NumericUpDown();
            this.numOutputRetryStep = new System.Windows.Forms.NumericUpDown();
            this.txtInputTrigger = new System.Windows.Forms.TextBox();
            this.txtOutputTrigger = new System.Windows.Forms.TextBox();
            this.btnInputConnect = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnOutputConnect = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnInputTest = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnOutputTest = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.btnSaveBarcode = new QMC.CDT_320.Ui.Controls.ActionButton();
            this.rootLayout.SuspendLayout();
            this.optionLayout.SuspendLayout();
            this.channelLayout.SuspendLayout();
            this.grpInputBarcode.SuspendLayout();
            this.grpOutputBarcode.SuspendLayout();
            this.inputBarcodeLayout.SuspendLayout();
            this.outputBarcodeLayout.SuspendLayout();
            this.inputButtonLayout.SuspendLayout();
            this.outputButtonLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numInputPort)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numOutputPort)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numInputBaud)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numOutputBaud)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numInputTimeout)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numOutputTimeout)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numInputRetry)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numOutputRetry)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numInputRetryStep)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numOutputRetryStep)).BeginInit();
            this.SuspendLayout();
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.channelLayout, 0, 1);
            this.rootLayout.Controls.Add(this.btnSaveBarcode, 0, 2);
            this.rootLayout.Controls.Add(this.lblLastResult, 0, 3);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Padding = new System.Windows.Forms.Padding(8);
            this.rootLayout.RowCount = 5;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 390F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 42F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lblHeader.BackColor = UiTheme.StatusBarBg;
            this.lblHeader.ForeColor = UiTheme.StatusBarFg;
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblHeader.Margin = new System.Windows.Forms.Padding(0, 0, 0, 4);
            this.lblHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblHeader.Text = "BARCODE";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.optionLayout.ColumnCount = 2;
            this.optionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 210F));
            this.optionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 280F));
            this.optionLayout.Dock = System.Windows.Forms.DockStyle.Left;
            this.optionLayout.Width = 520;
            this.optionLayout.RowCount = 11;
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 34F));
            this.optionLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.optionLayout.Controls.Add(this.lblPortTitle, 0, 0);
            this.optionLayout.Controls.Add(this.lblPortValue, 1, 0);
            this.optionLayout.Controls.Add(this.lblBaudTitle, 0, 1);
            this.optionLayout.Controls.Add(this.lblBaudValue, 1, 1);
            this.optionLayout.Controls.Add(this.lblDataBitsTitle, 0, 2);
            this.optionLayout.Controls.Add(this.lblDataBitsValue, 1, 2);
            this.optionLayout.Controls.Add(this.lblParityTitle, 0, 3);
            this.optionLayout.Controls.Add(this.lblParityValue, 1, 3);
            this.optionLayout.Controls.Add(this.lblStopBitsTitle, 0, 4);
            this.optionLayout.Controls.Add(this.lblStopBitsValue, 1, 4);
            this.optionLayout.Controls.Add(this.lblHeadCharTitle, 0, 5);
            this.optionLayout.Controls.Add(this.lblHeadCharValue, 1, 5);
            this.optionLayout.Controls.Add(this.lblTailCharTitle, 0, 6);
            this.optionLayout.Controls.Add(this.lblTailCharValue, 1, 6);
            this.optionLayout.Controls.Add(this.lblTimeoutTitle, 0, 7);
            this.optionLayout.Controls.Add(this.lblTimeoutValue, 1, 7);
            this.optionLayout.Controls.Add(this.lblRetryTitle, 0, 8);
            this.optionLayout.Controls.Add(this.lblRetryValue, 1, 8);
            this.optionLayout.Controls.Add(this.btnConnect, 0, 9);
            this.optionLayout.Controls.Add(this.btnTestRead, 1, 9);
            this.lblPortTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblPortTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPortTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPortTitle.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblPortTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblPortTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblPortTitle.Text = "PORT";
            this.lblPortTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPortValue.BackColor = System.Drawing.Color.White;
            this.lblPortValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblPortValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPortValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblPortValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblPortValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblPortValue.Text = "COM3";
            this.lblPortValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblBaudTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblBaudTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBaudTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBaudTitle.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblBaudTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblBaudTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblBaudTitle.Text = "BAUD RATE";
            this.lblBaudTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblBaudValue.BackColor = System.Drawing.Color.White;
            this.lblBaudValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblBaudValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblBaudValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblBaudValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblBaudValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblBaudValue.Text = "9600";
            this.lblBaudValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblDataBitsTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblDataBitsTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDataBitsTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataBitsTitle.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblDataBitsTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblDataBitsTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblDataBitsTitle.Text = "DATA BITS";
            this.lblDataBitsTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblDataBitsValue.BackColor = System.Drawing.Color.White;
            this.lblDataBitsValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDataBitsValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataBitsValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblDataBitsValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblDataBitsValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblDataBitsValue.Text = "8";
            this.lblDataBitsValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblParityTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblParityTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblParityTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblParityTitle.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblParityTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblParityTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblParityTitle.Text = "PARITY";
            this.lblParityTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblParityValue.BackColor = System.Drawing.Color.White;
            this.lblParityValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblParityValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblParityValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblParityValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblParityValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblParityValue.Text = "NONE";
            this.lblParityValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblStopBitsTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblStopBitsTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblStopBitsTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStopBitsTitle.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblStopBitsTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblStopBitsTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblStopBitsTitle.Text = "STOP BITS";
            this.lblStopBitsTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblStopBitsValue.BackColor = System.Drawing.Color.White;
            this.lblStopBitsValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblStopBitsValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStopBitsValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblStopBitsValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblStopBitsValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblStopBitsValue.Text = "1";
            this.lblStopBitsValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblHeadCharTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblHeadCharTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblHeadCharTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeadCharTitle.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblHeadCharTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblHeadCharTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblHeadCharTitle.Text = "HEAD CHAR";
            this.lblHeadCharTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblHeadCharValue.BackColor = System.Drawing.Color.White;
            this.lblHeadCharValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblHeadCharValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeadCharValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblHeadCharValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblHeadCharValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblHeadCharValue.Text = "STX";
            this.lblHeadCharValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblTailCharTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblTailCharTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTailCharTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTailCharTitle.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblTailCharTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblTailCharTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblTailCharTitle.Text = "TAIL CHAR";
            this.lblTailCharTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblTailCharValue.BackColor = System.Drawing.Color.White;
            this.lblTailCharValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTailCharValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTailCharValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblTailCharValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblTailCharValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblTailCharValue.Text = "ETX";
            this.lblTailCharValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblTimeoutTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblTimeoutTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTimeoutTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTimeoutTitle.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblTimeoutTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblTimeoutTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblTimeoutTitle.Text = "READ TIMEOUT";
            this.lblTimeoutTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblTimeoutValue.BackColor = System.Drawing.Color.White;
            this.lblTimeoutValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTimeoutValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTimeoutValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblTimeoutValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblTimeoutValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblTimeoutValue.Text = "3000 ms";
            this.lblTimeoutValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblRetryTitle.BackColor = System.Drawing.Color.FromArgb(208, 208, 208);
            this.lblRetryTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblRetryTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRetryTitle.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblRetryTitle.Margin = new System.Windows.Forms.Padding(2);
            this.lblRetryTitle.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblRetryTitle.Text = "RETRY COUNT";
            this.lblRetryTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblRetryValue.BackColor = System.Drawing.Color.White;
            this.lblRetryValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblRetryValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRetryValue.Font = new System.Drawing.Font("Consolas", 10F);
            this.lblRetryValue.Margin = new System.Windows.Forms.Padding(2);
            this.lblRetryValue.Padding = new System.Windows.Forms.Padding(0, 0, 6, 0);
            this.lblRetryValue.Text = "3";
            this.lblRetryValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnConnect.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnConnect.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.btnConnect.Margin = new System.Windows.Forms.Padding(2);
            this.btnConnect.Text = "CONNECT";
            this.btnTestRead.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnTestRead.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.btnTestRead.Margin = new System.Windows.Forms.Padding(2);
            this.btnTestRead.Text = "TEST READ";
            this.channelLayout.ColumnCount = 2;
            this.channelLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.channelLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.channelLayout.Controls.Add(this.grpInputBarcode, 0, 0);
            this.channelLayout.Controls.Add(this.grpOutputBarcode, 1, 0);
            this.channelLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.channelLayout.Padding = new System.Windows.Forms.Padding(0, 8, 0, 4);
            this.grpInputBarcode.Controls.Add(this.inputBarcodeLayout);
            this.grpInputBarcode.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpInputBarcode.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpInputBarcode.Margin = new System.Windows.Forms.Padding(0, 0, 4, 0);
            this.grpInputBarcode.Text = "INPUT WAFER BARCODE";
            this.grpOutputBarcode.Controls.Add(this.outputBarcodeLayout);
            this.grpOutputBarcode.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpOutputBarcode.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpOutputBarcode.Margin = new System.Windows.Forms.Padding(4, 0, 0, 0);
            this.grpOutputBarcode.Text = "OUTPUT BIN BARCODE";
            this.inputBarcodeLayout.ColumnCount = 2;
            this.inputBarcodeLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 190F));
            this.inputBarcodeLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.inputBarcodeLayout.Controls.Add(this.chkInputUse, 0, 0);
            this.inputBarcodeLayout.SetColumnSpan(this.chkInputUse, 2);
            this.inputBarcodeLayout.Controls.Add(this.lblInputPort, 0, 1);
            this.inputBarcodeLayout.Controls.Add(this.numInputPort, 1, 1);
            this.inputBarcodeLayout.Controls.Add(this.lblInputBaud, 0, 2);
            this.inputBarcodeLayout.Controls.Add(this.numInputBaud, 1, 2);
            this.inputBarcodeLayout.Controls.Add(this.lblInputTimeout, 0, 3);
            this.inputBarcodeLayout.Controls.Add(this.numInputTimeout, 1, 3);
            this.inputBarcodeLayout.Controls.Add(this.lblInputRetry, 0, 4);
            this.inputBarcodeLayout.Controls.Add(this.numInputRetry, 1, 4);
            this.inputBarcodeLayout.Controls.Add(this.lblInputRetryStep, 0, 5);
            this.inputBarcodeLayout.Controls.Add(this.numInputRetryStep, 1, 5);
            this.inputBarcodeLayout.Controls.Add(this.lblInputTrigger, 0, 6);
            this.inputBarcodeLayout.Controls.Add(this.txtInputTrigger, 1, 6);
            this.inputBarcodeLayout.Controls.Add(this.inputButtonLayout, 0, 7);
            this.inputBarcodeLayout.SetColumnSpan(this.inputButtonLayout, 2);
            this.inputBarcodeLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.inputBarcodeLayout.Padding = new System.Windows.Forms.Padding(10);
            this.inputBarcodeLayout.RowCount = 8;
            this.inputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.inputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.inputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.inputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.inputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.inputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.inputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.inputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.outputBarcodeLayout.ColumnCount = 2;
            this.outputBarcodeLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 190F));
            this.outputBarcodeLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.outputBarcodeLayout.Controls.Add(this.chkOutputUse, 0, 0);
            this.outputBarcodeLayout.SetColumnSpan(this.chkOutputUse, 2);
            this.outputBarcodeLayout.Controls.Add(this.lblOutputPort, 0, 1);
            this.outputBarcodeLayout.Controls.Add(this.numOutputPort, 1, 1);
            this.outputBarcodeLayout.Controls.Add(this.lblOutputBaud, 0, 2);
            this.outputBarcodeLayout.Controls.Add(this.numOutputBaud, 1, 2);
            this.outputBarcodeLayout.Controls.Add(this.lblOutputTimeout, 0, 3);
            this.outputBarcodeLayout.Controls.Add(this.numOutputTimeout, 1, 3);
            this.outputBarcodeLayout.Controls.Add(this.lblOutputRetry, 0, 4);
            this.outputBarcodeLayout.Controls.Add(this.numOutputRetry, 1, 4);
            this.outputBarcodeLayout.Controls.Add(this.lblOutputRetryStep, 0, 5);
            this.outputBarcodeLayout.Controls.Add(this.numOutputRetryStep, 1, 5);
            this.outputBarcodeLayout.Controls.Add(this.lblOutputTrigger, 0, 6);
            this.outputBarcodeLayout.Controls.Add(this.txtOutputTrigger, 1, 6);
            this.outputBarcodeLayout.Controls.Add(this.outputButtonLayout, 0, 7);
            this.outputBarcodeLayout.SetColumnSpan(this.outputButtonLayout, 2);
            this.outputBarcodeLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.outputBarcodeLayout.Padding = new System.Windows.Forms.Padding(10);
            this.outputBarcodeLayout.RowCount = 8;
            this.outputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.outputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.outputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.outputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.outputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.outputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.outputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.outputBarcodeLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.chkInputUse.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chkInputUse.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.chkInputUse.Text = "USE INPUT WAFER BARCODE";
            this.chkOutputUse.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chkOutputUse.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Bold);
            this.chkOutputUse.Text = "USE OUTPUT BIN BARCODE";
            this.lblInputPort.Text = "SERIAL PORT (COM)";
            this.lblOutputPort.Text = "SERIAL PORT (COM)";
            this.lblInputBaud.Text = "BAUD RATE";
            this.lblOutputBaud.Text = "BAUD RATE";
            this.lblInputTimeout.Text = "READ TIMEOUT (ms)";
            this.lblOutputTimeout.Text = "READ TIMEOUT (ms)";
            this.lblInputRetry.Text = "RETRY COUNT";
            this.lblOutputRetry.Text = "RETRY COUNT";
            this.lblInputRetryStep.Text = "Y RETRY STEP (mm)";
            this.lblOutputRetryStep.Text = "Y RETRY STEP (mm)";
            this.lblInputTrigger.Text = "TRIGGER (blank=listen)";
            this.lblOutputTrigger.Text = "TRIGGER (blank=listen)";
            this.lblInputPort.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblOutputPort.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInputBaud.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblOutputBaud.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInputTimeout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblOutputTimeout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInputRetry.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblOutputRetry.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInputRetryStep.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblOutputRetryStep.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInputTrigger.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblOutputTrigger.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInputPort.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblOutputPort.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblInputBaud.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblOutputBaud.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblInputTimeout.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblOutputTimeout.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblInputRetry.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblOutputRetry.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblInputRetryStep.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblOutputRetryStep.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblInputTrigger.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblOutputTrigger.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.numInputPort.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numOutputPort.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numInputPort.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.numOutputPort.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.numInputPort.Maximum = new decimal(new int[] { 256, 0, 0, 0 });
            this.numOutputPort.Maximum = new decimal(new int[] { 256, 0, 0, 0 });
            this.numInputBaud.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numOutputBaud.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numInputBaud.Minimum = new decimal(new int[] { 300, 0, 0, 0 });
            this.numOutputBaud.Minimum = new decimal(new int[] { 300, 0, 0, 0 });
            this.numInputBaud.Maximum = new decimal(new int[] { 1000000, 0, 0, 0 });
            this.numOutputBaud.Maximum = new decimal(new int[] { 1000000, 0, 0, 0 });
            this.numInputTimeout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numOutputTimeout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numInputTimeout.Minimum = new decimal(new int[] { 100, 0, 0, 0 });
            this.numOutputTimeout.Minimum = new decimal(new int[] { 100, 0, 0, 0 });
            this.numInputTimeout.Maximum = new decimal(new int[] { 60000, 0, 0, 0 });
            this.numOutputTimeout.Maximum = new decimal(new int[] { 60000, 0, 0, 0 });
            this.numInputRetry.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numOutputRetry.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numInputRetry.Maximum = new decimal(new int[] { 20, 0, 0, 0 });
            this.numOutputRetry.Maximum = new decimal(new int[] { 20, 0, 0, 0 });
            this.numInputRetryStep.DecimalPlaces = 3;
            this.numOutputRetryStep.DecimalPlaces = 3;
            this.numInputRetryStep.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numOutputRetryStep.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numInputRetryStep.Increment = new decimal(new int[] { 1, 0, 0, 196608 });
            this.numOutputRetryStep.Increment = new decimal(new int[] { 1, 0, 0, 196608 });
            this.numInputRetryStep.Minimum = new decimal(new int[] { 1, 0, 0, 196608 });
            this.numOutputRetryStep.Minimum = new decimal(new int[] { 1, 0, 0, 196608 });
            this.numInputRetryStep.Maximum = new decimal(new int[] { 100, 0, 0, 0 });
            this.numOutputRetryStep.Maximum = new decimal(new int[] { 100, 0, 0, 0 });
            this.txtInputTrigger.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtOutputTrigger.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtInputTrigger.Font = new System.Drawing.Font("Consolas", 9F);
            this.txtOutputTrigger.Font = new System.Drawing.Font("Consolas", 9F);
            this.txtInputTrigger.MaxLength = 128;
            this.txtOutputTrigger.MaxLength = 128;
            this.inputButtonLayout.ColumnCount = 2;
            this.inputButtonLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.inputButtonLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.inputButtonLayout.Controls.Add(this.btnInputConnect, 0, 0);
            this.inputButtonLayout.Controls.Add(this.btnInputTest, 1, 0);
            this.inputButtonLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.outputButtonLayout.ColumnCount = 2;
            this.outputButtonLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.outputButtonLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.outputButtonLayout.Controls.Add(this.btnOutputConnect, 0, 0);
            this.outputButtonLayout.Controls.Add(this.btnOutputTest, 1, 0);
            this.outputButtonLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnInputConnect.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnInputTest.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnOutputConnect.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnOutputTest.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnInputConnect.Text = "CONNECT";
            this.btnOutputConnect.Text = "CONNECT";
            this.btnInputTest.Text = "TEST READ";
            this.btnOutputTest.Text = "TEST READ";
            this.btnSaveBarcode.Dock = System.Windows.Forms.DockStyle.Right;
            this.btnSaveBarcode.Margin = new System.Windows.Forms.Padding(0, 3, 0, 3);
            this.btnSaveBarcode.Text = "SAVE BARCODE SETTINGS";
            this.btnSaveBarcode.Width = 260;
            this.lblLastResult.BackColor = System.Drawing.Color.Black;
            this.lblLastResult.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblLastResult.Font = new System.Drawing.Font("Consolas", 12F);
            this.lblLastResult.ForeColor = System.Drawing.Color.LimeGreen;
            this.lblLastResult.Margin = new System.Windows.Forms.Padding(0);
            this.lblLastResult.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.lblLastResult.Text = "Last Result : ";
            this.lblLastResult.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.rootLayout);
            this.Name = "BarcodeReaderPage";
            this.Size = new System.Drawing.Size(1678, 900);
            this.rootLayout.ResumeLayout(false);
            this.optionLayout.ResumeLayout(false);
            this.channelLayout.ResumeLayout(false);
            this.grpInputBarcode.ResumeLayout(false);
            this.grpOutputBarcode.ResumeLayout(false);
            this.inputBarcodeLayout.ResumeLayout(false);
            this.inputBarcodeLayout.PerformLayout();
            this.outputBarcodeLayout.ResumeLayout(false);
            this.outputBarcodeLayout.PerformLayout();
            this.inputButtonLayout.ResumeLayout(false);
            this.outputButtonLayout.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numInputPort)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numOutputPort)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numInputBaud)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numOutputBaud)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numInputTimeout)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numOutputTimeout)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numInputRetry)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numOutputRetry)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numInputRetryStep)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numOutputRetryStep)).EndInit();
            this.ResumeLayout(false);
        }
    }

    partial class ZoomLensPage
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.TableLayoutPanel lensLayout;
        private System.Windows.Forms.GroupBox grpInputVision;
        private System.Windows.Forms.GroupBox grpOutputVision;
        private System.Windows.Forms.GroupBox grpLowerVision;
        private System.Windows.Forms.GroupBox grpBottomVision;
        private System.Windows.Forms.GroupBox grpSideVisionFront;
        private System.Windows.Forms.GroupBox grpSideVisionRear;
        private System.Windows.Forms.TableLayoutPanel inputVisionLayout;
        private System.Windows.Forms.TableLayoutPanel outputVisionLayout;
        private System.Windows.Forms.TableLayoutPanel lowerVisionLayout;
        private System.Windows.Forms.TableLayoutPanel bottomVisionLayout;
        private System.Windows.Forms.TableLayoutPanel sideVisionFrontLayout;
        private System.Windows.Forms.TableLayoutPanel sideVisionRearLayout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.lensLayout = new System.Windows.Forms.TableLayoutPanel();
            this.grpInputVision = new System.Windows.Forms.GroupBox();
            this.grpOutputVision = new System.Windows.Forms.GroupBox();
            this.grpLowerVision = new System.Windows.Forms.GroupBox();
            this.grpBottomVision = new System.Windows.Forms.GroupBox();
            this.grpSideVisionFront = new System.Windows.Forms.GroupBox();
            this.grpSideVisionRear = new System.Windows.Forms.GroupBox();
            this.inputVisionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.outputVisionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lowerVisionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.bottomVisionLayout = new System.Windows.Forms.TableLayoutPanel();
            this.sideVisionFrontLayout = new System.Windows.Forms.TableLayoutPanel();
            this.sideVisionRearLayout = new System.Windows.Forms.TableLayoutPanel();
            this.rootLayout.SuspendLayout();
            this.lensLayout.SuspendLayout();
            this.grpInputVision.SuspendLayout();
            this.grpOutputVision.SuspendLayout();
            this.grpLowerVision.SuspendLayout();
            this.grpBottomVision.SuspendLayout();
            this.grpSideVisionFront.SuspendLayout();
            this.grpSideVisionRear.SuspendLayout();
            this.SuspendLayout();
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.lensLayout, 0, 1);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Padding = new System.Windows.Forms.Padding(8);
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 500F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lblHeader.BackColor = UiTheme.StatusBarBg;
            this.lblHeader.ForeColor = UiTheme.StatusBarFg;
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblHeader.Margin = new System.Windows.Forms.Padding(0, 0, 0, 4);
            this.lblHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblHeader.Text = "ZOOM LENS";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lensLayout.ColumnCount = 1;
            this.lensLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lensLayout.Controls.Add(this.grpInputVision, 0, 0);
            this.lensLayout.Controls.Add(this.grpOutputVision, 0, 1);
            this.lensLayout.Controls.Add(this.grpLowerVision, 0, 2);
            this.lensLayout.Controls.Add(this.grpBottomVision, 0, 3);
            this.lensLayout.Controls.Add(this.grpSideVisionFront, 0, 4);
            this.lensLayout.Controls.Add(this.grpSideVisionRear, 0, 5);
            this.lensLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lensLayout.RowCount = 6;
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.lensLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.grpInputVision.Controls.Add(this.inputVisionLayout);
            this.grpInputVision.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpInputVision.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpInputVision.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpInputVision.Text = "INPUT VISION";
            this.grpOutputVision.Controls.Add(this.outputVisionLayout);
            this.grpOutputVision.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpOutputVision.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpOutputVision.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpOutputVision.Text = "OUTPUT VISION";
            this.grpLowerVision.Controls.Add(this.lowerVisionLayout);
            this.grpLowerVision.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpLowerVision.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpLowerVision.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpLowerVision.Text = "LOWER VISION";
            this.grpBottomVision.Controls.Add(this.bottomVisionLayout);
            this.grpBottomVision.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpBottomVision.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpBottomVision.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpBottomVision.Text = "BOTTOM VISION";
            this.grpSideVisionFront.Controls.Add(this.sideVisionFrontLayout);
            this.grpSideVisionFront.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSideVisionFront.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpSideVisionFront.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpSideVisionFront.Text = "SIDE VISION (FRONT)";
            this.grpSideVisionRear.Controls.Add(this.sideVisionRearLayout);
            this.grpSideVisionRear.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSideVisionRear.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpSideVisionRear.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpSideVisionRear.Text = "SIDE VISION (REAR)";
            this.inputVisionLayout.ColumnCount = 7;
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.inputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.inputVisionLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.inputVisionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.inputVisionLayout.Padding = new System.Windows.Forms.Padding(8);
            this.outputVisionLayout.ColumnCount = 7;
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.outputVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.outputVisionLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.outputVisionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.outputVisionLayout.Padding = new System.Windows.Forms.Padding(8);
            this.lowerVisionLayout.ColumnCount = 7;
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.lowerVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.lowerVisionLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.lowerVisionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lowerVisionLayout.Padding = new System.Windows.Forms.Padding(8);
            this.bottomVisionLayout.ColumnCount = 7;
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.bottomVisionLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.bottomVisionLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.bottomVisionLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bottomVisionLayout.Padding = new System.Windows.Forms.Padding(8);
            this.sideVisionFrontLayout.ColumnCount = 7;
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionFrontLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.sideVisionFrontLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.sideVisionFrontLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sideVisionFrontLayout.Padding = new System.Windows.Forms.Padding(8);
            this.sideVisionRearLayout.ColumnCount = 7;
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionRearLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM4", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZOOM", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "50", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.sideVisionRearLayout.Controls.Add(new System.Windows.Forms.Button() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "APPLY", FlatStyle = System.Windows.Forms.FlatStyle.Flat, Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold) }, 6, 0);
            this.sideVisionRearLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sideVisionRearLayout.Padding = new System.Windows.Forms.Padding(8);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.rootLayout);
            this.Name = "ZoomLensPage";
            this.Size = new System.Drawing.Size(1678, 900);
            this.grpSideVisionRear.ResumeLayout(false);
            this.grpSideVisionFront.ResumeLayout(false);
            this.grpBottomVision.ResumeLayout(false);
            this.grpLowerVision.ResumeLayout(false);
            this.grpOutputVision.ResumeLayout(false);
            this.grpInputVision.ResumeLayout(false);
            this.lensLayout.ResumeLayout(false);
            this.rootLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }

    partial class HeightSensorPage
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.TableLayoutPanel sensorLayout;
        private System.Windows.Forms.GroupBox grpSensor1;
        private System.Windows.Forms.GroupBox grpSensor2;
        private System.Windows.Forms.TableLayoutPanel sensor1Layout;
        private System.Windows.Forms.TableLayoutPanel sensor2Layout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.lblHeader = new System.Windows.Forms.Label();
            this.sensorLayout = new System.Windows.Forms.TableLayoutPanel();
            this.grpSensor1 = new System.Windows.Forms.GroupBox();
            this.grpSensor2 = new System.Windows.Forms.GroupBox();
            this.sensor1Layout = new System.Windows.Forms.TableLayoutPanel();
            this.sensor2Layout = new System.Windows.Forms.TableLayoutPanel();
            this.rootLayout.SuspendLayout();
            this.sensorLayout.SuspendLayout();
            this.grpSensor1.SuspendLayout();
            this.grpSensor2.SuspendLayout();
            this.SuspendLayout();
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.lblHeader, 0, 0);
            this.rootLayout.Controls.Add(this.sensorLayout, 0, 1);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Padding = new System.Windows.Forms.Padding(8);
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 210F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lblHeader.BackColor = UiTheme.StatusBarBg;
            this.lblHeader.ForeColor = UiTheme.StatusBarFg;
            this.lblHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblHeader.Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.lblHeader.Margin = new System.Windows.Forms.Padding(0, 0, 0, 4);
            this.lblHeader.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblHeader.Text = "HEIGHT SENSOR";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.sensorLayout.ColumnCount = 1;
            this.sensorLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.sensorLayout.Controls.Add(this.grpSensor1, 0, 0);
            this.sensorLayout.Controls.Add(this.grpSensor2, 0, 1);
            this.sensorLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sensorLayout.RowCount = 2;
            this.sensorLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.sensorLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.grpSensor1.Controls.Add(this.sensor1Layout);
            this.grpSensor1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSensor1.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpSensor1.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpSensor1.Text = "SENSOR #1";
            this.grpSensor2.Controls.Add(this.sensor2Layout);
            this.grpSensor2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpSensor2.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Bold);
            this.grpSensor2.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.grpSensor2.Text = "SENSOR #2";
            this.sensor1Layout.ColumnCount = 6;
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM5", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZERO", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "0.00", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "LIMIT MIN", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 1);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "-10.00", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 1);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "LIMIT MAX", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 1);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "10.00", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 1);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "VALUE", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 1);
            this.sensor1Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "0.000 mm", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 1);
            this.sensor1Layout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sensor1Layout.Padding = new System.Windows.Forms.Padding(8);
            this.sensor1Layout.RowCount = 2;
            this.sensor1Layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.sensor1Layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.sensor2Layout.ColumnCount = 6;
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "PORT", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "COM5", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "CHANNEL", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "1", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "ZERO", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "0.00", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 0);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "LIMIT MIN", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 0, 1);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "-10.00", Font = new System.Drawing.Font("Consolas", 10F) }, 1, 1);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "LIMIT MAX", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 2, 1);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "10.00", Font = new System.Drawing.Font("Consolas", 10F) }, 3, 1);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.Label() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "VALUE", TextAlign = System.Drawing.ContentAlignment.MiddleLeft }, 4, 1);
            this.sensor2Layout.Controls.Add(new System.Windows.Forms.TextBox() { Dock = System.Windows.Forms.DockStyle.Fill, Text = "0.000 mm", Font = new System.Drawing.Font("Consolas", 10F) }, 5, 1);
            this.sensor2Layout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sensor2Layout.Padding = new System.Windows.Forms.Padding(8);
            this.sensor2Layout.RowCount = 2;
            this.sensor2Layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.sensor2Layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.rootLayout);
            this.Name = "HeightSensorPage";
            this.Size = new System.Drawing.Size(1678, 900);
            this.grpSensor2.ResumeLayout(false);
            this.grpSensor1.ResumeLayout(false);
            this.sensorLayout.ResumeLayout(false);
            this.rootLayout.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
