using System;
using System.Collections.Generic;
using System.Windows.Forms;
using QMC.CDT_320.Ui.Localization;

namespace QMC.CDT_320.Ui.Pages.Settings
{
    /// <summary>설정 화면의 표시 문구만 변환합니다. 설정 키, 셀 값과 장비 원문에는 적용하지 않습니다.</summary>
    internal static class SettingsUiText
    {
        private static readonly Dictionary<string, string> CaptionKeys =
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                { "ACC JERK %", "settingsUi.caption.accJerk" },
                { "ACCEL", "settingsUi.caption.accel" },
                { "ACTION", "settingsUi.caption.action" },
                { "ACTIVE", "settingsUi.caption.active" },
                { "ACTUAL", "settingsUi.caption.actual" },
                { "ACTUAL POSITION", "settingsUi.caption.actualPosition" },
                { "ADD ROW", "settingsUi.caption.addRow" },
                { "ADDR", "settingsUi.caption.addr" },
                { "ALARM", "settingsUi.caption.alarm" },
                { "ALARM CLEAR", "settingsUi.caption.alarmClear" },
                { "ALARM CODE", "settingsUi.caption.alarmCode" },
                { "ALARM LEVEL", "settingsUi.caption.alarmLevel" },
                { "ALARM VALUE", "settingsUi.caption.alarmValue" },
                { "ALL OFF", "settingsUi.caption.allOff" },
                { "ALL ON", "settingsUi.caption.allOn" },
                { "ALL STOP", "settingsUi.caption.allStop" },
                { "AMP FAULT LEVEL", "settingsUi.caption.ampFaultLevel" },
                { "AMP FAULT VALUE", "settingsUi.caption.ampFaultValue" },
                { "APPLIED", "settingsUi.caption.applied" },
                { "APPLY", "settingsUi.caption.apply" },
                { "APPLY (Soft Limit 반영)", "settingsUi.caption.applySoftLimit" },
                { "APPLY FAIL", "settingsUi.caption.applyFail" },
                { "AUTO CONN", "settingsUi.caption.autoConn" },
                { "AXIS", "settingsUi.caption.axis" },
                { "AXIS (#No)", "settingsUi.caption.axisNo" },
                { "AXIS JOG", "settingsUi.caption.axisJog" },
                { "AXIS NAME", "settingsUi.caption.axisName" },
                { "AXIS SETUP LIST", "settingsUi.caption.axisSetupList" },
                { "Action", "settingsUi.caption.action2" },
                { "AlarmMaster", "settingsUi.caption.alarmmaster" },
                { "Apply", "settingsUi.caption.apply2" },
                { "BAUD RATE", "settingsUi.caption.baudRate" },
                { "BIT", "settingsUi.caption.bit" },
                { "BOARD", "settingsUi.caption.board2" },
                { "BOARD SCAN", "settingsUi.caption.boardScan" },
                { "BOARD#", "settingsUi.caption.board" },
                { "BOTTOM VISION", "settingsUi.caption.bottomVision" },
                { "BRAKE TYPE", "settingsUi.caption.brakeType" },
                { "BWD", "settingsUi.caption.bwd" },
                { "BWD DI", "settingsUi.caption.bwdDi" },
                { "BWD DO", "settingsUi.caption.bwdDo" },
                { "BWD TEXT", "settingsUi.caption.bwdText" },
                { "BWD WAIT(ms)", "settingsUi.caption.bwdWaitMs" },
                { "Barcode TEST READ", "settingsUi.action.testBarcodeRead" },
                { "Barcode 설정 변경", "settingsUi.action.changeBarcodeSettings" },
                { "Barcode 설정 저장", "settingsUi.action.saveBarcodeSettings" },
                { "Barcode 연결 변경", "settingsUi.action.changeBarcodeConnection" },
                { "CAMERA SETUP", "settingsUi.caption.cameraSetup" },
                { "CH", "settingsUi.caption.ch" },
                { "CH (slot)", "settingsUi.caption.chSlot" },
                { "CHANNEL", "settingsUi.caption.channel" },
                { "COLOR", "settingsUi.caption.color" },
                { "COM PORT", "settingsUi.caption.comPort" },
                { "COMMAND", "settingsUi.caption.command" },
                { "COMMAND POSITION", "settingsUi.caption.commandPosition" },
                { "CONFIG", "settingsUi.caption.config" },
                { "CONFIGURATION", "settingsUi.caption.configuration" },
                { "CONNECT", "settingsUi.caption.connect" },
                { "CYLINDER", "settingsUi.caption.cylinder" },
                { "CYLINDER LIST", "settingsUi.caption.cylinderList" },
                { "CYLINDER TEST", "settingsUi.caption.cylinderTest" },
                { "Category", "settingsUi.caption.category2" },
                { "Category:", "settingsUi.caption.category" },
                { "Cause", "settingsUi.caption.cause" },
                { "Code", "settingsUi.caption.code" },
                { "DATA BITS", "settingsUi.caption.dataBits" },
                { "DEC JERK %", "settingsUi.caption.decJerk" },
                { "DECEL", "settingsUi.caption.decel" },
                { "DEFAULT SPEED SCALE %", "settingsUi.caption.defaultSpeedScale" },
                { "DEFAULT VEL", "settingsUi.caption.defaultVel" },
                { "DESCRIPTION", "settingsUi.caption.description" },
                { "DI", "settingsUi.caption.di" },
                { "DIGITAL I/O LIST", "settingsUi.caption.digitalIOList" },
                { "DIGITAL INPUT", "settingsUi.caption.digitalInput" },
                { "DIGITAL LINK", "settingsUi.caption.digitalLink" },
                { "DIGITAL OUTPUT", "settingsUi.caption.digitalOutput" },
                { "DIRECTION", "settingsUi.caption.direction" },
                { "DISCONNECT", "settingsUi.caption.disconnect" },
                { "DO", "settingsUi.caption.do" },
                { "DO OFF", "settingsUi.caption.doOff" },
                { "DO ON", "settingsUi.caption.doOn" },
                { "DONE", "settingsUi.caption.done" },
                { "EMERGENCY", "settingsUi.caption.emergency" },
                { "EMERGENCY SIGNAL", "settingsUi.caption.emergencySignal" },
                { "EMG LEVEL", "settingsUi.caption.emgLevel" },
                { "ENABLE", "settingsUi.caption.enable" },
                { "ERROR", "settingsUi.caption.error" },
                { "EXPOSURE(ms)", "settingsUi.caption.exposureMs" },
                { "FWD", "settingsUi.caption.fwd" },
                { "FWD DI", "settingsUi.caption.fwdDi" },
                { "FWD DO", "settingsUi.caption.fwdDo" },
                { "FWD TEXT", "settingsUi.caption.fwdText" },
                { "FWD WAIT(ms)", "settingsUi.caption.fwdWaitMs" },
                { "HEAD CHAR", "settingsUi.caption.headChar" },
                { "HEIGHT", "settingsUi.caption.height" },
                { "HOME", "settingsUi.caption.home" },
                { "HOME ACC 1", "settingsUi.caption.homeAcc1" },
                { "HOME ACC 2", "settingsUi.caption.homeAcc2" },
                { "HOME DEC 1", "settingsUi.caption.homeDec1" },
                { "HOME DEC 2", "settingsUi.caption.homeDec2" },
                { "HOME END", "settingsUi.caption.homeEnd" },
                { "HOME VEL 1", "settingsUi.caption.homeVel1" },
                { "HOME VEL 2", "settingsUi.caption.homeVel2" },
                { "HOME VEL 3", "settingsUi.caption.homeVel3" },
                { "HOME VEL 4", "settingsUi.caption.homeVel4" },
                { "HOST", "settingsUi.caption.host" },
                { "I/O Control", "settingsUi.caption.iOControl" },
                { "I/O SIM", "settingsUi.caption.iOSim" },
                { "I/O SIM MODE", "settingsUi.caption.iOSimMode" },
                { "IN-POS TOL", "settingsUi.caption.inPosTol" },
                { "INDEX", "settingsUi.caption.index" },
                { "INIT AXIS", "settingsUi.caption.initAxis" },
                { "INP DONE", "settingsUi.caption.inpDone" },
                { "INPOSITION", "settingsUi.caption.inposition" },
                { "INPUT MODE", "settingsUi.caption.inputMode" },
                { "INPUT SOURCE", "settingsUi.caption.inputSource" },
                { "INPUT VISION", "settingsUi.caption.inputVision" },
                { "INPUT WAFER BARCODE", "settingsUi.caption.inputWaferBarcode" },
                { "JOG ACC", "settingsUi.caption.jogAcc" },
                { "JOG COARSE", "settingsUi.caption.jogCoarse" },
                { "JOG DEC", "settingsUi.caption.jogDec" },
                { "JOG FINE", "settingsUi.caption.jogFine" },
                { "JOG STOP DEC", "settingsUi.caption.jogStopDec" },
                { "Jog", "settingsUi.caption.jog" },
                { "KEY", "settingsUi.caption.key" },
                { "LAMP LIST", "settingsUi.caption.lampList" },
                { "LEVEL", "settingsUi.caption.level" },
                { "LEVEL (0~255)", "settingsUi.caption.level0255" },
                { "LIGHT", "settingsUi.caption.light" },
                { "LIGHT CONTROLLER", "settingsUi.caption.lightController" },
                { "LIGHT SOURCE LIST", "settingsUi.caption.lightSourceList" },
                { "LIMIT", "settingsUi.caption.limit" },
                { "LIMIT MAX", "settingsUi.caption.limitMax" },
                { "LIMIT MIN", "settingsUi.caption.limitMin" },
                { "LOWER VISION", "settingsUi.caption.lowerVision" },
                { "MAX VELOCITY", "settingsUi.caption.maxVelocity" },
                { "MEL", "settingsUi.caption.mel" },
                { "MODE", "settingsUi.caption.mode" },
                { "MODULE", "settingsUi.caption.module" },
                { "MODULE LIST", "settingsUi.caption.moduleList" },
                { "MOTION", "settingsUi.caption.motion2" },
                { "MOTION TEST", "settingsUi.caption.motionTest" },
                { "MOVE TIMEOUT(ms)", "settingsUi.caption.moveTimeoutMs" },
                { "MOVE TO", "settingsUi.caption.moveTo" },
                { "Motion", "settingsUi.caption.motion" },
                { "NAME", "settingsUi.caption.name" },
                { "NEG ACTION", "settingsUi.caption.negAction" },
                { "NEG LEVEL", "settingsUi.caption.negLevel" },
                { "NEG VALUE", "settingsUi.caption.negValue" },
                { "NO", "settingsUi.caption.no2" },
                { "NO.", "settingsUi.caption.no" },
                { "OFF", "settingsUi.caption.off" },
                { "OFFSET", "settingsUi.caption.offset" },
                { "ON", "settingsUi.caption.on" },
                { "ORG", "settingsUi.caption.org" },
                { "OUTPUT BIN BARCODE", "settingsUi.caption.outputBinBarcode" },
                { "OUTPUT MODE", "settingsUi.caption.outputMode" },
                { "OUTPUT VISION", "settingsUi.caption.outputVision" },
                { "PARA LOAD", "settingsUi.caption.paraLoad" },
                { "PARA SAVE", "settingsUi.caption.paraSave" },
                { "PARITY", "settingsUi.caption.parity" },
                { "PEL", "settingsUi.caption.pel" },
                { "PICKER ZONE", "settingsUi.caption.pickerZone" },
                { "PORT", "settingsUi.caption.port" },
                { "POS ACTION", "settingsUi.caption.posAction" },
                { "POS LEVEL", "settingsUi.caption.posLevel" },
                { "POS VALUE", "settingsUi.caption.posValue" },
                { "POSITION", "settingsUi.caption.position" },
                { "POSITION TEACHING", "settingsUi.caption.positionTeaching" },
                { "POSITION TEACHING LIST", "settingsUi.caption.positionTeachingList" },
                { "PROFILE", "settingsUi.caption.profile" },
                { "PULSE 200ms", "settingsUi.caption.pulse200Ms" },
                { "PULSES/UNIT", "settingsUi.caption.pulsesUnit" },
                { "Picker Zone", "settingsUi.caption.pickerZone2" },
                { "Position Teaching", "settingsUi.caption.positionTeaching" },
                { "READ TIMEOUT", "settingsUi.caption.readTimeout" },
                { "READ TIMEOUT (ms)", "settingsUi.caption.readTimeoutMs" },
                { "READY", "settingsUi.caption.ready" },
                { "REFRESH", "settingsUi.caption.refresh" },
                { "RELOAD", "settingsUi.caption.reload" },
                { "RESET DEFAULT", "settingsUi.caption.resetDefault" },
                { "RESET LEVEL", "settingsUi.caption.resetLevel" },
                { "RETRY COUNT", "settingsUi.caption.retryCount" },
                { "ROLE", "settingsUi.caption.role" },
                { "Reload JSON", "settingsUi.caption.reloadJson" },
                { "Reset", "settingsUi.caption.reset" },
                { "SAVE", "settingsUi.caption.save" },
                { "SAVE BARCODE SETTINGS", "settingsUi.caption.saveBarcodeSettings" },
                { "SENSOR #1", "settingsUi.caption.sensor1" },
                { "SENSOR #2", "settingsUi.caption.sensor2" },
                { "SENSOR LEVEL", "settingsUi.caption.sensorLevel" },
                { "SENSOR VALUE", "settingsUi.caption.sensorValue" },
                { "SERIAL PORT (COM)", "settingsUi.caption.serialPortCom" },
                { "SERVO", "settingsUi.caption.servo" },
                { "SERVO LEVEL", "settingsUi.caption.servoLevel" },
                { "SERVO OFF", "settingsUi.caption.servoOff" },
                { "SERVO ON", "settingsUi.caption.servoOn" },
                { "SHARED RAIL X", "settingsUi.caption.sharedRailX" },
                { "SIDE VISION (FRONT)", "settingsUi.caption.sideVisionFront" },
                { "SIDE VISION (REAR)", "settingsUi.caption.sideVisionRear" },
                { "SIGNAL", "settingsUi.caption.signal" },
                { "SIM", "settingsUi.caption.sim" },
                { "SIM MODE", "settingsUi.caption.simMode" },
                { "SINGLE", "settingsUi.caption.single" },
                { "SOFT LIMIT(+)", "settingsUi.caption.softLimitPositive" },
                { "SOFT LIMIT(-)", "settingsUi.caption.softLimitNegative" },
                { "SPEED", "settingsUi.caption.speed" },
                { "STATE", "settingsUi.caption.state" },
                { "STATUS", "settingsUi.caption.status" },
                { "STOP BITS", "settingsUi.caption.stopBits" },
                { "STOP DEC", "settingsUi.caption.stopDec" },
                { "STOP MODE", "settingsUi.caption.stopMode" },
                { "STROKE", "settingsUi.caption.stroke" },
                { "SW ENABLED", "settingsUi.caption.swEnabled" },
                { "SW NEGATIVE", "settingsUi.caption.swNegative" },
                { "SW POSITIVE", "settingsUi.caption.swPositive" },
                { "SWITCH LIST", "settingsUi.caption.switchList" },
                { "SYMBOL", "settingsUi.caption.symbol" },
                { "Search:", "settingsUi.caption.search" },
                { "Select a grid row to switch axis automatically.", "settingsUi.caption.selectAGridRowToSwitchAxisAutomatically" },
                { "Severity", "settingsUi.caption.severity" },
                { "SharedRailX", "settingsUi.caption.sharedRailX" },
                { "Speed", "settingsUi.caption.speed2" },
                { "TAIL CHAR", "settingsUi.caption.tailChar" },
                { "TEACH", "settingsUi.caption.teach" },
                { "TEST CONN", "settingsUi.caption.testConn" },
                { "TEST READ", "settingsUi.caption.testRead" },
                { "TIMEOUT(ms)", "settingsUi.caption.timeoutMs" },
                { "TOLERANCE", "settingsUi.caption.tolerance" },
                { "TRIGGER", "settingsUi.caption.trigger" },
                { "Test Connection", "settingsUi.caption.testConnection" },
                { "Title", "settingsUi.caption.title" },
                { "UNIT", "settingsUi.caption.unit" },
                { "UNIT/PULSE", "settingsUi.caption.unitPulse" },
                { "USE INPUT WAFER BARCODE", "settingsUi.caption.useInputWaferBarcode" },
                { "USE OUTPUT BIN BARCODE", "settingsUi.caption.useOutputBinBarcode" },
                { "VALUE", "settingsUi.caption.value" },
                { "VELOCITY", "settingsUi.caption.velocity" },
                { "WIDTH", "settingsUi.caption.width" },
                { "Y RETRY STEP (mm)", "settingsUi.caption.yRetryStepMm" },
                { "Z PHASE LEVEL", "settingsUi.caption.zPhaseLevel" },
                { "ZERO", "settingsUi.caption.zero" },
                { "ZOOM", "settingsUi.caption.zoom" },
                { "input", "settingsUi.caption.input" },
                { "output", "settingsUi.caption.output" },
                { "축 설정 변경", "settingsUi.action.changeAxisSettings" },
                { "축 설정 저장", "settingsUi.action.saveAxisSettings" },
                { "축 설정 적용", "settingsUi.action.applyAxisSettings" },
                { "축 일괄 설정 변경", "settingsUi.action.changeAllAxisSettings" },
            };

        internal static string Display(string original)
        {
            if (string.IsNullOrEmpty(original)) return original ?? string.Empty;
            string key;
            return CaptionKeys.TryGetValue(original, out key) ? Lang.T(key) : original;
        }

        internal static void BindColumn(DataGridViewColumn column)
        {
            if (column == null) return;
            string key;
            if (CaptionKeys.TryGetValue(column.HeaderText, out key))
                Lang.BindKey(column, key);
        }

        // STATE 뒤에는 사용자가 설정한 실린더 이름이 올 수 있으므로 본문을 그대로 유지합니다.
        internal static string DisplayCylinderStatus(string original)
        {
            const string prefix = "STATE : ";
            if (original != null && original.StartsWith(prefix, StringComparison.Ordinal))
                return Lang.Format("settingsUi.io.state", original.Substring(prefix.Length));
            return Display(original);
        }
    }
}
